### ISSUE TITLE
Missing ID Token in `Logins` during federatedSignIn

### ISSUE THREAD

**Issue by chrisbonifacio** [aws-amplify/amplify-js#10060]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

When attempting to authenticate with `Amplify.federatedSignIn`, with a `responseType` of `code`, the request made to https://cognito-identity.us-east-1.amazonaws.com/ is missing the ID Token from `Logins` within the payload.

This results in an empty string being sent in the payload and this error being returned from Cognito.

### Expected behavior

ID Token should be sent in the payload and the user should finish the OAuth flow and be authenticated

### Reproduction steps

1. Configure auth resource with OAuth flow enabled with responseType of `code`
2. Configure social providers or OIDC
3. Attempt to sign in as federated user

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
Credentials - Error loading credentials ValidationException: 1 validation error detected: Value '{cognito-idp.us-west-1.amazonaws.com/us-west-1_N7Lcpfd80=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]

```

</details>

### Additional information and screenshots

<img width="1203" alt="screen_shot_2022-06-29_at_1 42 18_pm" src="https://user-images.githubusercontent.com/16952986/177411638-8095cb3e-17ed-45fe-bf30-247995b68120.png">

**Comment by JefStat** [comment]
Is there any workaround for this issue?

**Comment by chrisbonifacio** [comment]
> Is there any workaround for this issue?

Are you experiencing this on the latest version of `aws-amplify`?

**Comment by JefStat** [comment]
I have solved my issue. There were 2 problems having multiple redirect URLs and next js lint error when using `window` 

previously my `Amplify.configure(updatedAwsConfig);` in `_app.ts` was wrapped in `useEffect` because of nextjs compilation errors referencing the window object. Which meant the proper value of `oauth.redirectSignIn` was not set in time for when the login was returned from the congnito hosted UI.

now I polyfill the window object to enable nextjs to comply happily and the config is updated at the same time as the _app.ts component.

```
import awsConfig from '../aws-exports';
// next build lint step workaround
if (typeof window === 'undefined') {
  // @ts-ignore
  global.window = undefined
}
updatedAwsConfig.oauth.redirectSignIn = `${window?.location.origin}/`;
updatedAwsConfig.oauth.redirectSignOut = `${window?.location.origin}/`;
Amplify.configure(updatedAwsConfig);
```

**Comment by lucre74** [comment]
Experimenting the same issue with aws-amplify 5.0.3.
```
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "aws-amplify": "^5.0.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
```
The token is correctly fetched from the Amazon Cognito Domain.
Then a request is posted to https://cognito-identity.eu-west-1.amazonaws.com/ (x-amz-target: AWSCognitoIdentityService.GetId) with the following data: 
```
{
    "IdentityPoolId": "eu-west-1:IDENTITYPOOLID",
    "Logins": {
        "cognito-idp.eu-west-1.amazonaws.com/eu-west-1_USERPOOLID": ""
    }
}
```
Response status 400: 
```
x-amzn-errortype: ValidationException:
x-amzn-requestid: c4b0b487-555b-4ea8-8ea3-a961ca0f8863
x-amzn-errormessage: 1 validation error detected: Value '{cognito-idp.eu-west-1.amazonaws.com/eu-west-1_aSigjVkoc=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]
```

The code: 
```
import React, { useEffect, useState } from 'react'
import { Amplify, Auth, Hub } from 'aws-amplify';
import config from './config.js';

Amplify.configure( {
  Auth: {
    mandatorySignIn: false,
    region: "eu-west-1",
    userPoolId: config.Cognito.UserPoolId,
    identityPoolId: config.Cognito.IdentityPoolId,
    userPoolWebClientId: config.Cognito.AppClientId,
    identityPoolRegion: "eu-west-1",
    oauth: {
      domain: config.Cognito.Domain,
      scope: ['email'],
      redirectSignIn: "http://localhost:12500",
      redirectSignOut: "http://localhost:12500",
      responseType: "code"
    }
  }
});

export default function App(props) {
  const [user, setUser] = useState(null);
  const [customState, setCustomState] = useState(null);

  useEffect(()=> {
    const unsubscribe = Hub.listen("auth", ({ payload: { event, data } }) => {
      switch (event) {
        case "signIn":
          Auth.currentAuthenticatedUser()
            .then(user => setUser(user))
            .catch(() => console.log("Not signed in"));
          break;
        case "signOut":
          setUser(null);
          break;
        case "customOAuthState":
          setCustomState(data);
          break;
        default:
      }
    });
    return unsubscribe;
  }, []);

  let fbButton = "";
  let signoutButton = "";
  if (user == null) {
    fbButton = (<button onClick={() => Auth.federatedSignIn({provider: 'Facebook'})}>Facebook</button>);
  } else {
    signoutButton = (<button onClick={() => Auth.signOut()}>Sign Out {user.getUsername()}</button>);
  }

  return (
      <div className="App">
        <p>User: {(user !== null)?user: "null"}</p>
        <p>Custom state: {(customState !== null)?customState: "null"}</p>
        {fbButton}
        {signoutButton}
      </div>
  );
}
```

**Comment by JefStat** [comment]
My experience says that the redirectSignIn and redirectSignOut should be postfix with a trailing `/`

```
      redirectSignIn: "http://localhost:12500",
```
This return statement in the OAuth sign in is caused the `Logins:{"xxx":""` to be a blank string instead of a JWT. I think it has code to default to `/` when the redirectSignIn doesn't have the trailing `/`
https://github.com/aws-amplify/amplify-js/blob/e1b0b5be3e8ccb3c76e8e2e2f43f910d40d73254/packages/auth/src/OAuth/OAuth.ts#L122

**Comment by lucre74** [comment]
Same behaviour with trailing slash.
The issue happens after the federatedSignIn succeeds when the credentials are set from the session.
I isolated the issue at 
https://github.com/aws-amplify/amplify-js/blob/e1b0b5be3e8ccb3c76e8e2e2f43f910d40d73254/packages/core/src/Credentials.ts#L437

session.getIdToken().getJwtToken() is "".

The JwtToken is available in the session at session.getAccessToken().getJwtToken()

I need some more investigation and diving into OAuth before telling if this is expected or not.

**Comment by JefStat** [comment]
1. a suggestion I'm assuming you are debugging locally. Set `window.LOG_LEVEL = 'DEBUG';`
2. `session.getIdToken().getJwtToken();` the return value of this is set here in Auth

https://github.com/aws-amplify/amplify-js/blob/e1b0b5be3e8ccb3c76e8e2e2f43f910d40d73254/packages/auth/src/Auth.ts#L2436
```
const { accessToken, idToken, refreshToken, state } =
						await this._oAuthHandler.handleAuthResponse(currentUrl);
					const session = new CognitoUserSession({
						IdToken: new CognitoIdToken({ IdToken: idToken }),
						RefreshToken: new CognitoRefreshToken({
							RefreshToken: refreshToken,
						}),
						AccessToken: new CognitoAccessToken({
							AccessToken: accessToken,
						}),
					});
```
which requires the token returned from
https://github.com/aws-amplify/amplify-js/blob/e1b0b5be3e8ccb3c76e8e2e2f43f910d40d73254/packages/auth/src/OAuth/OAuth.ts#L204
this then drops into the following to 2 private functions which do the final step of requesting the JWT token from the oauth url
```
if (this._config.responseType === 'code') {
	return { ...(await this._handleCodeFlow(currentUrl)), state };
} else {
	return { ...(await this._handleImplicitFlow(currentUrl)), state };
}
```

**Comment by lucre74** [comment]
Debugging further.
The OAuth flow is correct until the /oauth2/token.
 - xxx.auth.eu-west-1-amazoncognito.com/oauth2/token with
    - grant_type: "authorisation_code"
    - code: [...]
    - client_id: [...]
    - redirect_uri: http://localhost:12500/
    - code_verifier: [...]

Response: 
{ access_token: [...], 
  refresh_token: [...],
  expires_in: 3600,
  token_type: "Bearer"}

The response is missing the id_token.

From https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-user-pool-oauth-2-0-grants/, it appears that "_id_token – A valid user pool ID token. Note that **an ID token is only provided if the openid scope was requested**._"

Adding the openid scope to the Allowed OAuth Scopes of the Cognito User Pool Appclient solved the issue.

It is not allowed in the current Cognito interfaces (web console/cloudformation) to add the email scope without the openid scope. The User Pool used when the issue appeared was created years ago when, I presume that the interface was allowing it at that time. 

Is it normal that Auth idtoken is null when the openid scope is not specified in the Cognito User Pool AppClient? I suppose so. 
I cannot reproduce the issue anymore since all my App Clients specify email+openid scopes and currently the interfaces (web console or cloud formation) do not allow having email scope without openid scope.

**Comment by chrisbonifacio** [comment]
Closing this out and pointing out @lucre74's comment as a possible solution. I'm unsure if everyone experiencing this issue needs to do the same and ensure that their app clients are configured to include the `email` and `openid` in their Allowed OAuth scopes. This can be configured from the Amplify CLI as well when configuring the auth resource with Federation/Social Providers.

If anyone is still experiencing this issue, please comment with the oauth setup in your `aws-exports` or, if manually configuring Amplify/Auth, please share the code snippet so we can see how you might be trying to add the scopes. Lastly, please add how you created your auth resource (via AWS Console, Amplify Studio, Amplify CLI, etc).

**Comment by billygerhard** [comment]
I have always had openid in my scopes, so the workaround from @lucre74's https://github.com/aws-amplify/amplify-js/issues/10060#issuecomment-1328334441 would not resolve my issue.

**Comment by chrisbonifacio** [comment]
> I have always had openid in my scopes, so the workaround from @lucre74's [#10060 (comment)](https://github.com/aws-amplify/amplify-js/issues/10060#issuecomment-1328334441) would not resolve my issue.

Can you give us some more information about your auth resource and how it's configured? Have you checked if your scopes are reflected in all appropriate places such as the `aws-exports.js` file and on your app clients in the User Pool console? How are you calling `Amplify.configure` or `Auth.configure`?

**Comment by billygerhard** [comment]
Sorry for the delay, yes, I used the CLI to generate the pools.

This is how I am setting up amplify on my app
```
import { Amplify, Storage } from 'aws-amplify';
import aws_exports from './aws-exports';

aws_exports.Auth = {
  mandatorySignId: true,
  region: 'us-west-2',
  userPoolId: 'xxxx',
  userPoolWebClientId: 'xxxx'
};
aws_exports.oauth = {
  domain: 'xxxx.us-west-2.amazoncognito.com', // check domain name under app integration
  redirectSignIn: isDevMode()?'http://localhost:8100/auth':'https://xxxx/auth',
  redirectSignOut: isDevMode()?'http://localhost:8100/auth':'https://xxx/auth',
  scope: [
    'phone',
    'email',
    'profile',
    'openid', // important
    'aws.cognito.signin.user.admin',
  ],
  responseType: 'token', //Code is not working, open ticket with Amplify team https://github.com/aws-amplify/amplify-js/issues/10060
  callbackUrls: ['http://localhost:8100/auth',`https://xxxx/auth`],
  logoutUrls: ['http://localhost:8100/auth',`https://xxxxx/auth`]
};

aws_exports.Storage = {
  AWSS3: {
    bucket: 'xxxx', //REQUIRED -  Amazon S3 bucket name
    region: 'us-west-2', //OPTIONAL -  Amazon service region
  }
}

//Amplify.Logger.LOG_LEVEL = isDevMode()?'DEBUG':Amplify.Logger.LOG_LEVEL;
Amplify.configure(aws_exports);
```

And here is my hosted login setup 

![Screen Shot 2022-12-13 at 11 05 01 AM](https://user-images.githubusercontent.com/2285204/207384119-dd59e146-e389-4061-91dc-af2d469a0065.png)

**Comment by billygerhard** [comment]
And to note, when we went over this initially, code flow works on local host, but does not work when its hosted.

**Comment by dafran7** [comment]
I have the same problem here.. The oauth works without flaws on localhost, but it just fail after hosted it on Amplify..
I have setup the callback and sign-out on cognito with the same pathname as on localhost, responseType to "code" and have "openid" on my scopes..

I do believe the problem is in this very line, but I unable to know which one is different / changed..
I have looked over mostly debug logs it produced. They seem to setup correctly, but I don't really know whats happening before this line is executed. If only there's a log before this..

https://github.com/aws-amplify/amplify-js/blob/e1b0b5be3e8ccb3c76e8e2e2f43f910d40d73254/packages/auth/src/OAuth/OAuth.ts#L122

I'm using VueJS currently.

**Comment by chrisbonifacio** [comment]
Hey Billy, just re-opened the issue. 

I see that you have your south configured correctly. If the code that the next commenter referred is the problem then one of those conditions has to be true. Is there no code in the query parameters or does the current url path not match the redirectSignIn url? Is there some trailing slash or something being added to the url on redirect and causing the url mismatch on the hosted site?

**Comment by chrisbonifacio** [comment]
@billygerhard going through the older comments, I noticed others had to include not only the `openid` scope but also a trailing slash and your redirect URLs do not have them, same with @dafran7. Can you try adding a trailing slash to your redirect URLs and see if that's what's causing the issue on the hosted site? This configuration can be very finicky about the format. It's the only thing that looks potentially off about your OAuth configs to me.

```
redirectSignIn: isDevMode()?'http://localhost:8100/auth/':'https://xxxx/auth/',
redirectSignOut: isDevMode()?'http://localhost:8100/auth/':'https://xxx/auth/',
```

**Comment by dafran7** [comment]
Hey @chrisbonifacio, thanks for the follow up.

Actually, I have figured it out last week. I have tried adding trailing slash, but it still didn't work. What worked is that I setup my Amplify differently. I emptied out the "oauth" setup for Amplify instead of referring awsExports directly from the file (or Environment Variables from the Amplify server?)

I can't confidently say why that could worked, but I think the Amplify configuration is overriding the Auth config somehow, which made the pathnames unequal. You can check out my solution below. I'm sure the config can be used to both Amplify and Auth.

```
import awsExports from "./aws-exports";

.......

Amplify.configure(awsExports);

import _ from "lodash";
const configured = _.toPlainObject(awsExports);
const oauth = _.clone(configured["oauth"]);
configured["oauth"] = {};
Amplify.configure(configured);

const serverURI = window.location.protocol + "//" + window.location.host;
configured["oauth"] = oauth;
configured["oauth"]["redirectSignIn"] = serverURI + "/callback";
configured["oauth"]["redirectSignOut"] = serverURI + "/logout";
Auth.configure(configured);
```

**Comment by erinleigh90** [comment]
Hi @billygerhard @dafran7,

We tried the configuration as described in the Amplify docs [here](https://docs.amplify.aws/lib/auth/social/q/platform/js/#configure-auth-category) and were able to get the app to work on Amplify hosting. I've pasted our code below in case that helps. We think the primary issue is with overriding awsConfig Auth and oauth completely instead of overriding the values that need to be changed. There may also be an issue with the isDevMode() method, depending on how you are implementing.


```javascript
import React from 'react';
import logo from './logo.svg';
import './App.css';
import { Auth, Amplify } from 'aws-amplify';
import awsConfig from './aws-exports';

const isLocalhost = Boolean(
  window.location.hostname === "localhost" ||
    // [::1] is the IPv6 localhost address.
    window.location.hostname === "[::1]" ||
    // 127.0.0.1/8 is considered localhost for IPv4.
    window.location.hostname.match(
      /^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/
    )
);

// Assuming you have two redirect URIs, and the first is for localhost and second is for production
const [
  localRedirectSignIn,
  productionRedirectSignIn,
] = awsConfig.oauth.redirectSignIn.split(",");

const [
  localRedirectSignOut,
  productionRedirectSignOut,
] = awsConfig.oauth.redirectSignOut.split(",");

const updatedAwsConfig = {
  ...awsConfig,
  oauth: {
    ...awsConfig.oauth,
    redirectSignIn: isLocalhost ? localRedirectSignIn : productionRedirectSignIn,
    redirectSignOut: isLocalhost ? localRedirectSignOut : productionRedirectSignOut,
  }
}

Amplify.configure(updatedAwsConfig);

function App() {
  async function checkUser() {
    console.log(await Auth.currentCredentials());
  }
  return (
    <div className="App">
      <button onClick={() => Auth.federatedSignIn()}>SignIn</button>
      <button onClick={checkUser}>CheckUser</button>
    </div>
  );
}

export default App;
```

Hope this helps!

**Comment by nadetastic** [comment]
@dafran7 @billygerhard - following up on this issue, are you still facing this blocker after reviewing the comment from @erinleigh90 above?

**Comment by nadetastic** [comment]
Adding this here for visibility - For Angular applications, I was able to get this working and setup a sample project on this repo under branch [10060](https://github.com/nadetastic/angular-amplified/tree/10060)

**Comment by billygerhard** [comment]
My issue was resolved because I was calling `Amplify.configure` twice inside an environment script with outdated redirect URLs once our domain changed. This error wasn't exposed so it was hard to find the error, but for anyone else having issues, check if you are re-configuring amplify somewhere else in your app.

**Comment by nadetastic** [comment]
@billygerhard glad we were able to get this resolved!

To clarify for others that may have this problem - if you are calling `Amplify.configure()` more than once where `oauth.redirectSignIn` and `oauth.redirectSignOut` changes, you will face this issue.

Although you are able to call `Amplify.configure()` multiple times, be sure not to change the `oauth.redirectSignIn` and `oauth.redirectSignOut` values once they are set. The response after federating will fail with this error.

**Comment by gstaykov** [comment]
I have the same problem with the latest version. I'm using this for the login:

```
import { signInWithRedirect } from "@aws-amplify/auth";

signInWithRedirect({
  provider: "Facebook",
});
```

And this on the page that opens after the login is successful:
```
useEffect(() => {
    currentSession().then((session) => {
      console.log(session.idToken.payload.email);
    });
}, []);
```

The error that I get is: "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'payload')". A.k.a `idToken` is undefined

Version of my amplify is:
```
"aws-amplify": "^6.0.13"
```

I'm using it with nextjs (`"next": "12.1.4"`) and react (`"react": "18.0.0"`)

**Comment by nadetastic** [comment]
Hi @gstaykov - are you calling `Amplify.configure()` more than once as well as changing the `redirectSignIn` params in your app? If not It, the problem is most likely unrelated and you would be able to get better assistance by opening a separate issue.

**Comment by nadetastic** [comment]
@gstaykov looks like you already opened this 😄 - #12927

**Comment by chrisbonifacio** [comment]
I'm going to close this out seeing as how the cause of this issue can be different between projects and, as mentioned before, dependent on configuration.

It's also been over a year and considering the changes introduced to Auth in v6 it's probably best for anyone experiencing a similar issue to open a new one with the particular details of their project and reproduction steps so that we can reproduce the issue on our end.
