### ISSUE TITLE
Update/Delete/Add UserAttributes to *unauthenticated* Cognito user on server

### ISSUE THREAD

**Issue by Leandros** [aws-amplify/amplify-js#1026]
I'm doing Cognito authentication, using amazon-cognito-identity-js on the server. 
The current flow is to create and login the user on the server, and send the jwt we're getting from Cognito to the user. 
This means we can't keep the authenticated `CognitoUser` around. How do I update a users attribute, based on just their email address on the server?

**Comment by powerful23** [comment]
@Leandros for now we don't have the method to update attributes without `CognitoUser` but you can do it by sending a request to Cognito service with the jwt token manually according to [this](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserAttributes.html) and [this](https://github.com/aws/aws-amplify/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js#L979). You may use the `Client` class from the package and make a call to the service.

**Comment by harrysolovay** [comment]
The `amazon-cognito-identity-js` package is NOT intended for server-side usage. It is a front-end library. If you use it on your front-end, you can make direct calls to your AWS resources, including your Cognito User Pool. Token refresh operations will occur behind-the-scenes, so that you don't lose this auth state. Using that auth state, you can send the Cognito [UpdateUserAttributes](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserAttributes.html) requests directly from the browser.
