### ISSUE TITLE
The sign event is called multiple time when login Hub.listen

### ISSUE THREAD

**Issue by LogTime1h** [aws-amplify/amplify-js#10333]
![image](https://user-images.githubusercontent.com/113431759/190610132-9ddf7363-dec8-4ebd-bb3b-da40cea65129.png)

**Comment by chrisbonifacio** [comment]
Hi @LogTime1h 👋 thanks for raising this issue. Which event is being called multiple times? It wasn't clear whether it was signIn or signIn_failure in the title.

If you're having issues with duplicate events, usually it's either because of the clean up of listeners or some duplicate amplify dependencies. I tested whether the hub listeners would be cleaned up properly from your code snippet and it seems they are so can you share your package.json so we can check if there are duplicate Auth instances that might be emitting events separately?

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
