### ISSUE TITLE
Support for new Google Identity Services for Web solution

### ISSUE THREAD

**Issue by muvashi** [aws-amplify/amplify-js#10509]
### Is this related to a new or existing framework?

React

### Describe the feature you'd like to request

Hello,

The Google Sign-In JavaScript platform library for Web is deprecated, and unavailable for download after March 31, 2023. 

Google is recommending to use the new Google Identity Services for Web solution to quickly and easily sign users into your app using their Google accounts.

Ref : https://developers.google.com/identity/sign-in/web/sign-in

Could you please confirm when amplify-js library will be updated as per the deprecation ?

Thanks

### Describe the solution you'd like

Google is recommending to use the new Google Identity Services for Web solution to quickly and easily sign users into your app using their Google accounts.

### Describe alternatives you've considered

NA

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by alettieri** [comment]
Looking forward to hearing more about this. We're currently adding federated sign-in support with amplify and noticed the deprecation warning.

**Comment by haverchuck** [comment]
Reading through [Google's Deprecation notice](https://developers.googleblog.com/2021/08/gsi-jsweb-deprecation.html), we are not seeing any Amplify changes required.

> The deprecation applies only to web apps using the [Google Sign-in JavaScript library]([https://developers.google.com/identity/sign-in/web/sign-in)…The](https://developers.google.com/identity/sign-in/web/sign-in)%E2%80%A6The) following are NOT affected by this deprecation announcement:
> * Android or iOS native app SDKs,
> * _apps or platforms directly calling Google's OAuth2 or OpenID services._
_(Italics mine)_

There are two potential issues to consider with Amplify: Cognito Hosted UI and Federated Identities (i.e. the [`Auth.federatedSignIn`](https://docs.amplify.aws/lib/auth/advanced/q/platform/js/#google-sign-in-react) API.

* Hosted UI: Our read of this notice from Google is that HostedUI will be fine since the Cognito service is calling OAuth/OIDC endpoints; 

* Federated Identities: these would similarly be unaffected since they're not changing token validation endpoints or the discovery endpoints. An app developer using [identity pool federation](https://docs.amplify.aws/lib/auth/advanced/q/platform/js/#identity-pool-federation) would be responsible for implementing the new library, but would continue to pass the ID token returned from Google to the Amplify `Auth.federatedSignIn` API.

We will update our documentation to reflect the new library as needed, but what changes do you believe are required by the Amplify library?

**Comment by acc-tfi** [comment]
Thanks for the response! I hadn't seen the deprecation notice article, only the banner on the page I linked.

However, it still appears that amplify makes use of the library being deprecated and is not directly calling the OAuth2 services. I believe the Google provider is affected as it loads the library in question: https://github.com/aws-amplify/amplify-js/blob/df95ea3724eb6406f64b03f25086cd3e8644cb5f/packages/aws-amplify-react/src/Auth/Provider/withGoogle.tsx#L132

It appears that [sign in](https://github.com/aws-amplify/amplify-js/blob/df95ea3724eb6406f64b03f25086cd3e8644cb5f/packages/aws-amplify-react/src/Auth/Provider/withGoogle.tsx#L43) and [sign out](https://github.com/aws-amplify/amplify-js/blob/df95ea3724eb6406f64b03f25086cd3e8644cb5f/packages/aws-amplify-react/src/Auth/Provider/withGoogle.tsx#L103) use the auth instance provided by the platform library. These methods do not appear to be directly calling Google's OAuth2 services. `signOut`, for instance, makes the same calls as what [Google has marked deprecated](https://developers.google.com/identity/sign-in/web/sign-in#sign_out_a_user). [Google's documentation on how to directly call their OAuth2 services](https://developers.google.com/identity/protocols/oauth2) even [marks the js api as being deprecated as well](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#js-client-library) and provides examples of how to directly call their OAuth2 services.

The [Hosted UI uses the client](https://github.com/aws-amplify/amplify-js/blob/bcf4498cc9ecfdeade2e772dfa28c0096fdf438c/packages/amplify-ui-components/src/components/amplify-google-button/amplify-google-button.tsx#L117) specified in [Google's migration guidelines here](https://developers.google.com/identity/gsi/web/guides/migration#libraries_and_configuration).

It would seem that both of the points you listed are what need to be updated to make use of [Google's new Sign in for web](https://developers.google.com/identity/gsi/web/guides/overview) flow and the [new js api](https://developers.google.com/identity/gsi/web/reference/js-reference)

**Comment by chrisbonifacio** [comment]
> Thanks for the response! I hadn't seen the deprecation notice article, only the banner on the page I linked.
> 
> However, it still appears that amplify makes use of the library being deprecated and is not directly calling the OAuth2 services. I believe the Google provider is affected as it loads the library in question:
> 
> https://github.com/aws-amplify/amplify-js/blob/df95ea3724eb6406f64b03f25086cd3e8644cb5f/packages/aws-amplify-react/src/Auth/Provider/withGoogle.tsx#L132
> 
> It appears that [sign in](https://github.com/aws-amplify/amplify-js/blob/df95ea3724eb6406f64b03f25086cd3e8644cb5f/packages/aws-amplify-react/src/Auth/Provider/withGoogle.tsx#L43) and [sign out](https://github.com/aws-amplify/amplify-js/blob/df95ea3724eb6406f64b03f25086cd3e8644cb5f/packages/aws-amplify-react/src/Auth/Provider/withGoogle.tsx#L103) use the auth instance provided by the platform library. These methods do not appear to be directly calling Google's OAuth2 services. `signOut`, for instance, makes the same calls as what [Google has marked deprecated](https://developers.google.com/identity/sign-in/web/sign-in#sign_out_a_user). [Google's documentation on how to directly call their OAuth2 services](https://developers.google.com/identity/protocols/oauth2) even [marks the js api as being deprecated as well](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#js-client-library) and provides examples of how to directly call their OAuth2 services.
> 
> The [Hosted UI uses the client](https://github.com/aws-amplify/amplify-js/blob/bcf4498cc9ecfdeade2e772dfa28c0096fdf438c/packages/amplify-ui-components/src/components/amplify-google-button/amplify-google-button.tsx#L117) specified in [Google's migration guidelines here](https://developers.google.com/identity/gsi/web/guides/migration#libraries_and_configuration).
> 
> It would seem that both of the points you listed are what need to be updated to make use of [Google's new Sign in for web](https://developers.google.com/identity/gsi/web/guides/overview) flow and the [new js api](https://developers.google.com/identity/gsi/web/reference/js-reference)

The packages you're referring to are outdated Amplify UI packages that are no longer being supported. We've since separated the UI components out into their own repo. This is the code we use for our OAuth flow when using the Auth library directly: https://github.com/aws-amplify/amplify-js/blob/cc35ad1943f91b0559438a832ffb8d72215558d5/packages/auth/src/OAuth/OAuth.ts#L115

You can see that we are making a request to the Google OAuth2.0 endpoint. The new UI components use the Amplify Auth library so the endpoint is the same. Does this answer your concern?
