### ISSUE TITLE
NotAuthorizedException : Cannot initiate DEVICE_SRP_AUTH flow without first authenticating

### ISSUE THREAD

**Issue by wmaca** [aws-amplify/amplify-js#10582]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 70.39 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 3.2.4 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 101.0.1
    Safari: 16.0
  npmPackages:
    @babel/core: 7.12.3 => 7.12.3 
    @my-scope/package-a:  0.0.0 
    @my-scope/package-b:  0.0.0 
    @testing-library/react: ^11.0.4 => 11.1.0 
    @testing-library/react-hooks: ^7.0.1 => 7.0.1 
    babel-jest: ^26.6.0 => 26.6.0 
    babel-loader: 8.1.0 => 8.1.0 
    babel-plugin-named-asset-import: ^0.3.7 => 0.3.8 
    baz:  undefined ()
    browser_field:  undefined ()
    date-fns: ^2.21.1 => undefined (2.16.1)
    invalid main:  undefined ()
    lint-staged: ^10.4.0 => 10.4.2 
    monorepo-symlink-test:  0.0.0 
    mylib:  0.0.0 
    react: ^16.9.0 => 16.14.0 
    react-autosuggest: ^10.0.0 => 10.0.3 
    react-datepicker: ^3.0.0 => 3.3.0 
    react-dom: ^16.9.0 => 16.14.0 
    react-redux: ^7.1.3 => 7.2.1 
    react-router-dom: ^5.1.2 => 5.2.0 
    react-transition-group: ^4.4.1 => 4.4.1 
    react-transition-group/CSSTransition:  undefined ()
    react-transition-group/ReplaceTransition:  undefined ()
    react-transition-group/SwitchTransition:  undefined ()
    react-transition-group/Transition:  undefined ()
    react-transition-group/TransitionGroup:  undefined ()
    react-transition-group/TransitionGroupContext:  undefined ()
    react-transition-group/config:  undefined ()
    resolve: 1.18.1 => 1.18.1 
    semver: 7.3.2 => undefined (5.7.1)
  npmGlobalPackages:
    corepack: 0.9.0
    npm: 7.24.0
    serve: 13.0.2
    yarn: 1.22.18
```

</details>

### Describe the bug

When signing-in calling `Auth.signIn` (passing username and password), I get a NotAuthorizedException exception **randomly**.

I've verified that the username and password are correct (setting a breakpoint before calling Amplify).

If I call it again, it may or may not work. It seems random.

Network has the following 400 response when calling Cognito:

{“__type”:“NotAuthorizedException”,“message”:“Cannot initiate DEVICE_SRP_AUTH flow without first authenticating”}

I assume that, as we are not doing any custom challenge, that Amplify is trying to authenticate the device before it authenticates the user.

As mentioned earlier, it seems to be at random. If I click on the same button that class `Auth.signIn`, it may authenticate successfully.

We are using aws-amplify@4.1.0

### Expected behavior

It should correctly authenticate the user.

### Reproduction steps

1. Call Auth.signIn with a valid username and password.
2. It may fail at random

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by wmaca** [comment]
It is being developed for the browser. We don't do automatic sign-ins, users are always required to type their password, but we do not require MFA if device signed-in before. I guess this is partially related on how our custom storage works.

The id token, access token, refresh token and last auth user are stored in session storage instead of local storage. The later keeps the rest.

Not sure this answers what you've asked me. Let me know if it does not.

**Comment by tannerabread** [comment]
So you don't have device tracking or MFA enabled for your user pool?

**Comment by wmaca** [comment]
Yes, I have device tracking and MFA enabled.

— Walter Macambira

On November 2, 2022, GitHub ***@***.***> wrote:
> So you don't have device tracking or MFA enabled for your user pool?
>

—
Reply to this email directly, view it on GitHub <https://github.com/aws-
amplify/amplify-js/issues/10582#issuecomment-1300783361>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AA27VNYC6NOX7HSC5RA5STTWGKGW7ANCNFSM6AAAAAARUFRAWI>.
You are receiving this because you were mentioned.Message ID: <aws-
***@***.***>

**Comment by tannerabread** [comment]
hi @wmaca, sorry for the delayed response
I've been trying to reproduce this and haven't had any luck on my end without changing the storage. I was able to successfully log in every time when using device remembering and always type in password.

I'm also curious how you set up your app to differentiate between the local/session storage? Can you send the class you used to modify your storage?

**Comment by wmaca** [comment]
Hi @tannerabread, sorry for the delay as well.

Below you can find our custom storage implementation. It uses localStorage or sessionStorage, according to the key. Our intended goal was to force the user to re-authenticate after the tab is closed.

```
class CustomStorage implements ICustomStorage {
	private readonly storagePrefix: string = "CustomStorage-";

	getItem(key: string): Nullable<string> {
		return this.getStorage(key).getItem(this.getInternalKey(key));
	}

	removeItem(key: string): void {
		this.getStorage(key).removeItem(this.getInternalKey(key));
	}

	setItem(key: string, value: string): void {
		this.getStorage(key).setItem(this.getInternalKey(key), value);
	}

	clear(): void {
		this.clearStorage(sessionStorage);
		this.clearStorage(localStorage);
	}

	getInternalKey(key: string): string {
		return `${this.storagePrefix}${key}`;
	}

	private getStorage(key: string): Storage {
		const volatileKeysRegEx = /(idToken|accessToken|refreshToken|LastAuthUser)$/;

		return key.search(volatileKeysRegEx) !== -1 ? sessionStorage : localStorage;
	}

	private clearStorage(storage: Storage) {
		const keysToRemove: string[] = [];
		for (let _i = 0; _i < storage.length; _i++) {
			const key = storage.key(_i);

			if (key !== null && key.startsWith(this.storagePrefix)) {
				keysToRemove.push(key);
			}
		}

		for (const key of keysToRemove) {
			storage.removeItem(key);
		}
	}
}
```

**Comment by tannerabread** [comment]
@wmaca 
I've implemented storage nearly the same as you, I wasn't using typescript so it's slightly different but I appreciate what you sent as it helped me split the cookies between session/local storage in the same way as you did.

I haven't been able to reproduce this so far, I know you said it's random. 
Follow up to that though is, how often are you seeing this behavior? I tried to sign-out then sign-in in succession probably about 100 times in a row and couldn't recreate the problem. 
Which browser are you seeing this in? I have been testing in Chrome only so far but if you are seeing it somewhere else I can try that.

Have you checked that the tokens are successfully removed from your storage when you close the tab or sign out? I did notice that if I press the signOut button, it removes all of the session storage and additionally it removes the keys `clockDrift`, `amplify-signIn-with-hostedUI`, and `userData` from localStorage. However, if I just close the tab it leaves all of those in localStorage. I don't think the first 2 would be causing any trouble but I am thinking the `userData` key might be causing the funny behavior.
I am going to ask internally if anyone has more information on that particular key and if it could cause this behavior.

I would suggest trying to put the `userData` key into your session storage as well and see if it solves the problem while I find out more.

**Comment by wmaca** [comment]
Here is the additional info I mentioned on my previous comment, @tannerabread.

When I actively sign out, the keys **preserved** are:

- deviceKey (localStorage)
- randomPassword (localStorage)
- amplify-redirected-from-hosted-ui (localStorage)
- deviceGroupKey (localStorage)
- userData (localStorage)
- clockDrift (localStorage)

Session storage is empty.

**Comment by tannerabread** [comment]
You are using hosted UI for this login flow?

**Comment by wmaca** [comment]
No, we are not, but I will try to be as descriptive as possible to be sure I am answering your question correctly.

Despite not using Hosted UI directly, if you use federated sign-in, Amplify still uses hosted UI (it sets a flag not to display any hosted UI and redirect back to your app).

**Comment by tannerabread** [comment]
Sorry, I asked because I do not even get the `amplify-redirected-from-hosted-ui` key in my local or sessionStorage when setting it up how you have described, I do get `amplify-signin-with-hostedUI` which is set to false. 

Additionally, when I actively sign out the only 3 keys preserved are:
* deviceGroupKey
* randomPasswordKey
* deviceKey

Internal discussions have pointed me to investigating the storage adapter further. The only difference should be the TS vs non-TS nature of our customStorage.
Are you configuring anything else custom in your `Amplify.configure`?
This is all that is configured in mine:
```js
Amplify.configure({
  ...config,
  storage: MyStorage,
});
```

**Comment by wmaca** [comment]
```
const baseAppUrl = process.env.REACT_APP_COGNITO_APP_URL ?? "";

	Amplify.configure({
		Auth: {
			region: process.env.REACT_APP_COGNITO_REGION as string,
			userPoolId: process.env.REACT_APP_COGNITO_USER_POOL_ID as string,
			userPoolWebClientId: process.env.REACT_APP_COGNITO_USER_POOL_WEB_CLIENT_ID as string,
			oauth: {
				domain: process.env.REACT_APP_COGNITO_OAUTH_DOMAIN as string,
				scope: ["profile", "email", "openid"],
				redirectSignIn: `${baseAppUrl}${federatedSignInCallbackPath}`,
				redirectSignOut: `${baseAppUrl}${federatedSignOutCallbackPath}`,
				responseType: "code"
			},
			storage: new CustomStorage()
		}
	});
```

**Comment by wmaca** [comment]
@tannerabreadm, no need to be sorry.

It seems we set our custom storage on different levels. As we use only Auth, we set it only for Auth.

```ts
const baseAppUrl = process.env.REACT_APP_COGNITO_APP_URL ?? "";

Amplify.configure({
	Auth: {
		region: process.env.REACT_APP_COGNITO_REGION as string,
		userPoolId: process.env.REACT_APP_COGNITO_USER_POOL_ID as string,
		userPoolWebClientId: process.env.REACT_APP_COGNITO_USER_POOL_WEB_CLIENT_ID as string,
		oauth: {
			domain: process.env.REACT_APP_COGNITO_OAUTH_DOMAIN as string,
			scope: ["profile", "email", "openid"],
			redirectSignIn: `${baseAppUrl}${federatedSignInCallbackPath}`,
			redirectSignOut: `${baseAppUrl}${federatedSignOutCallbackPath}`,
			responseType: "code"
		},
		storage: new CustomStorage()
	}
});
```

**Comment by tannerabread** [comment]
@wmaca I tried moving my storage to the Auth scope like you did but that still did not reproduce the problem. Currently I'm getting errors about `remember/forget/fetchDevice` methods not existing that I'm working through but I'm hoping what I found can help.

If you turn on debugger with `Amplify.Logger.LOG_LEVEL = "DEBUG";` before config, what do you see after `Parser - parse config` in your devtools console?

I tried a new project using TypeScript to see if that's where the problem was and noticed that the configuration for Auth/storage is much different when configuring the two different ways. The cookies seem to store in local/sessionStorage as expected but I'm not sure the config is working correctly.

In my regular JS app, I get the following:
![image](https://user-images.githubusercontent.com/30082936/204376894-4b680e81-5ebe-4046-8c89-4a3f94d8a274.png)

Whereas in the TS app, I get:
![image](https://user-images.githubusercontent.com/30082936/204377507-be95caca-1d4a-48b0-b715-d207a4c213b4.png)

Can you confirm if you see the same? I am not sure why for me it is actually storing the cookies as written but is not configuring the service with the entire class in the TS version, only the custom `storagePrefix`

**Comment by wmaca** [comment]
It is not visible on my print, but the line before is: `43:43.375 AuthClass - configure Auth`.

![image (10)](https://user-images.githubusercontent.com/3537591/204532833-ddadc5ff-86b0-4b06-a721-d6736f1ca4e6.png)

**Comment by tannerabread** [comment]
I was just about to say something to that effect. The docs [use static methods](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#managing-security-tokens) and don't create an instance.

In my vanilla JS app I was following the docs using static methods, and when I switched over to TS I copy/pasted your class then created my interface which required me to make an instance to avoid a "Empty Storage Object" error in the console.

I'm waiting on confirmation internally if that would cause issues but it would be worth a try to change over to static methods and not create an instance. When I changed it on the TS app and removed the instantiation, it showed `storage: class CustomStorage` and the methods were on the same level as my JS app.

I would test for you but I still have not been able to reproduce the original issue.

**Comment by wmaca** [comment]
That would be a problem only if Auth accidentally holds a reference to a method and call it with the wrong `this` argument. Which is odd.

I agree with you, as it is not easy to reproduce, I could also change it here, but I would still be unable to tell if that solved the problem.

**Comment by tannerabread** [comment]
Hi @wmaca, I looked at this with some of the team and we are a bit stuck as to how to proceed, still with no luck on reproduction from my end. We are not sure my previous logic was sound with the instance vs static class because why would it only fail intermittently.

Would you either be able to send some sort of sample repo that I can try to use to recreate it or screenshots of the network calls the next time it fails? I know it doesn't happen often so this might be slow to figure out the issue

**Comment by wmaca** [comment]
Hey, @tannerabread. I will send it when I reproduce it... but, as you mentioned, it is hard to reproduce.

**Comment by tannerabread** [comment]
Was anything outside of the ordinary when that happened? Anything I could try to add to my project to reproduce it

**Comment by israx** [comment]
hello @wmaca . Sorry for any inconvenience. To add some context:

When `device tracking` is enabled the underlying service will return `NewDeviceMetadata` and then the library will pickup these values and call `ConfirmDevice` under the hood -- This will start the device tracking flow. Then the library will set these device keys in the storage mechanism.

Then after signing in again, and as long as there is deviceMetadata and the device was remembered(either by setting device tracking to always or by calling Auth.rememberDevice), the `DEVICE_SRP_AUTH` flow is kicked off to bypass MFA. 

So probably the issue you are experiencing is because of the mix of storage mechanisms. A flow that could be causing this issue would be something like: 

`device A` creates device keys in local-storage -> `device A` changes to session storage -> `device A` logins with session storage -> this will call `ConfirmDevice` and set device metadata en session storage -> `device A` changes to local storage -> device A signs in -> the library will pickup previous device metadata

**Comment by wmaca-friday** [comment]
Hi, @israx. What do you mean by "avoid mixing up the device keys while switching to another storage mechanism"?

We do not change the location of the stored values once they are stored. The same keys goes to the same storage always.

**Comment by israx** [comment]
To troubleshoot, can you only set the device keys in localStorage ? They need to be present after sign-out to bypass MFA

**Comment by nadetastic** [comment]
Maybe related #12220

**Comment by wmaca-friday** [comment]
Hi, @israx. As mentioned, it is really hard to reproduce. Since I opened this issue, we have changed the way we store our keys, no longer using the code provided.

Still, I am not sure how the scenario you describe could happen.

If I sign and authenticate a device, device-related keys were kept in `localStorage`.
If I close the browser, only id, access, refresh tokens and last username would be erased. Nothing related to the device.

**Comment by ashwinkumar6** [comment]
Hi @wmaca-friday 

> If I sign and authenticate a device, device-related keys were kept in localStorage.
> If I close the browser, only id, access, refresh tokens and last username would be erased. Nothing related to the device.

Thanks for confirming this. This is the expected behavior, the device keys are retained in the localStorage while the other keys are erased. The device keys will be used to bypass MFA (if configured) the next time the user calls signIn.

Based on the error you had mentioned `NotAuthorizeException`, it's possible that sometimes the correct deviceKeys are fed during signIn while sometimes it was not. 

If my understanding of the issue is correct,
- sometimes signIn throws `NotAuthorizeException`
- if error occurs call signIn again, user successfully by-passes MFA and signs in

If possible could we always log the deviceKeys securely. When the error occurs, we could compare the current call (error) and the subsequent call (success) to check if the same deviceKeys were passed 
(this would verify our theory if the deviceKeys are getting mixed up)

**Comment by wmaca** [comment]
@ashwinkumar6 I am not sure I understand when you say this is the expected behaviour, since it (the custom key storage) was implemented by me. I am not talking about Amplify's default behaviour.

So you are saying that the device key somehow is tied to the access/id/refresh tokens? If so, shouldn't this always happen, as I always clean those tokens?

These are the only preserved keys: https://github.com/aws-amplify/amplify-js/issues/10582#issuecomment-1323572329

As mentioned before, this issue is really hard to reproduce.

**Comment by ashwinkumar6** [comment]
> I am not sure I understand when you say this is the expected behaviour

AmplifyJS retains the deviceMetadata from the configured localStore while other information like last user, refresh tokens etc are cleared on operations like signOut

>So you are saying that the device key somehow is tied to the access/id/refresh tokens? If so, shouldn't this always happen, as I always clean those tokens?

Nope, device key isn't tied to these tokens (access/id/refresh). During signIn, the previously retained deviceMetadata (if present) from localStore is automatically used to generate the new tokens (access/id/refresh)

When the `NotAuthorizeException` error occurs could we check if the correct deviceKeys are passed

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
