### ISSUE TITLE
Trying Auth.signout to clear the cognito session, shows a pop-up "Appname" wants to use "amazoncognito.com" to Sign in

### ISSUE THREAD

**Issue by payalb** [aws-amplify/amplify-js#10723]
**Page**: [`/lib/auth/emailpassword/q/platform/[platform]`](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js)

**Feedback**:

When trying to use Auth.signout to clear the cognito session, shows a pop-up "Appname" wants to use "amazoncognito.com" to Sign in. Is there a way to prevent this pop-up from being shown?
<img width="957" alt="1" src="https://user-images.githubusercontent.com/18390065/177698776-27474d7d-3851-4488-b244-260b83df7dc4.png">

**Comment by nadetastic** [comment]
Hi @payalb 👋,

This appears to be unexpected behavior, as the SignOut method should not display this pop up. Could you clarify your use case a bit more?

I.E. Did you sign in with cognito user pools or social sign in? (`Auth.signIn` vs `Auth.federatedSignIn`) also since there has been a recent major release of Amplify (V5) can you confirm if you are still facing this issue and on what version?

**Comment by nadetastic** [comment]
Hi @payalb following up here, I'll close this out since it is a duplicate of #3410 please follow up with any comments on the other issue.

**Comment by ucheNkadiCode** [comment]
I have this exact issue as well
