### ISSUE TITLE
graphql API not handling auth rules how I’d expect

### ISSUE THREAD

**Issue by johnpc** [aws-amplify/amplify-js#10797]
### Amplify CLI Version

10.5.2

### Question

If there is an auth rule on an optional parameter, it shouldn’t prevent creating of the resource without that parameter

This model has an optional account_created field that only certain people have access to:

<img width="307" alt="image (7)" src="https://user-images.githubusercontent.com/4824042/207694744-ec135297-dc79-4625-b2e6-c9f186830dc3.png">

But when creating an instance of the model without including that optional parameter, there’s a permissions error

<img width="207" alt="image (8)" src="https://user-images.githubusercontent.com/4824042/207694861-a2f65b72-95c0-4271-a967-40b70d29f2c1.png">

This request throws an error like "Permission denied. Unable to access account_created field" or words to that effect. But why is access to the account_created field required to create an instance of this model?

**Comment by chrisbonifacio** [comment]
Hi @Cedric-Magnan, apologies for the delayed response.

Just want to point out that while the `account_created` field is optional, the `Permission denied. Unable to access account_created field` error is occurring because the auto-generated `createUser` mutation is probably including it in the selection set.

For example:

```graphql
mutation CreateUser(input: CreateUserInput!) {
    id
    first_name
    last_name
    email
    account_created
}
```

In order to create a `User` record without running into errors about permission to read protected field values, simply remove the field from the selection set. This means you'd have to manually create the graphql mutation string.

```diff
mutation CreateUser(input: CreateUserInput!) {
    id
    first_name
    last_name
    email
- account_created # remove this field 
}
```

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
