### ISSUE TITLE
Non expiring URLs from Storage.get

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-js#10815]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Storage

### Is this related to another service?

S3

### Describe the feature you'd like to request

I have an app where a user can upload their own avatar image.  This is done with `Storage.put` to a public location so that other authenticated users of the app can have access to it as needed.  I do not want to make the bucket public for non-authenticated users, though that would simplify the issue.

This is an image that will rarely--if ever--change once set, in most scenarios.

I have a use case where User A can view a list of items.  An item can be User A's or someone else's.  Each item displays an avatar image (if uploaded; otherwise a placeholder is used) for the item's owner.

The naive solution is to do a `Storage.get`  to retrieve a URL for the avatar on each item in the list.  The list can potentially have many items, so this seems inefficient.

I could jump through some hoops and write some code to extract all relevant avatar URLs on app init and place them in state somewhere, but that's kind of a pain and seems like more of a work-around than a proper solution.

Ideally, what would be nice, is if--when I get the `response.key` from the initial `Storage.put` upon uploading an avatar image--I could follow that with a get and retrieve a URL that **does not expire** and store it in a property of a User object in a db (I'm using FaunaDB for this project).

Presently `Storage.get` allows a max of `{expires: 604799}` in options.  I do not foresee users updating their avatars every two weeks, so after a couple weeks any URL generated using that would stop working.

It seems like there should be a way to store stuff in S3 using Amplify Storage and be able to access it without having to deal with this URL expiration issue.

If there is, I'd love to hear what the solution might be.  If not, I think it's well worth you folks considering a way make that happen.

Thanks!

### Describe the solution you'd like

I'd like a way to access objects from Storage w/o having to do a `Storage.get` that has an expiration date. 

### Describe alternatives you've considered

I've tried various work-arounds and none of them seem right.  I think the issue is Amplify's cap on the expiration.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Related to #9418

**Comment by nadetastic** [comment]
Hi @kimfucious 

Thank you for opening this issue. At this time, Amplify Storage supports the use of [pre-signed URLs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html) which will always expire. There is a work around that you can configure to get the public URL, however, it includes modifying the bucket permissions/policy (with [`amplify override storage`](https://docs.amplify.aws/cli/storage/override/) ) to make it public - which means that anyone on the web with the url would have direct access to the bucket.

Another potential alternative is if you manually configure the S3 Bucket to Amplify Storage (in other words using [`amplify import storage`](https://docs.amplify.aws/cli/storage/import/) instead of `amplify add storage`) then add the permissions you need to the S3 bucket to limit who can upload to the bucket, then after creating a CloudFront distribution separately, add the bucket as a CloudFront origin. Below are some links that discuss how to do this.

[1] https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-https-requests-s3/
[2] https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-s3-amazon-cloudfront-a-match-made-in-the-cloud/

Also keep in mind that if you would like for Amplify to manage the CloudFront distrubution, you can add it as a custom resource with `amplify add custom` which uses either the [CDK](https://docs.amplify.aws/cli/custom/cdk/) or [CloudFormation](https://docs.amplify.aws/cli/custom/cloudformation/).

**Comment by nadetastic** [comment]
Hi @kimfucious, following up - let me know if you have additional questions on this. Since this feature request already exists on #9418 , I'll close this out soon in favor of it

**Comment by kimfucious** [comment]
Thanks for all the info @nadetastic.

I'll implement something to work around this and hope the feature gets implemented someday.

**Comment by nadetastic** [comment]
@nijarv we are actively working on a solution for this, and so for all related updates please subscribe to #9418 as we are tracking this item there. Thank you!
