### ISSUE TITLE
Option to disable lazy loading on DataStore

### ISSUE THREAD

**Issue by duckbytes** [aws-amplify/amplify-js#10913]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

DataStore

### Describe the feature you'd like to request

I've been working on updating my project to use the latest version of DataStore. There are some breaking changes, and a lot of code has to be rewritten.

Updating code to work with lazy loading has been quite challenging. Particularly because in many places I access nested records in React components. A React function component can't be async, so I can't add await to resolve fields. I have to resolve them in a separate function instead and change the type to fit it.

### Describe the solution you'd like

I would like the option to disable lazy loading until I am ready to fully switch over.

This will let me focus on refactoring my code to use the new query and filtering syntax, so that I can be up to date sooner, but not have to think about lazy loading.

I can see that there is a class LazyLoadingDisabled in node_modules/@aws-amplify/datastore/lib-esm/types.d.ts (which confusingly has one field `disabled: true`).

One solution would be to add a flag to amplify codegen models, something like --disable-lazyloading and have the generated types use Eager instead of Lazy types.

### Describe alternatives you've considered

The alternative is to continue refactoring my code until everything works again.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by dpilch** [comment]
Hi @duckbytes, unfortunately it is unlikely that will add such functionality. The `LazyLoadingDisabled` type you found is meant to keep the generated types backwards compatible with V4 of the library. This allowed us to push the type changes to codegen without needing a feature flag on the CLI (something we are trying to avoid). The generated types would be able to conditionally select the eager or lazy types based on the library version in use.

Even if we gave the option to only generate the eager types the library would no longer be compatible with these types. The library now uses lazy loading and the eager implementation was not kept in the codebase for V5.

I recommend something like the following to wait for the lazy items to load.


```graphql
type Foo @model {
  name: String
  bar: Bar @hasOne
}

type Bar @model {
  name: String
}
```

```jsx
import { AsyncItem } from '@aws-amplify/datastore';
import { Bar } from './models';

function BarWidget(bar: AsyncItem<Bar>) {
  const [loading, setLoading] = useState(true);
  const [loadedBar, setLoadedBar] = useState<Bar | null>(null);

  useEffect(() => {
    bar.then((b) => {
      setLoadedBar(b);
      setLoading(false);
    })
  }, [bar]);

  return (
    <div>
    {loading
      ? <spinner/>
      : <span>{loadedBar.name}</span>
    }
    </div>
  );
}
```

Another good option would be to move this functionality to a HOC.

```
unwrapLazyBar(BarWidget);
```

Where `BarWidget` is expecting the `Bar` type already unwrapped from `AsycnItem`.

**Comment by duckbytes** [comment]
Ah thanks @dpilch, I had a feeling that might be the case, but thought I'd ask anyway.

Thanks for the code suggestions too.

**Comment by SebSchwartz** [comment]
@dpilch 
I really don't understand why this breaking change is happening and why an optional flag for lazy models or not is not on the table...
We are using datastore since 4 years and this change would made us rewrite our all application...

First of all, the previous version was ok for simple link (Post -> Author) but not ok for N-N relations. What we did was to handle ourself this case and map in our code the objects. We have a project with more than 40 tables.

Our problem with this new breaking implementation is that our models are no more ok for the backend and some utility method using the same model in front and back may not work anymore as we could not call a simple post.author.name as we used to do before. The new Lazy generated types are then no more usable :( And the API generated types is having a problem with the __typename field present everywhere and that they may not be used by DataStore. 

So 3 years ago, we moved from Apollo Client to Datastore (as it was no more supported) and now we have to rewrite everything if we want to keep using datastore. We are considering using another library because those king of breaking change cannot be tolerated for larger production application.

Do you see or can you suggest a solution that we can use so we don't have to rewrite everything inside the app?
All we want is to keep using Datastore, keep using Eager generated types with direct link in our code and manage the lazy loading in some context giving the new models without AsyncItem<> for connections.

Thanks,
Sebastien
