### ISSUE TITLE
react native imports not working

### ISSUE THREAD

**Issue by philipheinser** [aws-amplify/amplify-js#10952]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

metro

### Please describe your bug.

error: Error: Unable to resolve module @aws-amplify/core from /Users/user/apps/pf-app-react/node_modules/aws-amplify-react-native/dist/Interactions/ChatBot.js: @aws-amplify/core could not be found within the project or in these directories:
  node_modules/aws-amplify-react-native/node_modules
  node_modules
> 1 | var _interopRequireDefault=require("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(exports,"__esModule",{value:true});exports.default=exports.ChatBot=void 0;var _regenerator=_interopRequireDefault(require("@babel/runtime/regenerator"));var _toConsumableArray2=_interopRequireDefault(require("@babel/runtime/helpers/toConsumableArray"));var _classCallCheck2=_interopRequireDefault(req

### What's the expected behaviour?

no import error

### Help us reproduce the bug!

installed amplify for react native according to the docs

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by cwomack** [comment]
@philipheinser, I've run through the existing React Native docs for installing/getting started with Amplify and didn't run into the error you've referenced.  Since we haven't heard back and there's no details of your Amplify version/link to docs that might have caused this, I'll close this issue down for now.  

Please feel free to reply back with what version of Amplify you're currently on and any links/references to the docs that might have led to this so we can update them.  We'd be happy to reopen the issue and assist further!
