### ISSUE TITLE
re-export isAxiosError from axios

### ISSUE THREAD

**Issue by aviv-skillset** [aws-amplify/amplify-js#10969]
### Is this related to a new or existing framework?

Angular, React, React Native, Vue, Web Components, Next.js, New framework

### Is this related to a new or existing API?

REST API

### Is this related to another service?

nope

### Describe the feature you'd like to request

since Axios is imported by Amplify, and `AxiosError` can be thrown, it should allow me to import both the interface and the type-guard without explicitly importing from Axios as an extraneous package or explicitly installing Axios.

### Describe the solution you'd like

your end: 
```ts
import axios from 'axios';
export const isAxiosError = axios.isAxiosError;
export type { AxiosError } from 'axios';
```

my end:
```ts
import { API, isAxiosError, AxiosError } from 'aws-amplify';

function handleTypesafeError(error: AxiosError) {
    return error.toJSON();
}

try {
  const payload = await API.get('api', '/broken-route');
  await functionThatMayThrowOtherTypeOfError();
  ...
} catch (error) { //error is either any or unknown, depends on `tsconfig.compilerOptions.useUnknownInCatchVariables`
  if (isAxiosError(error)) {
    return handleTypesafeError(error);
  }
}
```
### Describe alternatives you've considered

using azure instead 🙃

### Additional context

If you would like me to make a PR, I may do it from @avivnakar

### Is this something that you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by TamirFriedman-RecoLabs** [comment]
+1

**Comment by cwomack** [comment]
Hello, @aviv-skillset and @TamirFriedman-RecoLabs With the release of the latest major version of Amplify (aws-amplify@>6), this feature request won't be applicable.  We'd encourage everyone to upgrade to v6 if possible and you can refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

As for v5.x of Amplify, I'd recommend that you just install `axios` and use the type guard directly since it's already in your `node_modules` via Amplify.  Can you let me know if that would be an acceptable workaround? Thanks!
