### ISSUE TITLE
React Native: Replace Async Storage with React Native MMKV

### ISSUE THREAD

**Issue by ponikar** [aws-amplify/amplify-js#11070]
### Is this related to a new or existing framework?

React Native

### Is this related to a new or existing API?

Storage

### Describe the feature you'd like to request

Since the new architecture has come and JSI modules have been introduced there is a brand new way to communicate between the JavaScript world and Native World. You can read more about this in react-native official documents. 

one of the stable and fast libraries is react-native-mmkv which has built on top of the JSI modules. Which is 30x faster than Async Storage and I think this is a good time to think about replacing the AsyncStorage with MMKV. 

I can understand it can break the existing code we can let developers decide what they want to use as storage to store data.

As React Native developer, I think the Async library is too slow and can lead bad user experience. It's time to rethink how to store data locally on a user's device.

### Describe the solution you'd like

Let developers opt in for [react-native-mmkv ](https://github.com/mrousavy/react-native-mmkv)in a future release. 

### Describe alternatives you've considered

If anyone or myself can raise a PR to choose between Async Storage or react native mmkv that would be great.

### Additional context

New Architecture documentation link: https://reactnative.dev/docs/new-architecture-intro
React Native MMKV library link: https://github.com/mrousavy/react-native-mmkv

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by tannerabread** [comment]
Hi @ponikar, I appreciate you opening this feature-request and adding all of the extra documentation. We do have an existing feature-request #8968 asking for the same thing so in order to reduce duplication, I will close this one for the other.

To answer your question about the PR though, if you would like to contribute please follow [these guidelines](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md).

Thank you for taking the time to bring this to our attention and please follow/thumbs up the other issue so we can prioritize it better.
