### ISSUE TITLE
getServerSideProps + SSR.Auth.currentSession() is failing when a page is linked from an external website

### ISSUE THREAD

**Issue by phstc** [aws-amplify/amplify-js#11350]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Describe the bug

This is a separate issue for https://github.com/aws-amplify/amplify-js/issues/10290#issuecomment-1492213550

`getServerSideProps` + `SSR.Auth.currentSession()` is failing with "No Current User" when a page is linked from an external website.

Using this sample project https://github.com/phstc/cognito-amplify-cdk-10290 - if you click here http://localhost:3000/works-ssr (from this GitHub comment), it fails with No Current User, but if you copy http://localhost:3000/works-ssr and paste that into your browser, it works. 

Links from external websites (Gmail, GitHub, Slack, etc.) fail, but if you enter the URL directly or if it's a link within localhost (or whatever app domain), it works.

### Expected behavior

`getServerSideProps` + `SSR.Auth.currentSession()` should work no matter how the page is loaded. 

### Reproduction steps

1. Get this sample project running https://github.com/phstc/cognito-amplify-cdk-10290
2. Click here http://localhost:3000/works-ssr (from this GitHub comment)
3. It will fail
4. Copy and paste `http://localhost:3000/works-ssr`, and it will work

**Comment by phstc** [comment]
I believe I have found a solution. It works enabling `cookieStorage` without enabling it, I believe it defaults to localStorage, and it  does not work with some  external links, for example, when opening links from GitHub: http://localhost:3000/works-ssr.

I don't know why it does not work, but adding a `cookieStorage` seem to be working now. Still, feels like a bug, and can be very time-consuming to figure out what's going on.

**Comment by steoo** [comment]
adding a `cookieStorage` where? to what?

**Comment by phstc** [comment]
@steoo to the `Amplify.configure` call. 

```javascript
const amplifyConfig = {
  ssr: true,

  Auth: {
    // ... 
    cookieStorage: {
      domain: process.env.NEXT_PUBLIC_AUTH_COOKIE_DOMAIN,
      secure: true
    }
  }
}

Amplify.configure(amplifyConfig)
```

**Comment by nadetastic** [comment]
Hi @phstc following up here - I've discussed this with the team and wanted to share - this wouldn't be a bug and is expected. In short, `withSSRContext()` expects cookies to be passed in which will establish the session, however the browser didn’t send cookies since the request originated from an external domain and caused your original (No current user) issue.

It seems that the reason setting up cookieStorage works is because in your cookieStorage config, sameSite is not set, and in most of browsers if sameSite is unset, it behaves as lax, and the browser will send the cookies.

Additionally, a different possible workaround can be to instead check the Referer of the incoming http request, and if it is from an external domain, you can redirect to the requested URL again, which should then include the cookies in this second request.
