### ISSUE TITLE
SvelteKit support

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-js#11421]
### Is this related to a new or existing framework?

New framework

### Describe the feature you'd like to request

I along with many others are running into some issues trying to use sveltekit with aws amplify. I'm not sure if there is a formal feature request to get support for it or if it is being worked on to be supported by aws amplify. 

### Describe the solution you'd like

Ui components could be good eventually but even just getting it to work more easily or have simple guide would be great. I've managed to get around many of the gotchas but can't get it to build. Even if I somehow figure this part out it seams like there should be a more guided approach for using sveltekit with aws amplify

### Describe alternatives you've considered

https://github.com/aws/aws-sdk-js/issues/3673
aws-amplify/amplify-js#9639
https://github.com/aws-amplify/amplify-console/issues/1298
https://github.com/aws-amplify/amplify-console/issues/2318
https://github.com/aws-amplify/amplify-js/issues/9056

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by reesscot** [comment]
Transferred back to JS repo, as this is primarily related to SvelteKit support in main Amplify JS library.

**Comment by nadetastic** [comment]
Related to https://github.com/aws-amplify/amplify-js/issues/12578

**Comment by nadetastic** [comment]
With Amplify JS v6 we provide an adapter for only Next.js, although the underlying generic adapters may be used with other frameworks. You can find documentation on how to use the generic adapters here - [docs.amplify.aws/react/build-a-backend/server-side-rendering](https://docs.amplify.aws/react/build-a-backend/server-side-rendering/)

**Comment by nadetastic** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free [to reply and subscribe on this issue](https://github.com/aws-amplify/amplify-js/issues/12578).

Thank you!

**Comment by benmccann** [comment]
Leaving a link here for anyone who comes across this issue, so that they're aware there's now a SvelteKit Amplify adapter: https://github.com/gzimbron/amplify-adapter. The full list of adapters is available on https://www.sveltesociety.dev/packages?category=sveltekit-adapters - a few platforms have multiple adapters available

If anyone from AWS is interested in adding official first-party support for SvelteKit, please ping me and I'd be happy to add you to SvelteKit's partners program so that you can get direct support from the maintainers in supporting your integration

**Comment by dlamon1** [comment]
Sweet
