### ISSUE TITLE
Login with userpool works but not able to get credentials

### ISSUE THREAD

**Issue by epicfaace** [aws-amplify/amplify-js#1153]
When I log in with a user from my user pool from the AWS amplify component, the login completes successfully. Even my `onAuthStateChange` callback is called properly with the auth data. However, when I then try to call `Auth.currentSession()`, it gives me an error, "No current user". Any idea what I'm missing here?

**Comment by Rhymond** [comment]
I'm getting the same exact problem. On my localhost running `Auth.signIn` and it looks like that it goes trough successfully, because I can `console.log` output where I can see Session token. I checked localstorage and it looks like it's empty and as @epicfaace mentioned by calling`currentSession()` I get "No current user" too (I bet because localstorage is empty). I tried to use `Cache` library to check if amplify can write to LocalStorage, and by calling `Cache.setItem("test", "test")` new record in LocalStorage appeared. 

I attached my console:
![screen shot 2018-07-17 at 20 35 39](https://user-images.githubusercontent.com/3577968/42841141-087a9180-8a01-11e8-843c-9aa813ceab2b.png)

Here you can see I'm loggin output from `Auth.signIn` and after resolved promise I called `Auth.currentSession` which return rejected promise with "No current user"

**Comment by epicfaace** [comment]
@Rhymond, I found the issue, it seems like a known issue in the amplify library. Remove the `cookieStorage` object from the aws amplify config and it should work then, assuming your user pool is configured properly.

**Comment by Rhymond** [comment]
@epicfaace Thanks! My issue was different, just found a fix.
My user was with status `FORCE_CHANGE_PASSWORD` which doesn't let it login. I created user using `Auth.signUp` and it worked.

**Comment by noetix** [comment]
`FORCE_CHANGE_PASSWORD` was my issue too when trying to auth an admin created user.

See https://github.com/aws-amplify/amplify-js/issues/24 for solution.

**Comment by jordanranz** [comment]
Going to close this as the issue seems to have been solved. Please reopen if there are any related questions or concerns.
