### ISSUE TITLE
Username is different in Auth.currentAuthenticatedUser and signInUserSession.accessToken.payload - Why? 

### ISSUE THREAD

**Issue by biller-aivy** [aws-amplify/amplify-js#11554]
### Amplify CLI Version

10.5.2

### Question

Username is different in Auth.currentAuthenticatedUser and signInUserSession.accessToken.payload - Why? 

In Auth.currentAuthenticatedUser the Username is the Mail Adress. 
In signInUserSession.accessToken.payload the username is the sub.

**Comment by cwomack** [comment]
Hello, @biller-aivy 👋.  The difference you're seeing between the two methods is a result of how each one accesses the information/username for an authenticated user.  

- If already signed in, the `Auth.currentAuthenticatedUser()` call will grab the user object directly from local storage rather than the server (Cognito side).  This will usually contain the username (typically an email address) along with other attributes if you've optionally enabled them for users.  

- Calling the `signInUserSession.accessToken.payload()` will actually grab the user’s information related to the Cognito session from the fields within the access token’s payload, including the sub field ([see Cognito docs](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-access-token.html#:~:text=%3Ctoken%20signature%3E-,sub,sub%20claim%20is%20the%20best%20way%20to%20identify%20a%20given%20user.,-cognito%3Agroups)) that will usually map to the username.  The `sub` is a UUID however so if there are duplicate, non-unique usernames within a user pool... the`sub` _could_ be something different (though not common). 

So based on what you've described, it sounds like you're seeing the expected behavior for each of these methods.  Hope this helps clear things up, but let me know if there's any more questions you have tied to this!

**Comment by biller-aivy** [comment]
I understand, but the I guess the username should be always the same value? 

So when i have to call a function which needs the username than i want expect that every developer can use the username and it is always the same in the amplify universe.

**Comment by cwomack** [comment]
@biller-aivy, it sounds like you're just wanting to make sure that the function being used will always retrieve the username of the currently logged in user when called.  Is that right?  If so, then the `Auth.currentAuthenticatedUser()` should take care of this since it will have already gone through Amplify's Authentication flow and verified the user/obtained tokens from Cognito on the server side. Once called, you will have access to the `user` object and can store the `user.username` in a variable as needed.

If you're using email addresses as usernames then you'd need to access the email via `user.attributes.email` or destructure the `user` object returned by `Auth.currentAuthenticatedUser()` as shown in our documentation [here](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#retrieve-user-attributes).  

It might be helpful to share how you configured the Auth category/Cognito user pools as well so that I can assist further.  Thanks!

**Comment by cwomack** [comment]
@biller-aivy, after reviewing this issue again internally I wanted to get a little more clarity.  What is the login mechanism that you're using (e.g. phone number, email, username) and what does the code look like for your sign up methods?  Want to make sure we're giving you the proper guidance on this.  Thanks!

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
