### ISSUE TITLE
Improve typescript types

### ISSUE THREAD

**Issue by abarke** [aws-amplify/amplify-js#11723]
### Is this related to a new or existing framework?

Vanilla

### Is this related to a new or existing API?

Authentication

### Is this related to another service?

no

### Describe the feature you'd like to request

Add types for the following function: [Signer.sign](https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/Signer.ts#L52)

Additionally it is not clear what the [request.data](https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/Signer.ts#L30) should be 

I see quite that the `any` type is used quite often in places. This could be improved for better DX.

### Describe the solution you'd like

Strict types

### Describe alternatives you've considered

None

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
@abarke, wanted to follow up after reviewing this issue with the team internally.  The items you've outlined in this issue are already on our team's radar actually and will be addressed in the next major version.  I've already linked this issue with the TypeScript RFC with my previous [comment](https://github.com/aws-amplify/amplify-js/issues/11723#issuecomment-1665809472), so your requests should be captured there as well.  

I'll close this issue out in favor of the TypeScript RFC due to it containing all the TS improvements consolidated into one issue.  We appreciate you taking the time to open this issue and please refer to the RFC if you want to see other improvements we have on our radar for TS types in Amplify.  Thanks!
