### ISSUE TITLE
Load signup component at first withAuthenticator

### ISSUE THREAD

**Issue by yasithph** [aws-amplify/amplify-js#1189]
Signin page is what loads first instead of sign up when using withAuthenticator. Can I load the signup page at first?

**Comment by powerful23** [comment]
I am afraid you can't for now.

**Comment by yasithph** [comment]
The component loads with the initial state sign-in. Is there a way to change the state for example using changeState? @powerful23

**Comment by powerful23** [comment]
Hey maybe you can try using `Authenticator` directly and  pass the authState into Authenticator manually like: `<Authenticator authState='signUp'/>` so the initial state would be `signUp` instead of `signIn`.

**Comment by yasithph** [comment]
Thanks. I will check this and let you know whether this works. @powerful23

**Comment by powerful23** [comment]
@yasithph does this work for you? I am going to close this issue. Feel free to reopen if you still have this issue.

**Comment by jagregory** [comment]
Setting `authState='signUp'` doesn't work, because when the Authenticator component is mounted it calls `Auth.currentAuthenticatedUser()` and sets then goes through the signout flow, resulting in authState being set to `signIn` again. See: https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/Authenticator.jsx#L58

As far as I can tell, there isn't a way to show the sign up page declaratively.

**Comment by powerful23** [comment]
@jagregory good catch, will try to fix this later on.
