### ISSUE TITLE
Auth.setupTOTP silently disables TOTP if it's currently enabled

### ISSUE THREAD

**Issue by tomquisel** [aws-amplify/amplify-js#1226]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**

This is an issue with Amplify's Auth module, specifically `Auth.setupTOTP`.

We have a "Change MFA" button for the case where a user wants to change their TOTP MFA secret and already has MFA enabled. If the user clicks it, the app calls `Auth.setupTOTP` to show the user the new QR code. The bug occurs if the user cancels the process at this point: their `User.PreferredMFASetting` as reported by Cognito is still `SOFTWARE_TOKEN_MFA`, but their MFA is in fact disabled. Future signins (even from different devices / using incognito) will not prompt for an MFA code.

**The expected behavior is:**

1. Starting but not completing the setup of a new TOTP secret should not silently disable the old TOTP configuration.
1. If TOTP is disabled, there should be some indication (`User.PreferredMFASetting` should reset to `null`).

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**

All versions.

**Comment by powerful23** [comment]
@tomquisel are you using `aws-amplify-react` for this issue?

**Comment by tomquisel** [comment]
@powerful23 no, just `aws-amplify`

**Comment by powerful23** [comment]
@tomquisel thanks for the quick reply. I am now trying to reproduce this error. Can you provide some code snippets?

**Comment by powerful23** [comment]
The `setupTOTP` won't do anything to the `preferredMfaSetting`. You need to call `Auth.setPreferredMFA(user, 'TOTP')` to change that. So the logic I think is:
1. when clicking the change MFA button, first call `Auth.setPreferredMFA(user, 'TOTP')`
2. If the user has already setup the totp, then he will successfully change the mfa method to totp
3. If the user hasn't setup the totp, the function will throw an error, and you can then call `setupTOTP`
4. If the user finishes the whole verification process, call that `Auth.setPreferredMFA(user, 'TOTP')` again.
5. If the user drops the process, then you should do nothing about that since this process has been canceled, The mfa setting should remain as before.

**Comment by tomquisel** [comment]
@powerful23 Thanks for explaining that. What you describe sounds like a flow for:

1. Allowing users with TOTP MFA enabled to sync their MFA preference up to their setting
1. Allow users who do not have TOTP enabled to enable it

My goal is to allow a user with TOTP enabled to _change_ their TOTP secret without accidentally disabling their TOTP entirely. What flow do you recommend for that?

**Comment by powerful23** [comment]
@tomquisel I see. I will reproduce that and see how it works in this case. Thanks for you feedback.

**Comment by timwhunt** [comment]
The Cognito team does recognize this as an issue. We will fix it, but I cannot provide a timeline.

**Comment by mjmaix** [comment]
I don't think this should be closed @stale

**Comment by sammartinez** [comment]
This seems to be resolved. @tomquisel can you please confirm thanks!

**Comment by andrecadete** [comment]
I will assume the issue I'm seeing is related to this and in that case it's not solved at all. 

It still silently changes the MFA method when logging in "randomly". My use case:

SOFTWARE_TOKEN_MFA is set as preferred yet sometimes when logging in it send an SMS. Just yesterday I logged in multiple times with SOFTWARE_TOKEN and thought maybe this was something I did wrong before. To my surprise this morning the issue came back. Even though the user already signed in multiple times with the software token and the Cognito user still shows preferred mfa method as software token (`"PreferredMfaSetting":"SOFTWARE_TOKEN_MFA"`), he will get an SMS challenge and not a software token challenge.

I haven't done tests with having only SMS MFA setup to see if it falls back to no MFA at all. But judging from the description of this issue it seems to be related.. Not sure if it's a cognito pool or an implementation issue, but this causes a lot of hassle to our users and extra costs for us as a company. Plus it looks really bad that we request our customers to setup a Mobile authenticator for "extra security" and then they still get an SMS for logging in. 

PS: I'm calling amazon-cognito-identity-js methods directly as I do not wish to integrate anything from amplify but last I saw in your codebase it should have the same behaviour and amazon-cognito-identity-js belong to the amplify repository.

**Comment by rosspace** [comment]
This seems to be the root cause for issue #7254 - I was able to work around it by switch MFA to SMS, then setting to NOMFA, then I had to be careful to only make one call to setupTOTP() before verifying it.

**Comment by donal-s** [comment]
I'm currently still experiencing this problem (aws-amplify/auth v3.4.17). The use case is:

- Cognito user pool with optional MFA
- User sets up TOTP MFA ( `Auth.setupTOTP(user)` to get the QR challenge, `Auth.verifyTotpToken(user, code)` to verify the software token, then `Auth.setPreferredMFA(user, 'TOTP')` to set the preferred MFA to `SOFTWARE_TOKEN_MFA`
- User login now correctly uses the TOTP MFA challenge

All good. Now:

- User logs in
- User wants to reset their software token (or setup on a new device). Code calls `Auth.setupTOTP(user)` to get the QR challenge.
- User changes their mind, or cancels for other reasons. `Auth.verifyTotpToken(user, code)` is not successfully called.
- User logs out and logs back in again.

Here are the problems:

1. User preferred MFA is still `SOFTWARE_TOKEN_MFA`
2. User login however operates as `NOMFA` - there is no TOTP challenge
3. Attempts to call `Auth.setPreferredMFA(user, 'NOMFA')` fail with the error message `"User has not verified software token mfa"`

Number 2 is understandable - the incomplete TOTP reset/setup means the user may not be in a good state to login using TOTP anymore, so reverting to `NOMFA` is going to prevent users locking themselves out. However number 1 means the UI is still reporting the preferred MFA is still `SOFTWARE_TOKEN_MFA` even though its no longer being used.
More annoying though is number 3 - if a user who previously had TOTP setup aborts a TOTP reset, they are stuck in this error state (their preferred MFA being reported as `SOFTWARE_TOKEN_MFA` when in fact they can't login with TOTP) until they successfully do complete `Auth.verifyTotpToken`.

rosspace's [workaround](https://github.com/aws-amplify/amplify-js/issues/1226#issuecomment-747658565) doesn't work if SMS MFA is not set up for the user.

The behaviour I'd expect here is either:

1. An aborted TOTP reset leaves the previous TOTP setup alone. Preferred MFA is still `SOFTWARE_TOKEN_MFA` and user login requires TOTP verification using the previously set up device. If the user no longer has that TOTP setup available when logged out, then they can do a standard password reset using the existing mechanism.

or

1. An aborted TOTP for a user in a Cognito user pool with optional MFA sets the preferred MFA to `NOMFA`, and it is therefore clear that they have nuked their existing TOTP setup and need to redo it if they want to use it. In the meantime they are logging in with no MFA.
2. An aborted TOTP for a user in a Cognito user pool with required MFA reverts to the state a brand new user would be in when they first attempt to log in and are required to setup TOTP.

A workaround in code for now (in the case of optional MFA user pool) that seems to work is when the user has preferred MFA to be `SOFTWARE_TOKEN_MFA` and want to reset the token, call `Auth.setPreferredMFA(user, 'NOMFA')` before calling `Auth.setupTOTP(user)` (and finally  `Auth.setPreferredMFA(user, 'TOTP')` if the verification succeeds). Then if the process is aborted, the preferred MFA reflects what the user is actually able to do from then on.

**Comment by houmark** [comment]
Still an issue, experiencing exactly the same as @donal-s — I'd expect Cognito to automatically cleanup to `NOMFA` automatically on reset when calling `Auth.setupTOTP` so that it will become `SOFTWARE_TOKEN_MFA` if the user fully re-enrolls 2FA by calling `Auth.verifyTotpToken` with the correct TOTP token.

If that's not possible, then `Auth.setPreferredMFA(user, 'NOMFA')` should at least not fail, so we can manually reset it when re-enrolling a user.

As is, MFA can get into an inconsistent state with no way to fix it.

**Comment by garrettmaring** [comment]
It's very concerning if this (calling `setupTOTP` twice silently breaks MFA auth challenge flow). I'm not receiving `challengeName` after signing in for a user that has MFA preferred to `SOFTWARE_TOKEN_MFA` (I should receive a challenge). I'm now wondering if it's because setupTOTP was called a couple times.

**Comment by ericwhitefield** [comment]
We're having the same problem. The worst part is that the Cognito API is incapable of reporting its true internal state for TOTP via GetUser.

Internally Cognito has one place to store an SMS MFA and one place for TOTP MFA. So changing either option implies a "break-before-make" procedure.

This causes a problem with both types of MFA. Each has a different problem. But this thread is about the TOTP problem.

This is how TOTP 'enabled state' is reported ... 

Before A user enabled TOTP: UserMFASettingList: [ '' ]

After a user generated a TOTP secret (QR code): UserMFASettingList: [ '' ]

After the user confirmed the secret: UserMFASettingList: [ '' ]

After the user enabled TOTP: UserMFASettingList: [ 'SOFTWARE_TOKEN_MFA' ]

After the user generated a NEW secret: UserMFASettingList: [ 'SOFTWARE_TOKEN_MFA' ]

What is important is this final state. After generating a new secret TOTP is essentially disabled. However, the state reported is exactly the same as when TOTP was enabled. The login behavior will be as if the user never configured TOTP.

Cognito team knows this to be true. It's documented, that in this state, the login will behave as if TOTP is NOT enabled. That's a problem because UserMFASettingList indicates that it IS enabled.

Then, to make matters worse, the user can not DISABLE the TOTP option via setUserMfaPreference.

SetUserMFAPreference will report error "User has not verified software token mfa".

This is a problem because removing SOFTWARE_TOKEN_MFA from UserMFASettingList would align the GetUser report with the current behavior. Which is that TOTP is disabled.


Note this differs from SMS MFA:

With SMS MFA we get a bit more information. There is a UserAttributes.phone_number_verified. When a new phone_number is set then phone_number_verified is automatically set to false by Cognito.

There is no equivalent UserAttribute for TOTP, such as: 'totp_verified'.

The equivalent "unverified scenario" for SMS is also handled differently at the Login. With TOTP the Login will behave as if no TOTP is enabled. With an unverified SMS Cognito will send a code to that phone, even though it was never verified.

**Comment by gabipfeffer** [comment]
Any updates on this? Having the same issues as @donal-s

**Comment by bestis** [comment]
This is kind of annoying. You cannot get the proper state is software MFA enabled. You can get if it is preferred. But being preferred it doesn't mean that is enabled.

Also didn't find any way to get the status is it really enabled. This seems a huge lack of the API.

So what I did?

1. Get preferred MFA: `Auth.getPreferredMFA(cognitoUser)`
2. If 'NOMFA' => MFA is not on.
3. If 'SOFTWARE_TOKEN_MFA' => Try to set it back as preferred: `Auth.setPreferredMFA(cognitoUser, 'TOTP')`
4. If setting succeeds => MFA is on, if it fails => MFA is not on.

**Comment by JandenMa** [comment]
> It's very concerning if this (calling `setupTOTP` twice silently breaks MFA auth challenge flow). I'm not receiving `challengeName` after signing in for a user that has MFA preferred to `SOFTWARE_TOKEN_MFA` (I should receive a challenge). I'm now wondering if it's because setupTOTP was called a couple times.

I met the same issue today, it drove me so crazy until I saw this comment. I put the `setupTOTP` in a `useEffect` hook, and it had been invoked again the dependency changed. Thanks 😊

**Comment by zirkelc** [comment]
The workaround from @donal-s (https://github.com/aws-amplify/amplify-js/issues/1226#issuecomment-774097887) did work for me, however I would like avoid such a workaround in the first place. 

@powerful23 @timwhunt are there any updates from the Cognito team on this?

**Comment by jamesaucode** [comment]
Hi everyone, the Cognito team recently rolled out a change that fixes this behavior. Calling `Auth.setupTOTP` with a user that already has an existing MFA setup will no longer silently disable their MFA.

I have tested it with userpools on the following regions and I can confirm its working as intended: 
- ca-central-1
- us-west-1, 2
- us-east-1, 2
- eu-west-1,2,3
- eu-central-1
- eu-north-1
- ap-south-1
- ap-northeast-1,2
- ap-southeast-1,2
- sa-east-1
