### ISSUE TITLE
aws-aplify V6 > now no longer works with JEST Tests signIn() and fetchAuthSession()

### ISSUE THREAD

**Issue by JayMax23** [aws-amplify/amplify-js#12751]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Before upgrading from V5.10.** to v 6.0.9 you could use Typescript + JEST to use teh signIn() function.

However, since the implementation of breaking changes in V6, you now can not longer authenticate against the signIN() function using JEST. Rendering API Automation ineffective

What happens is when JEST tries to action : 
```js
            await signIn({ username, password });

            const cognitoTokens = (await fetchAuthSession()).tokens;
            return cognitoTokens?.idToken;
```

JEST will now always throw the following Error:

```
       at getCrypto (/Users/****/Source/****/node_modules/@aws-amplify/core/src/utils/globalHelpers/index.ts:15:11)
        at cryptoSecureRandomInt (/Users/****/Source/****/node_modules/@aws-amplify/core/src/utils/cryptoSecureRandomInt.ts:12:49)
        at WordArray.random (/Users/****/Source/****/node_modules/@aws-amplify/core/src/utils/WordArray.ts:41:73)
        at getRandomBytes (/Users/****/Source/****/node_modules/@aws-amplify/auth/src/providers/cognito/utils/srp/getRandomBytes.ts:15:41)
        at generateRandomBigInteger (/Users/****/Source/****/node_modules/@aws-amplify/auth/src/providers/cognito/utils/srp/getAuthenticationHelper.ts:35:97)
        at getAuthenticationHelper (/Users/****/Source/****/node_modules/@aws-amplify/auth/src/providers/cognito/utils/srp/getAuthenticationHelper.ts:23:15)
        at handleUserSRPAuthFlow (/Users/****/Source/****/node_modules/@aws-amplify/auth/src/providers/cognito/utils/signInHelpers.ts:236:73)
        at signInWithSRP (/Users/****/Source/****/node_modules/@aws-amplify/auth/src/providers/cognito/apis/signInWithSRP.ts:39:135)
        at signIn (/Users/****/Source/****/node_modules/@aws-amplify/auth/src/providers/cognito/apis/signIn.ts:35:53)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at Function.authenticateAndGetToken (/Users/****/Source/****/support/utils/cognito/cognito-user-management.ts:85:13)
        at Object.<anonymous> (/Users/****/Source/****/test/cognito/cognito-create-user.spec.ts:27:27) {
      underlyingError: undefined,
      recoverySuggestion: undefined,
      constructor: [class AmplifyError extends Error]`

```

Please FIX so we can use aws-amplify and a framework that is used worldwide 

### Expected behavior

Work without now throwing. the Pollyfil Error!

### Reproduction steps

1. Install AWS-Amplify
2. Install JEST
3. Setup a JEST Test to SignUp() > ConfirmConfirmationCode() > SignIn
4. Run
5. watch it exploded in Terminal

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @JayMax23.  Can you clarify if this is happening locally or with a deployed app? And since you've recently upgraded from `V5.10.** to v 6.0.9`, will you see if deleting your `node_modules` folder along with your `package-lock.json` and then reinstalling dependencies with `npm install` helps relieve the errors? Thanks!

**Comment by JayMax23** [comment]
Hi @cwomack 

I removed my node-moduels, i trined version 6..03 i also did a npm ci. None of this resolved the issue

The issue is specifically inside this file:
`import { AmplifyError } from '../../errors';

export const getCrypto = () => {
	if (typeof window === 'object' && typeof window.crypto === 'object') {
		return window.crypto;
	}

	// Next.js global polyfill
	if (typeof crypto === 'object') {
		return crypto;
	}

	throw new AmplifyError({
		name: 'MissingPolyfill',
		message: 'Cannot resolve the `crypto` function from the environment.',
	});
};

`

@aws-amplify > core > src > utils > globalHelpers > index.ts

**Comment by georgevicbell** [comment]
Note this seems to also be happening when you try to use signIn on lambda in v6/node18...(we login as a service user to perform actions).

Likely should not be getting crypto from window...since window may not exist everywhere...

<img width="1179" alt="Screenshot 2023-12-28 at 3 17 39 AM" src="https://github.com/aws-amplify/amplify-js/assets/4380159/5c0b9a70-373c-41d4-8bc0-ff6933a11d28">

**Comment by JayMax23** [comment]
@cwomack  Any update on this please. Having to add hacks in code is nasty

**Comment by liam-ot** [comment]
Also having this issue using node v18.x while using aws-amplify@6.0.17

**Comment by cshfang** [comment]
Hi @JayMax23. I would like to break down your issue in two parts and will try to address them both the best I can.

1. The goal of unit testing should be to isolate written code functionality. Generally speaking, when unit testing code which incorporate third party dependencies (e.g. Amplify), you should not be directly executing code against it - particularly when executing the code would lead to network or other upstream API calls - as is the case for the Amplify APIs mentioned here. I would strongly encourage that you instead mock out the Amplify functions in your unit tests so that your unit tests are testing the most important parts of your code - your code.
2. Next, I want to address what you can do if you must or simply want to break unit test conventions to fully exercise Amplify APIs in your dependencies. Amplify requires `crypto` in its auth API operation and does rely on the browser implementation. When running in Jest, `crypto` would indeed be inaccessible in the [default environment](https://jestjs.io/docs/configuration#testenvironment-string) (i.e. Node). However, I believe using [jsdom](https://github.com/jsdom/jsdom) as your Jest environment could help with this.

Although I believe leveraging jsdom could potentially help with your issue, I would still strongly advise that you consider refocusing the responsibility of your unit tests to be more isolated.

**Comment by cshfang** [comment]
Hi @JayMax23, the intention was not to be presumptuous or to imply that you do not know what unit tests are. I did make assumptions that this was for unit testing but this was largely due to the issue description and reproduction steps provided since it only mentions Jest tests which are indeed typically used for unit testing. So I apologize if I misunderstood.

After reading through your response, my understanding (and please correct me further if I am wrong) would be that Amplify is being consumed by some backend APIs (Node?) and the net result is that the crypto object isn't globally available in that runtime. Furthermore, the current workaround you and others on this thread are using is similar to (or is) the one shared [here](https://github.com/aws-amplify/amplify-js/issues/12751#issuecomment-1881195819) by @tsimbalar.

Here again we have two related but _sort of_ separate issues:

1. Amplify v6 lacks first-class Node support out of the box at this time. This was a decision taken as part of the initial v6 scope of work. We are evaluating internally if and when and how to introduce better support in non-browser runtimes. We realize this can be a pain point for our customers and I would encourage you to open or upvote a feature request for this. In the meantime, regarding the workaround proposed above...
2. I understand that this workaround seems unpalatable but, in fact, that is essentially what Amplify v5 was [doing](https://github.com/aws-amplify/amplify-js/blob/b88df662d434465e25e797e68f9038819e8756a2/packages/amazon-cognito-identity-js/src/utils/cryptoSecureRandomInt.js#L13-L23) under the hood and would likely be what we would have to do to introduce better Node compatibility as well - to check the runtime for a compatible crypto implementation, conditionally falling back until we can detect a working shim.

**Comment by cwomack** [comment]
@JayMax23 While we haven't heard back from you on this issue, we just wanted to touch base one more time and let you know that we'll consolidate all this feedback and context into the related Issue #7058 for improving our Node.js support for more use cases out of the box.  If you have further feedback or context you'd like to give, feel free to comment on that issue and give it a thumbs up for traction!

**Comment by JayMax23** [comment]
Given that that ticket is 4 years old and this is a year old, it clearly outlines your intent. We will find another tool.

(For anyone else here who has the same issue, I will post that tool in a follow up)



Thanks.

**Comment by wburgess-sdx** [comment]
I ran into this as well when running Amplify v6 `signIn()` outside of the browser. Upgrading to Node 20.x+ fixed it for me.

While the workaround above worked, it caused issues locally across the engineering team based on which Node version they had. 18.x would produce that error (the CI runner was also 18.x), while 20.x runs fine.
