### ISSUE TITLE
Embedded social logins

### ISSUE THREAD

**Issue by OperationalFallacy** [aws-amplify/amplify-js#12775]
### Is this related to a new or existing framework?

React, Next.js

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

I'd like to implemented embedded login page for social providers, so the user stays on the website page without redirects to idp oauth and then back.  

Idk what's exact technical term for such UX, it might be "overlay sign-in", "inline authentication" or there.

### Describe the solution you'd like

Here's an illustration:

![image](https://github.com/aws-amplify/amplify-js/assets/62673610/4b9ffd66-bccb-4120-9000-ec8be7621004)

### Describe alternatives you've considered

Not sure if any alternative ways of auth flow possible with Authenticator component.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Related to https://github.com/aws-amplify/amplify-js/issues/12431

**Comment by nadetastic** [comment]
Hi @OperationalFallacy thank you for opening this issue. We have identified it as a feature request, which is similar to an opening issue #12431. For now I will close out this issue in order to consolidate this requeust into one. If you have any further questions or comments please feel free to respond the the other issue as well as subscribing to it. Thanks!
