### ISSUE TITLE
After uploading a file as public with aws storage, I havent public access to the object URL.

### ISSUE THREAD

**Issue by rallona** [aws-amplify/amplify-js#13001]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React, Next.js

### Amplify APIs

Authentication, Storage

### Amplify Version

v6

### Amplify Categories

storage

### Backend

None

### Environment information

<details>

```
# Put output below this line

AWS AMPLIFY V6

```

</details>

### Describe the bug

I have uploaded an image using aws amplify storage. The upload is correct and I can see the image in the S3 bucket inside a /public folder, but I am unable to get the URL to that image.

I have used the getUrl method, but only gives me the signed URL, which has an expiring date. I need a public URL without expiration date.

Is this possible to achieve? Thanks!

### Expected behavior

I want to get the public URL of the image that I have just uploaded.

### Reproduction steps

Using the getUrl method

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @rallona and thanks for opening this issue.  Right now, the maximum timeframe that a download URL can be set for is 1 hour out of the box with the `getUrl` API.  As such, I'll mark this as a feature request rather than a bug or question.  

Not sure if you're wanting to dig into using the aws-sdk, but it does look like there's an ability to have [up to 7 days](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html#PresignedUrl-Expiration:~:text=If%20you%20create%20a%20presigned%20URL%20with%20the%20Amazon%20S3%20console%2C%20the%20expiration%20time%20can%20be%20set%20between%201%20minute%20and%2012%20hours.%20If%20you%20use%20the%20AWS%20CLI%20or%20AWS%20SDKs%2C%20the%20expiration%20time%20can%20be%20set%20as%20high%20as%207%20days.) before the signed URL expires.  Either way, we'll mark this as a feature request for the Amplify side and follow up with any further questions or progress from here!

**Comment by cwomack** [comment]
After reviewing this further internally, we're going to consolidate this issue into #9418.  Please follow that issue going forward for updates on this feature and feel free to add any comments, additional context, or upvotes to it to help with traction. Thank you!
