### ISSUE TITLE
[Gen2] Add sort key to model identifier

### ISSUE THREAD

**Issue by ryanmalesic** [aws-amplify/amplify-js#13201]
### Is this related to a new or existing API?

GraphQL API

### Is this related to another service?

DynamoDB

### Describe the feature you'd like to request

`.identifier()` on models should allow for sort keys. 

### Describe the solution you'd like

`.identifier({ hashKey: [...], sortKey: [...] })`

### Describe alternatives you've considered

GSIs with sort keys don't fit my use-case as duplicates are allowed in GSIs

### Is this something that you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @ryanmalesic 👋 and thank you for opening this issue.  It looks like you're referring to the Gen2 Developer Experience with this feature request.  Just to confirm, have you reviewed the [composite identifier](https://github.com/aws-amplify/amplify-js/issues/13201) section that shows how to use a sort key within the `identifier()` call? 

The first string that's passed into the array is the primary key.  The second (and any more) would be additional sort keys.

**Comment by ryanmalesic** [comment]
Also, it seems sort keys on the primary index don't support comparison operations? Is this correct

**Comment by chrisbonifacio** [comment]
Hi @ryanmalesic can you explain your use case a bit more? When performing a `get` request, the expected behavior is to return a single item so the arguments to the query are constrained as such, which means you can't use a filter expression. However, you can use a filter expression on a list query as it returns multiple items. So you can do something like this:

<img width="567" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/16952986/635f2103-b590-4d6c-bb6a-2fc392f6db48">

If this doesn't fit your use case either, then can you provide an example of your schema and the data access pattern you're trying to achieve?

**Comment by ryanmalesic** [comment]
Does list + filter convert to a Scan + Filter expression or a Query when calling DDB from the app sync resolver?

**Comment by chrisbonifacio** [comment]
> Understood on the get, that was a mistype.
> 
> Does list + filter convert to a Scan + Filter expression or a Query when calling DDB from the default generated app sync resolver?
> 
> If it's scan + filter, this is too unoptimized and comparatively expensive to a Query for my use-cases. Dynamo makes a point to discourage scan usage for things that could be queries
> 
> My use case would involve having a method called query (for example) on the generated model that accepts the pk and then optionally a query (beginsWith, lt, gt, etc) operation on the (composite) sort key. This would translate to a Query operation on the table in the resolver function
> 
> Also having a composite pk would be helpful. Instead of identifier having the first field of the array be the pk and the rest becoming a composite sk, it could be something like
> 
> ```
> .identifier({
>     hashKey: [...],
>     sortKey: [...],
> })
> ```

List + Filter would result in a Scan. 
For a GraphQL query to trigger a Query instead you would have to setup a secondary index and use a query expression.
https://docs.amplify.aws/react/build-a-backend/data/data-modeling/secondary-index/

Also, we do support composite PKs. 
[@aws-amplify/backend-cli](https://docs.amplify.aws/react/build-a-backend/data/data-modeling/identifiers/#composite-identifier)

We have launched and since made updates to the schema model. Please upgrade to the `latest` tag for both `@aws-amplify/backend` and `@aws-amplify/backend-cli` and let us know if you still have any issues or questions on the setup

```sh
npm i @aws-amplify/backend@latest @aws-amplify/backend-cli@latest 
```

**Comment by chrisbonifacio** [comment]
Closing this as fix has been releaesd

**Comment by Basovs** [comment]
How do we sort data without providing PK? I want to list Posts by createdAt for example.

**Comment by Basovs** [comment]
@chrisbonifacio Something is not as i want it to be. I have this code but the typescript complains:

`const schema = a.schema({
  Todo: a
    .model({
      id: a.id().required(),
      title: a.string(),
      content: a.string(),
      is_done: a.boolean(),
      created_at: a.datetime().required(),
    })
    .secondaryIndexes(index => [index('created_at').sortKeys(['created_at'])])
    .authorization(allow => [allow.guest()]),
})`

Can you please correct it? And maybe provide list query example it self as well. Cannot find any list query examples in the docs...

**Comment by sid-js** [comment]
@Basovs Were you able to implement this? I'm also looking to do the same

**Comment by Basovs** [comment]
> @Basovs Were you able to implement this? I'm also looking to do the same

Yes - here is how i solved it.
Add these two line to the Table you want to sort by created at:
a field named "type" which value will always be name of the table.
`type: a.string().required(),`
and then create secondary index based on that field "type"
`.secondaryIndexes(index => [index('type').sortKeys(['created_at']).queryField('listByDate')])`

Its kinda a smal hack that is also used in Amplify Gen1 sorting. Now when you create new Todo for example you need to provide field "type": "Todo" in the payload.

And then when listing the todos:
`amplifyClient.models.Todo.listByDate(
        {
          type: 'Todo',
        },
        {
          sortDirection: 'DESC',
          selectionSet: ['type', 'id', 'title', 'content'],
        },
      )`

**Comment by sid-js** [comment]
@Basovs Thanks, this worked. But is there any way to make this query paginated ? Can't find anything in the Docs either. 
@chrisbonifacio

**Comment by shlomiro** [comment]
@sid-js Were you able to find a way to paginate with sort key?

@Basovs @chrisbonifacio

**Comment by AlexThomas90210** [comment]
So whats the answer to this? Thread has been hijacked for something off topic. Initial point stands, we can create tables with a partitionKey and add sortKeys. However theres no way to execute a DynamoDB query on that defined sort key unless we create a new GSI.
