### ISSUE TITLE
InvalidLambdaResponseException: Invalid lambda function output : Invalid JSON when user not found in pool

### ISSUE THREAD

**Issue by saharJ95** [aws-amplify/amplify-js#13352]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line

Production
```

</details>

### Describe the bug

Using Cognito User Pool 

Getting InvalidLambdaResponseException: Invalid lambda function output : Invalid JSON when the user doesnot exisit in pool or deleted

### Expected behavior

Response should be User not Found with defined code 

### Reproduction steps

login with non exsisting users

### Code Snippet

![image](https://github.com/aws-amplify/amplify-js/assets/113641921/61401c42-e0a9-43bc-9f09-70e57a1b9502)

### Log output

![image](https://github.com/aws-amplify/amplify-js/assets/113641921/3937cd77-9fd3-4355-824b-d354f7470dc0)

**Comment by cwomack** [comment]
Hello, @saharJ95 👋 and sorry to hear you're running into this.  We may need a little more information on the steps you took to set up Auth to determine why this error is happening. Are you trying to use a custom lambda to send back a message when a user is not in the user pool?  Can you share the lambda code, which of the Auth lambdas are causing this, and a little more context there? Also, if you log in with an existing user is everything working just fine?

**Comment by saharJ95** [comment]
Hi @cwomack ,
I am not using any custom code/lambda
What I am doing is..

1. Configure aws 
2. Import **signIn** from aws-amplify/auth
3. Calling with required Attributes

Existing users work fine, I am trying to catch the exceptions although if the useremail or password is incorrect I am getting the correct response from Cognito APIs
But in the UserNotFound exception, it returns **InvalidLambdaResponseException**
![image](https://github.com/aws-amplify/amplify-js/assets/113641921/3d175a5a-5e88-4ab1-a02f-d5436dac1490)

**Comment by israx** [comment]
hello @saharJ95 . Could you please provide the following information:

1. Steps you took to configure amplify, did you use the CLI, gen2 or manually created resources ?
2. your amplify configuration refraining from adding any sensitive values.
3. Are you getting any errors when calling the `signIn` API with an existing user ?
4. What do you see when you go to `Cognito Console` -> user pool -> `User pool properties` -> `Lambda triggers`
5. network call request when getting this specific error.

This will help us to determine the root cause of the issue. Usually the `InvalidResponseLambdaException` is thrown when the userpool has a lambda trigger that is miss configured.

**Comment by saharJ95** [comment]
Hi @israx ,

1. Created an identity pool and imported amplify config to my existing project.

2. 
![image](https://github.com/aws-amplify/amplify-js/assets/113641921/1a38d732-5051-45a1-8ca9-dcbd161fa423)
![image](https://github.com/aws-amplify/amplify-js/assets/113641921/25c1ba48-e17d-4130-a5e2-2b14fb01ff49)

3. As I mentioned, the Existing user sign works fine, wrong password exception works fine. Issue is when the email is incorrect or the user doesn't exist

4.  
![image](https://github.com/aws-amplify/amplify-js/assets/113641921/81e3f9c7-41a2-48a7-83d8-b9535bc61a0e)
![image](https://github.com/aws-amplify/amplify-js/assets/113641921/0b62f372-2e8b-4e7a-8372-c5c9c3dc0f14)

5.
![image](https://github.com/aws-amplify/amplify-js/assets/113641921/97c83b8d-33fc-4c26-b111-428bfcdbccf4)
![image](https://github.com/aws-amplify/amplify-js/assets/113641921/fedd0049-999f-4644-8544-3dec17da680f)
![image](https://github.com/aws-amplify/amplify-js/assets/113641921/2855364d-2c5c-4a92-a659-ed4d7a7b5186)

**Comment by israx** [comment]
Hello @saharJ95 . Thank you for providing all the feedback. I see you have set a `pre authentication lambda` [trigger ](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-authentication.html) which can be used to perform extra validation before authenticating a user. So based on the lambda docs we have that

> Note
> This Lambda trigger doesn't activate when a user doesn't exist, or already has an existing session in your user pool. If the PreventUserExistenceErrors setting of a user pool app client is set to ENABLED, then the Lambda trigger will activate.

So the reason you are getting the `InvalidLambdaResponseException` error is because your user pool has activated the `PreventUserExistenceErrors` setting. This setting can be located at `Cognito console` -> user pools -> user pool -> `App integration` -> `App client list` -> pick your app client -> `App client information` -> edit -> `Prevent user existence errors`.

In order to solve your issue you could do the following:

1. Disable the `Prevent user existence errors` - NOT RECOMMENDED 
2. Edit your `Pre authentication lambda`  and throw an specific error - **RECOMMENDED** 

I highly recommend not disabling the `Prevent user existence errors` setting. This will help you to prevent user enumeration errors.

**Comment by saharJ95** [comment]
Hi @israx ,
Thank you for your quick response.
I fixed the pre auth  lambda with the proper exception and it works fine .

Thanks :)
