### ISSUE TITLE
Provide ES6 version

### ISSUE THREAD

**Issue by ArmorDarks** [aws-amplify/amplify-js#1336]
## Do you want to request a feature or report a bug?

Feature

## What is the current behavior?

Only CommonJS version is provided

## What is the expected behavior?

ES6 version to be available too, for tree shaking

## Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

1.0.4, Windows

**Comment by ArmorDarks** [comment]
nope

**Comment by sammartinez** [comment]
We are actively working on this. Please see the RFC reference link

**Comment by pravgupt** [comment]
@ArmorDarks , We have published ES6 builds in our [unstable release](https://www.npmjs.com/package/aws-amplify/v/1.2.3-unstable.5). Please try and let us know if you have any feedback.

**Comment by Amplifiyer** [comment]
@ArmorDarks this has been pushed to a stable release. Closing this, let us know if you face any problems by creating a new issue.

**Comment by 0xdevalias** [comment]
@Amplifiyer you linked the old [unstable release](https://www.npmjs.com/package/aws-amplify/v/1.2.3-unstable.5), and say it has since been made stable.

Looking at the versions on https://www.npmjs.com/package/aws-amplify there are all sorts of things, with various labels that seem rather odd:

eg. `latest` is at `2.2.6`, yet `beta` is at `1.1.24-beta.10`, and `next` is at `2.1.0`

It's kind of hard to try and reverse engineer which is actually meant to be the latest based on those labels, and which versions have the ES6 builds enabled in them (and how we can determine that)

![image](https://user-images.githubusercontent.com/753891/77139240-537ea180-6ac9-11ea-98e4-0aecfdc862de.png)
