### ISSUE TITLE
channelType, Address and optOut removed from v6, Alternative method to set these?

### ISSUE THREAD

**Issue by soplan** [aws-amplify/amplify-js#13386]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Analytics

### Amplify Version

v6

### Amplify Categories

analytics

### Backend

Other

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

In v5 I was able to set channelType, optOut and address.

With v6 I can't... all my users on our react website are registered as channelType "APN"  with a blank address..

Because of this, We can't use either Journeys or Campaigns. Because this requires an address and EMAIL as channeltype in our case... 

![image](https://github.com/aws-amplify/amplify-js/assets/63843090/35b4ee51-060f-4b58-8c41-a16a2015306d)

So is there a workaround or something to set the channelType to EMAIL and address?
I couldn't find it in the docs... 

### Expected behavior

Be able to set channelType, OptOut and Address using v6 library

### Reproduction steps

Install v6.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

Not using amplify push/pull, only the library.
Backend is set-up through CDK

**Comment by mohammedsahl** [comment]
+1 we're facing the same issue

**Comment by ashwinkumar6** [comment]
Hi @soplan @mohammedsahl 
Thanks for opening this ticket. Can you elaborate a bit more on the use case for the usage of `channelType` ,`OptOut` and `Address` in v6.  These options were removed since they don't impact analytics endpoint.  
[doc reference](https://docs.amplify.aws/gen1/javascript/build-a-backend/more-features/analytics/analytics-migration-guide/)

**Comment by mohammedsahl** [comment]
Hey @ashwinkumar6. We use `optOut` to know if a user has opted out of receiving messages. We have pinpoint journeys which depend on knowing if the endpoint channelType is email.

All we get now is that an endpoint is of APNS channelType which I assume is apple push notification service? Anyway that isn't very useful for our purposes.

**Comment by soplan** [comment]
@ashwinkumar6  

we use journeys and they depend on the channektype “email” and we use campaigns to send newsletters which also requires this channeltype. Without that channeltype the endpoint is not eligible for sending emails. 

OptOut is by default set to ALL when endpoint is created. For sending emails we have to set this to NONE. 

What does this even mean? 
“These options were removed since they don't impact analytics endpoint.”

I really do not understand that sentence in the docs. Clearly these options are very much required.

**Comment by mohammedsahl** [comment]
Hey @ashwinkumar6 would you have any updates on this?

**Comment by cwomack** [comment]
@soplan, @hisham, @mohammedsahl 

Just wanted to let you all know that we've reviewed this and the related #12721 internally to assess this as a migration blocker from v5 to v6 at this point.  We had made had made the decision to remove the `address`, `optOut`, and `channelType` options in v6, so that's why we're marking this a feature request (and not a bug).

I'll also be consolidating this issue into the older #12721 to ensure we are consolidating the context/feedback, so please feel free to add any relevant comments on that older issue and give it a "thumbs up" for traction.
