### ISSUE TITLE
Auth v6 - Sign-in -  Invalid phone number format. 

### ISSUE THREAD

**Issue by hanoj-budime** [aws-amplify/amplify-js#13761]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

....

### Describe the bug

Amplify checks phone_number is required during / once user migrated ?

During user migration required phone_number which is missing but user is mirgrated succesfully from one pool to other pool.
However sign-in failed with InvalidParameterException ( Invalid phone number format. )

![image](https://github.com/user-attachments/assets/bedd4406-0d58-4ed6-b635-70396438bbe5)

### Expected behavior

Amplify must improve nextstep like `CONFIRM_SIGN_IN_WITH_REQUIRED` ( where in-case phone_number will be required for MFA sign-in )

### Reproduction steps

1. auth v6.5
2. User Mirgation from old-pool to new-pool
3. In old-pool phone_number is not required.
4. In new-pool phobe_number is required ( for MFA sign-in ) .

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @hanoj-budime 👋.  Is this happening after upgrading from v5 of Amplify to v6? I believe this is the error you'd experience if you're trying to call the newer API using the `Auth.confirmSignIn()` parameters.  If so, there are changes to the `confirmSignIn()` parameters to include an object with a `challengeResponse` property rather than separate ones for user and code (like in v5). More information on the differences can be found [here](https://docs.amplify.aws/gen1/react/build-a-backend/auth/auth-migration-guide/#authconfirmsignin) in the docs.  

Can you see if calling the API like shown below helps resolve the issue? 
```
await confirmSignIn({ challengeResponse: "123456" });
```

**Comment by hanoj-budime** [comment]
@cwomack 

Amplify checks phone_number is required during / once user migrated ?

During user migration required phone_number which is missing but user is mirgrated succesfully from one pool to other pool.
However sign-in failed with InvalidParameterException ( Invalid phone number format. )

**Comment by israx** [comment]
hello @hanoj-budime. Sorry for any inconvenience using the library. 

The `Invalid phone number format` error message is due to providing an incorrect `phone_number` format either during `signUp` or `signIn`.

**Bad:**
`signIn({username:"9990009999", password:*****}`

**Good:**
`signIn({username:"+19990009999", password:*****}`

Also, are both of your user pools configured to **login** with `phone_number`, or/and they require a phone_number attribute during `signUp`?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
