### ISSUE TITLE
Unable to create a dynamic segment using identifyUser

### ISSUE THREAD

**Issue by renso3x** [aws-amplify/amplify-js#14024]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Analytics

### Amplify Version

v6

### Amplify Categories

analytics

### Backend

None

### Environment information

<details>

```
```

</details>

### Describe the bug

I was creating a dynamic segment in AWS Pinpoint to filter users based on the organizationName. Initially, I encountered an issue where supplying only customProperties resulted in no endpoints being filtered. Additionally, it appears that triggering an event is required to apply the segment criteria.

Upon further investigation, I found that including options.userAttributes allows segments to be filtered based on this attribute. However, the documentation provided [here](https://docs.amplify.aws/gen1/react/build-a-backend/more-features/analytics/identify-user/) is unclear about how to create segments effectively. Furthermore, version 6 of the library seems to have limited features for this purpose.

### Expected behavior

I expect that when I trigger the identifyUser I can create a Segment based on those user criteria

### Reproduction steps

npm install aws-amplify @aws-amplify/analytics

### Code Snippet

```javascript
// Put your code below this line.

await identifyUser({
    userId,
    userProfile: {
      customProperties: {
        organizationName: 'ABC',
      },
    },
    options: {
      userAttributes: {
        organizationName: 'ABC',
      },
    },
  });

record({
  event: EventTrackerType.USER_SIGNIN,
  eventData: { email: userId },
});


```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @renso3x 👋 and thanks for opening this issue.  Pinpoint's updateEndpoint API is called under the hood when `identifyUser()` is called by Amplify, so we'll look into this further to determine if there's a bug in how the attributes are being passed.  Can you confirm if you see the `organizationName` attribute being updated properly when you make the `identifyUser()` call?

If you create a Segment in Pinpoint console (see [here](https://docs.aws.amazon.com/pinpoint/latest/userguide/segments-building.html)), are you trying to then use this attribute to add user to an existing one? Or is the goal to have a new segment made when the `identifyUser()` API is called from the client side?

**Comment by renso3x** [comment]
Hi @cwomack,

My goal is to create a segment based on identifyUser. Should I only use identifyUser() and skip calling record()?

**Comment by cwomack** [comment]
@renso3x, thanks for the additional context here.  That delay you see for the `organizationName` being around 45 min to an hour is expected behavior within the Pinpoint console (and a subject we can't really control on the Amplify side).  Same thing happens for events being record I'm sure as well.  You can _somewhat_ speed up the recording of events by [flushing them](https://docs.amplify.aws/react/build-a-backend/add-aws-services/analytics/record-events/#flush-events-3) so that they aren't stored in the buffer and only sent periodically.

Let me know if I'm understanding your goal properly, but it sounds like the intent is to have the Dynamic Segment created programmatically.  If that's the case, then there's no Amplify API that can be called on the client side to do this simultaneously when the `organizationName` attribute is sent off to Pinpoint. However, this could be done [using a Lambda function](https://docs.aws.amazon.com/pinpoint/latest/developerguide/segments-dynamic.html) that would set up to create/modify a segment possibly when the `organizationName` attribute is updated or given a value.

**Comment by renso3x** [comment]
Hi @cwomack,

Yes, my goal is to create the dynamic segment in Amplify. Generally, I trigger the identifyUser function only once when the user signs in to the app. However, if my goal is to update the user endpoint, would it be better to use a Lambda function instead?

**Comment by cwomack** [comment]
@renso3x, appreciate the clarity.  I think the best way to achieve this then would be to use the Lambda function then to create the dynamic segment when there are changes to the attribute recorded by Pinpoint.  Any type of client side implementation runs the risk of potentially allowing a malicious user to create a large amount of segments that could then complicate or drive up costs on our campaigns or messages that use them.  Because of this, it wouldn't be a feature that we'd consider implementing on the Amplify side at this time (and it's also not something Pinpoint supports at this time even if we could).  

Hope that helps clear things up, but let us know if there's further questions here!

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If there's further questions or guidance needed, please feel free to reply back and we'd be happy to re-open the issue.

Thank you!
