### ISSUE TITLE
Why is there no entry under Apps (in mobile hub) for the Amplify app I have set up?

### ISSUE THREAD

**Issue by edzillion** [aws-amplify/amplify-js#1502]
After setting up and (awsmobile push) pushing an AWS Amplify app, when I log into the console I do not see any entry in the App section in my mobile-hub Project.

Is this the correct behavior?

**Comment by swaminator** [comment]
The Amplify CLI directly uses CloudFormation instead of Mobile Hub so the projects don't show up in the Hub console. Checkout this link to learn more: https://aws.amazon.com/blogs/mobile/announcing-the-aws-amplify-cli-toolchain/
Here's the relevant bits: "Existing Mobile Hub projects continue to work without requiring any app changes. If you’re using the AWS Mobile CLI for existing projects, you can also continue to use that older CLI. However, going forward, new features will be added to the AWS Amplify CLI toolchain which does not use Mobile Hub." Let me know if you have any further questions.
