### ISSUE TITLE
Storage.vault.put returns key only

### ISSUE THREAD

**Issue by ivanji** [aws-amplify/amplify-js#1548]
Do you want to request a feature or report a bug?
- Seems like a bug.

What is the current behavior?

- I'm using Storage.vault.put which is supposed to return "promise resolves to object on success". All I get in the response is the key. Shouldn't the response contain data about the object, such as location, bucket, etc. (apart from the key)

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
- 1.0.6

**Comment by ivanji** [comment]
Hi guys, I see this has been marked as an 'enhancement'. A bit strange then that this wasn't the normal behaviour in the first place, I thought I was doing something wrong. 

I wonder now what's the purpose of returning the key only. Is there any way of getting all the object details from the key only? please advise. Glad to implement an alternative approach until this enhancement is added.

**Comment by mlabieniec** [comment]
The library doesn’t make an additional call to retrieve the item for you but simply just puts the item you can then retrieve it via the key with a storage.get. This not only limits network requests but there could also be permissions involved I.e. your client might have put permissions but not get etc. It is marked as an enhancement since we could potentially put in an additonal arg to perhaps return the object. Would this be your feedback as to what this would look like considering this?

**Comment by ivanji** [comment]
I totally understand your reasoning behind the current implementation. The additional arg would certainly help to go that extra step - and it'd seem like a more complete solution. Thanks for your explanation and help with this.

**Comment by sammartinez** [comment]
Resolving this as the above comment from @mlabieniec
