### ISSUE TITLE
Confirm Sign Up - Username can not be set after refresh

### ISSUE THREAD

**Issue by SteveHoggNZ** [aws-amplify/amplify-js#1886]
**Describe the bug**
If a user refreshes the page between creating an account and entering the confirmation code the confirmSignUp form has a blank username that can not be changed.

**To Reproduce**
1. Create an account
2. Refresh the page
3. Login
4. Go to enter your code, but notice the username is blank and can not be changed

**Expected behavior**
The username should be set to the one that was just used for the login

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 69.0.3497.100

**Additional context**
aws-amplify-react 2.0.7

**Debug Logs**
```
[DEBUG] 36:03.120 SignIn - the user is not confirmed
ConsoleLogger.js:100 {[DEBUG] 36:03.121 Authenticator - authenticator state change confirmSignUp: undefined}
ConsoleLogger.js:100 {[DEBUG] 36:03.149 AuthClass - Failed to get the current user: "No current user"}[DEBUG] 36:03.149 AuthClass - Failed to get the current user: "No current user"__proto__: Object
ConsoleLogger.js:100 {[DEBUG] 36:03.152 AuthClass - getting session failed: "No current user"}
ConsoleLogger.js:84 [DEBUG] 36:03.155 Credentials - setting credentials for guest
```

**Comment by carlpwilliams** [comment]
I have this same issue, how was this fixed?

**Comment by StephenHartfield** [comment]
Having the same issue. @powerful23 not sure how the mention issue, #1890, helps, as this is a problem with the signUp and confirmSignUp. 

In my application, the user signs up and is given the confirmation code and is routed to page where they can enter confirmation code. However, if they accidentally refresh the page, the username becomes empty and they cannot proceed, even with the confirmation code, because the username is empty. We cannot re-sign up with that email, because it is already in as a user - says user with that email already exists. So essentially this accidental refresh locks that email out of the app.
