### ISSUE TITLE
Amplify w/ Next.js

### ISSUE THREAD

**Issue by rfdc** [aws-amplify/amplify-js#1934]
Hi there,
Is there a work flow example for Nextjs with:
- Sing-up and Login
- AuthenticatedRoute and UnauthenticatedRoute

Thanks

**Comment by emanuelherrmann** [comment]
Is there any example?

**Comment by ajhool** [comment]
I have a potential workaround flow that leverages next's dynamic imports. I'm not sure why it's necessary, but the internals of Amplify-react seem to require it.

This solution DOES NOT render any auth information on the server side. It is merely a patch that allows the Authenticator component to be used in the nextjs ecosystem, but it is unable to leverage SSR for rendering the components that live inside the Authenticator. If you are using SSR for SEO, this is usually okay because search engines shouldn't be indexing authenticated resources anyways.

The flow (Note: Even though it looks long, I believe it's a very simple, intuitive procedure):

1. Import the Dynamic module from next/dynamic
2. Create a flag in the component state called "isClient" and set the initial value to false
3. The nextjs server will render a dummy component on the server side after seeing that "isClient" is false.
4. The component calls "componentDidMount" when it is mounted on the client side (this internal function is NEVER called server side)
5. the componentDidMount function sets the `isClient` flag to true and forces a rerender
6. the rerender checks the `isClient` flag, which is now true, and tells nextjs to dynamically import the `Authenticator` component
7. Finally, render the Authenticator component and the secrets within

```
// pages/auth.jsx
import * as React from 'react';
import dynamic from 'next/dynamic';

export class extends React.Component {
  constructor() {
    this.state = {
      isClient: false
    }
  }

  componentDidMount(){
    this.setState({
      isClient: true
    });
  }

  render(){
    const { isClient } = this.state;

    if(isClient) {
      const Authenticator = dynamic(import('aws-amplify-react').then(mod => mod.Authenticator))

      return (<Authenticator>
        <div>I will only ever render on the client!</div>
      </Authenticator>)
   } else {
     return (<div>Some placeholder component should go here.</div>);
   }
  }
}
```

**Comment by joehillen** [comment]
@ajhool I tried your technique and it works, but it turns out that it's not necessary. To make aws-amplify-react work with Next.js, I just had to add the following to the top of my `next.config.js`:

```js
if (typeof require !== "undefined") {
  require.extensions[".less"] = () => {};
  require.extensions[".css"] = (file) => {};
}```

Then I can use the HOC and Authenticator component like any other. Sensitive pages aren't rendered server-side because the next server isn't authenticated with cognito.

**Comment by ajhool** [comment]
Thanks @joehillen I'll try that out. I did find some issues with that technique, so if anybody is coming to this page in the future, I'd recommend trying @joehillen 's solution first

**Comment by ajhool** [comment]
@joehillen I had forgotten what the issue with that solution is, but it's a doozy. I find that your solution works when I'm navigating directly to the page with authentication on it (eg. www .site .com/user) but there is a silent error when navigating to the authenticated page via a next/link.

Let /user be the page with authentication and /hello be the page without authentication:

This works:

1. Enter "www . site . com/user" into  my browser. [ SUCCESS ]

This won't work:

1. Enter "www . site . com/hello" into my browser. [ SUCCESS ]
2. On the Hello page, click a link to "www . site . com/user" [ THIS FAILS SILENTLY, INEXPLICABLY ]

This also works:

1. Enter "www . site . com/user" into my browser. [ SUCCESS ]
2. Click a next/link to "/hello" [ SUCCESS ]
3. Click a next/link back to "/user" [ SUCCESS ]

I'm using Now version 2

The fact that the third case works but the second case doesn't work tells me there's some wonky behavior going on with the SSR Authenticator component. It fails silently so I'm not sure where to even begin debugging it, but I did find that the `isClient` workaround that I posted solves the problem. It introduces a few other problems but they're not too bad AFAIK
