### ISSUE TITLE
Feature request : Roadmap

### ISSUE THREAD

**Issue by romainquellec** [aws-amplify/amplify-js#2045]
Hello.

Is there any clear roadmap for amplify-js somewhere ? 
If not, maybe add it to the docs or to github wiki/pages.

Thanks.

**Comment by mlabieniec** [comment]
@romainquellec we mostly work directly off GitHub here. So anything marked as a feature-request on GH is what our roadmap is. So if you filter GH issues based on feature-request label you can see what our roadmap looks like :) outside of that we do use a tracking tool to plan out what we want to work on internally but 90% of that is also based on customer feedback/issues. The one improvement i think would help here is assigning some of these to milestones (which we've tried to do in the past but since we use another internal tracking tool it becomes a bit of an ops overload managing in two places). Will try and consider a better solution for delivering the further looking information though thanks for the feedback.

**Comment by cyrfer** [comment]
Since this was closed by @mlabieniec maybe those interested will upvote over here:
https://github.com/aws-amplify/docs/issues/1096
