### ISSUE TITLE
I can not re start amplify

### ISSUE THREAD

**Issue by dogboy602k** [aws-amplify/amplify-js#2068]
** Which Category is your question related to? **
AWS Amplify, restarting the CLI to orignial state
** What AWS Services are you utilizing? **
S3, cognito
** Provide additional details e.g. code snippets **
So recently ive been working with AWS amplify and it was really nice until I restarted my computer. I cant start up my project like I was able to do before. I have the bash window open and try to start up my aws cli and I cant. I first cd to my file location. Then I enter in amplify init. Then I select my editor, Atom Editor, and when it asks what type of app am I building I select Javascript, then when it asks for frame work i choose none. For the Source Directory Path i put in my file name/its location, and then for  Distribution Directory Path I have the default (pressed enter).

Here lies  my issue. I get 2 options, one is to to add an API, either GraphQL or REST, I dont remember doing anything with that so I skip that and try to run the command amplify status, and I see I have no hosting or auth. So im lost now if i try to add hosting it says that I already have it and cant add it, though it doesn't show up in my amplify status.  I have also tried the amplify-js-app file but same issue.

My entire bash log:
https://pastebin.com/a9c2mLV5
My file path:
![image](https://user-images.githubusercontent.com/9836315/48162507-4b92d880-e2ab-11e8-8a21-42419b125808.png)

**Comment by UnleashedMind** [comment]
I was not able to reproduce the issue. But from what you described, it's likely because somehow your `amplify/backend/hosting` folder is not amplify, but the `amplify/backend/amplify-meta.json` file does not have a `hosting` property or the `hosting` property is an empty object. 
To recover the project to a workable state, you have two options: 
- If you want to keep an existing deployed hosting bucket (and cloudfront if it's configured), try to recover the meta data of the the hosting category and insert it into the `amplify-meta.json` file in both the `backend` and the `current-cloud-backend` folders. 
- If you just want to start fresh and create a new set of hosting resources, remove the the hosting folder from both the `amplify/backend` and the `amplify/#current-cloud-backend` folders; and run `amplify hosting add`.

**Comment by kaustavghosh06** [comment]
@dogboy602k Please let me know if you're still stuck on this and re-open this issue.
