### ISSUE TITLE
Make Amplify.configure() return Promise

### ISSUE THREAD

**Issue by pronevich** [aws-amplify/amplify-js#2082]
**Is your feature request related to a problem? Please describe.**
When you authorize with Amplify, you need to wait for `Amplify.configure()` to complete. Problem is to get notified that amplify is configured. Then you should use ` Hub.listen('auth', ...)` but this is not a perfect solution and it limits our possibilities:

- you can't use Amplify.configure with React Suspense, because of Suspense is waiting for a promise. This will help with not showing spinners when auth configuration is pretty fast
- no need to use `Hub.listen()` . When the promise is ready you can just setState and etc.

**Describe the solution you'd like**
`Amplify.configure()` should return promise

**Comment by D2KX** [comment]
I don't know much about React etc., but I think you are mixing a few things here:

I am pretty sure Amplify.configure() itself is not asyncronous. If, for some reason, it needs to be a Promise in your case, you can try wrapping it in a syncronous Promise.resolve() call if it's just about the type. But again, I don't think Amplify.configure() is asyncronous. It just quickly configures stuff internally.

What you are referring to sounds like the Auth module trying to get initial credentials, which depending on your configuration is automatically triggered after Amplify.configure() is done. This only happens when you have 1) a Cognito Federated Identity Pool configured and 2) not set the mandatorySignIn option, which would mean you're looking to get credentials for unauthenticated users, or you are have a User Pool configured with someone already logged in, wanting to get credentials.

You could probably wrap this in a real Promise, but even then, you would want to know the state of your Auth module before resolving the Promise, which is what the Hub is for. Because you would want to know if you've got the credentials or if something went wrong, etc.

**Comment by pronevich** [comment]
@D2KX yes, my main concern is about Auth:

- `Amplify.configure()` take some time and before it "configured" I can't retrieve current authenticated user `Auth.currentAuthenticatedUser()` and etc. Here [example](https://aws-amplify.github.io/docs/js/hub#listening-authentication-events ) of all Auth events including "configured'

- yes I'm using Cognito Federated Identity Pool and not set the mandatorySignIn option reasonably

- I'am want solution when I know "state of Auth module" not through Hub event system, but through Promise for the reason described earlier

**Comment by sammartinez** [comment]
@pronevich Is this still a valid use case for you? Please let us know, thanks!

**Comment by pronevich** [comment]
@sammartinez no, currently not using it

**Comment by sammartinez** [comment]
@pronevich Thanks for the response back, going to close this as per your comment.
