### ISSUE TITLE
Make React Authenticator CSS class names customization friendly

### ISSUE THREAD

**Issue by kennu** [aws-amplify/amplify-js#2161]
It is currently difficult to customize the React Authenticator components (SignIn, SignUp, etc) using normal CSS classes, because they have some kind of dynamic class names like `Form__formContainer___Ht990`.

If you could simplify these class names into something like `amplify-form-container`, these components could be customized simply by adding the appropriate CSS to the React project.

**Comment by jordanranz** [comment]
Hi @kennu,

We are working on a better way to allow customized theming for UI components using css modules. This will include a way to pass in your own css to components. 

In the meantime you are able to pass a theme object to the React Authenticator. Have you tried this?
https://aws-amplify.github.io/docs/js/authentication#customize-ui-theme

**Comment by kennu** [comment]
Sounds good, thanks. I have used the theme object approach and it works. But my first "instinct" was to use Chrome Developer Tools to check the Amplify CSS class names and simply override them in my own CSS, which would have been convenient but not possible at this time.

**Comment by jordanranz** [comment]
Right, we are taking the approach of scoped CSS to allow better modularity and reusability with our CSS. It also cleans up the global scope css so that there is no conflicts with classes our users define. This however is the tradeoff for the convenience of easily being able to override our classes.

Ideally we will allow user defined css to be passed into the UI component instead of object of selectors like we use today. Similar to this approach:
https://github.com/react-toolbox/react-toolbox#customizing-

**Comment by kennu** [comment]
I can see the point that the CSS is scoped, but does it need to be randomly named? If the scope naming is predictable, developers can treat is as normal HTML/CSS part of their application if they prefer.

**Comment by JVUnderground** [comment]
@kennu I'm pretty sure randomness is to avoid CSS conflicts, since they use pretty normal components (Button, FormSection, etc).

They probably won't drop this. What could solve your problem, is if we could specify extra class names. I've tried this, but amplify seems to remove those.

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

#3279

**Comment by StefanJelner** [comment]
I would really like to see the possibility to add custom class-names to every element, because then one could use BEM-notation and while the class-names are user-defined, there are no conflicts.

For now, i used this approach: `<div class="amplify"><Authenticator /></div>` and used this CSS:

```
.amplify [class^='Section__container'] {
    background-color: red;
}

.amplify [class^='Section__sectionHeader'] {
    background-color: blue;
}

...
```

Attribute selectors with matching are a little bit odd, but it works like a charm. I hope this helps.

**Comment by ashika01** [comment]
Closing this feature request. Since the new UI components handles theming through CSS custom properties. For more info - https://docs.amplify.aws/ui/customization/theming/q/framework/react

If there are improvement / bugs or suggestions for the new UI component feel to open up a new issue.
