### ISSUE TITLE
Storage Documentation S3 Policy For Cognito Identity

### ISSUE THREAD

**Issue by JSafaiyeh** [aws-amplify/amplify-js#2228]
Following the Storage documentation, you will run into a permission error when trying to write to the bucket. It is related to the Identity Pool not having S3 Access.

Here is an example policy that needs to be attached to the Cognito Identity Role:

Replacing `{enter bucket name}` with the correct bucket name.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::{enter bucket name}/public/*",
                "arn:aws:s3:::{enter bucket name}/protected/${cognito-identity.amazonaws.com:sub}/*",
                "arn:aws:s3:::{enter bucket name}/private/${cognito-identity.amazonaws.com:sub}/*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::{enter bucket name}/uploads/*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::{enter bucket name}/protected/*"
            ],
            "Effect": "Allow"
        },
        {
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "public/",
                        "public/*",
                        "protected/",
                        "protected/*",
                        "private/${cognito-identity.amazonaws.com:sub}/",
                        "private/${cognito-identity.amazonaws.com:sub}/*"
                    ]
                }
            },
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::{enter bucket name}"
            ],
            "Effect": "Allow"
        }
    ]
}
```

**Comment by 10ky** [comment]
I did not follow the guide at https://aws-amplify.github.io/docs/js/storage

But have created a bucket using amplify add storage.  It automatically added two roles with name prefix s3_amplify_.  One role for auth and one for unauth.  This is because I selected public and private security needs for my S3 access.  Perhaps you took different selection and would help the issue if you provide exact steps to reproduce your problem.

**Comment by JSafaiyeh** [comment]
Ahh yes. I forgot to note, I did not use Amplify CLI. I manually created my
Cognito and S3 resources. The step is needed for the manual setup section.

**Comment by manueliglesias** [comment]
Hi @JSafaiyeh 

Yes, creating the resources using the `aws-amplify` cli is the recommended way since it takes care of a lot of the required config/policies/roles, etc that might be needed.

Having the policies in the docs could benefit users that want to do things manually, so I am labeling the issue as "documentation" 

For now, if you are curious of the different policies configured, you can take a look at the ["S3 resource stack creation using Amplify CLI"](https://github.com/aws-amplify/amplify-cli/blob/b12d20b9d85f7fc6abf7e2f7fbe11e1a108911b9/packages/amplify-category-storage/provider-utils/awscloudformation/cloudformation-templates/s3-cloudformation-template.json)

**Comment by JSafaiyeh** [comment]
Thank you for the resource! Definitely exactly what I would have wanted mapped out on the documentation. Even a simple link to the S3 stack creation on the manual section, would have been sufficient for me.

I'm sure other parts of the documentation needs this type of information, I just have not touched the SDK.
