### ISSUE TITLE
Getting the user authentication info

### ISSUE THREAD

**Issue by nomadus** [aws-amplify/amplify-js#2232]
In my App component, I am using const currentUser = await Auth.currentAuthenticatedUser() to check if a user is authenticated. This takes some time as it is calling AWS API and I show a loading indicator while the check is complete. Is there any way to make this process faster or have some local variable, which tells if the user is authenticated? So instead of calling AWS API I could check the local/session storage?

**Comment by YikSanChan** [comment]
May I ask what is the use case? Some of the use cases can be covered by specifying `@auth` in graphql model, if you want to limit access to some model. https://aws-amplify.github.io/docs/cli/graphql#auth

**Comment by manueliglesias** [comment]
Hi @nomadus 

This might be a bug in the library, I did some preliminary tests and wasn't able to get a hold of user info without making a network request.

For now maybe this helps you a little?

```javascript
const session = await Auth
    .userPool
    .getCurrentUser()
    .getSession((err, data) => new Promise((res, rej) => err ? rej(err) : res(data) ));

session.isValid();
```

**Comment by nomadus** [comment]
> May I ask what is the use case? Some of the use cases can be covered by specifying `@auth` in graphql model, if you want to limit access to some model. https://aws-amplify.github.io/docs/cli/graphql#auth

When I use this approach, it evaluates each time if a user is authenticated, which causes additional delays. What I want to achieve is to have a quicker way of checking if the user session is still valid and the user is still authenticated, maybe in offline mode or using local checks

**Comment by powerful23** [comment]
@nomadus  I am going to close this because it's duplicated to #2154 . Currently when calling `currentAuthenticatedUser()` it will send a call to Cognito to get the user attributes which is the main cause of the problem. 

As a workaround you can check your cache(localStorage) to see if there is an item like `CognitoIdentityServiceProvider*****LastAuthUser`.

**Comment by jkeys-ecg-nmsu** [comment]
@nomadus Are you using the Amplify React Components? If so, login events will be published to the 'auth' channel in the Hub category, and you have the `authData` prop in your top-level component (assuming you are using `withAuthenticator` HOC or `<Authenticator>...</Authenticator>`).

**Comment by nomadus** [comment]
@jkeys-ecg-nmsu I am using React and APP component is wrapped within
import { withOAuth } from 'aws-amplify-react';
Will it have the authData?

**Comment by powerful23** [comment]
@nomadus no, the `withOAuth` is just an HOC to help you launch the Cognito Hosted UI.

**Comment by matthamil** [comment]
Apologies for commenting on a closed ticket. Does the Cognito JS SDK and/or Amplify expose a method that can read cached user info **without** making a network request to Cognito? We use Amplify in a React Native app. The app needs to work entirely offline. I can check the app's cache to see if a key like `CognitoIdentityServiceProvider` exists, but since this isn't accessed through a public API, I am concerned that this could become a nasty bug for us in the future. Is there a way through the Auth module to get the current user even if their token has expired? Does `getCurrentAuthenticatedUser` return a user only when the token is still valid?

**Comment by jkeys-ecg-nmsu** [comment]
I think you want this:

>await Auth.currentSession() //will refresh credentials if they are expired

When you say their token has expired, do you mean the access token or the refresh token? Although I think either way it will still refresh. (My understanding is that a refresh token can be exchanged for another refresh token with a fresh expiry date.)

**Comment by matthamil** [comment]
Update since my previous comment: if you want to check if the user is authenticated without waiting for a network request, you can implement your own Auth storage interface: https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens. You can use that to keep an in-memory cache that also writes to some kind of storage like localStorage/AsyncStorage/etc. In our case, we are using a React Native app that needs to work while offline. Since the methods on the Auth client (like getCurrentAuthenticatedUser) attempt to make a network request to refresh the access token if it's expired, and since `fetch` in React Native throws an error while attempting a network request while offline, a custom auth storage client seems to be a good fit for us. I just wrapped up writing an implementation that lets us not only hook into auth events, but also read from the cache to see if a user exists. In my opinion, this is a cleaner solution than suggested in https://github.com/aws-amplify/amplify-js/issues/2232#issuecomment-443821459 since a custom auth storage client lets you choose which keys your auth things are written to, rather than hard-coding in your app an arbitrary key that Amplify's Auth is writing to as of the current version of the library. If you are reading this and also are working on a React Native app that has to work fully offline, I recommend checking out the first link I posted in this comment.

**Comment by dmarkham95** [comment]
@matthamil  Can you share a code snippet? I'm trying to go this route but running to an issue with this approach

**Comment by matthamil** [comment]
@dmarkham95 What problems are you running into in particular?

This is a shortened version of what we're doing. I've omitted some code, but I hope this helps you:

```js
// The AWSAmplifyAuthStorage interface is a Flow class interface 
// that we have created in our own code base--it's a copy of 
// the TS interface.
class AuthStorageClient implements AWSAmplifyAuthStorage {
  inMemoryCache: InMemoryCache = {}

  syncPromise: ?Promise<void> = null

  didSync: boolean = false

  /**
   * @description
   *   Holds references to handlers to call when an item has been added
   *   to the in-memory cache or storage (at an auth key)
   *   This is NOT part of the AWSAmplifyAuthStorage interface.
   */
  authListeners: Set<AuthListener> = new Set()

  constructor() {
    // Start loading stored auth data into memory on initialization
    this.sync()
  }

  addAuthListener = (handler: AuthListener): UnsubscribeHandler => {
    this.authListeners.add(handler)

    // Emitting id token to all new subscribers
    // You may choose to not emit anything to new subscribers.
    // This made our particular requirements easier for us.
    if (this.didSync) {
      const idToken = getIdToken(this.inMemoryCache)
      const syncCompletedAction: IdTokenUpdateAction = {
        type: AuthCacheEvents.ID_TOKEN_UPDATE,
        payload: { idToken },
      }
      handler(syncCompletedAction)
    }

    // Call the returned function to unsubscribe to auth events
    return (): void => {
      this.authListeners.delete(handler)
    }
  }

  setItem = (key: string, value: string): string => {
    try {
      this.inMemoryCache[key] = JSON.parse(value)
    } catch (error) {
      this.inMemoryCache[key] = value
    }
    AsyncStorage.setItem(`${STORAGE_KEY_PREFIX}${key}`, value).catch(
      (error: Error): void => log.error('Failed to write to cache at key', { error, key })
    )

    const actionType = getActionTypeForWriteAtCacheKey(key)
    if (actionType) {
      const authUpdateAction: IdTokenUpdateAction = {
        type: actionType,
        payload: { idToken: value },
      }
      callEach(this.authListeners, authUpdateAction)
    }

    return value
  }

  getItem = (key: string): ?string => {
    const item = this.inMemoryCache[key]
    return item
  }

  removeItem = (key: string): void => {
    AsyncStorage.removeItem(`${STORAGE_KEY_PREFIX}${key}`).catch((error) => {
      log.error('Failed to remove item from cache at key', { error, key })
    })
    const { [key]: toRemove, ...restOfCache } = this.inMemoryCache
    this.inMemoryCache = restOfCache
  }

  clear = (): void => {
    this.inMemoryCache = {}
  }

  sync = (): Promise<void> => {
    if (!this.syncPromise) {
      this.syncPromise = this.startSyncFromAuthStorage()
    }
    return this.syncPromise
  }

  startSyncFromAuthStorage = async (): Promise<void> => {
    const isSyncing = Boolean(this.syncPromise)
    if (isSyncing) {
      return
    }

    try {
      const keys = await AsyncStorage.getAllKeys()
      const entries = await AsyncStorage.multiGet(keys)
      const cache = entries.reduce((map, [key, value]): void => {
        const keySansPrefix = key.replace(STORAGE_KEY_PREFIX, '')
        map[keySansPrefix] = value
        return map
      }, {})
      this.inMemoryCache = cache
      log.debug('InMemoryCache loaded from sync storage')
    } catch (error) {
      log.error('Failed to sync auth storage and load into memory', { error })
    }

    this.didSync = true
    // Emit id token update action on completion of storage sync
    const idTokenUpdateAction: IdTokenUpdateAction = {
      type: AuthCacheEvents.ID_TOKEN_UPDATE,
      payload: {
        idToken: getIdToken(this.inMemoryCache),
      },
    }
    callEach(this.authListeners, idTokenUpdateAction)
  }
}

// in amplify setup:
Auth.config({ storage: new AuthStorageClient() })
// or
Amplify.config({ ...restOfSetup, Auth: { ...authConfig, storage: new AuthStorageClient() } })
```
