### ISSUE TITLE
Process for forking entire aws-amplify and building ourselves

### ISSUE THREAD

**Issue by CodingToBeWithHer** [aws-amplify/amplify-js#2271]
** Which Category is your question related to? **
aws-amplify

** What AWS Services are you utilizing? **
aws-amplify
aws-amplify-react

** Provide additional details e.g. code snippets **

I needed the following adjustments in aws-amplify-react:
- different language
- change colors
- add extra signup fields
- add extra error handlings (for phone number and new attributes)
- remove username field and submit in its place the email itself
- add extra text clarifying that the "6 digits code has been sent to your email"
- adding image logo above the login screen

I was unsure how to achieve all reusing aws-amplify-react that so in the end I 
- forked aws-amplify library,
- made changes I needed, 
- I investigate how aws-amplify is built (using typescript) so I installed typescript and built it
- I imported my new version of aws-amplify-react to node_modules
- I built my entire project

screenshots:
<img width="393" alt="screen shot 2018-12-06 at 15 01 23" src="https://user-images.githubusercontent.com/14866119/49591999-e09af700-f967-11e8-9e87-55b539bbbedf.png">
<img width="441" alt="screen shot 2018-12-06 at 15 03 15" src="https://user-images.githubusercontent.com/14866119/49592099-29eb4680-f968-11e8-99fd-b030cabac86b.png">

but
- this is not easy to automate - I have 2 separate building processes - for aws-amplify-react package and then different for my entire project
- the colors (and other css I had to modify) are imported from: @aws-amplify which is separate to aws-amplify-react so I had to change it manually

Is there better procedure I could follow to achieve results like on the screenshots above, while reusing already built in UI (and just modifying it how I need it) ?

**Comment by jordanranz** [comment]
Hi @CodingToBeWithHer,

Thanks for the feedback. There are a few points I can touch on here. With the current aws-amplify-react implementation you can achieve:
- different language
  - Using the i18n utility: https://aws-amplify.github.io/docs/js/i18n
- change colors: 
  - You can pass in a theme object to add inline styles to specific components: https://aws-amplify.github.io/docs/js/authentication#customize-ui-theme. (Note: We are working on improving this use case)
- add extra signup fields:
  - This is a feature that currently exists on our Beta branch. It will soon be in the release version.

Questions:
- adding image logo above the login screen
  - Would you like this to be inside of the Authenticator component above the top input field or outside of the component?
- remove username field and submit in its place the email itself
  - Does this mean have an email input instead of username and remove the submit button at the bottom?

Feature requests:
- add extra error handlings (for phone number and new attributes)
  - This is something we are looking update to allow custom error handling per field. It is in our backlog.
- add extra text clarifying that the "6 digits code has been sent to your email"
  - Also something we would like to allow our users to do is manipulate the subcomponents a bit more flexibly. Also something on our backlog. 

For local development procedure, take a look at:
https://github.com/aws-amplify/amplify-js/wiki/Local-Development

Thanks again for the feedback. Hope some of this helps.

**Comment by CodingToBeWithHer** [comment]
Thank you for the answer - I enjoy working with Cognito, so thx for doing a good work.

Answers to Questions:
- I put the logo above the top input field, outside the component, but it does not really matter if outside or inside
- In Cognito Console I have selected: 
<img width="864" alt="screen shot 2018-12-07 at 21 42 33" src="https://user-images.githubusercontent.com/14866119/49674215-1378e400-fa69-11e8-9938-43940ea3ef03.png">

so in the default UI with: username, password, email, phone,   the behaviour
 is very confusing because if username needs to be an email (otherwise there is error for user) user ends up typing twice his email in both fields: username and email

so I removed username field, I only have email field and I just submit the email that user typed automatically in signup request as username and as email attribute

(the two fields above email that you see on my screenshot are not username, but first and last name - attributes I added)
--------------------

I'll take a look in the Local Deployment file, I'd suggest to write some detailed tutorial how one can just fork the aws-amplify and modify how he needs it to.
It'll be hard to cover all usage cases in the near future.
(for example: what if one needs phone number validation, what if one needs to add extra terms and condition tick box on the sign up page, what if one needs extra confirmation password field etc)
-----------------

I was also wondering whether there is plan to support PKCE flow to use web view also as sign in process for iOS and Android - what would save a lot of dev time
(for time being our team would need to fork all three libraries: Web, Android, iOS and make the changes I've spoken before - or implement UI from scratch, and PKCE could make one - web login usable everywhere)
Regarding PKCE, let's move the discussion here:
https://github.com/aws-amplify/amplify-js/issues/2283

**Comment by ericclemmons** [comment]
Most, if not all, of the requested customizations have been resolved via `@aws-amplify/ui-react`:
> https://docs.amplify.aws/ui/q/framework/react

Including custom messages via I18n:
> https://docs.amplify.aws/ui/customization/translations/q/framework/react
