### ISSUE TITLE
Auth.updateUserAttributes not working

### ISSUE THREAD

**Issue by risingtalent22** [aws-amplify/amplify-js#2276]
I tried to update phone_number attribute using Auth.updateUserAttributes, but had an error.
My code:
let user = await Auth.currentAuthenticatedUser();
let result = await Auth.updateUserAttributes(user, {'phone_number': phone});

Error:
TypeError: user.getSession is not a function

Version:
"aws-amplify": "^1.1.11",
"react": "16.6.1",
"react-native": "0.57.5",

**Comment by powerful23** [comment]
@risingtalent22 Hi seems like the user you got `currentAuthenticatedUser` is not a valid `CognitoUser` object. Can you print that user object? Also can you check if you called `Auth.federatedSignIn()` in your code?

**Comment by risingtalent22** [comment]
@powerful23 , return value of `currentAuthenticatedUser` is `{id: "us-east-1:c4e2cd39-04ef-47b9-a200-9767652ffa37"}`. 
And I used `Auth.federatedSignIn` to implement google signin.
await GoogleSignin.hasPlayServices();
const userInfo = await GoogleSignin.signIn();
const {idToken, accessTokenExpirationDate} = userInfo;
return Auth.federatedSignIn('accounts.google.com', {
        token: idToken,
        expires_at: accessTokenExpirationDate,
}, {});

**Comment by powerful23** [comment]
@risingtalent22 seems like the current user is not a Cognito user but a user generated after calling `Auth.federatedSignIn()`. 

The `Auth.federatedSignIn()` has **no** relation to the Cognito User Pool. When you sign in with that method, the user you get from `Auth.currentAuthenticatedUser()` is the user object passed through `Auth.federatedSignIn()` plus the identity id from the Cognito Federated Identity Pool. Since you are not pass any user object in that method, the returned value only contains the identity id.

**Comment by risingtalent22** [comment]
@powerful23 , what should I do to get currentAuthenticatedUser after federatedSignIn?

**Comment by risingtalent22** [comment]
@powerful23 , you are right.
And now I need to update user attributes after federatedSignIn. But how can I get current user object to use in `updateUserAttributes` function

**Comment by powerful23** [comment]
@risingtalent22 you can **not** use the `updateUserAttributes` in this case because this method is only for Cognito Users.

**Comment by powerful23** [comment]
Closing the issue due to no further response. Feel free to reopen if you still have this issue.

**Comment by DeniferSantiago** [comment]
Here is the solution I found to this problem: https://github.com/aws-amplify/amplify-js/issues/6444#issuecomment-841614409
