### ISSUE TITLE
AWS Amplify - terminates session when there is no user activity (making api calls, etc.)

### ISSUE THREAD

**Issue by haimLeibovitc** [aws-amplify/amplify-js#2384]
I'm using the AWS-Amplify library in my single page application. The user login is managed by Amazon-cognito.

Client - API requests contain JWT (header - Bearer Authentication).

Server side(node.js) - receives the token and validates it (via jsonwebtoken).

This works well to the point that there is no user activity for a long period (over an hour).

I simulated this scenario. In my client side app i was inactive, and before sending the request i checked the state of the session:

const session = await Auth.currentSession();
if (!session.isValid()) {
    ...
}
The isValid method returns always true, because the expiration time of the token is automatically extended. When this token is being sent to the server, the authentication fails.

How can i overcome the inactivity issue, without workarounds (timers etc...)?

**Comment by elorzafe** [comment]
@haimLeibovitc how are you passing the JWT to make API requests? Can you share a code snippet?

**Comment by haimLeibovitc** [comment]
Just wanted to mention that it works perfectly fine to the point that there is no user activity for a long period.

try {
   const { jwtToken } = user;
   const response = await fetch(url, {
        headers: {
            Authorization: `Bearer ${jwtToken}`
        }
    });
    const data = await response.json();
    const { catalogCategories } = data;
} catch (err) {
    Logger.log(err);
}

**Comment by jkeys-ecg-nmsu** [comment]
@haimLeibovitc Amplify will refresh your tokens for you on the client-side, but it can't refresh the tokens for you in the backend, especially since you're not providing the backend a refresh token :D. 

You need to send your Lambda/Node server the refresh token too, and check if the access token's expired in your Lambda before trying to use it; if it is expired, use the refresh token to get a new access token.

https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-user-pools-using-the-refresh-token

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference//API_AdminInitiateAuth.html

> AuthFlow - The authentication flow for this call to execute. The API action will depend on this value. For example:
> 
> REFRESH_TOKEN_AUTH will take in a valid refresh token and return new tokens.
> [...]
> Valid values include:
> [...]
> REFRESH_TOKEN_AUTH/REFRESH_TOKEN: Authentication flow for refreshing the access token and ID token by supplying a valid refresh token.
