### ISSUE TITLE
Create signInConfig similar to signUpConfig for <amplify-authenticator>

### ISSUE THREAD

**Issue by holtc** [aws-amplify/amplify-js#2403]
**Is your feature request related to a problem? Please describe.**
It would be great to have a `signInConfig` similar to the `signUpConfig` attribute to customize the names of the fields shown in the sign up form.  For example, the UI currently prompts for `Username`, but my app uses emails to sign up/sign in, so this could be confusing for users.

**Describe the solution you'd like**
It would be great to be able to set the label manually, so users could change it to say 'Email', or 'Phone Number' if they use phone numbers to log in on their apps.

**Describe alternatives you've considered**
I've written a sign in page on my own, but I'd really like to leverage the default UI for this.

**Comment by holtc** [comment]
@elorzafe great, thanks!

**Comment by holtc** [comment]
I tried to create a PR but I do not have the permissions, so I have uploaded the diff files as .txt files.  I have tested locally and it works as desired.  The code also helps solve [2414](https://github.com/aws-amplify/amplify-js/issues/2414) and [2403](https://github.com/aws-amplify/amplify-js/issues/2403).

[authenticator.component.core.ts.txt](https://github.com/aws-amplify/amplify-js/files/2709655/authenticator.component.core.ts.txt)
[authenticator.factory.ts.txt](https://github.com/aws-amplify/amplify-js/files/2709656/authenticator.factory.ts.txt)
[sign-in.component.core.ts.txt](https://github.com/aws-amplify/amplify-js/files/2709674/sign-in.component.core.ts.txt)
[sign-in.component.factory.ts.txt](https://github.com/aws-amplify/amplify-js/files/2709675/sign-in.component.factory.ts.txt)

**Comment by NisaarAgharia** [comment]
its available for react and vue, why is this issue with angular? can any one please help

**Comment by NisaarAgharia** [comment]
@holtc , hi chris, 
i changed the node_modules files of aws amplify angular, but the html page cant recognize the signInConfig, my packages updated pages are not getting picked up.

**Comment by holtc** [comment]
I actually cloned the repo and then built it and pointed my dependency to my local copy, and that should fix it

**Comment by Firefox2005** [comment]
+1

**Comment by jarrettj** [comment]
+1

**Comment by runcible** [comment]
You could use the i18n service available from the **aws-amplify-angular** npm package, intended to provide internationalisation functionality through the use of translation libraries. The amplify-authenticator component uses this service to inject the text being displayed, so if you modify the translation library for the language in your locale, the component will display that text instead of the default.

The method on the i18n service is **putVocabularies** which requires a json object specifying the locale the translations refer to and a series of key/value pairs, where the key is simply the text currently being displayed

**myauth.component.html**
`
<amplify-authenticator [signUpConfig]="signUpConfig"></amplify-authenticator>
`
**myauth.component.ts**
`
import { Component } from '@angular/core';
import { AmplifyService } from 'aws-amplify-angular';

@Component({
    selector: 'myauth',
    templateUrl: './myauth.component.html'
})
export class MyAuthComponent {
    constructor(private amplifyService: AmplifyService) {
        this.amplifyService.i18n().putVocabularies({
            'en-US':
            {
                'Username': 'Email address',
                'Username *': 'Email *',
                'Reset your password': 'Forgotten your password?',
                'You will receive a verification code': 'Submit an email to receive a verification code'
            }
        })
    }
}
`

**Comment by sammartinez** [comment]
Closing as the above implementation is complete from the reference
