### ISSUE TITLE
[React][aws-amplify-react]: Authenticator component does pass pass the 'signOut' event to child components 

### ISSUE THREAD

**Issue by lambda0xff** [aws-amplify/amplify-js#2419]
**Describe the bug**
When wrapping components inside a custom `<Authenticator>`, auth events are correctly propagated to child components through props, except for 'signOut'

**To Reproduce**
```
const AlwaysOn = (props: any) => {
  console.log('Always on ', props.authState)
  return (
    <div>
      <div>I am always here to show current auth state: {props.authState}</div>
    </div>
  )
}

ReactDOM.render(
  <Authenticator hideDefault={true}>
    <AlwaysOn/>
    <SignUp />
    <SignIn />
    <App />
  </Authenticator>,
document.getElementById('root')
```
The AlwaysOn component does not correctly display the 'signOut' event

**Expected behavior**
'signOut' event should be passed to child components

**Comment by haverchuck** [comment]
@lambda0xff - Are you saying that the child components for <Authenticator> should all receive the event as props?  I hesitate to do this because it could introduce unexpected behavior for existing apps using this package.   Have you tried having the child components[ listening for the Hub signout event](this.onHubCapsule.bind = this.onHubCapsule.bind(this))?

**Comment by haverchuck** [comment]
Hi @lambda0xff  - I see your point.

**Comment by sammartinez** [comment]
@lambda0xff Is this still a valid use case for you? Seems like Hub would give you this and I do see that you called out it works as expected. Please let us know.

**Comment by lambda0xff** [comment]
👍
