### ISSUE TITLE
Storage List order by date uploaded

### ISSUE THREAD

**Issue by safaiyeh** [aws-amplify/amplify-js#2429]
I am using an S3 Bucket as a CDN. It would be helpful if Storage.list had order by time uploaded/modified.

Could be as simple as Storage.list('photos/', { order: 'date' }).

**Comment by jkeys-ecg-nmsu** [comment]
@jordanranz We (or at least I) haven't really explored the Storage category, but it might be useful for realtime ingestion of data into S3 datalakes if we could specify prefixes (representing dimensions, e.g. year/month/day uploaded in @JSafaiyeh's example) as JSON schema.

**Comment by JSafaiyeh** [comment]
I went through the aws-sdk S3 docs. If I am not mistaken, it does not include any "order by" filtering. Solutions seem to be client side only. Would this be appropriate to implement in Amplify or does Amplify expose the metadata to sort client side?

**Comment by jkeys-ecg-nmsu** [comment]
@JSafaiyeh S3 is object storage. Since objects have no natural ordering -- you cannot simply compare any two random "objects" and expect one to be less than, equal to, or greater than the other, in whatever metric you choose -- you need to add metadata to your objects that can be compared against in some sort of comparison function. And even then you can't really keep your data "sorted" directly in S3; the alternative is to make it efficient to query for date by prefix, then compare by query. Or, just simple to ingest into a traditional SQL data warehouse and go from there.

In the case of S3, the commonly described files and directories of S3 are a fiction invented to ease adoption. There are only objects, with either no prefix (`/` prefix), or some prefix ("prefixes") which may or may not reflect some data that can be ordered on. So say you have objects with which you want an ordering granularity of daily, you might add three prefixes (or, three "dimensions" in the statistical/machine learning sense) to every object following this schema:

`https://s3.amazonaws.com/my-bucket/year/month/day/[50meBAsE640bject.json]`

Then you could use a big data tool to ingest your data and query it at the granularity of objects by year, month, or day. If you had some other hierarchical ordering criterion, you could make those your prefixes as you put objects to your bucket.

Before rolling my own sol'n though I'd check the package manager for your language of choice for any stable package that treats S3 as datalakes (e.g. prefixes as dimensions). 

(Knowledge regarding S3 prefixes as dimensions, and big data concerns at large, courtesy of Big Data course presented to Electronic Caregiver devs by Bruno Reis @bfreis of AWS. @jordanranz @bfreis please correct any mistakes!)
