### ISSUE TITLE
User session is not refreshed after period of idle in the browser

### ISSUE THREAD

**Issue by dnagir** [aws-amplify/amplify-js#2503]
**Describe the bug**

Getting `No credentials` (more - `[WARN] 33:03.724 AWSS3Provider - ensure credentials error cannot get guest credentials when mandatory signin enabled`) after a period of inactivity.

**To Reproduce**
Steps to reproduce the behaviour:

1. Use the example code attached below.
2. Sign In via hosted UI (redirect back to the site - localhost in my case).
3. The current user is correctly read; `Hub` `signIn` notification is correctly received.
4. Upload a file to S3 using `Storage` API (-> successfully)
5. Wait for _a while_ (in my case it was ~12hrs~ 1hr)
6. Upload a file to S3 using `Storage` API

**Expected behaviour**
After step 6, I am expecting Amplify to automatically refresh the token and upload the file successfully.

But _actual_ behaviour is that the current user is no longer available and as such upload fails.

**Screenshots**
<img width="955" alt="screen shot 2019-01-09 at 12 56 44 pm" src="https://user-images.githubusercontent.com/195035/50881530-ff445000-1435-11e9-9777-4d5ae471b545.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser:  Chrome 71
- Amplifyjs version: 1.1.18

**Additional context**

The JS code on the web page:

```javascript
import Amplify, { Auth, Hub, Storage } from 'aws-amplify';

Amplify.configure({
  Auth: {
    identityPoolId: process.env.ELM_APP_IDENTITY_POOL_ID,
    region: process.env.ELM_APP_REGION,
    userPoolId: process.env.ELM_APP_USER_POOL_ID,
    userPoolWebClientId: process.env.ELM_APP_USER_POOL_CLIENT_ID,

    mandatorySignIn: true,

    oauth: {
      domain: process.env.ELM_APP_OAUTH_DOMAIN,
      scope: ['phone', 'email', 'profile', 'aws.cognito.signin.user.admin', 'openid'],
      redirectSignIn: process.env.ELM_APP_OAUTH_SIGNED_IN_URL,
      redirectSignOut: process.env.ELM_APP_OAUTH_SIGNED_OUT_URL,
      responseType: 'token',
      options: {
        AdvancedSecurityDataCollectionFlag: false
      }
    },
  },
  Storage: {
    bucket: process.env.ELM_APP_USER_FILES_BUCKET,
    region: process.env.ELM_APP_REGION
  }
});

// TODO: Expose for debugging purposes to play in console
window.app = app;
window.Auth = Auth;
window.Storage = Storage;

Hub.listen('auth', {
  onHubCapsule: (capsule) => {
    switch (capsule.payload.event) {
      case 'signIn':
        console.error('user signed in', capsule);
        readCurrenUser(capsule.payload.data);
        break;
      case 'signUp':
        console.error('user signed up', capsule);
        break;
      case 'signOut':
        console.error('user signed out', capsule);
        readCurrenUser(null);
        break;
      case 'signIn_failure':
        console.error('user sign in failed', capsule);
        break;
      case 'configured':
        console.error('the Auth module is configured', capsule);
        break;
    }
  }
});

function readCurrenUser(user) {
  window.user = user;

  if (user) {
    // TODO: Verify user is authenticated before asking for attributes (otherwise promise fails)
    Auth.userAttributes(user).then(attributes => {
      const email = attributes.find(x => x.Name == 'email').Value;
      // TODO: debugging
      window.userAttributes = attributes;
    });
  } else {
    app.ports.currentUserSet.send(null);
  }
};

// Get out with Auth.signOut()
// Trigger current user auth
Auth.currentAuthenticatedUser().then(user => readCurrentuser(user));
```

**Full console output with debugging**

<img width="1678" alt="screen shot 2019-01-09 at 6 58 12 pm" src="https://user-images.githubusercontent.com/195035/50885035-b1811500-1440-11e9-8b33-9413086d58b0.png">

**Comment by powerful23** [comment]
@dnagir because the flow you are using is `token` as the response type in your oauth config which would not return the refresh token thus the session will be expired and cannot be refreshed after 1 hr. You need to switch to the `code` flow. For more info: https://aws-amplify.github.io/docs/js/authentication#setup-your-cognito-app-client -> Select an Oauth flow

**Comment by dnagir** [comment]
@powerful23 thanks, switching to `token` will update after a bit of idle :)

I couldn't find in the docs that it stated it _only_ refreshes token for `code` response type/flow.
Perhaps some clarification is required in the docs?

But I'm pretty sure the refresh token was returned with the `token` flow too?
This is what Amplify stored in the browser local storage:

<img width="1671" alt="screen shot 2019-01-10 at 1 52 30 pm" src="https://user-images.githubusercontent.com/195035/50943066-01aeb480-14df-11e9-826d-6eae12dd776b.png">

**Comment by powerful23** [comment]
@dnagir from the Cognito doc: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-idp-settings.html

> Allowed OAuth Flows
The Authorization code grant flow initiates a code grant flow, which provides an authorization code as the response. This code can be exchanged for access tokens with the TOKEN Endpoint. Because the tokens are never exposed directly to an end user, they are less likely to become compromised. However, a custom application is required on the backend to exchange the authorization code for user pool tokens.
Note
For security reasons, we highly recommend that you use only the Authorization code grant flow, together with PKCE, for mobile apps.
The Implicit grant flow allows the client to get the access token (and, optionally, ID token, based on scopes) directly from the AUTHORIZATION Endpoint. Choose this flow if your app cannot initiate the Authorization code grant flow. For more information, see the OAuth 2.0 specification.
You can enable both the Authorization code grant and the Implicit code grant, and then use each grant as needed.

As it says, the implicit grant flow only returns the access token and ID token(based on your scopes)

**Comment by powerful23** [comment]
Closing this issue due to no further response. Feel free to reopen if you still have this issue.

**Comment by undefobj** [comment]
Hello everyone, we have created an RFC for feature work that should make the challenges found in this issue easier in the future. If you have a moment please read through the details and add any comments: https://github.com/aws-amplify/amplify-js/issues/2716

Your feedback in the RFC will help us ensure that we are delivering the best experience possible. Thank you.
