### ISSUE TITLE
[Vue] AmplifyEventBus Unnecessary?

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#2540]
** Which Category is your question related to? **

aws-amplify-vue

** Provide additional details e.g. code snippets **

In reviewing the code for aws-amplify-vue, I don't see why the AmplifyEventBus is even needed when we already have the Hub in the main Amplify package. It seems that this is redundant and prone to misuse/misunderstanding. I vote for deprecating AmplifyEventBus in favor of the Hub.

**Comment by haverchuck** [comment]
@cliffordh - We implemented the AmplifyEventBus thinking that it would be more familiar to Vue developers, but you certainly have a point.  I think it is time to consider making the change you suggest. I'm marking this as an enhancement request.

**Comment by Pyronerd62** [comment]
I'm not part of the amplify team but as a dev I stumbled upon this today. I slightly disagree. AmplifyEventBus is super simplistic and honestly easy to use. It's pretty difficult to screw up. 

However, It is true using Hub is available but the purpose of libraries is to wrap modules into simplistic ones. Saying that the AmplifyEventBus is unnecessary is like saying axios is unnecessary because you can always use an XMLHttpRequest. Just my 2 cents. Anyway, as devs we always adjust to changes but I figured I'd make a case for leaving it as is.

**Comment by cliffordh** [comment]
Using the Hub is not really more difficult than using AmplifyEventBus (which incidentally doesn't exist in the React or Angular libraries). From my experience, using the Hub in a larger app leads to a cleaner architecture.

**Comment by fboudra** [comment]
based on my question https://github.com/aws-amplify/amplify-js/discussions/5824, I would rather see a clear message to deprecate AmplifyEventBus and better migration documentation for Vue framework users. Some examples with Vuex will be appreciated. At the moment, Vue is still a 2nd class citizen, even Hub documentation is toward React and Redux/Mobx. I suggest to split Hub state management to the relevant framework and provide examples to integrate with redux, mobx, vuex, etc...

**Comment by ericclemmons** [comment]
With https://docs.amplify.aws/ui/q/framework/vue, the AmplifyEventBus is no longer necessary. `Hub` is preferred!
