### ISSUE TITLE
Auto signin after confirm email

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#2562]
**Is your feature request related to a problem? Please describe.**
Currently, users must sign in after email confirmation. It would be ideal if a user did not have to sign in after creating their account and verifying their email.

**Describe the solution you'd like**
I would like the user to automatically be signed in after email confirmation.

**Describe alternatives you've considered**
I have not dug into the code to see how I might accomplish this on my own. Ideally, this should be parameterized, i.e., autoSigninAfterConfirmEmail: true.

**Comment by haverchuck** [comment]
@cliffordh - I marked this as an enhancement request.  Just want to note for future consideration, however, that this flow could be awkward if user verification upon signup AND MFA are configured for a User Pool.  With this scenario, an automated signin would result in the end user:

1. Receiving a text/email after they signup.
2. Confirming using the registration code.
3. Immediately receiving another text/email.  

Not necessarily a giant issue (assuming these messages have good subject lines configured) but definitely something to consider.

**Comment by alpeshgaglani** [comment]
I wanted to echo same concern.. I have read several threads that have this issue. For our case, we have two customers who use phone-number-only auth (similar to WhatsApp). The first-time sign up is a critical consideration for these consumer oriented companies. 
We really want to use Amplify because we love everything else about it. However, forcing the user to respond to two sms codes on first-time use is a non-starter.

Any ideas if/when this will be done?

**Comment by wyzzy** [comment]
We have a similar issue. We confirm a user sign up with an SMS and want to be able to establish a user session at that point, without an explicit sign in immediately after the sign up.

There appear to be several folks interested in this feature: 

https://github.com/amazon-archives/amazon-cognito-identity-js/issues/186

**Comment by Nanobrainiac** [comment]
Okay, so here we are feb 4, 2019...has this feature been added yet??

**Comment by jdrydn** [comment]
I'm with @Nanobrainiac here - three plus years have gone by and the "best solution" to this currently is:

> [@chetanme commented on 24 Oct 2016](https://github.com/amazon-archives/amazon-cognito-identity-js/issues/186#issuecomment-255657874)
> From the SignUp page, you already have user's username and password in the app context. You can just use those values to create a new CognitoUser and then calling authenticateUser on the user object onSuccess of the user confirmation. On authentication success, userPool.getCurrentUser should return you the logged in user.

It's also strange how poorly documented the Amazon Cognito Identity JS package is. Plenty of examples, sure, but zero documentation.

**Comment by powerful23** [comment]
Related #991

**Comment by hounded** [comment]
If you have their pass from some registration form could you do something like below or is this bad? 
```javascript 
const { email, pass } = this.form
const { code } = this.confirmation
await this.$Auth.confirmSignUp(email, code).then( async data => {
          await this.$Auth.signIn(email, pass).then( data => { 
               this.$router.push({ name: 'home' })
          })
})
```

**Comment by frontr-uk** [comment]
where would you get the code from?

**Comment by staneslevski** [comment]
@frontr-uk 

I came across this thread because I'm trying that right now and keep failing to be able to successfully call `Auth.signIn` immediately after calling `Auth.confirmSignUp`. I'm currently not sure why, but each time I get
`[ERROR] 59:30.277 AuthClass - Failed to get the signed in user No current user`
as an error.

When you tried this method, did it work?

**Comment by RWOverdijk** [comment]
Is this going anywhere?

**Comment by murribu** [comment]
My solution was to combine the `SignUp` and the `ConfirmSignUp` Components:

```jsx
export default class MySignUp extends SignUp {
  constructor(props) {
    super(props);
    this._validAuthStates = ["signUp", "confirmSignUp"];
    ...
  }

  confirm() {
    const username = this.usernameFromAuthData() || this.inputs.username;
    const { code } = this.inputs;
    if (!Auth || typeof Auth.confirmSignUp !== "function") {
      throw new Error(
        "No Auth module found, please ensure @aws-amplify/auth is imported"
      );
    }
    let self = this;
    Auth.confirmSignUp(username, code)
      .then(async () => {
        debugger;
        const user = await Auth.signIn(username, this.inputs.password);
        this.changeState("signedIn", user);
      })
      .catch(err => this.error(err));
  }

  showComponent(theme) {
    if (this.props.authState === "signUp") {
      return this.showSignUpComponent(theme);
    }
    if (this.props.authState === "confirmSignUp") {
      return this.showConfirmSignUpComponent(theme);
    }
  }

  showConfirmSignUpComponent(theme) {
    ...[copied from ConfirmSignUp's showComponent method]...
  }

  showSignUpComponent(theme) {
    ...[copied from SignUp's showComponent method]...
  }
}
```

**Comment by sarahgriffis** [comment]
Would love an update on the Cognito team!  This feature seems like a no brainer.

**Comment by shbhmbnsl1** [comment]
Any update from the amplify team? I am also working on a project with a similar use case, if this feature could be added then it could be very helpful in building a customer friendly onboarding flow. We see customers getting off the application when prompted to sign in just after sign up.

**Comment by pbirsinger** [comment]
The lack of this feature is causing major friction in our signup phase and major complaints from our users

**Comment by martaGonz** [comment]
I had this problem too, I was forced to create custom sign up screens (because I was unable to remove the "phone" field from the Drop-in UI), and after the user confirms the email,  it is not automatically signed in. 

In case someone needs this, I fixed this problem by I taking "username" and "password" fields from the Sign Up and making a manual Sign In using this function:

 ```

  
func signIn(){
        AWSMobileClient.default().signIn(username: username, password: password) { (signInResult, error) in
            if let error = error  {
                print("\(error.localizedDescription)")
            } else if let signInResult = signInResult {
                switch (signInResult.signInState) {
                case .signedIn:
                    print("User is signed in.")
                case .smsMFA:
                    print("SMS message sent to \(signInResult.codeDetails!.destination!)")
                default:
                    print("Sign In needs info which is not et supported.")
                }
            }
        }
    }
```

**Comment by xitanggg** [comment]
The amplify team should definitely work on this to get it fix to improve user experience and avoid wasting developer's time to build work around. In the meanwhile, here is my work around for anyone sharing this bad user experience. The idea is to store username & password in a tempInfo variable during signUp and call autoSignIn when user signedUp. Note this won't work if user don't finish code authentication in one stop as the temporary variable would be lost when page refreshes/reloads.

```
function App() {
	var tempInfo = {
		u: '',
		p: ''
	};
	const setTempInfo = (input) => {
		tempInfo.u = input.u;
		tempInfo.p = input.p;
	};
       return(<Authenticator
			authState=''
			hide={[SignIn, SignUp]}
			amplifyConfig={awsconfig}>
			<CustomSignIn
				tempInfo={tempInfo}
				setTempInfo={setTempInfo}
			/>
			<CustomSignUp
				tempInfo={tempInfo}
				setTempInfo={setTempInfo}
			/>
		</Authenticator>);
```
class CustomSignUp extends SignUp {
	constructor(props) {
		super(props);
		this._validAuthStates = ['signUp'];
	}

	//Copy what ever signUp has in the documentation (https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/SignUp.tsx)
	signUp() {
		//rest is skipped
		Auth.signUp(signup_info)
		.then((data) => {
			this.props.setTempInfo({ u: username, p: password }); //Add this to store info before changing state
			this.changeState('confirmSignUp', data.user.username);
		})
		//rest is skipped
}
```

```
class CustomSignIn extends SignIn {
	constructor(props) {
		super(props);
		this._validAuthStates = ['signIn', 'signedOut', 'signedUp'];
		this.resetState = this.resetState.bind(this);
		this.autoSignIn = this.autoSignIn.bind(this);
	}

	//--- Auto Sign in after Sign up
	async autoSignIn() {
		if (this.props.tempInfo.u !== '' && this.props.tempInfo.p !== '') {
			try {
				const user = await Auth.signIn(
					this.props.tempInfo.u,
					this.props.tempInfo.p
				);
				this.props.setTempInfo({ u: '', p: '' }); //Clear temp info after successful sign in
				this.checkContact(user);
			} catch (err) {
				console.log(err);
			}
		}
	}

	showComponent(theme) {
		//Check current authState and trigger autoSignIn if it is signedUp
		if (this.props.authState === 'signedUp') {
			this.autoSignIn();
		}
		//skip the rest
	}
}
```

**Comment by mousedownmike** [comment]
This will be really nice to have implemented but in the meantime, I redirect users to the sign-in page with a message like the following:

> You have successfully verified your account. For your security, please log in now.

They typically only see this once and I don't feel comfortable storing the user's password, even temporarily.  

Hopefully this will eventually be handled with tokens from Cognito.

**Comment by xitanggg** [comment]
> This will be really nice to have implemented but in the meantime, I redirect users to the sign-in page with a message like the following:
> 
> > You have successfully verified your account. For your security, please log in now.
> 
> They typically only see this once and I don't feel comfortable storing the user's password, even temporarily.
> 
> Hopefully this will eventually be handled with tokens from Cognito.

I like the message. That is what I have as well if autoSignIn fails due to page refresh. That is the trade off we have to make right now between security and user experience. To make the best of both, we can store username and auto fill username.

**Comment by ashika01** [comment]
This should be now be the natural behavior for the new ui-component - https://docs.amplify.aws/ui/auth/authenticator/q/framework/react

If there is still some parts missing, please feel free to comment here and I will reopen the issue.

**Comment by mousedownmike** [comment]
@ashika01, this request (at least from my perspective) was to support logging in after confirming a signup with the [AuthClass confirmSignUp](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#confirmsignup) method.  

I don't see how a UI specific implementation resolves the fundamental issue with `confirmSignUp`.  Is the react component storing the password locally and using that to sign in (if so, is that really secure)?  Or, has the Cognito endpoint been updated to return authenticated user tokens as part of the confirmation (seems more secure)? 

Maybe if you could link to the code where this is being implemented in the react UI, or document a best practice for this, we could implement it in other UIs.

**Comment by andrewdavidcostello** [comment]
@mousedownmike Looks like the password may be the case based on this line https://github.com/aws-amplify/amplify-js/blob/4f752631d427e149df423a681c1d822abead95a1/packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx#L218

**Comment by mousedownmike** [comment]
@andrewdavidcostello, thanks, that clarifies that this solution is only going to work for React and apparently relies on the plain text password being persisted locally.  It doesn't look like the Amplify team (@ashika01 ?) plan to reopen this ticket so I think I'm going to open a new one.  I don't use React so this isn't really the solution I was hoping for.

**Comment by mousedownmike** [comment]
I've opened #6320 with a proposed use case that would resolve this without the need to persist passwords locally.

**Comment by ashika01** [comment]
@mousedownmike Apologies for not reopening the issue. But I closed this issue with specific to UI components. I see you are talking about Auth in general. Thanks for opening the new issue. We can track it there.

**Comment by trip-sc** [comment]
This issue pushed me over the edge to now use Firebase Auth. Just too awkward of a sign up flow in a world where frictionless sign up is very important. Especially on the first sign in and experience of our users. If it's an internal app, it isn't much of a problem. But if you have external users, it's a problem, and localstorage/inmemory on the client side of the password is not how we want to be forced to implement this.

**Comment by jjalonso** [comment]
Totally agree, on all websites when you sign up, you are already signed in, it should be already available like firebase and the rest of the world does, we use Amplify to have a almost-ready-easy-to-use platform and doing that is quite bad for us/it

**Comment by overgrowninfnat** [comment]
As of now, a smooth authentication workflow is only possible using a pre built UI component which exploits the Auth class and in general the Auth APIs, but it is not possibile to achieve the same result calling the authentication methods directly on the Auth class, on which the Amplify UI Components are built on.

This sounds very strange, but is a matter of fact.

**Comment by sleeviin** [comment]
This really sucks, why they still don't fix this workflow, it's something really common and easy to implement, and looks like they don't care about it.

This makes me think to never use Cognito anymore.

**Comment by dwhiteGUK** [comment]
My solution was to store the user password in local state (it's a react app) and auto sign-in after confirmation

```javascript
  async function confirmSignUp({ code }) {
    try {
      await Auth.confirmSignUp(user.username, code);

      await Auth.signIn(user.username, user.password);

      router.push('/client-protected')
    } catch (error) {
      console.log('error confirming sign up', error);
    }
  }
```

Works well and keeps the nice UI flow

**Comment by disbelief** [comment]
I do something very similar storing it in memory client-side, which isn't great but it works and doesn't cause users any friction.

It does seem that Cognito is barely being supported by AWS though, judging by the treatment of major long-standing issues like this [and others](https://github.com/aws-amplify/amplify-js/issues/3732).

**Comment by overgrowninfnat** [comment]
> My solution was to store the user password in local state (it's a react app) and auto sign-in after confirmation
> 
> ```js
>   async function confirmSignUp({ code }) {
>     try {
>       await Auth.confirmSignUp(user.username, code);
> 
>       await Auth.signIn(user.username, user.password);
> 
>       router.push('/client-protected')
>     } catch (error) {
>       console.log('error confirming sign up', error);
>     }
>   }
> ```
> 
> Works well and keeps the nice UI flow

It’s always a bad idea to store sensitive information on client side (easily accessible from dev tools).

**Comment by jdrydn** [comment]
> It’s always a bad idea to store sensitive information on client side (easily accessible from dev tools).

Not really applicable here, unless `user` in the example given points to some mad global like `window.user` 🤦‍♂️

**Comment by disbelief** [comment]
Agreed it's a poor security practice to store the password in memory. I ensure it's in memory for as brief an amount of time as possible. However dev tools are able to listen to network calls, so they'd see the password anyway wouldn't they?

**Comment by dwhiteGUK** [comment]
> Agreed it's a poor security practice to store the password in memory. I ensure it's in memory for as brief an amount of time as possible. However dev tools are able to listen to network calls, so they'd see the password anyway wouldn't they?

That would be my thinking.... as if somebody has access to devtools on my computer then I've got bigger issues. Or is the issue that a different website can get remote access via devtools?

**Comment by disbelief** [comment]
I imagine modern browsers sandbox memory such that external websites can't access it even if they have JS on the page. 

My assumption re storing sensitive data in plaintext in memory is that there could be a malicious browser extension or 3rd party/malware running on the user's machine that can access it.

Disclaimer: I'm not a security expert

**Comment by dwhiteGUK** [comment]
Done. Good point, I realise my implementation was rather naive and I hadn't through if the user/customer comes back later.

**Comment by stefanvucic** [comment]
The problem about storing the password in local state is that user signs up and he trys to log in after 2 days, he confirms his email but there is no way to have his password at thet point to triger manually signIn method . Why you just do not make the SignIn after confirmSignUp like it is done with withAuthenticator!?

**Comment by BernhardSmuts** [comment]
11 Mar 2022 and this is still an issue... FFS.

**Comment by mayfairr** [comment]
20 May 2022 and this is still an issue... FFS.

**Comment by kyokosdream** [comment]
Is this seriously still an issue? I can't believe this. I've setup my whole stack on AWS and am now stuck here.

**Comment by kyokosdream** [comment]
## Background

I've thought about this for a while and I think with some work we can resolve this and improve everybody's projects. People are here because they want to create custom login, sign-up, etc components in their application but are unable to respond to user email confirmation events during the sign-up process, ruining the user experience of their application, and turning off potential clients. 

I believe there are 3 options for creating a custom UI using AWS Amplify Auth:

1. [Customize the CSS](https://ui.docs.amplify.aws/react/components/authenticator#styling) of the [default pre-made AWS Authenticator UI component](https://ui.docs.amplify.aws/react/components/authenticator) (limited, unrealistic)
2. Customize the components shown when the Authenticator UI component is in one of the [various authState possibilities](https://ui.docs.amplify.aws/react/components/authenticator#access-auth-state) using the component in a "headless" way (more difficult and is AWS-specific) using the [useAuthenticator](https://ui.docs.amplify.aws/react/components/authenticator#useauthenticator-hook) hook.
3. [Create your own UI component](https://docs.amplify.aws/guides/authentication/custom-auth-flow/q/platform/js/) that manually calls AWS Amplify Auth functions to sign-in or sign-up the user (simple, platform independent can be re-used with other authentication backends!)

Now, it's not that the built-in Authenticator UI component is terrible looking, but that it is unrealistic that developers and those building production-level software with specific design systems and their own custom animations won't need to build their own login and sign-up components. Thus, Option 1 CSS customization was out of the question, I wanted to start from scratch using a CSS framework I have recently adopted called Tailwind CSS.

I only considered Option 2 and Option 3 as viable. Despite the complexity and annoyance posed by Option 2, I decided to pursue it first. It seemed like the correct way according to AWS documentation. This is because for some reason or another, _the built-in Authenticator UI component does not suffer from the issue discussed here_. So I thought that this could be the ideal solution. 

## Option 2

Following the documentation, I wrapped my app in an <Authenticator.Provider> https://ui.docs.amplify.aws/react/components/authenticator?platform=react#useauthenticator-hook

And decided to try to conditionally show the my own custom Tailwind CSS login components according to the current authState of the Authenticator.Provider. 
https://ui.docs.amplify.aws/react/components/authenticator?platform=react#access-auth-state

I honestly got sick of trying to do this, not only was I becoming frustrated with how long it was taking me to try to get the useAuthenticator to work and read all the API methods of the Authenticator when I just wanted to do a few simple actions, but I also realized that none of the best developers I know would ever write front-end UI authentication components for a specific authentication backend. They would make it re-usable and fully independent from some service like AWS, easily swapping in with Firebase or Okta if they wanted to. This is when I came to believe that Option 3 was a better architecture. 
## Option 3

I finally read a [part of the Amplify docs](https://docs.amplify.aws/guides/authentication/custom-auth-flow/q/platform/js/) that seemed designed just for my use case! It utilizes the Auth and Hub (Pub/Sub) parts of Amplify in a custom authentication flow. 

> The Amplify UI Component library allows you to scaffold out an end-to-end authentication flow in just a few lines of code, but you will often need to create a custom authentication flow from scratch.

Exactly. I fell back to removing the Authenticator component entirely from my application and just manually calling the Amplify Auth JS library from my own custom UI components. It just felt way simpler and more natural than trying to dig through examples and trigger transition and render custom components through the AWS Authenticator component. 

Here’s the main useEffect in my App.js:

But then I come to the issue that after entering the confirmation code, user’s are re-directed to sign-in again. You can see this in the [official documentation](https://docs.amplify.aws/guides/authentication/custom-auth-flow/q/platform/js/#implementation-of-a-custom-authentication-flow) here beginning on Line 28. This means that the password would have to be stored temporarily in the client browser and also leading to the problem discussed in which they can’t confirm in another browser session or through a re-direct link in the email as has been discussed in this thread.

# The Solution 

Until progress can be made by AWS on improving Option 3. I think we must try to return to Option 2 and try to create our custom UI within the [Authenticator component](https://ui.docs.amplify.aws/react/components/authenticator) which does not suffer from this issue. I will continue to update the community as I progress.

**Comment by trip-sc** [comment]
Option 4: Use firebase auth ;)

**Comment by abdallahshaban557** [comment]
Thank you @kyokosdream for the breakdown of these possible solutions! Our team is currently exploring how to enable this feature for developers using the Amplify JS library, and we will be communicating progress on this feature on this [Github issue](https://github.com/aws-amplify/amplify-js/issues/6320)
