### ISSUE TITLE
How to know if an observable is successfully subscribed to a topic?

### ISSUE THREAD

**Issue by joseph-d-p** [aws-amplify/amplify-js#2573]
**Which Category is your question related to?** 
AWS Amplify - API Subscription Observable

 **What AWS Services are you utilizing?** 
AWS Amplify, AppSync

 **Provide additional details e.g. code snippets** 
I wanted to know when an observable is successfully subscribed to a specific topic.
This is for the app to start triggering some actions.

Here's what I tried thinking that `complete` is the callback where the observer is "now connected" or subscribed.
```js
  subscription.subscribe({
    next: (data) => {},
    error: (error) => {},
    complete: () => {
      console.log('subscribed');
      /* emit(subscribed()); */ 
    },
  });
```

Unfortunately, doesn't print out `'subscribed'`.

Any thoughts?

**Comment by haverchuck** [comment]
@joseph-d-p - There is currently not a simple way to check if the subscription is successfully established, so I am marking this as an enhacement request.

BTW - I believe complete() is called when no more data is forthcoming (i.e. next() is called for last time) and error() hasn't been called.

**Comment by joseph-d-p** [comment]
@haverchuck, say for an example, there's a network error and the observable wasn't successfully hooked up to the topic. Will this be handled in `error` callback or `subscribe()` throws an error?

**Comment by kashirin-dm** [comment]
Any updates on this?

**Comment by ahansson89** [comment]
I really need this too as I need to reset my exponential backoff on a successful connection. Please prioritize!

**Comment by tolgaozkan** [comment]
Is there any workaround for that? Sometimes network delays causes our code work unexpectatly. We can not be sure if client is successfully subscribed and rest of the code relies on subscription.

**Comment by ume-daniel** [comment]
we run a "ping" test when we first create the subscription. we create the subscription and on a 1 second interval, send a message to that subscription with a unique id so that only we are listening to it. once we can "hear" our subscription, we disable the interval and proceed to initialize the correct subscription or do any other initialization.

NOTE: do not delete your "ping" subscription or at least wait until you subscribe to other subs as deleting the first subscription with no other's initialized will result in the websocket closing down.

**Comment by stocaaro** [comment]
On Monday a change was released that adds AppSync subscription connection states to Hub. With this change, it is now possible to monitor as your subscription causes the connection to transition from Disconnected -> Connecting -> Connected so that your application can know when everything is up and working.

The documentation change to cover this behavior is currently [in review](https://github.com/aws-amplify/docs/pull/4505).

This should cover the use-case described here, I'm going to resolve the issue, but would be happy to review further if there is any aspect of this problem not covered by the Hub events.
