### ISSUE TITLE
"Native Module cannot be null" Error

### ISSUE THREAD

**Issue by danielmhanover** [aws-amplify/amplify-js#2584]
For those of you who are encountering an "Native Module cannot be null" Error when using Amplify with a Cocoapods-installed variant of React Native, just make sure you install both the "LinkingIOS" and "RCTPushNotification" subspecs of React.

**Comment by petrbela** [comment]
I've added both subspecs and the problem still exists. Specifically, it happens when I call `Amplify.configure`. In case it's relevant, these are the options:

```js
{
  aws_project_region: '..',
  aws_cognito_identity_pool_id: '',
  aws_cognito_region: '..',
  aws_user_pools_id: '..',
  aws_user_pools_web_client_id: '..',
  aws_appsync_graphqlEndpoint: '..',
  aws_appsync_region: '..',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
}
```

React Native should really tell you _which_ module cannot be null. However, the problem also is that the amplify package is not well documented in terms of dependencies for this case. `aws-amplify-react-native` even has a few packages in peer dependencies, which are supposedly required but not documented anywhere?

**Comment by predescu** [comment]
I have the same error if I'm trying to migrate react-native-push-notification-ios from the core react-native module to the react-native-community module.
