### ISSUE TITLE
Add support for role customisation in the Auth package

### ISSUE THREAD

**Issue by barroij** [aws-amplify/amplify-js#2675]
As of today, there is no way to pass the parameter `CustomRoleArn` to amplify so that it is used when getting the credentials (by calling `new AWS.CognitoIdentityCredentials`). It is part of the API : https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetCredentialsForIdentity.html

The alternative is to not use Amplify and to use directly aws-sdk and some other packages.

So it would be nice to add support for that !

**Comment by undefobj** [comment]
Would the Fine Grained Access Control option in this RFC meet your needs? https://github.com/aws-amplify/amplify-cli/issues/766

This has the benefit of being controlled by the backend rather than needing to pass this in the client, which could be compromised and also leaks backend implementation into the API (which we would rather avoid).

**Comment by barroij** [comment]
I'm not talking about the CLI but the javascript plugin. And not about configuring CognitoUserGroup but dynamically assigning a role to a user in my client app.

My Identity Pool do use the fine grained access control based on group membership, but in case of a user belonging to two groups with the same precedence, no princial role is assigned to the user, but it is possible to ask credentials for one the available roles by specifying hte `CustomRoleArn` property of the `GetCredentialsForIdentityInput` (cognitoidentity.d.ts in aws-sdk).

The purpose of this feature request to make this available in the amplify package.

**Comment by undefobj** [comment]
Yup, I understand you are talking about doing it in the client app. However as stated this is generally not good practice as clients are spoofable, it also leaks implementation into the client which we try to avoid in Amplify design. In that RFC you will see it's not only talking about Cognito Groups for dynamic access but also dynamic role assignment based on rules in claim attributes.

Could you give us details on why you are trying to accomplish this? Knowing the use case and business scenario would better help understand the request.

**Comment by barroij** [comment]
My use case is :
I have a web app in which user can sign up. Users are grouped by Team/Compagny. The user that creates the team becomes the "team owner". A Team has different projects. The "team owner" assign team members to one or several projects. And the permission to access/modify ressource of a user depends on the projects it has been assigned to and/or whether it the "team owner" or equivalent.

So the permissions  a user is beeing given is pretty "dynamic". It might have rights on project 'A', 'B', but not 'C'.

And I am evaluating aws and cognito to see how to use policies/roles and cognito to achieve that. And in my tests to understand how cognito works and how to use it, I stumbled upon this issue when a user belongs to two groups with same precedence.

However, from my current understanding of how those things work, I came the conclusion that the role assignment per group membership or per attribute is probably not the way to go for my use case.
What I'd like to achieve is the ability to dynamically generate a role for a user, which would contain  policies depending on what the user can do. For instance : RW access for project 'A' + RW access for project 'B' + Read only access for project 'C'.
Still I'm not sure what's the best pratice in such a case. To check rights and give/forbid access to the user in a Lambda authorizer of an API ? Or dynamically generate a single role per user and update it automatically in some lamda with triggers ? but In that how do I assign this role the cognito user ?
Could you point me to some resources/examples ?

I'm new to the aws ecosystem, so I might have missed something fundamental to make it work... If so, feel free to tell :)

thanks @undefobj

**Comment by undefobj** [comment]
Hi @barroij I understand now. Essentially you are looking for a Union of permissions. You are correct that per https://docs.aws.amazon.com/cognito/latest/developerguide/role-based-access-control.html#using-tokens-to-assign-roles-to-users in the case of multiple possible roles (which happens if precedence is equal) then your only option might be setting `CustomRoleArn` on the client which is not ideal per my comments above, and will end up working against you setting up these Fine Grained Access Controls on the backend.

Essentially what you are looking for is to have your Authorization metadata (meaning what users/groups can write to which items) stored somewhere so that a runtime check can take place and you can grant/deny reads or writes as appropriate. Our recommendation for the architecture in this scenario would be to look at one of two possibilities:

1. Use the GraphQL transformer with the `@auth` directive which has these use cases baked in: https://aws-amplify.github.io/docs/cli/graphql#auth

2. Use a REST endpoint with API Gateway and do the runtime authorization inside either a Lambda Authorizer or the service (perhaps using Lambda) that you are proxying into.

The first option is perhaps the most "out of the box" but it does require using GraphQL on the client. It uses AWS AppSync under the covers and here is a good video to learn more around these techniques: https://www.youtube.com/watch?v=2U4RsbFO4bA
The second is a standard REST client but more DIY approach. In both cases you would either have the authorization metadata on the item you're updating or in a separate place, like a DynamoDB table.

**Comment by barroij** [comment]
Thanks a lot for your answer @undefobj ! I'll have a look at grahQL and see which option is better.
