### ISSUE TITLE
how to include validation across two model attributes? (e.g. startDate < endDate)

### ISSUE THREAD

**Issue by callagga** [aws-amplify/amplify-js#2826]
Using AWS Amplify how does one update the schema.graphql model file so as to cause backend validation across multiple fields for the graphql API that is created.  

For example with the following schema.graphql file for amplify, how could I update this (or with the additional of other files in the project), so as to include a server side validation check on the graphql API it created such that:  

"startDate should be before endDate"

schema.graphql file:

```
    type Event @model {
      id: ID!
      name: String!
      startDate: AWSDate!
      endDate: AWSDate!
      plan: Plan! @connection(name: "PlanEvents")
    }
```

Aside - If this is not possible with amplify (note I'm using javascript amplify with react front end), any tips re what approach to take to implement would be appreciated (e.g. what backend AWS components would I have to look into and learn, and how this would integrate in with the automated graphql api that amplify is effectively automatically building already for me).

**Comment by elorzafe** [comment]
@callagga currently you need to edit your request mapping template on AppSync console (unfortunately if you change AppSync configuration on the Amplify cli that will overwrite this changes )

In order to edit the request mapping template you should go to **Schema** tab, then select createEvent mutation (on the resolvers section, right side of the console). Finally paste this on the request mapping template.

```
## [Start] Prepare DynamoDB PutItem Request. **
$util.qr($context.args.input.put("createdAt", $util.time.nowISO8601()))
$util.qr($context.args.input.put("updatedAt", $util.time.nowISO8601()))
$util.qr($context.args.input.put("__typename", "Event"))

## Initiate string variables with startDate, endDate with format compatible with parseFormattedTo... function
#set( $startDateString = $ctx.args.input.startDate + " 00:00:00+0000")
#set( $endDateString = $ctx.args.input.endDate + " 00:00:00+0000")

## Parse the string to a timestamp 
#set( $startDate = $util.time.parseFormattedToEpochMilliSeconds($startDateString, "yyyy-MM-dd HH:mm:ssZ"))
#set( $endDate = $util.time.parseFormattedToEpochMilliSeconds($endDateString, "yyyy-MM-dd HH:mm:ssZ"))

## Compare timestamps and return error when startDate is after endDate
#if ($startDate > $endDate)
  $util.error("Start date shoud be before end date")
#end

{
  "version": "2017-02-28",
  "operation": "PutItem",
  "key": {
      "id":     $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.args.input.id, $util.autoId()))
  },
  "attributeValues": $util.dynamodb.toMapValuesJson($context.args.input),
  "condition": {
      "expression": "attribute_not_exists(#id)",
      "expressionNames": {
          "#id": "id"
    }
  }
}
## [End] Prepare DynamoDB PutItem Request. **
```

**Comment by callagga** [comment]
thanks elorzafe - I've just started with AWS using amplify, but I'm wondering whether amplify (at the moment) is more something that could assist in simply AWS apps?  Would it be best to go back to understanding how to code graphql API interfaces (for react) with a dynamodb backend directly in the AWS consoles perhaps?   (before then using amplify)

Perhaps my question is given the constraint you mentioned "unfortunately if you change AppSync configuration on the Amplify cli that will overwrite this changes", how would you recommend to manage/test/deploy changes to code that makes up a graphql api backend?  Any pointers re where I should look/dig into?

**Comment by elorzafe** [comment]
@callagga with the latest version of the cli you can edit the resolvers inside of your `amplify` directory!

I've[ just tested and there is available documentation in order to do that. https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-resolver-that-targets-an-aws-lambda-function that is an example that uses lambda as a data source, but is the same pattern to change locally request mapping templates without going to the console.

On my app backend, I went to `amplify/backend/api/<my-api-name>/resolvers` directory and added a file called `Mutation.createEvent.req.vtl` where `createEvent` is the name of the mutation and `req` means for request mapping template (`res` will be for response mapping template). Just paste the same code there and save it, then do `amplify push` and your mapping template will get updated!

**Comment by callagga** [comment]
thanks for the pointer will look into this - does it do any validation/syntax checks on the code before it uploads by chance?
