### ISSUE TITLE
Amplify Core includes jmespath 80Kb

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#2894]
Inspecting the bundled JavaScript I see that the jmespath module is included which adds 80kb:

@aws-amplify/core@1.0.23
│ │ ├─┬ aws-sdk@2.329.0
│ │ │ ├── buffer@4.9.1 deduped
│ │ │ ├── events@1.1.1
│ │ │ ├── ieee754@1.1.8
│ │ │ ├── jmespath@0.15.0
│ │ │ ├── querystring@0.2.0 deduped
│ │ │ ├── sax@1.2.1
│ │ │ ├─┬ url@0.10.3

Inspecting the usage of jmespath and what the library provides, it seems overkill to use jmespath. I'd like to suggest replacing jmespath with a leaner solution. Also, I note that the AWS SDK is version 2.329.0 and the latest AWS SDK is 2.423.0.

**Comment by manueliglesias** [comment]
Hi @cliffordh 

thank you for using Amplify

`jmespath` is a dependency of the `aws-sdk` (which amplify uses to interact with aws services like Cognito, S3, Pinpoint, etc)

Regarding the version, we are pinning it to that specific one since it is proven to work with all Amplify features.

There are some other github issues regarding bundle size, it is under our radar and we're thinking about how to do better in that regard, e.g. #488 

I will be closing this issue, feel free to open a new one if you have more suggestions/feature requests
