### ISSUE TITLE
Changing user roles in Cognito does not get reflected until next session

### ISSUE THREAD

**Issue by aldo-roman** [aws-amplify/amplify-js#2987]
**Describe the bug**
After changing the user groups in Cognito, the method `Auth.currentAuthenticatedUser` still returns  the old groups.

**To Reproduce**
1. Register a user with group 'A'
2. Sign in on AWS Amplify app
3. Change user to group 'B'
4. Invoke `Auth.currentAuthenticatedUser`

**Expected behavior**
The returned object `signInUserSession.accessToken.payload['cognito:groups']` should have the newly updated group
OR
The session should terminate

**Screenshots**
<None>

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Comment by elorzafe** [comment]
@aldo-roman I can mark this as a feature-request rather than a bug, what you mention, it looks like a reasonable use case to support and we can add this to our backlog.

Thank you for your feedback!

**Comment by elorzafe** [comment]
@aldo-roman we have open this RFC https://github.com/aws-amplify/amplify-cli/issues/766 feel free to add any suggestion you like for auth.

**Comment by 10001oleg** [comment]
up

**Comment by nadetastic** [comment]
Hi all, wanted to follow up on this issue and provide a solution/work-around for this.

By default, `Auth.currentAuthenticatedUser()` will retrieve user information in the local cache that is set when the user initially signs in. Because of this, any changes made on the server/Cognito (ex adding to a group) after the user has signed in will not reflect.

However you can control this behavior by passing a parameter `bypassCache:true` which will force it to retrieve the latest user information.

You can read more about this in our documentation here - https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#retrieve-current-authenticated-user
