### ISSUE TITLE
amplify-authenticator angular adding rememberme

### ISSUE THREAD

**Issue by vjindalaurea** [aws-amplify/amplify-js#3010]
How can we add remember me option in amplify-authenticator of angular ?

**Comment by elorzafe** [comment]
@vjindalaurea remember me Is not available right now, I will mark this as a feature request.
Thanks for your feedback.

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

#3279

**Comment by saaniaki** [comment]
Any progress on this? Would you please give us any directions for alternatives? How can we implement it ourselves?
I have created an issue related to this one here:
https://github.com/aws-amplify/amplify-js/issues/3933

**Comment by integraitco** [comment]
This is key issue for us, any progress?

**Comment by KOSSOKO** [comment]
Is it possible to develop it just using api provided ?

**Comment by stefanomiccoli** [comment]
any update on this issue approaching its second birthday?

**Comment by cwomack** [comment]
@vjindalaurea (or anyone else following this issue), can you provide more context on what you'd expect the functionality to be for this feature request?  What would be the scope of items being "remembered"?

**Comment by cwomack** [comment]
After reviewing this feature request internally, we will be closing this issue down due to concerns over storing personally identifiable information (PII) for users if this feature was implemented.

For anyone following this issue, the Authenticator and other connected components are now managed within the [amplify-ui](https://github.com/aws-amplify/amplify-ui) repo (which is a change since this issue was originally opened).  Any new feature requests or issues tied to the connected components can be opened [here](https://github.com/aws-amplify/amplify-ui/issues).
