### ISSUE TITLE
AWS Amplify Console's app build setting page is completely broken, doesn't detect the environment

### ISSUE THREAD

**Issue by AbhishekRaval** [aws-amplify/amplify-js#3011]
**Describe the bug**
- So AWS Amplify console's app build settings is broken. I can get list of backend environment of only default selection branch. i.e. I had production branch which had production sandbox. But I was not able to see production env in build settings.
- By default my abc-demo branch was selected in "Select a branch" dropdown. To playaround I added production sandbox in abc-demo branch's team-provider-config.json and I was able to see production sandbox in dropdown. That's weird. 
- Probably the listener of Branch dropdown is broken, as backend environment list doesn't change while selection different branches. https://console.aws.amazon.com/amplify/home?region=us-east-1

**To Reproduce**
1. Go to  [AWS Amplify console](https://console.aws.amazon.com/amplify/home?region=us-east-1)
2. Click on connect app and select any repo with different environments on different branches. 
3. Scroll down to branch selection and try to select backend environment which is different from default selection of branch dropdown. 
4. See error that even though you have environment in team-provider-config, you won't be able to see your backend. But got to the branch that is default selection of branch dropdown and push new sandbox/sandbox from other branch to it. Now you'll be able to see the backend. 

**Expected behavior**
Expected behaviour was to fetch different backend environment for different branches. 

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.2
 - Browser chrome
 - Version 73

**Comment by swaminator** [comment]
Not quite sure I understand the issue. You have branches:
- branchA
- branchB

Backend envs:
- backend1
- backend2

Let's say when you connect the repo you connect branchA with backend1.
Then you goto connect branchB:
1. Is the issue you cannot select any backend?
2. Something else?

**Comment by AbhishekRaval** [comment]
The issue is basically:
1. When I select branch from "Branch Dropdown" I cannot see it's backend env. In your example the app config setting has "branchA" as default selection thus in my backend dropdown I can only see backend1. Now I select "branchB" from dropdown, still the backend environment dropdown doesn't update and it still keeps showing backend1. Whereas, it should have shown backend2.

**Comment by garyleefight** [comment]
@AbhishekRaval Thanks for reporting this bug. We appreciate your feedback. We will work on this issue.

**Comment by OtterFlip** [comment]
Our team ran into this issue on Friday, and it's still a bug today.  This issue is fundamentally breaking Amplify Console for multi-env backend development.  I'm surprised that it hasn't received more comments.

Steps to repro:

1) Create an empty repo in CodeCommit.  Add an empty file to the repo using CodeCommit's UI so that the "master" branch is created.
2) Clone the repo
3) Use create-react-app to create a simple hello world app in the root of the repo named "hello"
4) use "amplify init" and "amplify env add" to add prod, test and dev backends, following the instructions here:

https://docs.aws.amazon.com/amplify/latest/userguide/multi-environments.html

5) Now that the git code and the backends are all created, commit everything back to the remote git origin.
6) Go over to Amplify Console and attempt to deploy an app.  Amplify Console lets you pick the new "hello" repo, and it also lets you select a branch in the repo, but it does NOT let you specify the backend environment to associate with the git branch (that's all on Step 2 in Amplify Console).  On to Step 3, the build settings that Amplify Console generates are bad - it's missing the basic "npm run build" command and instead Amplify Console's build command is an empty array.  There is some disconnect there within Amplify Console.

**Comment by OtterFlip** [comment]
@garyleefight 

Update:  We also tested this with a repo on GitHub with the same results (same results as with CodeCommit).  It doesn't work.

Amplify Console is fundamentally broken.  It does not allow you to connect your git branch to the backend AWS resources you provisioned with the "amplify env add" command.

Try it out and tell me if I'm wrong.  Create a new empty repo, add a project to the root of the repo using create-react-app, and then use the amplify CLI to init the project and add backend environments to it as directed here:

https://docs.aws.amazon.com/amplify/latest/userguide/multi-environments.html

You will find that if your repo is stored on GitHub or CodeCommit, in either case the Amplify Console GUI doesn't give you any option (as is pictured in the instructions) to connect the backend environment to your git branch(es).

Can someone from AWS please confirm this?

**Comment by OtterFlip** [comment]
@garyleefight 

Aha!  We discovered that the project files such as project.json must be in the root of the repo itself.  They can't be in a subdirectory of the repo (such as in a project directory).  When the project files are in the root of the repo then the Amplify Console DOES indeed find them as well as present the option to connect a backend environment.

The documents are out-of-date and misleading.

[This document](https://docs.aws.amazon.com/amplify/latest/userguide/multi-environments.html) clearly shows the following sequence of commands.  Note how a project directory is created.  This will NOT work with Amplify Console.  Rather, Amplify Console expects all of the project files to be in the root of the Git repo itself.  This is unfortunate.  SUGGESTION TO AWS:  Ideally we could create some text file in the root of the repo which would point Amplify Console to the project directory to look in, which would enable us to have a more elaborate repo (such as a repo with two project sibling subdirectories, one for mobile and one for web).

You can see in the linked documentation, under the "Feature branch workflow" the following commands (which, again, will not work, because they place the project files in a subdirectory rather than the repo root):

create-react-app next-unicorn
cd next-unicorn
amplify init

[This document](https://aws-amplify.github.io/docs/cli/multienv) is also misleading because it too says, "From the root of your project, execute the following commands"... rather than from the root of the Repo...

**Comment by OtterFlip** [comment]
@garyleefight 

Additionally, the AWS documentation shows screenshots of connecting the backend in step 2 (the "Add repository branch" step).  The current Amplify Console interface actually shows the GUI elements to connect the backend during step 2 ("Configure Build Settings").

**Comment by cslogan-red** [comment]
For documentation's sake, the original bug behavior described here has been corrected and will be available globally by Tuesday, July 30th.
