### ISSUE TITLE
X-ray support

### ISSUE THREAD

**Issue by KowalskiP** [aws-amplify/amplify-js#3062]
**Which Category is your question related to?**
Request tracing

**What AWS Services are you utilizing?**
Amazon X-ray

Hello.
I wonder if there is the way to use X-ray request tracing feature on React-Native app? I didn't find a way yo utilize it like web app described here
https://docs.aws.amazon.com/en_us/xray/latest/devguide/scorekeep-client.html

**Comment by alebiavati** [comment]
Hi @KowalskiP, could you please specify what features of AWS Amplify you are using in your app? also, how exactly where you hoping to integrate AWS Amplify with AWS X-ray?

**Comment by KowalskiP** [comment]
Hi @alebiavati 
The app is using Auth and API features. 
Backend team want to trace requests from mobile app by this technology, because they already have setupped env for that.
The only way to do it from my side - generate X-Amzn-Trace-Id by myself. This way don't support segments.

**Comment by elorzafe** [comment]
@KowalskiP you can set a custom header for API, more info [here](https://aws-amplify.github.io/docs/js/api#custom-request-headers) 

```javascript
Amplify.configure({
  API: {
    endpoints: [
      {
        name: "sampleCloudApi",
        endpoint: "https://xyz.execute-api.us-east-1.amazonaws.com/Development",
        custom_header: async () => { 
          return { X-Amzn-Trace-Id :  ''} 
       
        }
      }
    ]
  }
});
```

We will review this feature, Thanks

**Comment by KowalskiP** [comment]
@elorzafe 
Thanks. Actually, I have described this way above =)
If amplify will have this feature, it would be great.

**Comment by undefobj** [comment]
@KowalskiP we have looked into this in the past but it's an avenue we haven't pursued due to two things:

1. Costs might end up being higher than expected if you are sending many requests from a high number of mobile/web clients
2. Security permissions aren't fine grained with X-Ray with mobile/web clients in mind is it was designed for service logging 

So if we could re-phrase the question: What exactly are you trying to accomplish when you say "tracing" in your apps? Are you looking to capture analytics data or something else? Perhaps we can accomplish your use case using the metrics and attribute tracking capabilities in Amplify's Analytics category which is designed for mobile and web apps?

**Comment by idclipr** [comment]
AppSync has [added support](https://docs.aws.amazon.com/appsync/latest/devguide/x-ray-tracing.html) for X-Ray on 2/7/2020 but it's still not clear if it's possible and how to start instrumentation on the client side which makes requests using Amplify's `API.graphql()`.
