### ISSUE TITLE
Types for aws-amplify-angular

### ISSUE THREAD

**Issue by achutkiran** [aws-amplify/amplify-js#3067]
** Which Category is your question related to? **
AWS Amplify

** What AWS Services are you utilizing? **
AWS Amplify

** Provide additional details e.g. code snippets **
I am using AmplifyService from aws-amplify-angular. Api docs  says for signIn() returns Promise<CognitoUser | any> but aws-amplify-angular returns Promise<any>. Is there any definitely typed package i can use for types in angular?

**Comment by haverchuck** [comment]
@achutkiran What version of AWS-amplify-angular are you using?

**Comment by achutkiran** [comment]
version 2.1.11

**Comment by cmckni3** [comment]
Since the return types in the [Amplify Service](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-angular/src/providers/amplify.service.ts#L62) are specified as `any`, I use a variable to specify the type.

Example:

```
const auth: AuthClass = this.amplifyService.auth();

// can autocomplete methods now in editor!
auth.signIn(username, password);
```

You could also use Type Assertion (`as AuthClass`) for quicker access. Type Assertion has disadvantages in certain cases in TypeScript (e.g. updating an object of a certain type).

```
(this.amplifyService.auth() as AuthClass).signIn(username, password);
```

I am running aws-amplify-angular 3.0.2

**Comment by achutkiran** [comment]
@cmckni3 Thanks. I am also started using like that. But it would nice if they are typed out of box instead of typecasting (Type assertion)

**Comment by cmckni3** [comment]
Agreed. Not sure why the return types are set to `any`.
