### ISSUE TITLE
Convert an anonymous account to a permanent account

### ISSUE THREAD

**Issue by ovandr** [aws-amplify/amplify-js#3073]
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
Hello! I have implemented unauthorized access to API Gateway. When an unauthorized user signs up to my app, I want to allow them to continue their work with their new account — for example, I want to make the items the user added to their shopping cart (items in DynamoDB) before they signed up available in their new account's shopping cart.

How can I achieve this? Thanks for help!

I use AmplifyJS. To get unauthorized credentials I use Auth.currentCredentials() method

**Comment by powerful23** [comment]
@ovandr related to #1931 

Although it's related to identity merging, we would recommend you to store the items into the cookie when you are unauthenticated and after you sign in, get the cached items from cookie. Or you can cache the unauth id and use that to get the items from S3 after signing in.

I will mark this as feature request as we need to look into this identity merging feature more and clarify the user cases for it.

And I am going to close it because it's a duplicated one. Please let us know if you have further concern.
