### ISSUE TITLE
AWSPinpointProvider updateEndpoint failed

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-js#3101]
**Describe the bug**
When enabling the Analytics category and using `mandatorySignIn: true`, AWSPinpointProvider fails to validate because it expects the claims in the User.UserAttributes property to be arrays. I think this is a bug; there should only be one cognito sub per user, as well as one cognito username.

Pinpoint claims to be successfully configured after the fact, but it still throws this error.

**To Reproduce**
1. Configure Analytics
2. Enable window.LOG_LEVEL = "DEBUG"
3. Observe that a call to "updateEndpoint failed", see screenshot for stack trace

**Expected behavior**
Pinpoint authenticates with the current session without failure.

**Screenshots**
![image](https://user-images.githubusercontent.com/22964702/56146096-d8c91000-5f62-11e9-9fe9-0529b8589f32.png)

![image](https://user-images.githubusercontent.com/22964702/56146155-f5654800-5f62-11e9-8a99-95ec7eb5802b.png)

**Desktop (please complete the following information):**
`$ amplify -v`
1.6.1

**Comment by powerful23** [comment]
@jkeys-ecg-nmsu the validation logic is defined by the Pinpoint service team so we can't change it in the Amplify library. Could you send your feedback to the service team directly through the AWS forum? https://aws.amazon.com/premiumsupport/knowledge-center/send-feedback-aws/

Also I think you should put the `userCognitoSub` into the `userId` instead of the `userAttributes` since it's an unique id per user.
