### ISSUE TITLE
Batch GraphQL Queries

### ISSUE THREAD

**Issue by EgidioCaprino** [aws-amplify/amplify-js#3107]
** Which Category is your question related to? **
GraphQL API

** What AWS Services are you utilizing? **
Cognito and AppSync

** Provide additional details e.g. code snippets **
The Apollo client provides a `shouldBatch` option to batch query operations so that multiple queries will be sent in a single network roundtrip. Is there a way to set Amplify in order to use the same functionality?

**Comment by AndrewMorsillo** [comment]
There is a batchinvoke function for lambda resolvers, I'm not sure about others

https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-lambda-resolvers.html

Unfortunately it looks like it is severely limited. There is an undocumented limitation that it will only invoke batches of 5 so it doesn't really do much to help in a lot of situations. Unfortunately that doesn't looks like it is going to change either, it has been 15 months since AWS said they are looking into it but the thread has gone dead with no responses about it. 

https://forums.aws.amazon.com/thread.jspa?threadID=270548&tstart=0

**Comment by EgidioCaprino** [comment]
@AndrewMorsillo thank you for your answer. Just to be sure, I'm talking about a client-side feature that will fire subsequent GraphQL queries in a single network request.

**Comment by undefobj** [comment]
@EgidioCaprino query batching is a feature that AppSync doesn't support at this time as it is not part of the GraphQL specification. I would suggest opening a feature request in the AppSync forum or on the community page to gauge interest from the larger ecosystem: https://github.com/aws/aws-appsync-community

**Comment by janhesters** [comment]
@EgidioCaprino If you'd like to know how to batch create or delete up to 25 items simultaneously check out [this tutorial that I wrote](https://geromekevin.com/creating-graphql-batch-operations-for-aws-amplify/). I hope it might help you.
