### ISSUE TITLE
Create cognito user

### ISSUE THREAD

**Issue by marcschroeter** [aws-amplify/amplify-js#3123]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
We have user in two different groups: Admin / User. We want to allow admin users to create cognito user. How can we do this exactly?

**Comment by haverchuck** [comment]
This functionality is available in the Cognito Console, but not currently available via Amplify.  However, we have an RFC out right now in which we are detailing some improvement we'd like to make - and this request seems to fit in.  Please feel free to weigh in on this RFC:   https://github.com/aws-amplify/amplify-cli/issues/766

**Comment by marcschroeter** [comment]
Unfortunately we cannot wait until this feature will be developed. How cloud be an alternative way to create cognito users through our React WebApp?

Could we use the Amazon Cognito SDK for JavaScript instead of Amplify JS SDK to create Cognito users for a userprool which was created by Amplify CLI  @haverchuck 

https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-javascript-examples.html

**Comment by undefobj** [comment]
@marcschroeter you can alternatively grant AWS IAM permissions to the Cognito Identity Pool Role policy that your clients are granted after authenticating. Note that this will open up a larger surface area from a security perspective and therefore associated risks, so we do not recommend this as a good practice.

**Comment by saqibameen** [comment]
@haverchuck @undefobj is there any update on this feature request? @marcschroeter how did you implement this feature? I'm looking forward to doing the same. 

Is there a way we can use AWS Amplify' `Sign Up` and `Complete new password` methods to achieve the same thing? The issue here is, sign up will set an actual password instead of a temporary one, and I'll never be able to get `NEW_PASSWORD_REQUIRED` challenge in the response. 

So, probably I will have to go for `aws-sdk` (JS) achieve the same thing. I want to use the `aws-sdk` for just adding the user. Then, I would like to use the `Complete new password` method by AWS Amplify to actually set the **password** and **required attributes**. So, any thoughts on how can I do the first task using AWS SKD (JS)?

**Comment by undefobj** [comment]
We have just released new functionality referenced in the RFC above which will allow you to accomplish this task. Please take a read here:

https://aws-amplify.github.io/docs/cli-toolchain/quickstart#group-management
https://aws-amplify.github.io/docs/cli-toolchain/quickstart#group-access-controls
https://aws-amplify.github.io/docs/cli-toolchain/quickstart#administrative-actions

For the OP @marcschroeter to create a user you would need to modify the underlying Lambda function which is created by the Admin Queries API. The code is fairly boilerplate so it should be mostly copy/paste.

**Comment by sammartinez** [comment]
Resolving as per the comment above. This is now implemented via [Cognito Lambda triggers.](https://aws-amplify.github.io/docs/cli-toolchain/cognito-triggers)

**Comment by julescsv** [comment]
> We have just released new functionality referenced in the RFC above which will allow you to accomplish this task. Please take a read here:
> 
> https://aws-amplify.github.io/docs/cli-toolchain/quickstart#group-management
> https://aws-amplify.github.io/docs/cli-toolchain/quickstart#group-access-controls
> https://aws-amplify.github.io/docs/cli-toolchain/quickstart#administrative-actions
> 
> For the OP @marcschroeter to create a user you would need to modify the underlying Lambda function which is created by the Admin Queries API. The code is fairly boilerplate so it should be mostly copy/paste.

Why don't we have an endpoint for "createUser" and "deleteUser"?  I went ahead and created both endpoint and updated the policy accordingly. The problem arises when I run `amplify update auth` ... my custom code is overridden and I have to do it all over again.

**Comment by SaucyJack** [comment]
This is a critical feature for us as well and we need it available to our Node back-end, _not_ in the CLI. Is there any timeline on this? The PHP SDK has this functionality built in.

**Comment by undefobj** [comment]
@SaucyJack the AWS NodeJS SDK already supports this. That's a separate project from Amplify which is designed for mobile and web apps. The CLI functionality outlined above uses the NodeJS SDK in a Lambda function.

**Comment by pabloVoorvaart** [comment]
Wouldnt it be usefull that the create/delete endpoints are created by default?
I think create/delete are critical actions regarding user administration.
I would be more than happy to code this implementation and create a pr.

**Comment by undefobj** [comment]
@pabloVoorvaart no there are extra associated costs for those endpoints. It's a simple command to run and spin it up if needed: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#administrative-actions

**Comment by pabloVoorvaart** [comment]
Sorry for the misunderstanding, I meant by default when spinning up the administrative-actions api.

**Comment by shaleenmundra** [comment]
I was at the same problem. 
I used Amplify for authenticating users. Now there was the use case to give authenticated user to create/add new user to cognito user pool. I am only using cognito and not any 3rd party identity provider.
We don't need signUp since we don't want to give every user the ability to add themselves, just some admins who are added to admin group in user pool.
Eventually these admins will be added by developer or owner of the AWS account. (giving them IAM user is a security concern since it mean exposing all of cognito to the user.)

If I understand correctly, you are also looking for an api corresponding to **adminCreateUser** from **aws-sdk** to accomplish this task. 
I searched a lot and result is : **there isn't any.**

I tried with two methods
  1. Creating Lambda and invoking using api gateway.
  2. Using aws-sdk in my package for implementing create-user function.

  - If I create a `lambda function`, I'll have to create an api trigger and give it permissions to invoke adminCreateUser on the user pool and assign correct IAM role to invoke that. The only problem I had with this is how to provide the event containing user and user pool data to perform the required operation. 

  - Using `aws-sdk`, we need to setup the AWS config in order to call any api.
    - Required parameter for configuring the AWS config are: 
      1. region : AWS region (in my case it is same region in cognito user pool)
      2. identity pool id
      3. RoleArn : arn for IAM role assumed by the authenticated users in identity pool
      4. idToken : returned by cognito after successful authentication.

You will know region and identity pool id.
 For Role arn, go to IAM roles and select the role which is given to authenticated users in identity pool.
 
  - For that : Go to identity pool, click on _edit identity pool_ and check the role for authenticated users.
Now go to IAM role and click on the role you saw in your identity pool. You will find the role arn in the details.

For idToken, you can use amplify api here. 
```
Auth.currentAuthenticatedUser().then(user => {
    idToken = user.signInUserSession.idToken.getJwtToken();
})
```

**Note :** 
  1. your IAM role should have permission to call adminCreateUser. If not, then you will have to edit its inline policy and add the required action in it.
 ```"Action": ["cognito-idp:AdminCreateUser", ...] ```


  2. You might also need to edit its trust relationship if it does not already contains your identity pool id to establish the relationship.
```
"Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "cognito-identity.amazonaws.com:aud": "<IdentityPoolId>"
        },
        "ForAnyValue:StringLike": {
          "cognito-identity.amazonaws.com:amr": "authenticated"
        }
``` 


- After this you should be ready to call `adminCreateUser` api programmatically from your app.

**My createUser function**

```
const updateConfigAndCreateUser = () => {
    AWS.config.region = CONFIG.REGION;
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: CONFIG.IDENTITY_POOL_ID,
      RoleArn:
        CONFIG.IAM_ROLE_ARN,
      Logins: {
        'cognito-idp.<region>.amazonaws.com/<UserPoolId>': idToken
      }
    });

    let cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider();
    let params = {
      UserPoolId: CONFIG.USER_POOL_ID,
      Username: 'username',
      UserAttributes: [
        {
          Name: 'email',
          Value: <email>
        },
        {
          Name: 'email_verified',
          Value: 'true'
        },
        {
          Name: 'custom:admin', // custom attribute
          Value: 'true'
        }
      ]
    };

    cognitoidentityserviceprovider.adminCreateUser(params, function(
      err: any,
      result: any
    ) {
      if (err) {
        console.log(err);
        return;
      }
      if (result) {
        console.log(result);
        return;
      }
    });
  };
```

When calling the api in browser if there is a problem, then go to network tab
  1. Problem from `https://cognito-idp.eu-west-1.amazonaws.com` has something to do with IAM role, its inline policy or its trust policy.
  2. Problem from `sts.amazon.com` has something to do with idToken, IAM role trust policy.

This might not cover all the cases for everyone, but I hope it helps someone stuck at same errors and finding hard to pin point the problem

**Comment by IsaacTrevino** [comment]
> We have just released new functionality referenced in the RFC above which will allow you to accomplish this task. Please take a read here:
> 
> https://aws-amplify.github.io/docs/cli-toolchain/quickstart#group-management
> https://aws-amplify.github.io/docs/cli-toolchain/quickstart#group-access-controls
> https://aws-amplify.github.io/docs/cli-toolchain/quickstart#administrative-actions
> 
> For the OP @marcschroeter to create a user you would need to modify the underlying Lambda function which is created by the Admin Queries API. The code is fairly boilerplate so it should be mostly copy/paste.

I followed this approach, by editing the `cognitoActions.js` and adding `adminCreateUser`. Though I will need to follow @shaleenmundra approach for the identity pool for customers.

**Comment by SwagMuffinMcYoloPants** [comment]
@IsaacTrevino , did you have the same problem as @julescsv or did you make a brand new function and not append to the existing admin queries api?

**Comment by IsaacTrevino** [comment]
> @IsaacTrevino , did you have the same problem as @julescsv or did you make a brand new function and not append to the existing admin queries api?

@julescsv applies to my situation as well.

I was able to append to AdminQuery src files generated by amplify cli.  So I am now able to Create, Update, and Delete Users
by **adding** my own function to `app.js`, & `cognitoActions.js` **only**.

But I believe to @shaleenmundra issue was to switch between `USER POOLS` is why he mentions to update `AWS.config`, where as I have both Employee and Customer Logins. However my current progress focuses only on Employees, since that is what I created with `amplify add auth`.

**Comment by GeorgeBellTMH** [comment]
It would be great if someone could add the code for adminCreateUser to admin queries by default, inviting users from the UI is a common use-case.

**Comment by bmilesp** [comment]
Piggy-backing off of @GeorgeBellTMH , a `@cognitoModel` directive that can use @auth directives would be the crème de la crème:

```
type Users
  @cognitoModel
  @auth(
    rules: [
      { allow: owner, operations: [create, update, delete, read] },
    ])
{
  id: ID!
  username: String!
  custom: String
}
```

This directive could auto-apply the necessary Lambda functions that connect directly to Cognito through Appsync.

**Comment by cnbrkkaya** [comment]
> It would be great if someone could add the code for adminCreateUser to admin queries by default, inviting users from the UI is a common use-case.

Is there any progress in this subject? Or do we have to write our own createUser functions?

**Comment by madhurisandbhor** [comment]
I followed @shaleenmundra's 2nd solution, creating user with aws-sdk, with few additions I got it working.
`
      let params = {
        UserPoolId: "us-west-XXX",
        Username: <email/username>,
        TemporaryPassword: <password>,
        UserAttributes: [
          {
            Name: 'email',
            Value: <email>,
          },
          {
            Name: 'email_verified',
            Value: 'true'
          },
        ]
      };
      
      const user = await Auth.currentAuthenticatedUser() // get user authentication
      const idToken = user.signInUserSession.idToken.getJwtToken();  // get session token

      AWS.config.region = 'us-west-2'
      AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: "us-west-2:XXX",  // create identity pool with authentication provider as Cognito, also assign two roles generated while creating Identity pool for the first time to "Unauthenticated role & Authenticated role" respectively.
        RoleArn: "arn:aws:iam::<account-number>:role/Cognito_mantix_Identity_poolAuth_Role",
          //ROLE_ARN : arn for IAM role assumed by the authenticated users in identity pool,
          // role should have cognito-idp full access to create new user
        Logins: {
          'cognito-idp.us-west-2.amazonaws.com/<UserPoolId>': idToken
        }
      });

      let cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider()
      cognitoidentityserviceprovider.adminCreateUser(params, function (
        err: any,
        result: any
      ) {
        if (err) {
          console.log(err)
        }
        if (result) {
          console.log(result) // user object
        }
      })
      `
