### ISSUE TITLE
Optional attributes cannot be empty during sign-up in Vue

### ISSUE THREAD

**Issue by borisdayma** [aws-amplify/amplify-js#3174]
**Describe the bug**
When using the SignUp component in Vue and leaving optional parameters with a blank value, an error is raised.

**To Reproduce**
1. Use `<amplify-sign-up>` component
2. Add in the `signUpConfig` the following:
```
{
  label: this.$Amplify.I18n.get('Middle Name'),
  key: 'middle_name',
  required: false,
  type: 'string',
  displayOrder: 10
}
```
3. Leave the value empty and sign-up
4. See error **Attribute value for middle_name must not be null**

**Expected behavior**
Since the parameter is optional, no error should be raised

**Additional context**
The validation on the component seems to be working properly and no error is raised, Error seems to come from the cognito server.

I believe it would be solved by not adding elements in `user.attributes` that are empty (the fact that they are optional is already taken care of by the `validate` part of the form.

**Comment by manueliglesias** [comment]
Hi @borisdayma 

When the network request is made to Cognito, is the optional attribute sent? What's its value?

According to the [Cognito docs for attributes](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AttributeType.html), the value part is not required. I am thinking that maybe the request is being sent with e.g. `""` instead of no `value` at all.

If that's the issue, then this will need to be fixed at the library level (`@aws-amplify/auth`) instead of at the UI level. (in fact, you pointed out that the UI piece seems correct)

https://github.com/aws-amplify/amplify-js/blob/47c7cfdd6308b14a1f7673e339680021c2a8764f/packages/auth/src/Auth.ts#L252-L257

**Comment by borisdayma** [comment]
I think the issue is on that same section.
`ele` needs to be pushed to `attributes` only if `Value` is non empty.

As you pointed out, it is not required but `""` is being sent, which for some reason is not accepted.
Maybe another alternative would be for `ele` not to contain `Value`. But in this case there may be no point in providing this specific attribute.

**Comment by manueliglesias** [comment]
@borisdayma  would you be interested in sending a contribution to this repo?
