### ISSUE TITLE
Social Login (Facebook) through user pool, hosted, ui, invalid_grant error. 

### ISSUE THREAD

**Issue by calboru** [aws-amplify/amplify-js#3185]
Followings are my settings. When I try to test social login I always  get invalid_grant error. 

WHEN I INVOKE: 
  federatedSignIn() {
    const provider: FederatedSignInOptionsCustom = { customProvider: 'Facebook' };
    return from(this.auth.federatedSignIn(provider));
  }

OR TEST URL: https://xxxx.auth.us-east-2.amazoncognito.com/login?response_type=code&client_id=xxxx&redirect_uri=https://localhost:4200

Error happens after PKCE event:  https://localhost:4200/?code=16c65151-7f92-4611-99c3-d872a44cacb6

MY SETTINGS AS FOLLOW:
const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_XXX',
  aws_user_pools_web_client_id: 'XXXXX',
  Auth: {
    oauth: {
      domain: 'XXX.auth.us-east-2.amazoncognito.com',
      redirectSignIn: 'https://localhost:4200',
      redirectSignOut: 'https://localhost:4200',
      mandatorySignIn: true,
      scope: ['public_profile', 'openid', 'email', 'first_name', 'last_name'],
      responseType: 'code'
    }
  }
};
![image](https://user-images.githubusercontent.com/26364385/56869722-0fc30b00-69d2-11e9-90fc-9abff592e19d.png)

![image](https://user-images.githubusercontent.com/26364385/56869618-9ecf2380-69d0-11e9-9bbe-dacd41746e73.png)

![image](https://user-images.githubusercontent.com/26364385/56869630-c0c8a600-69d0-11e9-8676-5cb9bda2f460.png)

**Comment by manueliglesias** [comment]
Hi @calboru 

`invalid_grant` could mean that:
- Refresh token has been revoked.
- Authorization code has been consumed already or does not exist.

(According to [TOKEN Endpoint docs](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html))

Do you see duplicate/multiple calls to the token endpoint in the network inspector?

**Comment by calboru** [comment]
> Hi @calboru
> 
> `invalid_grant` could mean that:
> 
> * Refresh token has been revoked.
> * Authorization code has been consumed already or does not exist.
> 
> (According to [TOKEN Endpoint docs](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html))
> 
> Do you see duplicate/multiple calls to the token endpoint in the network inspector?

Hi Manuel,
Yes I saw two calls even though I call it once. Is it an amplify bug?

**Comment by nandoise** [comment]
It seems you are calling two times, may be in you code.

you set at begining the imports , right?

import Amplify, { Auth } from 'aws-amplify';
import amplify from './aws-exports';

then you set:

Amplify.configure(amplify); //somthing like that

this is all..
but in some tutorials give an extra step

ej. 
 oauth = {
  domain: 'cartoapp-dev.auth.us-east-1.amazoncognito.com',
  scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
  redirectSignIn: 'http://localhost:4200',
  redirectSignOut: 'http://localhost:4200',
  responseType: 'code',
  options: {
    AdvancedSecurityDataCollectionFlag : false
  }
};

Auth.configure({ 
  oauth:oauth
 })
this is not necesary because your "import amplify from './aws-exports';" has the  parameters, 
chek you development tool f12 if you has somthing like this [img]
![err](https://user-images.githubusercontent.com/1266719/57802509-bb32c600-771b-11e9-8d64-c23088135d78.jpg)

**Comment by jordanranz** [comment]
@nandoise, I too ran into this issue. Removing the manual config from the documentation example fixed the 'invalid_grant' error.

**Comment by MTajuddin96** [comment]
Write Amplify.configure(awsConfig) after your initial component mounted. This actually solved my issue.
