### ISSUE TITLE
Vue amplify-authenticator messed up layout on hiding phone_number

### ISSUE THREAD

**Issue by rahulserver** [aws-amplify/amplify-js#3251]
On hiding the phone_number signup field using `hiddenDefaults` like below code, the signup form looks a bit off as in screenshot attached.

```
        <amplify-authenticator v-bind:authConfig="authConfig"></amplify-authenticator>

       // ....
          data: function () {
      return {
        authConfig: {
          signUpConfig: {
            header: "Custom header",
            hiddenDefaults: ['phone_number']
          }
        }
      }
```

The form looks like this now:

![image](https://user-images.githubusercontent.com/5101740/57478352-4e04d800-72b8-11e9-878d-71c6ac31ef50.png)

There is no space between Log in link and Create Account button.
In no way can I use this in production if I have to remove the telephone number.

So is there a way I can fix this myself?

**Comment by powerful23** [comment]
@rahulserver Hi which version of aws-amplify-vue are you using? Can you try the latest one?

**Comment by rahulserver** [comment]
@powerful23 I was on version 0.2.5. Updated to latest 0.2.10 and still get the same issue.

**Comment by sammartinez** [comment]
@rahulserver Since this is a little bit old and there are newer versions of `aws-amplify-vue` can you upgrade to the latest version and see if you are experiencing the same issue. Also, please remove the `node_modules` and the lock file (e.g. `package-lock.json or `yarn.lock`) prior to installing the latest version
