### ISSUE TITLE
what auth states are supported and what is their meaning ?

### ISSUE THREAD

**Issue by dd-ssc** [aws-amplify/amplify-js#3262]
**Which Category is your question related to?**
Documentation

**What AWS Services are you utilizing?**
AWS Amplify for React Native with AWS Cognito backend

**Provide additional details e.g. code snippets**
According to the [documentation](https://aws-amplify.github.io/docs/js/authentication#show-your-app-after-sign-in), _authState is the current authentication state (a string)_:

```
- confirmSignIn
- confirmSignUp
- forgotPassword
- signedIn
- signIn
- signUp
- verifyContact
```

(I've sorted the list alphabetically for easier comparison with below.)

However, when I grep for e.g. `_validAuthStates` in `node_modules/aws-amplify-react-native/dist`, I find these auth states (also sorted alphabetically):

```
- confirmSignIn
- confirmSignUp
- forgotPassword
- loading
- requireNewPassword
- signedOut
- signedUp
- signIn
- signUp
- verifyContact
```

Is there any official documentation on what auth states are supported and what they mean exactly, i.e. in what situation they are assumed ?

**Comment by sammartinez** [comment]
@dd-ssc, 

Currently the documentation is out of date with loading / requireNewPassword being added recently, however these auth states are used in order to justify which component to show on initial load of the Authenticator. Here is a link to the documentation for [Using the Authenticator Component](https://aws-amplify.github.io/docs/js/authentication#using-the-authenticator-component). 

Also, if you have your own custom component for SignIn or SignUp and inject it into the Authenticator you use authState in order to update the component base on the state. Here is a guide to [Create your own UI ](https://aws-amplify.github.io/docs/js/authentication#create-your-own-ui)

**Comment by haverchuck** [comment]
Closing this issue as an answer has been provided and due to inactivity.  If problems persist, please feel free to open new issue with additional detail.
