### ISSUE TITLE
using window.sessionStorage as auth storage broken

### ISSUE THREAD

**Issue by blathers16** [aws-amplify/amplify-js#3284]
**Describe the bug**

if you create a angular project using aws-amplify-angular for cognito authentication, and you try to set the storage to window.sessionStorage, you get an error "The storage in the auth config cannot be empty!"

**To Reproduce**

1. take a working angular project using aws-amplify-angular for cognito oauth singin.
2. in the auth config, add:
storage: window.sessionStorage,
3. get error

**Expected behavior**

the amplify framework should sessionStorage for storing tokens instead of localStorage

**Screenshots**
![Screenshot (285)](https://user-images.githubusercontent.com/2584455/57800578-98e27d80-7706-11e9-85c5-f7582d3d1860.png)
![Screenshot (287)](https://user-images.githubusercontent.com/2584455/57800604-a0a22200-7706-11e9-972b-18c7989efe69.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Lubuntu 18.04 LTS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 74

**Additional context**

I believe this is a side effect of https://github.com/aws-amplify/amplify-js/pull/3026

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by Siveran** [comment]
The bug is definitely being caused by #3026, and can affect things outside of Angular. The isEmpty() check before throwing "The storage in the Auth config can not be empty!" and "Empty storage object" only checks to make sure the storage object has zero enumerable keys. If you provide a custom storage object, its implementation may make it appear to be empty. window.sessionStorage has this problem (`Object.keys(window.sessionStorage)` returns `[]` when fresh) and a function-only class would have the same problem.

You can work around this by adding a useless property to your storage object. If your config has:
```
{
  ...
  Auth: {
    ...
    storage: new CustomStorage()
  }
}
```
You can throw a useless property on it:
```
var customStorage = new CustomStorage();
customStorage.workaround = null;

{
  ...
  Auth: {
    ...
    storage: customStorage
  }
}
```
No more error!

To fix this on Amplify's end, the new isEmpty() check should probably be removed for normal storage. Basically, revert the Auth.ts part of #3026.
