### ISSUE TITLE
Directly call Lambda, no API Gateway

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#3288]
** What AWS Services are you utilizing? **
AWS Lambda

** Provide additional details e.g. code snippets **
I would like to avoid the overhead of using API Gateway and invoke a Lambda directly. I have been able to do this using just the aws-sdk but I would like to do the same using Amplify. Is it possible to invoke a Lambda directly without using API Gateway?

Thanks.

**Comment by undefobj** [comment]
Yes Amplify provides an escape hatch where you can directly call any service using a passthrough with the Auth module as outlined in the bottom of this section: https://aws-amplify.github.io/docs/js/start#step-5-launch-your-app

```
import Route53 from 'aws-sdk/clients/route53';

...

Auth.currentCredentials()
  .then(credentials => {
    const route53 = new Route53({
      apiVersion: '2013-04-01',
      credentials: Auth.essentialCredentials(credentials)
    });

    // more code working with route53 object
    // route53.changeResourceRecordSets();
  })
```

Instead of Route53 substitute in the appropriate Lambda imports and invocation method.

**Comment by cliffordh** [comment]
Thanks. I think I got it figured out.

**Comment by wtrevena** [comment]
> Thanks. I think I got it figured out.

@cliffordh 
I am glad to see that someone else recognized this same opportunity! If you have a second could you please share the workaround that you found? Thanks!
