### ISSUE TITLE
Federated Credentials not stored after calling federatedSignIn

### ISSUE THREAD

**Issue by Dellybro** [aws-amplify/amplify-js#3296]
**Describe the bug**

After calling `Auth.federatedSignIn( domain, {token, expires_at} user )` credentials are not stored immediately in the cache thus unable to make AppSync graphQL requests upon signing in.

The error when calling graphQL after signing in is the following: Error: No federated jwt

**To Reproduce**

```
Auth.federatedSignIn(domain, {token, expires_at} user)
.then(response => {
   return Auth.currentAuthenticatedUser
})
.then(user => {
    return API.graphql(graphqlOperation(query))
})
.then(response => {
    // Block never executed because graphql thinks federated JWT does not exist at this point
})
.catch(error => {
    console.log(error)
    // Prints Error: No federated jwt
})

```

**Expected behavior**

Graphql should already have the JWT present after calling federatedSignIn

**Smartphone (please complete the following information):**

ReactNative iOS

**Comment by Dellybro** [comment]
Any news on this issue ?

**Comment by scaralfred** [comment]
Any news on this?
I came across this today. When I logIn with a federated identity (federated.signIn method), I'm unable to use graphQl (like the graphqlOperation method) as it throws the following error:
"No current user"
With a normal signIn in (via email), everything works fine.

**Comment by elorzafe** [comment]
The root cause of this issue is because `Cache.setItem` is async on react-native and is not been awaited.
https://github.com/aws-amplify/amplify-js/blob/97cfb916ec9101e024ca42f62d9bffd4dd6805b7/packages/core/src/Credentials.ts#L301

`AsyncStorageCache` is `async`
https://github.com/aws-amplify/amplify-js/blob/97cfb916ec9101e024ca42f62d9bffd4dd6805b7/packages/cache/src/AsyncStorageCache.ts#L244
