### ISSUE TITLE
validationData prop for SignIn and SignUp react components

### ISSUE THREAD

**Issue by hupe1980** [aws-amplify/amplify-js#3323]
**Is your feature request related to a problem? Please describe.**
We need the possibility to provide data that we can check in the PreAuthentication Lambda trigger

**Describe the solution you'd like**
```jsx
<Authenticator>
    <SignIn validationData={validationData} />
    <SignUp validationData={validationData} />
</Authenticator>  
```

**Describe alternatives you've considered**
We tested it with our own components. But we would rather use the standard components

**Comment by tannerabread** [comment]
There have been many updates to the React Authenticator since this issue was opened and I believe you could handle this with [overriding function calls](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#override-function-calls).

If this does not solve your issue, please let me know so I can reopen this issue and pass it to the [UI repo](https://github.com/aws-amplify/amplify-ui)

Thank you!
