### ISSUE TITLE
aws-amplify-react  Connect mutation does not handle errors in graphQL operation correctly.

### ISSUE THREAD

**Issue by gmisa** [aws-amplify/amplify-js#3369]
### Describe the bug
**A clear and concise description of what the bug is.**

This is related to a closed bug which was for aws-amplify-vue. [https://github.com/aws-amplify/amplify-js/issues/2568](url)  This bug however is present in aws-amplify-react.

The bug is in the block constrained by the if statement "if (hasValidMutation) on line 73 of packages/aws-amplify-react/src/API/GraphQL/Connect.js. There is no error handling and any error is essentially swallowed by the code and only emitted to console, making it invisible to the component. Instead, there should be error handling that pushes the error into the errors list, as it does in the block above (if (hasValidQuery)).

     if (hasValidQuery) {
            try {
                data = null;

                const response = await API.graphql({ query, variables });

                data = response.data;
            } catch (err) {
                data = err.data;
                errors = err.errors;
            }
        }

        if (hasValidMutation) {
            mutationProp = async (variables) => {

               /* Needs a try/catch block here
                const result = await API.graphql({ query: mutation, variables });

                this.forceUpdate();
                return result;
            };
        }

**To Reproduce**
Create a form that uses a mutation against a DynamoDB database using GraphQL. Make a field required, but omit it the value in the submitted form or put an invalid (to Dynamo) value in the form and submit the form. The form will not complete processing and an error is displayed in the console.

**Expected behavior**
The error to be pushed to errors so I could handle it in the form code.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.

**Comment by wlee221** [comment]
Hello, 

Thanks for bringing this to our attention. Try catch block needs to be added in the client app (and not in the source code) because onCreate function is passed as a prop from the client app. 

We updated the documentation to reflect this: [link](https://github.com/aws-amplify/docs/pull/707).

**Comment by gmisa** [comment]
Hi @wlee221, I added try catch in the client app but the error is thrown in the source code and goes straight to the console.  The app is unable to catch the error.

**Comment by matwerber1** [comment]
Hi, running into a similar issue. In my case, I am using AWS_IAM auth type with the <Connect/> component. I log the results as the query attempt happens, and this is what I see: 

```
{ data: undefined, loading: true, errors: undefined }
{ data: undefined, loading: true, errors: undefined }
{ data: null, loading: false, errors: undefined }
```

The messages above suggested that the connection to AppSync was working fine since status went from `loading: true` to `loading:false`, and data went from `undefined` to `null`. Since `errors: undefined` never changed, suggesting no errors occurred. However, my simple query was failing to return results even though it worked fine in the AWS AppSync console. 

I later tested the same code in an AWS Lambda function, and this time received a more detailed error that DynamoDB permissions were missing from my user... I mistakenly thought that `appsync:*` was sufficient for my Cognito auth role. Anyway, I added `dynamodb:*` (overly permissive, I know) to my Cognito Auth role and _boom_, my <Connect/> app started returning results within the `data` key. 

I would thing that the `errors:` key should have shown me a permissions problem in my query.

**Comment by harrysolovay** [comment]
Are you utilizing [the render-props version](https://docs.amplify.aws/ui-legacy/api/connect/q/framework/react) of the connect component? If so, please confirm that the error is not propagated into `errors` (passed into the closure of `Connect`).
