### ISSUE TITLE
On Edge TypeError: Failed to execute 'fetch()' on 'Window': Invalid argument with Hosted UI

### ISSUE THREAD

**Issue by JohanRin** [aws-amplify/amplify-js#3397]
**Describe the bug**
In Edge, when I use the Hosted UI I have the following error:
"Uncaught (in promise): TypeError: Failed to execute 'fetch()' on 'Window': Invalid argument.

**To Reproduce**
1. Install and configure the Hosted UI
2. Click on Hosted UI button
3. See error

**Expected behavior**
No error on Edge after using Hosted UI.

**Screenshots**
![Failed to execute fetch](https://user-images.githubusercontent.com/13972080/58902003-96ba8000-8702-11e9-96d2-09d243b304c1.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The problem occurs only on Edge. I have no problem on Chrome, Safari or even IE11.

**Sample code**
```
export class AppComponent implements OnInit {

  ngOnInit() {
    Hub.listen('auth', (data) => {
      const { payload } = data;
      this.onAuthEvent(payload);
    });
  }

  onAuthEvent(payload: any) {
    switch (payload.event) {
      case 'signIn':
        console.log('signIn');
        break;
      case "signOut":
        console.log('signOut');
        break;
    }
  }

  onHostedUI() {
    Auth.federatedSignIn();
  }

  onSignOut() {
    Auth.signOut();
  }
}
```

**Comment by EssyTech** [comment]
Any movement on this? or is there a work around?  I have tried some polyfills but no luck. I currently have this issue and can't release latest build with amplify integration until it is resolved. However, I don't want to remove amplify completely because of this issue, but will have to if I see no movement.  

Company does not want to pay me to spend time debugging and fixing an amazon provided authentication framework in which the company already pays cloud fees to use it.

**Comment by gustavo-luis-bsd** [comment]
Update "aws-amplify" to version 1.1.36.

This version has the following fix:
-fix(@aws-amplify/core): Edge browser misidentified as Chrome (#3807)

**Comment by JohanRin** [comment]
@gustavo-luis-bsd Thanks for the information. I close the issue.
