### ISSUE TITLE
Continous Errors  https://cognito-identity.us_east_1.amazonaws.com/ net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by srinivasyl** [aws-amplify/amplify-js#3417]
I'm trying to signUp/signIn with AWS Congnito I'm able to signup/signin with AWS-amplify
below is my configuration file 

```
const CognitoConfig = {
    Auth: {
      // REQUIRED - Amazon Cognito Identity Pool ID
      identityPoolId: 'xx-xxxx-xxx-xxxxxx', 
      // REQUIRED - Amazon Cognito Region
      region: 'xxxx', 
      // OPTIONAL - Amazon Cognito User Pool ID
      userPoolId: '-xxxxx-xxxx',
      // OPTIONAL - Amazon Cognito Web Client ID
      userPoolWebClientId: 'xxxxxxxxxxxxxx', 
    }
  }
```
I'm able to signup/signin but errors appearing continuously in console

**Comment by jordanranz** [comment]
Can you post the error you are seeing in the browser console's Network tab? Also, can you tell us how you are using the Auth category in your code/UI? 

I believe this may occur because by default your identity pool does not enable unauthenticated identities. This means that when a guest user visits the page, Cognito will throw a 400 with a message saying something like: "Your user pool does not allow unauthenticated identities".
