### ISSUE TITLE
DynamoDB:ConditionalCheckFailedException

### ISSUE THREAD

**Issue by n00bm5st3r69** [aws-amplify/amplify-js#3485]
Hi All! I have a table with the following fields:

userID: ID
username: String
firstname: String
lastname: String
usertype: String
status: String

I want to change the value of the status field from "Active" to "Inactive" by performing a mutation update but unfortunately I am getting the below error.

errorType: "DynamoDB:ConditionalCheckFailedException"
message: "The conditional request failed (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ConditionalCheckFailedException; Request ID: MCJ872GCFE7ULCC8Q9ACQHM3S7VV4KQNSO5AEMVJF66Q9ASUAAJG)

Below is the sample code I am trying to run. 
 try {
            await API.graphql(graphqlOperation(updateUsers, { input: { userID: 27848, status: "Inactive" } })).then(data => {
                console.log("updateUsers", data)
            });
        }
        catch (error) {
            console.log("Error: ", error)
        }

**Comment by sammartinez** [comment]
@n00bm5st3r69 Seeing that there are some errors with a 400 status code and the error code ConditionalCheckFailedException, I did find this [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html) on DynamoDB for more insight into those error messages. As for the graphqlOperation, I would verify that the `updateUsers` is in fact a mutation of GraphQL in order to do the update. Here's a [link](https://aws-amplify.github.io/docs/js/api#amplify-graphql-client) to our documentation going over GraphQL.
