### ISSUE TITLE
The "Create Account" button is not disabled while a request is pending

### ISSUE THREAD

**Issue by all-iver** [aws-amplify/amplify-js#3558]
**Describe the bug**
During sign up, the "Create Account" button is not disabled while a request is pending.  Additionally there is no indication that it is doing anything.  In particular, if there is a lambda trigger involved then the request may take several seconds.  This leads to the user frustratedly pressing the button multiple times and results in a new Cognito user for every button press.

**To Reproduce**
1. Make a react app using withAuthenticator() and try to create a new user.
2. Quickly press the "Create Account" a bunch of times.
3. Observe that multiple new users have been created in your User Pool.

**Expected behavior**
The "Create Account" button should disable while a request is pending.

**Comment by haverchuck** [comment]
@all-iver We have a PR open which fixes this in aws-amplify-react.  We will merge it as soon as we are able.

**Comment by BardiaN** [comment]
This issue is back or it hasn't been resolved completely.
So I have a pre signup lambda that checks for a secret and the button stays enabled during the lambda runtime, so user is able to press the button so many times. (And Cognito has a known bug that let the same user being created if requests are too close to each other)
@all-iver Was your problem fixed?

**Comment by all-iver** [comment]
> 
> 
> This issue is back or it hasn't been resolved completely.
> So I have a pre signup lambda that checks for a secret and the button stays enabled during the lambda runtime, so user is able to press the button so many times. (And Cognito has a known bug that let the same user being created if requests are too close to each other)
> @all-iver Was your problem fixed?

I just tried to replicate and it seems to be fixed for me, but I haven't updated in quite a while so there could have been a regression.  I'm still on aws-amplify-react 4.1.7.

**Comment by BardiaN** [comment]
> > This issue is back or it hasn't been resolved completely.
> > So I have a pre signup lambda that checks for a secret and the button stays enabled during the lambda runtime, so user is able to press the button so many times. (And Cognito has a known bug that let the same user being created if requests are too close to each other)
> > @all-iver Was your problem fixed?
> 
> I just tried to replicate and it seems to be fixed for me, but I haven't updated in quite a while so there could have been a regression. I'm still on aws-amplify-react 4.1.7.

Thanks for the reply @all-iver 
So I tested my scenario and I guess I found my problem, but I think I have to open a new issue for it. It's related to the user being in `Unconfirmed` status and it happens because it takes a while for my user to be created due to existence of the PreSignUp trigger. 

So when a user is in `Unconfirmed` status you can create duplicates, but Amplify is preventing that on the frontend side unless you refresh the page in between, so could you please test this to see if you can also reproduce the bug:

- Use you sign-up form to create a user, but don't enter the code, so the user would stay `Unconfirmed`
- Refresh your page, so amplify will forget that it has to check the email before calling `SignUp` method and then go to sign-up form again
- Use the same email to create the user

And then please let me know if you were able to create a duplicate.
I'd really appreciate your help.

**Comment by all-iver** [comment]
@BardiaN , my setup uses username plus email.  Cognito seems to prevent me from making a duplicate account with the same username, regardless of whether the existing account is confirmed or not.  However, it seems happy to let me have multiple accounts with the same email address but different username.  I can log in with username on either of them, but only one of them can have a verified email address.  If I verify the same email address on a new account, it un-verifies the old one.  When I log in with email address, it logs in to the one that has the email verified.  I don't know why they designed it like that but I guess it's intended behavior?  If you're not using username and only using email, I'm not sure what intended behavior is...I guess maybe the same behavior except you can't log in with username?
