### ISSUE TITLE
Executing a graphqlOperation only returns a Promise and not Observabe

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws-amplify/amplify-js#3704]
**Describe the bug**
Looking at the type definition of API.graphql I see that it either returns `Promise<GraphQLResult>` or `Observable<object>`.

However, when I look at the code returned from a query I see a Promise:
![image](https://user-images.githubusercontent.com/5285035/61614958-409c9e80-aca8-11e9-8e39-8d088067adb3.png)

Now I always have to do a ugly promise conversion, for example:
```
 return from<Promise<{ data: { getPosts: GetPostQuery[] } }>>(API.graphql(
      graphqlOperation(statement, args))
    )
      .pipe(
        map(response => response.data.getPosts)
      ) as Observable<GetPostQuery[]>;
```
Any chance Observable (RXJS and not Zen) can be used?

**Comment by manueliglesias** [comment]
Hi @mattiLeBlanc 

A promise is returned for queries/mutations and an observable for subscriptions. You can see the relevant code here

https://github.com/aws-amplify/amplify-js/blob/799a1cfe59f7244f1cc51bdc0220a6c4ebf81455/packages/api/src/API.ts#L338-L344

**Comment by mattiLeBlanc** [comment]
@manueliglesias I understand.

**Comment by manueliglesias** [comment]
I think we can do a better job with the typings by specifying proper [overloads](https://www.typescriptlang.org/docs/handbook/functions.html#overloads) instead of using union types.

I'll tag this as an enhancement

**Comment by mattiLeBlanc** [comment]
It would also be nice to support generics <T> so that we can set our return type.

**Comment by rob3c** [comment]
I agree with the OP that rxjs should replace zen for the observable implementation 👍 

While it may seem obvious that promises should be used for requests that only return single values and observables should be used for those that stream multiple values over time, that's not necessarily the case.

The reason that libraries like angular use observables instead of promises for even simple http requests that will only every return single values (like the queries and mutations mentioned above), is that they make canceling the requests trivial. This also normally aborts the http request's connection in addition to just leaving it alive and ignoring the result, which is a nice optimization to get for free. Standard promise implementations do not support cancellation, which makes things like typeahead searches, request timeouts and other request-related logic much harder to implement efficiently.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
