### ISSUE TITLE
Send metrics along with Analytics.autoTrack('pageView') Events

### ISSUE THREAD

**Issue by peterjungx** [aws-amplify/amplify-js#3713]
**Is your feature request related to a problem? Please describe.**
I would like to send a metric along with the automatically tracked pageView to Pinpoint, to be able to analyse it in Pinpoint. Pinpoint would support this, but it is not implemented in amplify-js.

**Describe the solution you'd like**
Implement sending metrics (similarly to attributes) along with autoTrack pageView Events.

**Describe alternatives you've considered**
1. I could send the number I am interested in as an attribute, encoding the number as a string. But then the metric is basically not analysable in pinpoint.
2. I could implement a custom tracker that does the same as the pageView tracker but also sends metrics. But I would like to avoid this overhead.

**Additional context**
...

**Comment by cwomack** [comment]
@peterjungx, apologies for the delay in response on this issue.  The metrics tied to any recorded event can be configured within `Analytics.record()` as referenced in the docs [here](https://docs.amplify.aws/lib/analytics/record/q/platform/js/#record-engagement-metrics).  Although they have to be configured manually and don't come ready out of the box... they should show within the Pinpoint dashboard after you've configured them in your code under **Analytics > Events > Filters > Event Attributes and Metrics > [your-metric]**.  You can also throw in the [immediate flag](https://docs.amplify.aws/lib/analytics/record/q/platform/js/#record-engagement-metrics:~:text=float%20or%20integer.-,Record%20Events%20Immediately,-Amazon%20Pinpoint%20provider) to view them more quickly when testing.   

Note - At the "Filters" step above, you might have to hit a "More Information" button and then "Enable Filters" if it's the first time you're drilling down into the event filters.  

I'll close this issue since it's now a feature that Amplify offers through Pinpoint (although maybe this wasn't the case/there was issues when you opened this). Feel free to comment back if you feel this issue was closed in error, and we can reopen it or discuss how to get the specific metrics that you're looking for.

**Comment by peterjungx** [comment]
Ah, thanks for the answer! 3 years and 4 months is not bad as a response time. Lol.

Btw thanks for building amplify, it is great!
