### ISSUE TITLE
aws-amplify-react Authenticator component not updating authState

### ISSUE THREAD

**Issue by johnbowdenatfacet** [aws-amplify/amplify-js#3738]
**Describe the bug**
When using amplify to logout e.g.:
`
const currentUser = Auth.userPool.getCurrentUser();
await currentUser.signOut();
`
The Authenticator component does not update the authState so dependent components still see the state as authed.

**Expected behavior**
The Authenticator component should update the authState to an appropriate value.

**Comment by johnbowdenatfacet** [comment]
Already logged https://github.com/aws-amplify/amplify-js/issues/3636

**Comment by johnbowdenatfacet** [comment]
Sorry, this is still relevant and differs to the above issue.

**Comment by haverchuck** [comment]
@johnbowdenatfacet  - Can you please clarify what you mean by 'dependent components still see the state as authed'?

**Comment by johnbowdenatfacet** [comment]
> @johnbowdenatfacet - Can you please clarify what you mean by 'dependent components still see the state as authed'?

For example:
`<Authenticator>
<Child />
</Authenticator>`
props.authState on the component 'Child' remains signed in, this should change once signOut() is called.

**Comment by ChrisLFieldsII** [comment]
Hello,

I've been looking into this problem for about a day and have a proposed solution. I ran into the same thing where calling `Auth.signOut()` while using `withAuthenticator` HOC does successfully log the user out but it fails to update the authState because of the `isMounted` checks [here](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/Authenticator.js#L93). The `withAuthenticator` HOC does pass through the `onStateChange` [prop](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/index.js#L109) so you should be able to use that within your components like [this](https://github.com/aws-amplify/amplify-js/issues/174). However I am using react-native with react-navigation and the screen I am calling `Auth.signOut()` in fails to get the `onStateChange` prop due to I believe react-navigation not passing props through as you can see in the attached image. 
![Screen Shot 2019-08-18 at 4 42 36 AM](https://user-images.githubusercontent.com/30332608/63222877-ccec9500-c172-11e9-8ea1-e098dcea0eae.png)

If I had availability to the `onStateChange` prop, even though the auth Hub [listener](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/Authenticator.js#L91) would early return due to `isMounted`, I could do `onStateChange('signIn')` in the then() block of `Auth.signOut()` and all would be good but that is not the case!

I think there should be a built in way for us to dispatch an event to Hub which would trigger a signOut and update the authStatus although this could possibly get hairy with us sending malformed events if not well documented and made obvious you could possibly argue. 

Since `Auth.js signOut()` [dispatches](https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/Auth.ts#L1299) to auth channel with signOut event automatically, the [code](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/Authenticator.js#L88)  for the Authenticator Hub listener on the auth channel should maybe filter for the signOut event and set the authState instead of just doing `checkUser()` which doesnt run if the Authenticator isn't mounted which will always be the case when in a situation where a User has to hit a Sign Out button

This is what I am using currently to get around this for my case for the Authenticator [onHubCapsule](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/Authenticator.js#L86) listener.

```onHubCapsule(capsule) {
    const { channel, payload, source } = capsule;

    if (channel === 'auth') {
      // calling Auth.signOut() automatically dispatches Hub payload to Auth channel with signOut event
      if (payload.event === 'signOut') {
        // due this to circumvent isMounted checks in checkUser() as signOut is a case we want Authenticator
        // to take over if though it isnt mounted
        this.setState({ authState: 'signIn', authData: null, error: null });
        if (this.props.onStateChange) {
          this.props.onStateChange('signIn', null);
        }
      }
    } else {
      this.checkUser(payload);
    }
  }```
