### ISSUE TITLE
Angular: amplify-authenticator shows technical user-id

### ISSUE THREAD

**Issue by StefanV85** [aws-amplify/amplify-js#3822]
Hello,

We are using Amplify with Angular 7 in our Project.
We created an AWS Cognito Userpool using the amplify cli. 

And in Angular we are using: <amplify-authenticator> directive to sign-in/sign-up.
But our User Pool use e-mail adresses for Logins (no custom username)

when we login in our project, the <amplify-authenticator> directive shows the technical user-id.

![image](https://user-images.githubusercontent.com/48675734/62689955-0df2e580-b9cc-11e9-9dc9-6cd186fe1dc8.png)

This is, how the user looks like in Cognito: 
![image](https://user-images.githubusercontent.com/48675734/62690280-bdc85300-b9cc-11e9-9886-87452eb18aad.png)

Is there any way to show the e-mail adress instead of the technical user-id?
Otherwise in my opinion it's a bug. right?

Kind Regards
Stefan

**Comment by ericclemmons** [comment]
I found via a quick search:
https://github.com/aws-amplify/amplify-js/blob/6d34cbd865d813bb6b542bcd90d9ce05eaac40a0/packages/aws-amplify-angular/src/components/authenticator/greeting-component/greeting.component.core.ts#L71-L84

Compared to the React implementation:
https://github.com/aws-amplify/amplify-js/blob/6d34cbd865d813bb6b542bcd90d9ce05eaac40a0/packages/aws-amplify-react/src/Auth/Greetings.jsx#L84-L86
https://github.com/aws-amplify/amplify-js/blob/ce67450168b16c1c446661f213eae02acaa99423/packages/aws-amplify-react/src/Auth/AuthPiece.jsx#L32

At first glance, it looks like there's either a difference in reference for the fallback (`username` vs. `Username`?) or the logic blocks for preferring email & phone are failing due to the value of `this._usernameAttributes`.

**Comment by ericclemmons** [comment]
Hi @StefanV85,

I was able your example this morning with a small sample app:

> <img width="804" alt="Screen Shot 2019-10-18 at 10 02 30 AM" src="https://user-images.githubusercontent.com/15182/67113488-7e697000-f18e-11e9-896e-39272328a2ff.png">

**Good news!** This should be readily fixable via the steps outlined here:
> https://aws-amplify.github.io/docs/js/angular#sign-upin-with-emailphone-number

```diff
diff --git a/samples/angular/auth/amplify-authenticator-email/src/app/app.component.html b/samples/angular/auth/amplify-authenticator-email/src/app/app.component.html
index 458fe92..60adffe 100644
--- a/samples/angular/auth/amplify-authenticator-email/src/app/app.component.html
+++ b/samples/angular/auth/amplify-authenticator-email/src/app/app.component.html
@@ -1,6 +1,6 @@
 <!--The content below is only a placeholder and can be replaced.-->
 <div>
-  <amplify-authenticator></amplify-authenticator>
+  <amplify-authenticator [usernameAttributes]="usernameAttributes"></amplify-authenticator>
   <div *ngIf="signedIn">
     <div style="text-align:center">
       <h1>
```

```diff
diff --git a/samples/angular/auth/amplify-authenticator-email/src/app/app.component.ts b/samples/angular/auth/amplify-authenticator-email/src/app/app.component.ts
index a8b6cc8..7d94574 100644
--- a/samples/angular/auth/amplify-authenticator-email/src/app/app.component.ts
+++ b/samples/angular/auth/amplify-authenticator-email/src/app/app.component.ts
@@ -10,6 +10,7 @@ export class AppComponent {
   title = "Amplify Authenticator Angular Starter";
   signedIn: boolean;
   user: any;
+  usernameAttributes = "email";
   greeting: string;

   constructor(private amplifyService: AmplifyService) {
```

After making these changes, the greeting uses the `email`

> <img width="799" alt="Screen Shot 2019-10-18 at 10 02 17 AM" src="https://user-images.githubusercontent.com/15182/67113586-c25c7500-f18e-11e9-82e9-fae177cbb838.png">

@StefanV85 If this doesn't work, be sure to let us know.
