### ISSUE TITLE
Release Changelog

### ISSUE THREAD

**Issue by Domino987** [aws-amplify/amplify-js#3974]
Hi aws team,
is it possible to generate a release changelog so that we can see what changed since the last version? I really like how material-ui does it:
![image](https://user-images.githubusercontent.com/17567991/64346607-b3609f80-cff2-11e9-9e7b-c104c4b0d374.png)
This would make it easier to get new fueature or see if a bug was fixed.
Great work anyway. Thank you!

**Comment by haverchuck** [comment]
@Domino987 - We do have change logs in our individual packages, but I think the example you've posted is very clean and useful.  I will mark this as a feature request, since I think our process could be greatly improved.  Thanks for sharing this.

**Comment by schellack** [comment]
Personally, I'm can usually find the relevant information in the changelogs, after some hunting around through each package. But this setup does not take advantage of GitHub's release notifications:
![image](https://user-images.githubusercontent.com/70819/64915753-3c36b400-d734-11e9-8f35-f6cc92f79e17.png)

For whatever reason I never get any release notifications for https://github.com/aws-amplify/amplify-js.

Also, since all of the Amplify packages seem to get updated with every release, new releases frequently appear (for example @aws-amplify/auth on npm's web site):
![recent versions of @aws-amplify/auth on npm web site](https://user-images.githubusercontent.com/70819/64915774-c717ae80-d734-11e9-9596-3f2a71ac0e11.png)
So in theory you could try to monitor for new releases there for just the packages you use.

Yet for many Amplify packages (screenshot below is from auth), those releases don't include any actual changes:
![@awsamplify/auth package changelog](https://user-images.githubusercontent.com/70819/64915794-1f4eb080-d735-11e9-874f-96e392ceda95.png)

So once you figure out where the changelogs live, you still have to go visit each one for each package you use every time Amplify gets an update. And most of the time none of the packages you use actually changed (i.e., you just see "version bumps").

All of which is to say, it would be a significant quality-of-life improvement to have one place to go look to find when changes actually occur, particularly if that took advantage of GitHub's out-of-the-box release functionality.

**Comment by ajhool** [comment]
@schellack same, I never get notifications for amplify-js releases

**Comment by clementAC** [comment]
I strongly agreed with @schellack. Find changes is like a treasure hunt and clearly it's a waste of time for users. A global changelog that keep trace of all real changes accross the packages would be a great improvement

**Comment by mauerbac** [comment]
Closing this issue in favor of an implementation across all Amplify repos https://github.com/aws-amplify/docs/issues/3183
