### ISSUE TITLE
Federated Sign In (Google) with Cognito is not working on Android and Expo Standalone

### ISSUE THREAD

**Issue by oriharel** [aws-amplify/amplify-js#4003]
**Describe the bug**
I'm using withOAuth() HOC. User is directed to the Google (code) flow, comes back to the app. Linking url event is triggered (with code parameter in the url) thus causing a call to Amplify token endpoint (with code_verifier). However, multiple additional Linking url events are fired, causing a throttle of token endpoint calls to trigger (all of them without code_verifier) that ends up with invalid_request and invalid_grant and eventually crashes the app. 
This happens only on Android (iOS works fine) and in Expo standalone (for some reason, when running the app in the Expo Client, it works fine because the url is stripped from the code this the token endpoint is not called).

**To Reproduce**
User Expo standalone Android app with Amplify withOAuth HOC to call google.

**Expected behavior**
Avoid invalid calls to the token endpoint.

**Smartphone (please complete the following information):**
 - Device: Any Android device
 - OS: Any Android version
 - Expo Standalone

Here is the relevant config of Auth.configure:

```
const urlOpener = async (url, redirectUrl) => {
	const { type, url: newUrl } = await WebBrowser.openAuthSessionAsync(
		url,
		redirectUrl
	);

	if (Platform.OS === 'ios') {
		if (type === 'success') {
			await WebBrowser.dismissBrowser();
			return Linking.openURL(newUrl);
		}
	}
};
export const oauth = {
	domain: 'some.domain.com',
	scope: [
		'phone',
		'email',
		'openid',
		'profile',
		'aws.cognito.signin.user.admin'
	],

	redirectSignIn: Linking.makeUrl('/signIn'),
	redirectSignOut: Linking.makeUrl('/signOut'),
	responseType: 'code',

	urlOpener: urlOpener
};
```

**Comment by elorzafe** [comment]
@oriharel thanks for your feedback. Can you share your package.json and expo-cli version?

**Comment by oriharel** [comment]
I've opened a PR #4005

**Comment by oriharel** [comment]
So this issue is actually not an Amplify issue, but an expo one. For some reason, expo standalone apps fires multiple events on deep linking on Android. There is an issue on this matter [here](https://github.com/expo/expo/issues/2128).
Perhaps @brentvatne can take a look. However, Amplify can provide a hook to workaround this as suggested in the PR (#4005).

Thanks.

**Comment by schellack** [comment]
I have this issue as well  on standalone Android builds, generated using Expo. I can see the error when connecting to a debugger (shows up a couple times before the app crashes):

> 2019-09-18 18:14:56.861 17177-17500/? E/ReactNativeJS: '[ERROR] 14:56.849 OAuth - Error handling auth response.', { [Error: invalid_grant]
>       line: 978,
>       column: 4017,
>       sourceURL: '/data/user/0/redactedappslug/files/34.0.0/cached-bundle-experience-%40redacted%2Fappnameredacted-1424113275-34.0.0' }

**Comment by oriharel** [comment]
@schellack Yes, this is caused by multiple calls to the TOKEN ENDPOINT of Cognito. theis endpoint can be called only once (no matter if fails or succeeded) and consecutive calls result in an invalid grant (which means that the code used in the request is no longer valid)

**Comment by schellack** [comment]
I can see that's what's happening. Do you know of a workaround @oriharel?

**Comment by oriharel** [comment]
I ended up overriding Linking.addEventListener function and wrapped the handler passed as a property. in the override I ignore multiple calls with the same 'url' value.
Hopefully we'll have amplify provide the urlListener as a configuration parameter so we won't have to do this ugly workaround.

**Comment by loganwedwards** [comment]
@oriharel I have been following all matter of oauth flow-related issues (FB, specifically) with an ejected Expo 33 app and just stumbled upon this issue. I believe I am experiencing the exact same root problem on iOS. I went as far as attempting to manually monkey patch it without success and your linked PR looks like a nice improvement. When you specifically mention, you `overriding Linking.addEventListener`, would you mind sharing any specific details? Did you override the function globally?

**Comment by loganwedwards** [comment]
@oriharel @schellack I dug into this a bit more and discovered the issues is actually partly my fault in how I installed the project or an architectural one on the Amplify side. I disccovered that the `urlListener` is in fact executing the code flow twice, *but* it was only happening once in `@aws-amplify/auth`. Come to find out, there is a separate `node_modules` directory under `aws-amplify` (seems to be required no matter what by `aws-amplify-react-native` and another under `@aws-amplify/api`. The extra urlListeners are actually exectuting the code flow as well. I nuked the node modules directory since amplify is correct using the `require('@aws-amplify/auth')`, so it does end up resolving to the correct issues.

Related, this also fixed my problem where Amplify complained that `.configure` was not called (or not called correctly), which now makes sense since there were multiple copies of the Auth service installed. I tried yarn, which may have cleared all of this up, but it introduced other issues in my detached Expo project, so I reverted to using npm and manually deleting the requisite node_modules. 

Here is my (relevant) bits of the package.json:

```
"dependencies": {
    "@aws-amplify/api": "^1.0.42", // manually deleted these node_modules
    "@aws-amplify/auth": "1.2.31",
    "@aws-amplify/core": "^1.1.0",
    "@aws-amplify/storage": "^1.1.0",
    "aws-amplify": "^1.1.36", // manually deleted these node_modules
    "aws-amplify-react-native": "2.1.16",
    "aws-appsync": "1.8.1",
    "aws-appsync-react": "1.2.9",
   ...
}
```

It seems there may be a conflict with using both the modularized packages `@aws-amplify` and the original package `aws-amplify`. I hope this helps as I have been struggling with this issue for months.

Any suggestions from @manueliglesias or other members of the Amplify team on a non-hacked resolution?

**Comment by schellack** [comment]
Interesting. Any particular reason why you are using the scoped package imports (e.g., `@aws-amplify/auth`) and also importing the full `aws-amplify` library?

I will take another look at my project to see if that's at all related to the issue I see. Personally I only use the scoped imports.

**Comment by loganwedwards** [comment]
It's been a while, but I think I was trying to trim my deps down (I only need API, Auth, Core) instead of everything (don't use Analytics, MQTT, Chatbot, etc...). The idea was to get rid of just `aws-amplify`, but it seems it's required by the Amplify RN package.

@schellack Are you using React Native?

**Comment by schellack** [comment]
For what it's worth, I don't see multiple code flow events. I track every auth event published to the Hub on the 'auth' channel and only see a single `codeFlow` event.

@loganwedwards if you are still seeing multiple codeFlow events, then you should probably look at only using the scoped packages (and removing aws-amplify) or only use aws-amplify (and removing scoped packages).

My app is all React Native, but I do not import the Amplify React Native package. Instead I directly use a modified version of [withOAuth](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/withOAuth.js). Since I'm using the Amplify hosted UI, there was no need for me to use any of the other stuff in the package, as all the rest of it is UI-related.

The original behavior described above by @oriharel still occurs for me when running on actual Android hardware (not an emulator).

Here are the steps that occur: 
1. Import `@aws-amplify/auth` (elsewhere I already imported the Hub from `@aws-amplify/core` and subscribed to its auth events).
2. Configure amplify auth: `Auth.configure({...`
3. Call custom provider signin (in my case; in [oriharel's case](#issue-492220936) he was using the Google provider, I believe)
4. Amplify calls the configured `urlOpener` to prompt the user to sign in. In step 1, above, I configured the `urlOpener` to use `await WebBrowser.openAuthSessionAsync(url, redirectUrl)`, where WebBrowser is imported from [expo-web-browser](https://docs.expo.io/versions/latest/sdk/webbrowser/). This is per the [Amplify instructions for Expo users](https://aws-amplify.github.io/docs/js/authentication#a-note-for-expo-users).
5. The Android device opens a Chrome Custom Tab and takes the user the the auth URL.
6. The user signs in and is redirected back to the app (via the `redirectUrl` parameter that was passed to `WebBrowser.openAuthSessionAsync` in step 4).
7. Expo returns the `dismiss` result type as part of the result returned from  `WebBrowser.openAuthSessionAsync`.
8. Meanwhile Amplify is parsing things (I see the `parsingCallbackUrl` event published on the Hub).
9. `WebBrowser.openAuthSessionAsync` then inexplicably returns again, only this time the result type is `cancel` instead of dismiss. This is not visible on the screen. The urlOpener I configured was not called again (I check for that), but rather WebBrowser is apparently acting up (the underlying problem here).
10. Now I have competing states to deal with: a successful authentication, still being processed, and a cancellation from web browser that was supposed to load the auth URL. Since I have to handle cancel events in order to know when a user closes the Chrome custom tab (something that they can do), I can't just ignore those events. Hence the need to handle this before the url is called.

**Comment by loganwedwards** [comment]
It seems the actual errors/flows are subtly different in our use cases, but I am sure the steps you outlined above will help other Android users.

**Comment by sammartinez** [comment]
The above Pull Request that is merged in seems to resolve this issue. @oriharel Can you confirm this?
