### ISSUE TITLE
S3 Upload: CredentialsError: "Missing credentials in config"

### ISSUE THREAD

**Issue by McCrearyD** [aws-amplify/amplify-js#4091]
**Describe the bug**
After authenticating a user, and using the Storage component to put an object, it gives the error CredentialsError: "Missing credentials in config".

I followed the instructions of other issues on this repo, however all of them say to uninstall the node_modules/package-lock.json & reinstall. This simply does not do anything for me. There is no duplicate aws-sdk versions and aws-sdk is not included in my package.json.

**To Reproduce**

1. Create angular app with version ~8.2.8.
2. Install these dependencies:
    "@aws-amplify/ui": "^1.0.25",
    "aws-amplify": "^1.1.40",
    "aws-amplify-angular": "^3.0.15",
3. Init amplify then add Storage & Auth.
4. Enable "choose from token" for the user identity pools providers.
3. Create & sign into a user.
4. Attempt to make the following call:
Storage.put('somejson.json', {'test': 'test'}, {
      level: 'private',
      contentType: 'application/json'
    });

**Expected behavior**
Upload the given json folder to the key in the user's private folder.

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.2 LTS
- Browser Firefox

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

Debug Log Level Pastebin:
https://pastebin.com/QXsnFsnb

**Comment by McCrearyD** [comment]
I figured it out, since I have roles being assumed due to the "choose from token" feature, I need to add their inline permissions for those users to adhere to the standard: 

https://aws-amplify.github.io/docs/js/storage#using-amazon-s3

**Comment by manueliglesias** [comment]
@McCrearyD  Nice! Thanks for sharing your solution

**Comment by elliott-king** [comment]
Coming in to share that I also had this problem. When turning on the debug logs, I had the additional message `[DEBUG] 22:18.960 Credentials - Failed to load credentials`.

My solution instead came from this great StackOverflow post, which is also helpful to understand user pools vs identities:

https://stackoverflow.com/questions/44043289/aws-invalid-identity-pool-configuration-check-assigned-iam-roles-for-this-poo

Plus my url is better because it contains 'poo'.
