### ISSUE TITLE
React + TypeScript: AuthPiece implementation types should override type for render

### ISSUE THREAD

**Issue by xMartin** [aws-amplify/amplify-js#4226]
**Describe the bug**
TypeScript error when passing `<SignIn />` or other `AuthPiece` implementations to `withAuthenticator`:

```
JSX element type 'SignIn' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => void' is not assignable to type '() => ReactNode'.
      Type 'void' is not assignable to type 'ReactNode'.  TS2605

    63 |   withTranslation()(AppRouter),
    64 |   false,
  > 65 |   [<SignIn />],
       |    ^
    66 |   {},
    67 |   AuthenticatorTheme,
    68 |   {}
```

**Amplify context**
- aws-amplify-react@2.5.2

**Additional context**
The `AuthPiece` implementations inherit the render type (`render(): void`) but as they are returning the result of `showComponent` it should be overridden  with `render(): JSX.Element`.

**Comment by Amplifiyer** [comment]
@xMartin, we have few any types and ts-ignores in the react package after javascript -> typescript conversion with this PR https://github.com/aws-amplify/amplify-js/pull/3715 because of which you are seeing this error.
This should only be a compile time error due to missing type information, can you try adding ts-ignore and see if your code runs fine?

We will convert this a feature request to add type information to amplify react package.

**Comment by fdelhoste** [comment]
Same issue here. I've tried to add `// @ts-ignore` before the `<SignIn />`and it fails at runtime with `TypeError: undefined is not an object (evaluating 'child.props.override')`.

**Comment by aldo-roman** [comment]
I can reproduce this with the `<Authenticator />` component as well.

```JSX
<Authenticator hideDefault={true} onStateChange={this.handleAuthStateChange}>
    <SignIn/>
    <VerifyContact/>
    <RequireNewPassword/>
    <ForgotPassword/>
</Authenticator>
```

This worked as of `"@aws-amplify/api": "^1.3.3"`.
Broken after updating to `"@aws-amplify/auth": "^1.4.2"`

**Comment by Amplifiyer** [comment]
@aldo-roman, are you able to reproduce this at run time as well? I just tried with a fresh typescript react app and aws-amplify-react@2.5.2 + aws-amplify/auth@1.4.2 and the app works at runtime (with @ts-ignore). Just want to understand if the issue is just with the types or functionality as well.

@fdelhoste, can you post your code sample that you are using? Does downgrading to aws-amplify-react@2.3.13 which is pre ts-conversion has the same issue or does it work?

I'll try to add typings in the meanwhile to the react package to avoid the ts-ignore in consumer applications.

**Comment by aldo-roman** [comment]
Hi @Amplifiyer 
I am not able to run the app because I also get into #4186

**Comment by Amplifiyer** [comment]
@aldo-roman, is your dev build working and you are able to run?

I tried reproducing a prod build as per issue 4186 but it is not failing for me with a simple react app using withAuthentication HOC.

**Comment by buggy** [comment]
@fdelhoste and @aldo-roman How did you start your projects? When writing the conversion PR I did notice some differences between apps started with create-react-app and those I started with TypeScript + Webpack.

**Comment by aldo-roman** [comment]
@Amplifiyer No, it doesn't build nor runs because of these two issues (so far).

@buggy Created with create-react-app, using typescript

IMHO, the underlying root cause is the project is making heavy use of inheritance on this part, which tends to be an anti-pattern in React. This probably wouldn't happen if we design it using composition.

We can also try just overriding `render()` as OP proposes.

**Comment by Amplifiyer** [comment]
https://github.com/aws-amplify/amplify-js/pull/4237 will fix the build issues, I have tested with a create-react-app with typescript. For the production build issues, I'll continue trying to debug it in #4186
