### ISSUE TITLE
Cognito OAuth Code Grant Flow.

### ISSUE THREAD

**Issue by AbeerSperadian** [aws-amplify/amplify-js#4264]
HI,
I have recently started working with AWS amplify. Currently, the Issue I am facing is in Amplify is that I need to change the Cognito hosted UI to make my login user experience the same way as it is on my web page,
Constraints:
must use Cognito OAuth Code grand flow. so that it will send the code to the Alexa skill directly and Alexa will be able to get tokens on the behalf of code.

what I found up till now is AWS amplify works for implicit grant flow and Auth grant flow which will return tokens. for OAuthSignIn AWS amplify redirects the user to the Cognito Hosted UI.

let me know if what I need is even possible or not at the moment. If possible then please share some working code snippet that would be wonderful. 

Regards:
Muhammad Abeer Ur Rehman.

**Comment by Amplifiyer** [comment]
Hi @AbeerSperadian, sorry to get to your question so late. Amplify supports code grant oauth flows (it's also the default) with Cognito hosted UI and you can configure the hosted UI as per https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-ui-customization.html

However I believe you need access to the code so that you can send it to the Alexa skill which would exchange it for the tokens. I'm wondering if you need to sign the customer in to your webapp as well?

As a workaround to retrieve the code, you can probably listen to [parsingCallbackUrl](https://github.com/aws-amplify/amplify-js/blob/1baab7807dbaed9bf3915f061053fa2da729fa99/packages/auth/src/Auth.ts#L1794-L1798) Hub event which will fire when cognito hosted UI returns back to your app with the URL having the code in it.
