### ISSUE TITLE
Authentication problem: error=redirect_mismatch

### ISSUE THREAD

**Issue by tobon96** [aws-amplify/amplify-js#4308]
**Describe the bug**
I have a federated authentication with google. When the redirect urls are localhost there's no problem, even when I publish the project to cloudfront, but when I change the redirect urls to the one provided by cloudfront, everytime I try to login it keeps me sending to the same error page.

![image](https://user-images.githubusercontent.com/17577509/67960523-694a0380-fbc8-11e9-8f3c-6c89b1d1cb87.png). I tryed redirecting to the google search page (https://www.google.com) and it's the same: On localhost it works, but after I publish to cloudfront, it simply fails.

I really hope you can help me.

**Comment by haverchuck** [comment]
@tobon96 When you say you've changed the redirect URL, you mean that you've changed the 'Callback URL' in Cognito?

**Comment by tobon96** [comment]
Yes, I changed the 'Callback URL' through the Amplify console. It just works in localhost.

**Comment by jordanranz** [comment]
@tobon96, Amplify Console or Cognito Console?

**Comment by tobon96** [comment]
Maybe I wasn't specific enough. Through the CLI, with amplify update auth, add/edit redirect urls.

**Comment by tobon96** [comment]
I'm still having the issue after updating de CLI. Any update over this matter?

**Comment by oliverandersencox** [comment]
having the same issue here with Facebook login. Redirecting back to localhost ionic always gives this error

**Comment by haverchuck** [comment]
@tobon96 Can you post the redirect uris exactly as they appear under the oauth key in your aws-exports?

**Comment by ryanweaver718** [comment]
I'm having the exact same issue where it was working on my local host and when I stoop up my cloudfront/s3 https site and added that as redirects along with my localhost.
Has anyone gotten to a solution?

**Comment by zhihongl** [comment]
This is because of the mismatched url for either redirectSignIn or redirectSignOut. Please check both setup in aws console and code aws_config, and make them consistent.
 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/4370435/89646542-51de3a80-d8ff-11ea-9ac6-fdb58edbe040.png">

![image](https://user-images.githubusercontent.com/4370435/89646690-97026c80-d8ff-11ea-95b8-e4409af4bf07.png)

![image](https://user-images.githubusercontent.com/4370435/89646714-a5508880-d8ff-11ea-9b1d-3ebfcb09efd2.png)
![image](https://user-images.githubusercontent.com/4370435/89646747-b7322b80-d8ff-11ea-8b58-8f3b7c3b4d1d.png)
![image](https://user-images.githubusercontent.com/4370435/89646773-c1ecc080-d8ff-11ea-8d51-3eff4a5e3cc6.png)
