### ISSUE TITLE
IE 11 - Avoid Caching of Storage.list Results

### ISSUE THREAD

**Issue by ncstrause** [aws-amplify/amplify-js#4322]
** Which Category is your question related to? **
Storage
** What AWS Services are you utilizing? **
S3, Cognito, API Gateway
** Provide additional details e.g. code snippets **
aws-amplify version: 1.1.30

I'm trying to display a list of files that a user has uploaded to an S3 bucket under private for their identityId. I do this by calling Storage.list and displaying the results in a table. The user has the ability to manage their files by removing files or uploading more files.

In most browsers this works perfectly. However, in some versions of Internet Explorer 11, calling Storage.list after adding or deleting a file will not reflect the change in the list of files because the browser will load the previous response from cache.

Is there a way to force the list response to not be cached?

**Comment by dweiger** [comment]
Are there any news on this topic? I have the exact dame issue.

**Comment by dweiger** [comment]
I found a workaround for this. It is not really beautiful but it works for me since I am not using maxKeys. I use the maxKeys option and Date.now() to create unique requests all the Time. 

const uniqueNumber = parseInt((Date.now()).toString().substr(-4)) // make the number smaller

Storage.list(`documents`, {maxKeys: uniqueNumber})
            .then(..)

I think a possibility to set the request headers would be great, though.

**Comment by harrysolovay** [comment]
Same as #7095 

> You can specify a custom [`Cache-Control`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) header by including it under the key `cacheControl` on the `config` (optional) that you supply to `Storage.get`.
>
>Supplying `"no-cache"`, for instance, will ensure that it's always re-validated.
