### ISSUE TITLE
Confirm code page

### ISSUE THREAD

**Issue by ashish-dirkmedia-de** [aws-amplify/amplify-js#4344]
I am using angular 6 aws-amplify-angular for auth
When I signup without entering verify code. And when try to login it says error user not verified. How can I show the verify code page. So that in case he misses entering verify code at signup can enter.

**Comment by delenamalan** [comment]
I had the same question, but eventually figured out you can use the `Auth.resendSignUp(username)` and `Auth.confirmSignUp(username, verification_code)` methods to send another verification code and submit it again.

I used these methods directly so I don't know whether there are any Angular components available to do this.

**Comment by jordanranz** [comment]
@ashish-dirkmedia-de, are you using the `amplify-authenticator` in `aws-amplify-angular`?

**Comment by ashika01** [comment]
Closing the question because of the lack of activity on the issue. 

Also, our UI system is going through revamps. The new UI provides you the functionality you have questions around. If interested give it a try [New UI Components](https://github.com/aws-amplify/amplify-js/tree/ui-components/master/packages/amplify-ui-components#quick-start)
