### ISSUE TITLE
Is Amplify compatible with a vanilla javascript + HTML client-side static website?

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-js#4471]
** Which Category is your question related to? **

Amplify core. (although I am specifically interested in Auth).

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
HTML + CSS + Javascript, classic website. Have found the other cognito javascript SDKs to be unmanageable and would like to upgrade to Amplify javascript (preferably via cdn rather than npm import).

Is there any reason that Amplify can't be used in a vanilla JS client-side website? Would the flow still be basically:

```
// pseudocode from memory
Amplify.configure({  ... existing Cognito hostedUI information, s3 buckets, etc. ... })
Auth.federatedSignIn();
```

**Comment by haverchuck** [comment]
@ajhool You should be able to accomplish this.  [These docs](https://aws-amplify.github.io/docs/js/start?platform=purejs) should point you in the right direction, and include a webpack config to help.

**Comment by ajhool** [comment]
@haverchuck Thanks. So, just to be clear, there isn't an official existing script that can be imported; the script needs to be built with webpack to target es5 (https://caniuse.com/#search=es5) or es6 (https://caniuse.com/#search=es6), first?

Would the amplify team be interested in a PR that would add a circleci step to run webpack and build the vanilla javascript with an es5 or es6 target, with the eventual goal of creating an amplify script cdn for each module? The "old" way to integrate cognito with a standard html + js app (https://github.com/aws/amazon-cognito-auth-js) appears to be no longer maintained, so there might be a user base that would benefit from a hosted vanilla script like this.

For instance, I have a client who would like to integrate Cognito with their traditional html + js website and even "small" extra steps like a webpack build can make maintenance difficult.

**Comment by haverchuck** [comment]
@ajhool I believe that webpack config is just for the demo app, not the library itself.  You may be able to just download the package and point to it with a hardcoded script tag (though I haven't actually tried this).  I'm raising the idea of a CDN with our team.

**Comment by ajhool** [comment]
Okay, thanks. I will try it within the next week and can report back about how it goes!

**Comment by ajhool** [comment]
So far, importing the `amplify.min.js` file from the downloaded amplify node_module appears to be worlking. Would still appreciate an official CDN!

**Comment by SciTechDude** [comment]
Recently I implemented a browser based App with plain JS + HTML. I did not use ammplify cli. I basically directly configured using amplify UI , connected codecommit repo , configured cognito backend and Route-53. 
With this I was able to deploy webApp directly.  
I see that amplify basically launches app on a docker container with minimal config.
Only drawback is probably because there is no backend created and all of the dependancies are browser based, I could not access process.env to switch between prod and dev branch automatically.
I need to change one variable manually everytime code is pushed from dev. or if dev is refreshed from dev to make sure it doesnt point to wrong portal.

**Comment by t829702** [comment]
> @ajhool You should be able to accomplish this. [These docs](https://aws-amplify.github.io/docs/js/start?platform=purejs) should point you in the right direction, and include a webpack config to help.

Your link https://aws-amplify.github.io/docs/js/start?platform=purejs now redirects to front page https://docs.amplify.aws/start there no longer has any purejs example, do you still have the purejs example at another place?

**Comment by bannostookaylo** [comment]
I'd just like to bring life to this that the purejs link, whatever it looked like in the past, no longer seems to work. There no longer seems to be any "pure" or "vanilla" js examples. There is clearly an individual links for Javascript and since its listed with React and other frameworks you would think it would go to a "vanilla" or es6 solution... but it does not

**Comment by bannostookaylo** [comment]
I'd be curious if there is still a "pure" js example in place... something without using webpack or any kind of bundler... I've ran across this nice write up https://arcoirislabs.medium.com/aws-amplify-in-vanilla-javascript-6c4d8b3f29b0 kinda getting stuck on how to implement the hosted ui though... i think with all the time i've waisted looking at solutions i probably could have built my own LOL which I may end up doing haha
