### ISSUE TITLE
Using withAuthenticator can you allow sign in for only a specific cognito group?

### ISSUE THREAD

**Issue by kyangy** [aws-amplify/amplify-js#4481]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito

**Comment by haverchuck** [comment]
@kyangy Can you elaborate on what you mean by 'a single Cognito group'?

**Comment by kyangy** [comment]
@haverchuck I am trying to create an admin dashboard and I am using withAuthenticator for authentication.  These admins are part of a group created in Cognito. I was wondering if there was a way to only allow the admins to sign in?

**Comment by haverchuck** [comment]
@kyangy The issue here is that the user's Cognito group membership would need to be checked after the authentication request is received by Cognito but before the successful response w/tokens are sent back to the client.  This might be a good use case for Cognito triggers - specifically the [Pre-Authentication trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-authentication.html).  I haven't actually tried this, but perhaps you could write a trigger that would perform initial authentication, check the group membership, and then only send back a successful response if the user is in the right group (again, I haven't actually tried this so I can't 100% say whether it would work or be secure).  The Amplify CLI [supports the configuration of Lambda triggers](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#adding-a-lambda-trigger).
