### ISSUE TITLE
Users get "Refresh Token has expired" after less then 30 days

### ISSUE THREAD

**Issue by oriharel** [aws-amplify/amplify-js#4542]
My user pool app client **Refresh token expiration (days)** setting is set to 30.
However, few users (not all) get an error from aws-amplify Auth class:
`{"code":"NotAuthorizedException","name":"NotAuthorizedException","message":"Refresh Token has expired"}`

**Expected behavior**
Refresh token to be valid within the configured time frame

I'm using aws-amplify inside a React-Native app and Expo managed workflow.
React Native 0.59
Expo SDK 35
aws-amplify 2.2.0
aws-amplify-react-native 2.2.3

**Comment by manueliglesias** [comment]
Hi @oriharel 

Are your users getting the message close to 30 days? or much earlier?

**Comment by oriharel** [comment]
Much earlier. I have users get that 2 days after a perfectly good session.

**Comment by oriharel** [comment]
I think this is a misunderstanding of the docs. I was under the impression that the refresh token is being re-issued on every session, thus users should never get to the expiration time while they are active. 
Apparently this is not the case, as users are issued a refresh token upon login only and that token is being persistent on the client side storage. No matter if they are active or not, this token is expired after 30 days (or else configured) and then need to re-login again.
@manueliglesias can you confirm?

**Comment by andreialecu** [comment]
Is it possible to refresh the "refresh token" without forcing the user to re-enter the credentials?

Did you find a workaround @oriharel ?

**Comment by andrea66x** [comment]
I have the same problem with the refresh token. I set the expiration time to 60 minutes, because I need the user to sign out after 1 hour of inactivity. I can refresh the session (to get a new accessToken) within this time when the user is still active, but the session can not be refreshed after 1 hour since the authentication and a new sign in is required. Is there any method that can reset the expiration time of the refresh token or is it possible to generate a new refresh token?
