### ISSUE TITLE
[react-native] Customize authenticator wrapper component

### ISSUE THREAD

**Issue by ricardoribas** [aws-amplify/amplify-js#4549]
**Problem**
The **Authenticator** component used to handle authentication states in react-native is wrapped inside [SafeAreaView](https://facebook.github.io/react-native/docs/safeareaview). However, the component itself is not open to customisation. For instance, if we want to add attributes to the SafeAreaView or even add a custom wrapper, we are not able to do it easily.

**Proposal**
Add a prop called `wrapper` which is a rendered component. This particular property should be a **node**. By default it would use the SafeAreaView that is already included in the code.

**Comment by bhaskarmurthy** [comment]
Would like this as well - an example use I have is to customize the safeareainsets for navigation.
In general though - do we need SafeAreaView at all here? Why not just let the parent component of this view manage SafeAreaView if needed instead of forcing use here?

**Comment by mk-nickyang** [comment]
+1 for this.

`Authenticator` component should let user handle `SafeAreaView` on their own for custom child components, otherwise the extra paddings can be really annoying sometimes (e.g. when using `react-navigation` in App component).

Also, the `SafeAreaView` used by `aws-amplify-react-native` is imported from `react-native`, but it actually has a known bug (see https://github.com/react-native-community/react-native-safe-area-view#forceinset). The solution to this issue is either remove the `SafeAreaView` in `Authenticator` or replace it with the [react-native-community SafeAreaView](https://github.com/react-native-community/react-native-safe-area-view) and add `forceInset`.

Submitted a PR https://github.com/aws-amplify/amplify-js/pull/5375 so user can add a `container` prop to remove the `SafeAreaView` or customise the container wrapper component. The `container` prop actually already exists for the `Authenticator` component in `aws-amplify-react` (https://aws-amplify.github.io/amplify-js/api/interfaces/iauthenticatorprops.html#container), it's just missing for `aws-amplify-react-native`.

Example use will be like
```
<Authenticator
    container={({ children }) => (
        <View style={{ flex: 1, width: '100%' }}>{children}</View>
    )}
>
    <App />
</Authenticator>
```
