### ISSUE TITLE
Auth.currentSession not providing jwtToken for Unauthenticated users

### ISSUE THREAD

**Issue by VicFrolov** [aws-amplify/amplify-js#4561]
Hello,

 I have tried to rerun `amplify auth update`, and ensured that I selected unauthed users to have access: ` Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes`.

In the console:

```
"Possible Unhandled Promise Rejection (id: 1):
"No current user"
```

`Auth.currentCredentials` returns what appears to be a  valid `CognitoIdentityCredentials` object, currentSession throws an error saying no current user.

Below is my client setup

```
const url = awsconfig.aws_appsync_graphqlEndpoint;
const region = awsconfig.aws_appsync_region;
const auth = {
  jwtToken: async () =>
    (await Auth.currentSession()).getIdToken().getJwtToken(),
  type: awsconfig.aws_appsync_authenticationType,
} as AuthOptions;

const httpLink = createHttpLink({ uri: url });
const link = ApolloLink.from([
  createAuthLink({ auth, region, url }),
  createSubscriptionHandshakeLink(url, httpLink),
]);

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link,
});
```

Any suggestions?

Versions:
- Apple iPhone 11 Simulator and Device
- aws-amplify: 2.2.0

**Comment by davegariepy** [comment]
I dont use AppSync or `@auth` directive, so not sure exactly how this applies in your situation but the principles should be the same since it's still Cognito.

JWTs are obtained from a UserPool or third party identity provider like Facebook or Google.

IAM auth uses Identity Pools to issue temporary credentials and sign each request using AWS Sigv4. IAM auth can have `unauthenticated` role and `authenticated` roles, each with an IAM policy for permissions to use AWS resources (ie execute-api).

User Pools dont have a guest access feature so there is no JWT for the guest, the call is just blocked and an error returned saying not authorized. If you want public access but still with some protection you have to use AWS IAM / Identity Pool.

**Comment by elorzafe** [comment]
@davegariepy thanks for your reply!

@VicFrolov this clarify your question?

**Comment by VicFrolov** [comment]
Thanks for the reply @davegariepy ! The question is mainly around 

`Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) Yes` 

when configuring `amplify add auth`. this seems to imply that unauthenticated requests would still  work. Does this mean that I would need to set up two auths?

**Comment by davegariepy** [comment]
@VicFrolov yeah, I think this is where the `@auth` decorator comes in. I'm not sure how this works with the CLI or Appsync, though. Pretty sure you can specify `aws_iam` or `userpool`(?) with `@auth` to let Appsync know the permissions for each model or field.
