### ISSUE TITLE
SSR error "Not supported"

### ISSUE THREAD

**Issue by powerfulj** [aws-amplify/amplify-js#4576]
Hi,

I got an error when run the build for Server Side Rendering, error is "Not Supported".

The source code has a browser check which cause this issue.

package version is:

"@aws-amplify/auth": "2.1.1"

Thanks
CJ

**Comment by Amplifiyer** [comment]
@powerfulj can you try this https://github.com/aws-amplify/amplify-js/issues/4243#issuecomment-564553889 and see if that helps?

I believe the issue is that nextJs apps are using the `main` field of pacakge.json for entry point rather than `module` and so consumes the webpack bundles which are not compatible with nodejs (webpack does polyfill for nodejs process and doesn't have process.versions.node set). Hence overriding the browserOrNode() in your app (before executing the library) skips the pollyfills and return the right results i.e. isNode = true.

**Comment by powerfulj** [comment]
> @powerfulj can you try this [#4243 (comment)](https://github.com/aws-amplify/amplify-js/issues/4243#issuecomment-564553889) and see if that helps?
> 
> I believe the issue is that nextJs apps are using the `main` field of pacakge.json for entry point rather than `module` and so consumes the webpack bundles which are not compatible with nodejs (webpack does polyfill for nodejs process and doesn't have process.versions.node set). Hence overriding the browserOrNode() in your app (before executing the library) skips the pollyfills and return the right results i.e. isNode = true.

I changed my code by following the comment which works great! Tons of thanks mate.

Actually I'm not using NextJS but using Express that customized all the SSR settings.

Thanks again!
