### ISSUE TITLE
Receiving CORB warning for Pinpoint `_session.stop` event when navigating to new tab in Chrome.

### ISSUE THREAD

**Issue by jmpolitzer** [aws-amplify/amplify-js#4606]
**Describe the bug**
Receiving CORB warning for Pinpoint `_session.stop` event when navigating to new tab in Chrome.

**To Reproduce**
1. Create amplify (1.2.4) app using create-react-app (3.2.0) and set up Analytics following instructions in documentation.
2. Open in Chrome 78.
3. Navigate to new tab.
4. Return to tab in which the amplify app is running.
5. Observe CORB warning in the console.

<img width="1663" alt="Screen Shot 2019-12-19 at 9 03 35 AM" src="https://user-images.githubusercontent.com/5421419/71184487-71750580-223f-11ea-8db8-580f5c6bf09b.png">

**Additional context**
The `_session.stop` event, along with all other events, is received and recorded in Pinpoint as expected. The only issue is this CORB warning.

**Comment by sammartinez** [comment]
@jmpolitzer Are you experiencing with the latest version of `aws-amplify`? Please let us know. Thanks!

**Comment by sahaam** [comment]
I am still experiencing this issue with the latest version of aws-amplify. 

Looks like the issue happens because response header for url `https://pinpoint.${region}.amazonaws.com/v1/apps/${ApplicationId}/events` has `Content-Type: application/json`, but request header has `Content-Type: text/plain;charset=UTF-8` (due to navigator.beacon supports that). So here we have a mismatch of the Content-Type.
