### ISSUE TITLE
Expose a greater amount of Auth Hub Events, e.g., Cognito Token Refresh events

### ISSUE THREAD

**Issue by omkarv-amazon** [aws-amplify/amplify-js#4609]
**Is your feature request related to a problem? Please describe.**
It is not possible to subscribe to granular Auth events for processes handled by the Amplify Auth Module, other than the events currently exposed through [Hub](https://aws-amplify.github.io/docs/js/hub)

**Describe the solution you'd like**
It would be helpful if the Hub eventing system publishes a greater range of Auth related [Hub](https://aws-amplify.github.io/docs/js/hub) events.
Events that would be helpful:
- Cognito Auth Token Refresh
- AWS Federated Credentials Refresh
- OAuth sign in 'in progress' (i.e., for the OAuth Authorization Code flow, the amplify library is calling the [Cognito /TOKEN endpoint](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html)

**Describe alternatives you've considered**
Implicitly determining when there is a token refresh by storing an Auth Token locally, and checking if there is a difference in the Auth Token after calling an Amplify API, e.g. `Auth.currentSession()`

**Additional context**
N/A

**Comment by cantwelc** [comment]
Is there any update on this?

**Comment by cwomack** [comment]
Hello, @omkarv-amazon 👋. Apologies on the delayed response on this feature request, but wanted to get some clarity on what the specific use case for it might be.  

Given the time elapsed since this was created, [Hub](https://docs.amplify.aws/lib/utilities/hub/q/platform/js/) likely has a few more features that were added... but not specifically for the tokens/credential events that you've stated above.  Can you elaborate on how you're looking for them to be used?  Want to see if there's also possibly a workaround that could be provided.  Thanks!

**Comment by cwomack** [comment]
Reviewed with @omkarv-amazon internally and determined we can close this issue down due to the time that elapsed.  We'll reopen if any dependent projects have further needs for more Hub events than are currently offered out of the box.
