### ISSUE TITLE
Allow users to set default init options across all RestClient requests

### ISSUE THREAD

**Issue by dendle** [aws-amplify/amplify-js#4675]
**Is your feature request related to a problem? Please describe.**
amplify-js allows you to supply 'init' options to each API call (Please see myInit [here](https://aws-amplify.github.io/docs/js/api#get)). However, these options are only settable *per request*, with no global defaults settable anywhere.

My acutal problem is that when an API that i'm calling responds with a 403 status code, and no JSON body, the catch method in the promose gets given an error with no response information. So i'd need to set the response=true in the init call in every call.

**Describe the solution you'd like**
I think a good idea would be to implement something like the axios default settings to enable this.
Please see [global-axios-defaults](https://github.com/axios/axios#global-axios-defaults)

The initParams gets taken directly from the request call - perhaps defaults could be merged in [here](https://github.com/aws-amplify/amplify-js/blob/a811091e5bd5c22fee44ea9b4be503b6499b42ce/packages/api/src/RestClient.ts#L94)?

**Comment by elorzafe** [comment]
Thanks for the feature request @dendle I am looking on this now

**Comment by cwomack** [comment]
Hello, @dendle 👋. With the release of the latest major version of Amplify (aws-amplify@>6), this feature request is likely no longer needed due to axios being just a dev dependency at this point.  Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information on how to upgrade to the next major version of Amplify.

Feel free to reply back if you think there's further need for a feature to be implemented around this, and appreciate your patience on our replies here!
