### ISSUE TITLE
Object.assign is not a function

### ISSUE THREAD

**Issue by Prudhvi1357** [aws-amplify/amplify-js#4688]
Describe the bug
TypeError · Object.assign is not a function
../node_modules/@aws-amplify/cache/lib/StorageCache.js:37t.e

@param config - the configuration of the cache
--
  | */
  | function StorageCache(config) {
  | this.config = Object.assign({}, config);
  | this.cacheCurSizeKey = this.config.keyPrefix + 'CurSize';
  | this.checkConfig();
  | }

Smartphone (please complete the following information):

Device: Android Smartphones
OS: Android 5.1 or Android 6
Browser Chrome Mobile(79.0.3945.93)/ Chrome Mobile WebView
Additional context
It seems that it's only happening in Android 5.1 & 6 OS

**Comment by iartemiev** [comment]
Hey @Prudhvi1357 this seems to be related to the versions of JavaScript being run on those older versions of Android. 5.1 and 6 are 5 and 4 years old respectively at this point, and `Object.assign` has been widely supported for many years (as of ES6). 

Could you please tell us more about your use case with these older version of Android so that we can understand it better?
