### ISSUE TITLE
angular 9 with amplify authenticator UI

### ISSUE THREAD

**Issue by alexAlchemy** [aws-amplify/amplify-js#4744]
**Describe the bug**
I recently upgraded to angular 9 and after a previous issue with amplify and angular deactivated ivy. (I mention this for context in case somebody suggests I opt-out).

I tried using the amplify authenticator component and it won't render. Looking at the error and debugging in the console it seems to be failing here. 

![image](https://user-images.githubusercontent.com/32409073/72731287-545b8b80-3b8b-11ea-91a1-bca0fb9673e6.png)

componentHost is undefined.

Not sure if I'm missing something obvious or if this is an angular 9 issue.

**To Reproduce**
I set up a minimal repro from using ng new and then going through the aws amplify angular instructions on the main site. 

I've added the repro to github

https://github.com/alexAlchemy/aws-amplify-angular-min-repro

Thanks Alex

**Comment by pabloFuente** [comment]
Same exact error here. I've updated to Angular 9, deactivated Ivy and component will fail here because `componentHost` is undefined
![Selection_344](https://user-images.githubusercontent.com/15049534/74046976-da6f3300-49cf-11ea-9fc7-40a3a0952881.png)

**Comment by promobulls** [comment]
Same error, can anyone help?

**Comment by steevegldev** [comment]
I tried to investigate. I did not found why componentHost do not get the DynamicComponentDirective value.

I think it's because Angular 9 change the way Views work and that make Amplify Authenticate incompatible.

For my side, I will rollback to Angular 8 for now.

**Comment by muchrm** [comment]
i try to add ` {static: true}` in complied code in node_module it work, but it's should to migrate this library to angular > 8?

**Comment by bostondevin** [comment]
Broken for me as well with Angular 9

**Comment by cjardine** [comment]
@sammartinez Any progress on Angular support, both for v. 9 and Ivy?

**Comment by sammartinez** [comment]
@cjardine We have been working on a newer implementation of our UI Components as based on this [RFC](https://github.com/aws-amplify/amplify-js/issues/3279#issuecomment-589909938). This is currently in Preview and we are looking for feedback from the community on this. Please let us know what you think! I did test Angular 9 with this preview and it does work but was unable to test Ivy due to time constrains, if you have time to test and provide feedback it would be much appreciated !

**Comment by cjardine** [comment]
@sammartinez Appreciate the response, and I am eager to have this when it's ready. Unfortunately, I am not able to put the preview in as a test in our main application due to time, risk and testing constraints, but if I can and I find some time, I'll try it out on something less critical. What would be the best way to be informed of this release?

**Comment by wickstargazer** [comment]
Hi,
I think it is linked with this issue #4681 
Also linked with this PR #4963

**Comment by NL33** [comment]
HI guys. I'm trying to follow how amplify is working with ivy. Is it safe to say that, for a production app, I should NOT try to use Angular 9 (with Ivy) + Amplify for auth?

In that case, I'll stick with Angular 8 + Amplify Auth for now.

**Comment by eshacham** [comment]
I confirm. I had to downgrade to angular 8 to make amplify authentication ui component to work.

**Comment by sammartinez** [comment]
@NL33 i can state that Amplify doesn’t currently support Angular 9 and Ivy. As stated above, please downgrade to Angular 8 as we do support this.

**Comment by NL33** [comment]
Thank you. It's helpful to get that clarity. 

Right now, the docs just say, buried down: "Please also note that the AWS Amplify Angular components do not yet support Ivy." I recommend the team make this more clear--like at the top of the doc say that Amplify Auth does not yet work with Angular 9 with ivy, so it's recommended to downgrade to Angular 8 if you want to work with Amplify Auth.

**Comment by wickstargazer** [comment]
@sammartinez I still confirm that this fix resolves the ivy build issue
Fix dynamic rendering to support Angular 9 in --> #4963

**Comment by cedvdb** [comment]
Ivy and ng9 support would be more than welcomed. The angular team fixed the _spread issue, but there is still an issue with AmplifyIonic module that does something with the FormModule. 

Thing is ng9 also bumps the typescript version and so on so it's a bit annoying.

**Comment by wickstargazer** [comment]
Hi guys, i have published `@flowaccoun/aws-amplify-angular` version `4.2.11`

[@flowaccount/aws-amplify-angular](https://www.npmjs.com/package/@flowaccount/aws-amplify-angular)

Its working with angular 9 now, the issue with the PR here is the auto-build isn't working because of `yarn version` and I changed the way its packaged, so it will take time for them to publish

We need to use it now, so I took the liberty :)

Cheers

**Comment by cedvdb** [comment]
@wickstargazer did you make a pull request here for this ? so we can upvote it ?

**Comment by wickstargazer** [comment]
Yes indeed i did, its here
[Pull Request] (https://github.com/aws-amplify/amplify-js/pull/4963)

**Comment by krimple** [comment]
We have a client that we might use Amplify & Angular on - is Angular 9 / Ivy support moving forward or is the version above stable enough across all of Angular to get the job done?

**Comment by krimple** [comment]
Note - we ended up switching to the new official library
```
in package.json dependencies:
"aws-amplify": "^3.0.10",
"@aws-amplify/ui-angular": "^0.2.5",
```
We also decided NOT to use the Angular modules for now - just the core amplify Auth library and our own screens. No current problems with Angular 9 and this set above.  I was not aware of the new library until someone else mentioned it. But there is a migration guide here: https://docs.amplify.aws/ui/q/framework/angular (the old one was listed on the nav bar as "Legacy". HTH anyone who ran into this and was concerned. Looks like it works for us.

**Comment by YoshiDatoutou** [comment]
confirm. I had to downgrade to angular 8 to make amplify authentication ui component to work. this will block us from upgrading to angular 9, hopefully it resolve soon.

**Comment by ignaciofuentes** [comment]
I believe the issue is that you are still using the legacy npm package, which is not supported with Angular 9.

"Angular 9 is not supported in the legacy version of the Angular UI Components. If you app in using Angular 9, please see our new Angular UI Component package."

https://docs.amplify.aws/ui-legacy/q/framework/angular

**Comment by wahmd** [comment]
@wickstargazer thanks. just a suggestion: I was not able to use @import '~@flowaccount/aws-amplify-angular/theme.css'. Add if feasible.

**Comment by tannerabread** [comment]
This should be resolved now with new versions of the Angular Authenticator component. Please see [this comment](https://github.com/aws-amplify/amplify-js/issues/4681#issuecomment-672153203) on a similar issue that outlines all that has been done to remedy this issue
