### ISSUE TITLE
Use @aws-amplify/api with pure html/js

### ISSUE THREAD

**Issue by mkozjak** [aws-amplify/amplify-js#4778]
Is there a way to use the API package from aws-amplify in pure html/js?

What I'm trying to do is basically requesting API Gateway endpoints like this:
```html
<html>
        <header>
                <script src="node_modules/amazon-cognito-identity-js/dist/amazon-cognito-identity.min.js"></script>
                <script src="node_modules/aws-sdk/dist/aws-sdk.min.js"></script>
                <script src="node_modules/@aws-amplify/api/dist/aws-amplify-api.min.js"></script>
                <script type="text/javascript">
                    <... js code>
                    <... using AmazonCognitoIdentity works here>
                    <... and API isn't found here. Maybe it's exported like something else?>
        </header>
</html>
```

** Which Category is your question related to? **
API
** What AWS Services are you utilizing? **
Cognito, API Gateway

**Comment by mkozjak** [comment]
This also appears on page load: ```TypeError: undefined is not an object (evaluating 'new a.ConsoleLogger')```

**Comment by mkozjak** [comment]
Ended up using [cognitocurl](https://github.com/nordcloud/cognitocurl) and [Postman](https://www.getpostman.com).

```
cognitocurl --cognitoclient <client_id> --userpool <pool_id> --token
```
Add that token to `Bearer Token` type under `Authorization` in Postman.

Would be good to know how to use `aws-amplify-api.min.js` without all those magical frameworks, though.

**Comment by ericclemmons** [comment]
@mkozjak Yes, this is possible!

Our documentation is a good starting point for scaffolding the necessary build-step to get Amplify (and all of its dependencies) into a single bundle:
> https://docs.amplify.aws/start/getting-started/setup/q/integration/js#create-a-new-javascript-app

From there, you can make a few tweaks to export `API` onto the `window` object. 

If you already have a `webpack.config.js`, this comment covers the changes you'll need:
> https://github.com/aws-amplify/amplify-js/issues/4510#issuecomment-579961345

Otherwise, I've written up a solution on how to expose categories (e.g. `API`) with all of the necessary code (+ demo!) here:
> https://github.com/aws-amplify/amplify-js/issues/4829#issuecomment-584783688

The Amplify team adopted `amazon-cognito-identity-js` to continue maintaining it as a dependency of our project.  This package supports importing via a standalone `<script>` tag, but other categories (e.g. `API`, `Auth`) share dependencies, which require bundling (via webpack or similar).
> https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js#install-using-separate-javascript-file

**Comment by ameykshirsagar** [comment]
I was able to do it in this way. It works perfectly
```html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="./node_modules/aws-amplify/dist/aws-amplify.min.js"></script>
    <script>

        aws_amplify.Amplify.configure({
            // content of aws-exports.js
        });

        try {
            const user = aws_amplify.Amplify.Auth.signIn("<username>", "<pass>");
            console.log(user);
        } catch (error) {
            console.log('error signing in', error);
        }

        try {
            const { user } = aws_amplify.Amplify.Auth.signUp({
                username: "<username>",
                password: "<pass>",
                attributes: {
                    email: "<email>" // optional

                }
            });
            console.log(user);
        } catch (error) {
            console.log('error signing up:', error);
        }
    </script>
</head>
<body>
    
</body>
</html>`
