### ISSUE TITLE
No types when installed for Vue 1.1.2

### ISSUE THREAD

**Issue by adamAtDemarq** [aws-amplify/amplify-js#4790]
**Describe the bug**
no type definitions for official supported use of typescript however the project has typescript as a tag. Looks like great work and its a shame this isn't supported yet, any update on when this could be implemented?

**Comment by sammartinez** [comment]
@adamAtDemarq Thanks for the feedback on this. As you have found, we currently don't have type definitions contained within our `aws-amplify-vue` package. I'm marking this as a feature request in order to take this into consideration for the future. While we don't have an ETA on when this work will be completed, we do always want to empower people like yourself to contribute if you'd like. If you are interested in contributing, here is a link to [Local Development](https://github.com/aws-amplify/amplify-js/wiki/Local-Development) for `amplify-js`.

**Comment by calebpollman** [comment]
For those currently watching this ticket, Amplify UI has released a new package for Vue components: `@aws-amplify/ui-vue` (additionally, `aws-amplify-vue` is no longer maintained).

You can find the package [here](https://github.com/aws-amplify/amplify-ui) and the documentation [here](https://ui.docs.amplify.aws/vue), please let us know if it meets your needs!
