### ISSUE TITLE
Is it possible to key off of sign up events when using a federated sign in?

### ISSUE THREAD

**Issue by cmaycumber** [aws-amplify/amplify-js#4877]
** Which Category is your question related to? **

Auth, Hub

** What AWS Services are you utilizing? **

Cognito, Federated Identities

** Provide additional details e.g. code snippets **

We need to call a function that aliases the user to an anonymous id only a single time. This would ideally be called right after a sign-up but are having trouble determining the best way to handle this when using federated identities.

Are there any best practices for this? Or should we try to key off of something like the created date or reference to the user in our dynamo?

**Comment by kylegwalsh** [comment]
Federated sign-in's through amplify do not seem to provide any distinction between a sign-up (which creates a user in the userpool) and a sign-in.

Is there any way to detect a sign-up event using federated sign in, or is this information currently obscured?

**Comment by ericclemmons** [comment]
Rather than doing this in the UI, it sounds like you're looking for a custom Cognito Lambda trigger:
> https://docs.amplify.aws/cli/usage/lambda-triggers#cognito-lambda-triggers

This would allow your lambda to get access to the newly-created user and associate the anonymous id when first registered, similar to this trigger:
> https://docs.amplify.aws/cli/usage/lambda-triggers#add-user-to-group

I would need to know more about your specific use-case (and your proposed alternatives of keying off of dates) to help further.

**Comment by kylegwalsh** [comment]
Mixpanel recently rolled out a new feature the removed the need to alias users. Therefore, we were able to remove the need to key off the signup event.

However, before the change, we had to create a DynamoDB that tracked whether a user had already been aliased. Then, we would query that property during the "Sign In" to determine whether the user was actually "Signing Up" so that we could alias them.

Ideally, I imagine that the federated sign in would be aware of the fact that it is creating a user in the backend and make note of that in the frontend. We were using the amplify Hub to listen for the sign up event, but recieved a sign in event instead.

Regardless, our issue is solved. Just something to consider for future improvements.

**Comment by ericclemmons** [comment]
This is great feedback! I used to use MixPanel, so your example hits home :)

I was looking into our current list of events, and you're right: federated behaves misses the `signUp` event:
> https://docs.amplify.aws/lib/utilities/hub/q/platform/js#authentication-events

During the federation flow, Cognito Hosted UI is implicitly handling the sign-up event, so the app is only aware that the user has signed-in (via the `signIn` event).

At least for now, the best recommendation is to rely on lambdas (linked above) for that initial registration.  Any changes to the federation flow (firing `signUp` and `signIn`, or replacing `signUp` with `signIn`) would have to be considered with backwards compatibility.

Keep up the feedback!  I'll be raising this in our weekly discussions with the Cognito team.

**Comment by shaharkazaz** [comment]
@ericclemmons 
Is there any consideration in adding the `signUp` event to the federated flow? In my use case, I need to be aware of that in the UI.

We are using the lambda triggers for some logic but the UI needs to redirect to one place in the case of `signIn` and to another in case of `signUp`.

Any way I can achieve that using Cognito? maybe pass some custom response from the lambda trigger? or anything else you have in mind? this is blocking us 😞 

```
"@aws-amplify/auth": "^3.4.28",
"@aws-amplify/core": "^3.8.20",
```
