### ISSUE TITLE
S3Image isn't customisable enough

### ISSUE THREAD

**Issue by dmoskovtsov** [aws-amplify/amplify-js#4959]
**Is your feature request related to a problem? Please describe.**

Currently, it's hard to customise react implementation of S3Image. I faced these 3 problems so far: 

1. There is no way to pass 'alt' to the image. This is important for SEO. 
2. It's not obvious how to style img dom element using css styles. (theme={{photoImg: {}}}) is an answer)
3. There is no way to style div wrapper around that img element. Its style is currently hardcoded to containerStyle = { position: 'relative' } which does not always work for the design requirements one have. 

**Describe the solution you'd like**
I would propose to add three new props to the component: 

- containerProps:Object
- imageProps:Object
- overlayProps:Object

which would be passed to the corresponding dom elements. This would give flexibility to solve above-mentioned use cases, as well as others I'm not aware of, without need to change the library. 

I can potentially write the implementation if you're ok with the approach. 
Thanks.

**Comment by ahansson89** [comment]
Additional features that would be nice to have for this:

1. Have a loading indicator prop or "loadingDone" prop that passes a boolean value
2. Option for doing local caching of the image - especially useful in React Native apps

I may just end up writing this myself, but would prefer not to and stick to the framework as much as possible.

**Comment by ashika01** [comment]
@dmoskovtsov We are moving to new UI component implementation for storage. I am closing this issue, since the existing components will be going into maintenance and we are actively developing in the new implementation.

Read more - https://github.com/aws-amplify/amplify-js/issues/6104#issuecomment-656882695

@ahansson89 We are working on implementing the two for new components. I would keep an eye out for that.
