### ISSUE TITLE
How can I force a click on the Microphone button without the user having to click it

### ISSUE THREAD

**Issue by aravindkaws** [aws-amplify/amplify-js#4967]
** Which Category is your question related to? **
Interactions
** What AWS Services are you utilizing? **
Cognito, Lex

I'd like to be able to do a face auth and if a valid user is found, I'd like to simulate a click of the Microphone button without the user having to do so. How can this be done with the existing Chatbot component ?

**Comment by Ashish-Nanda** [comment]
@aravindkaws which platform are you using Web or React Native?

I've added this as a feature request. Could you provide more details with regards to what the API would look like.

Also let us know if you would like to put in a PR for this and we can help you with it.

**Comment by aravindkaws** [comment]
I am using React Web.
So this is a use case for having the Bot initiate the conversation with the client. There are use cases where the Client does not have to Initiate a conversation (like a Client approaching a character in a VR scene).  I was able to use the Lex PutSession API in the Chatbot.jsx to get this going. Do let me know how I can add a PR.

**Comment by stocaaro** [comment]
Hello @aravindkaws ,

Reading over you're request, I'm not quite clear on how this would work. I think it's possible to start using the users microphone if they have approved use for your webapp already.  The chatbot component you refer to has been deprecated and I'm not sure what the future is regarding a UI component for the Interaction category behavior. 

If your question is specific to this deprecated component and automating a click in that interface, I can redirect this request to the UI team. I'm not sure if there is work on the roadmap to build a new chatbot component, but this could be a feature request into any work that might be planned.

Since this component is deprecated, I would not recommend submitting a PR to support this behavior as there wouldn't be good support to get such a change reviewed and merged.

Thanks!
Aaron
