### ISSUE TITLE
AppSync : Sorting by String type should not be case sensitive

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-js#5042]
**Describe the bug**

Sorting with field of type `String` is case sensitive where the Uppercase letters are taking precedence of the lowercase letters.

**To Reproduce**

1. Create schema

```graphql
type SampleModel
  @model
  @searchable
  @auth(rules: [{ allow: public, provider: apiKey }, { allow: private }])  {
  id: ID!
  title: String
}
```

2. Insert sample data

```js
[
  {
    id: 1,
    title: 'This is upper case'
  },
  {
    id: 2,
    title: 'a lower case title'
  }
]
```

3. Execute the following query on **appsync console > queries**

```graphql
{
  searchTasks (
    limit: 999,
    sort: {
      field: title,
      direction: asc
    }
  ) {
    items {
      id
      title
    }
  }
}
```

4: See unwanted result:

```json
{
  "data": {
    "searchTasks": {
      "items": [
        {
          "id": "a2a7e0ce-d4b5-4f6b-bd34-a304f2cb8bec",
          "title": "This is a capitalized title"
        },
        {
          "id": "72eaf34b-de44-4f1c-a99b-aec757bea4ba",
          "title": "a non-capitalized title"
        }
      ]
    }
  }
}
```

**Expected behavior**

AppSync should sort String types in a non-case sensitive manner or if that is intended then it should provide a way to allow the developers to sort results in a non-case sensitive manner.

**Screenshots**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

We can verify this by changing the `direction` to `desc` and you'll get the following result:

```json
{
  "data": {
    "searchTasks": {
      "items": [
        {
          "id": "72eaf34b-de44-4f1c-a99b-aec757bea4ba",
          "title": "a non-capitalized title"
        },
        {
          "id": "a2a7e0ce-d4b5-4f6b-bd34-a304f2cb8bec",
          "title": "This is a capitalized title"
        }
      ]
    }
  }
}
```

Now lowercase take precedence which proves that it is case-sensitive.

**Sample code**

See above info

**Comment by kylejoeckel** [comment]
any update on this?

**Comment by casendler** [comment]
Also facing the same issue. Any resolution / work arounds?

**Comment by chrisbonifacio** [comment]
@casendler @kylejoeckel @aprilmintacpineda are you or anyone else still experiencing this issue?

I've reached out to the service team to clarify what the expected behavior should be. As of now, this might be a feature request as it suggests adding a toggle for case insensitive sorting.

I'm not personally experienced with OpenSearch, so this is an assumption based on a quick google search, but since it is a fork of ElasticSearch perhaps this issue is very similar to this stack overflow question:
https://stackoverflow.com/questions/22099906/unexpected-case-insensitive-string-sorting-in-elasticsearch

The answer to that question mentions that ElasticSearch sorts by capital letters first, then lowercase. Their use of an analyzer to achieve case insensitive may or may not be configurable through AppSync.

I'll provide an update once I hear back from the team. Thank you for your patience.

**Comment by kylejoeckel** [comment]
3 years later... lol no idea if this is still a problem
