### ISSUE TITLE
At what frequency is DataStore synchronized with the backend?

### ISSUE THREAD

**Issue by AndrewPrifer** [aws-amplify/amplify-js#5049]
** Which Category is your question related to? **
DataStore
** What AWS Services are you utilizing? **
AWS AppSync

How often is DataStore synchronized with the backend? Can we set maximum frequency somehow? Should we manually debounce writes to the database in case e.g. a note editor where you don't want backend requests to be made at every keystroke? Or can we update items as often as we want (it is asynchronous after all) and trust that it only synchronizes at reasonable intervals?

I want to implement a sort of auto-save feature where I want to persist state as often to the database as possible but I'm worried about the implications.

**Comment by undefobj** [comment]
DataStore is automatically synced with the cloud, the mental model is just work on the data and it takes care of everything for you. When your client has network connectivity this happens via GraphQL subscriptions. When the client is offline the missed items are written to a separate DynamoDB table as a change journal so that upon coming back online only the deltas go down to the client. More information can be found here: https://aws-amplify.github.io/docs/js/datastore#how-it-works

**Comment by AndrewPrifer** [comment]
@undefobj so it synchronizes with the cloud as often as it can? I know how it works, I just wasn’t sure if there’s some extra request batching logic we can rely on.

**Comment by undefobj** [comment]
Yes that's accurate. No batching is necessary.
