### ISSUE TITLE
How to configure and use AWS Amplify for Cognito user pool with SAML? Is it through "Auth.federatedSignIn()" or "Auth.signIn()"

### ISSUE THREAD

**Issue by angesh3** [aws-amplify/amplify-js#5087]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito "User Pool -> SAML (ADFS)"
** Provide additional details e.g. code snippets **
I am receiving token with the following url.
https://rapxxxx.auth.us-west-2.amazoncognito.com/authorize?idp_identifier=sandxxxxom&response_type=token&client_id=7sjs3u0xxxx&redirect_uri=http://localhost:8100

#my code:

export interface AuthCodeDeliveryDetail {
  authState: AuthState,
  codeDeliveryDetail: CodeDeliveryDetail
}

export function init(config: Config): void {
  Amplify.configure({
    Auth: {
      region: config.auth.region,
      userPoolId: config.auth.userPoolId,
      redirectSignIn: 'http://localhost:8080/',
      redirectSignOut: 'http://localhost:8080/',
      responseType: 'code',
      identityPoolId: 'sandpit-2',
      userPoolWebClientId: config.auth.userPoolWebClientId,
      authenticationFlowType: config.auth.authenticationFlowType,
    }
  });
  console.log("auth init");
}

export async function fedSignIn(username: string, provider: string,id_token: string, expires_in: string): Promise<AuthState> {
  console.log("I am here in fedSignIn");
  pendingAuth = null;

  let status: AuthState;
  try {
    const authResponse = await Auth.federatedSignIn(
      'LoginWithAmazon',
    {
        token: id_token,
        expires_at: parseInt(expires_in) * 1000 + new Date().getTime() // the expiration timestamp
    },
    { 
        name,
        email:username,
    });
    console.log("authResponse");
    console.log(authResponse);

      status = AuthState.AUTHENTICATED;
  } catch (err) {
      console.log(err)
      return Promise.reject(new Error('Failed to sign in.'));
  }

  return status;
}

Error:
![image](https://user-images.githubusercontent.com/51677134/76588861-6da2f900-64a5-11ea-81b0-d4a7bb84c22a.png)

**Comment by mrgoos** [comment]
@angesh3 - were you able to resolve this?

**Comment by askurat** [comment]
Did anyone get this working or some type of workaround?

**Comment by amhinson** [comment]
@angesh3 Were you able to solve your issue? 

From the code snippet you provided, you are actually trying to federate with Identity Pools instead of User Pools ([docs](https://docs.amplify.aws/lib/auth/advanced/q/platform/js#identity-pool-federation)). If you would like to authenticate with User Pools instead, you don't need to pass the object with the token as the 2nd argument to `federatedSignIn`, i.e. just pass the provider: `Auth.federatedSignIn({provider: 'LoginWithAmazon'})` ([docs](https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-frontend)).
