### ISSUE TITLE
How to query datastore with array of ID's with single request not array of requests

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-js#5098]
**Which Category is your question related to?**
Datastore

**What AWS Services are you utilizing?**
Cognito, AWS AppSync, Datastore

**Provide additional details e.g. code snippets**
I have product schema like this.
```
type Product @model 
  @auth(rules: [ {allow: private} ]) {
  id: ID!
  name: String!
 }
```
I have array of product ID's and I want to fetch only those 

```
try {

        const originals = await DataStore.query(Product, c => c.id('eq', productIDArray[0]).or(c => c.id("eq", productIDArray[1])))

        console.log(originals)

    } catch (err) {

        console.error(err)
    }
```
I tried another solution
```
async function failAttempt() {
    
    const idArray: string[] = ['16d34702-3447-405d-bff9-45bd62691615', 'ce9eb336-6c47-4ffd-86b4-ebebfafb9c32']

    const funcArray: Function[] = idArray.map(id => (c:any) => c.id('eq', id))

    try {

      const originals = await DataStore.query(Product, funcArray.join('.or'))

      console.log(originals)

    } catch (err) {

      console.error(err)
    }
  }
```
result is undefined

**Comment by BearFRA** [comment]
Same question. How to query with multiple IDs?

**Comment by ericclemmons** [comment]
Based off of https://docs.amplify.aws/lib/datastore/data-access/q/platform/js#query-with-predicates, I tested the following successfully:

```js
const ids = [
	'3f8609f8-622f-4350-8469-FOO',
	'75e76906-7fdd-4167-901d-BAR',
];

DataStore.query(Post, (c) =>
	c.or((c) => ids.reduce((c, id) => c.id('eq', id), c))
).then((results) => {
	console.log('Matching IDs', results.length, results);
});
```

```console
Matching IDs 2 
(2) […]
​
0: Object { title: "FOO", status: "ACTIVE", rating: 1, … }
​
1: Object { title: "BAR", status: "ACTIVE", rating: 1, … }
​
length: 2
```


The trick here is that `c.id('eq', id1).id('eq', id2)` has an implicit _and_, so wrapping it in `c.or(c => ...)` resolves it.  (That's why I used `.reduce` to chain the predicates, whereas `.map` won't work)


Note that, if `ids` is empty (`[]`), then this acts like `DataStore.query(Post)` and returns all `Post`s.
