### ISSUE TITLE
Can I change pre-authentication signUp phone_number?

### ISSUE THREAD

**Issue by johnmesotech** [aws-amplify/amplify-js#5114]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito

Cognito uses SMS to verify phone_number during signUp() and signIn(). Can the Amplify library be used to fix the signUp() case where a user provided a valid but incorrect phone_number (simple typo or a land-line number)?

.updateUserAttributes() seems to require a user already be authenticated. Calling signUp() with the corrected attribute complains that the username is taken from the failed attempt.

It looks like I have to write a lambda for the backend that deletes the erroneous signUp() and the frontend needs to signUp() again. Is that right?

**Comment by sammartinez** [comment]
@johnmesotech Apologizes for the late response to your question on this. This is by design that you will need to authenticate in order to change a users wrong phone number. Since Amplify uses Cognito as a pass through to the service, I would advise to open a feature request with the Amazon Cognito team via their [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173)
