### ISSUE TITLE
Multi-Auth using Multiple Clients with NextJs

### ISSUE THREAD

**Issue by connorrusso** [aws-amplify/amplify-js#5121]
I'm using Next.js and am trying to figure out best practice for unauthenticated and authenticated access with SSR.

I was able to successfully use this [with-apollo next.js example](https://github.com/zeit/next.js/tree/canary/examples/with-apollo ) to create an HOC that allows me to make queries using a client with API auth on pages that will be server side rendered.

I got it working with CRA, but I can't find an example using Next.js with multiple Apollo clients as suggested in the [amplify docs](https://aws-amplify.github.io/docs/js/api#aws-appsync-multi-auth-1) and am not sure how to go about integrating them with the Authenticator components that only work client side.

**Comment by sammartinez** [comment]
@locostudioco We currently don't have support for Next.js or Sever Side Rendering within Amplify JS. However, I am going to mark this as "help wanted" in order to see if someone from the community has done a similar implementation to your own. Can you please add your reaction to this current [Feature Request we have for SSR](https://github.com/aws-amplify/amplify-js/issues/1613)

**Comment by ericclemmons** [comment]
This is being worked on, so re-opening for tracking purposes.

**Comment by aniljaiswal** [comment]
This is great @ericclemmons . I have been waiting for NextJS support within the AWS Amplify ecosystem.
