### ISSUE TITLE
How to get IdentiyID all users from Admin Queries

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-js#5177]
**Which Category is your question related to?**
Auth, Storage

**What AWS Services are you utilizing?**
Cognito, AWS AppSync, Lambda, Storage

**Provide additional details e.g. code snippets**
as mentioned in #2203 I need each users `IdentityID` to just to read `protected` images stored in S3.

It also mentions that you can get current user's `IdenitityID` by 
```
const cred = await Auth.currentCredentials()

console.log('Identity Id', cred.identityId)
```
But how do I get `IdentityID` after I `listUsers` from admin queries?

**Comment by kylekirkby** [comment]
Any update on this? I also need to get the users identity id... I can't retrieve a users protected file from s3 without it...

**Comment by myfairshare** [comment]
I'm wondering about this also, in my case users upload a pdf file to the protected folder, but if I want users to be able to let other users view these docs then I need their identityId.  Otherwise I could use public but I dont want to use public.  Is this something I could do in my statements.  Or should I save the users identityId to my user model and go about it this way, thank you.

**Comment by silasmahler** [comment]
Any updates on this?

**Comment by ingwinlu** [comment]
It is really a shame there is no easy way to do this. Retrieving the identityId ranges from a chore to downright unpractical.

**Comment by hkjpotato** [comment]
Does the list-identities call help to address the issue? https://docs.aws.amazon.com/cli/latest/reference/cognito-identity/list-identities.html

It does not provide you the 1-1 mapping between a user in user pool and its identity id in identity pool, but it can help polling for all the identities (paginated) in an identity pool.

**Comment by abdallahshaban557** [comment]
Hi @apoorvmote - does the solution mentioned by @hkjpotato provide you with what you need? This might be something we should expend on our admin APIs provided by the CLI as well. https://docs.amplify.aws/cli/auth/admin/#admin-queries-api

**Comment by soulcubby** [comment]
I'm surprised that this is 2 years old. I am using Cognito. My use case is that User A has uploaded an asset to S3 and User B, related to User A, needs to access it. Do I understand correctly that I need to track the IdentityID of every User and check for permissions at the application-level in order to accomplish that?
