### ISSUE TITLE
Deleting optional string doesn't work with Datastore

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-js#5206]
**Describe the bug**
I save image on S3 and the url for the image on Dynamodb with optional String. When I delete image I tried to set it to undefined and I get following error
`Field imageKey should be of type string, undefined received. undefined`

**Amplify CLI Version**
4.17.1

**To Reproduce**
1. `npx create-react-app test --use-npm --template typescript`
1. `amplify init`
1. `amplify add auth` default everything
1. `amplify add api` Then add following schema
```
type Product @model 
  @auth(rules:[ 
    {allow: owner}
  ]) {
  id: ID!
  owner: String!
  name: String!
  imageKey: String
}
```

Then I had image url saved in `imageKey` Now I deleted the image so I tried to set `imageKey` to undefined
```
const original = await DataStore.query(Product, id)

const results = await DataStore.save(
            Farmer.copyOf(original, updated => {updated.imageKey = undefined})
        )
```
I got following error
`Field imageKey should be of type string, undefined received. undefined`

**Expected behavior**
It should delete the key and set it as undefined 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 with Windows WSL2
 - Node Version. 12.16.1

**Additional context**
I also tried with setting imageKey to '' string with nothing I also got another error. I will post it soon.

**Comment by wei** [comment]
I was able to reproduce this issue. It happens when `copyOf` is called. 
Minimal example repo: [wei/amplify-js-5206](https://github.com/wei/amplify-js-5206) [[snippet](https://github.com/wei/amplify-js-5206/blob/master/src/App.tsx#L29-L31)]

![image](https://user-images.githubusercontent.com/5880908/96820902-ed5a5400-13f4-11eb-8c62-c87c4451a3ca.png)

It's clearly not required, however, it still failed validation:
![image](https://user-images.githubusercontent.com/5880908/96820459-07dffd80-13f4-11eb-876d-980bc1fa44c0.png)

Relevant lines in `datastore.ts`:
https://github.com/aws-amplify/amplify-js/blob/96fda2ae7ef480c1c19030fb576f2c0559eb1aca/packages/datastore/src/datastore/datastore.ts#L282-L286

A fix would be changing line 282 to
```js
} else if (isRequired && typeof v !== jsType && v !== null) { 
```

cc/ @iartemiev

**Comment by ltaljaard** [comment]
Hello, when roughly are you expecting to release this fix and would it then be in the stable release or what can i do to get the fix asap?

**Comment by iartemiev** [comment]
@ltaljaard we'll verify and test the fix internally and then will release it shortly thereafter.

**Comment by ltaljaard** [comment]
@iartemiev Thank you, may i also suggest to remove the to-be-reproduced tags for this #5206 and potentially #6744 and #6453, seeing that this issue has now been successfully reproduced.

**Comment by wei** [comment]
> I tried it regardless. I got this error.
> `Type 'null' is not assignable to type 'string | undefined'`

You can set `"strictNullChecks": false,` in `tsconfig.js` which will allow you to set it to null.

**Comment by wei** [comment]
> I tried it regardless. I got this error.
> `Type 'null' is not assignable to type 'string | undefined'`

@apoorvmote You can set `"strictNullChecks": false,` in `tsconfig.js` which will allow you to set it to null.

**Comment by wei** [comment]
@apoorvmote @ltaljaard Thanks for the issue!

The fix has been merged 🎉 ! Please try it with `aws-amplify@unstable` for now and feel free to comment if you have any questions.
