### ISSUE TITLE
DataStore | Not working with Vue.js subscribe from other device mutation

### ISSUE THREAD

**Issue by r3-yamauchi** [aws-amplify/amplify-js#5223]
** Which Category is your question related to? **
Amplify DataStore with Vue.js
** What AWS Services are you utilizing? **
AWS AppSync, DynamoDB, Cognito User Pools.
** Provide additional details e.g. code snippets **
```
    this.sub = DataStore.observe(ShoppingListItem).subscribe(msg => {
```
https://github.com/r3-yamauchi/amplify-shopping-list-vue/blob/master/src/views/Home.vue#L59

I am trying to use Amplify DataStore with Vue.js.
Mutations on DataStore are synchronized to DynamoDB.

But, I can't receive operations performed from other devices or browsers.

It works as expected in React and Angular, but not in Vue.
What should I do ?

**Comment by r3-yamauchi** [comment]
I tried this on Node.js v12.13.0 on Windows 10 and v10.16.0 on Ubuntu 18.04.
But it doesn't work in any of them.

**Comment by ashika01** [comment]
@r3-yamauchi I doubt it would work with node.js since we use local storage indexedDB. However looks like subscribe is working as expected. So I am closing this issue. If you encounter an issue, let us know.

Also, feel free to ask the community on any questions you have in our discord channel - https://discord.gg/Px5YVfQ
