### ISSUE TITLE
Auto filled username and password on login shows "Username cannot be empty" in firefox

### ISSUE THREAD

**Issue by satishmolletipipra** [aws-amplify/amplify-js#5254]
I am using angular with amplify. All works but in firefox when username and password are autofill shows username and password cannot be empty. in chrome it is working fine. some one logged the same issue in following url https://github.com/aws-amplify/amplify-js/issues/4180 but i did't get any solution from that.

**Comment by sammartinez** [comment]
@satishmolletipipra Can you provide us more information on your environment? Please running the follow command so we are able to troubleshoot: 

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

**Comment by satishmolletipipra** [comment]
Hello @sammartinez please find environment information

 System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 11.30 GB / 15.91 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
  npmPackages:
    angular5-csv: ^0.2.11 => 0.2.11
    apollo-client: ^2.6.2 => 2.6.4
    aws-amplify: ^1.1.28 => 1.2.4
    aws-amplify-angular: ^3.0.3 => 3.1.4
    aws-appsync: ^1.8.0 => 1.8.1
    bootstrap: ^4.2.1 => 4.3.1
    codelyzer: ~3.2.0 => 3.2.2
    core-js: ^2.4.1 => 2.5.0
    enhanced-resolve: ^3.3.0 => 3.4.1
    font-awesome: ^4.7.0 => 4.7.0
    graphql-tag: ^2.10.1 => 2.10.1
    hammerjs: ^2.0.8 => 2.0.8
    jasmine-core: ~2.6.2 => 2.6.4
    jasmine-spec-reporter: ~4.1.0 => 4.1.1
    jquery: ^3.4.0 => 3.4.1
    karma: ~1.7.0 => 1.7.0
    karma-chrome-launcher: ~2.1.1 => 2.1.1
    karma-cli: ~1.0.1 => 1.0.1
    karma-coverage-istanbul-reporter: ^1.2.1 => 1.3.0
    karma-jasmine: ~1.1.0 => 1.1.0
    karma-jasmine-html-reporter: ^0.2.2 => 0.2.2
    ng2-dragula: ^2.1.1 => 2.1.1
    ng4-loading-spinner: ^1.2.3 => 1.2.3
    ngx-cookie-service: ^2.2.0 => 2.2.0
    ngx-image-cropper: ^1.4.1 => 1.4.1
    ngx-print: ^1.2.0-beta.3 => 1.2.0-beta.3
    popper.js: ^1.14.7 => 1.15.0
    primeflex: ^1.0.0-rc.1 => 1.0.0-rc.1
    primeicons: ^1.0.0 => 1.0.0
    primeng: 5.2.7 => 5.2.7
    protractor: ~5.1.2 => 5.1.2
    rxjs: ^5.5.2 => 5.5.12
    ts-node: ~3.0.4 => 3.0.6
    tslint: ~5.7.0 => 5.7.0
    typescript: 3.3.3333 => 3.3.3333
    zone.js: ^0.8.14 => 0.8.16

**Comment by satishmolletipipra** [comment]
@sammartinez  Can you please help me onthis.

**Comment by alertme-edwin** [comment]
I'm having the same issue using Amplify with Vuetify.  Firefox produces the "Username cannot be empty" message, or 

```
[Vue warn]: Error in v-on handler: "TypeError: obj is null"

found in

---> <SignIn>
       <Authenticator>
         <Welcome> at src/components/Welcome.vue
           <VApp>
             <App> at src/App.vue
               <Root>
```

in the console.

When I attempt to log in using Chrome, the "Confirm Sign In" dialog is shown for entering the MFA code, but no code is sent.

    aws-amplify: ^3.0.9 => 3.0.9 
    aws-amplify-vue: ^2.1.1 => 2.1.1 
    aws-sdk: ^2.333.0 => 2.478.0
    vue: ^2.6.10 => 2.6.10
    vuetify: ^2.2.3 => 2.2.3

**Comment by alertme-edwin** [comment]
The issue with the invalid user session turned out to be an unrelated bug.  I was seeing errors like this in the console:
```
warning  in ./node_modules/@aws-sdk/signature-v4/dist/es/cloneRequest.js

"export '__spreadArrays' was not found in 'tslib'
```
(which was more obvious when turning on `window.LOG_LEVEL = 'DEBUG'` in the app).  For the benefit of future searchers, I fixed this by running `npm update --depth 9 tslib`.  (Setting the depth to `999` caused the process to hang, and not specifying the depth caused npm to make no changes).

So the remaining problem is still the "Username cannot be empty" message in Firefox (and not Chrome).  This seems to be due to the way Firefox auto-fills the username and password boxes, with it perhaps not triggering some expected event on the input boxes (or triggering an event at a time the library doesn't expect).

As a **workaround**, if you place the text cursor in the username field and press an arrow key, the Sign In button then works as expected.  Also, for the record, the problem seems to occur whether the Amplify is configured with `usernameAttributes` in the `authConfig`, or `key: 'username'` in the `signUpFields` to indicate the username field.

**Comment by satishmolletipipra** [comment]
@alertme-edwin Still the issue is there. do you have any solution for the same.

**Comment by alertme-edwin** [comment]
@satishmolletipipra You may be interested in another workaround I've come up with, which seems to prevent the "Username cannot be empty" error even if the user doesn't press any keys in the username/password input fields.

The details of the solution will obviously depend on which framework or libraries you use, but in Vue it involved a method like this:
```javascript
    helpFirefox: function () {
      const event = new KeyboardEvent('keyup', {
        key: 'ArrowRight'
      })
      const firstInputNode = this.$el.querySelector('input')
      if (firstInputNode) {
        firstInputNode.dispatchEvent(event)
      }
    },
```
This method has to be called when the page loads (or when the "sign in" form appears), but unfortunately that's not the only case that needs to trigger the method.  When the form appears, it is possible to click through to the "sign up" form instead, and then back to the "sign in" form.  Fortunately, Amplify fires an event when these changes happen, however there is a race condition such that calling the helper function immediately upon registering the event is too early.

To work around the timing problem, I used the following code:
```javascript
  mounted () {
    const onSignIn = this.helpFirefox
    AmplifyEventBus.$on('authState', function (data) {
      if (data === 'signIn') {
        requestAnimationFrame(() => {
          requestAnimationFrame(() => {
            onSignIn()
          })
        })
      }
    })
  },
```
which is based on an idea I found in a bug report in the VueJS project (#9200).  I don't know if the problem is specific to Vue-based web apps, nor if the solution is limited to such apps, but I'd be interested to know whether something like this works for you.

**Comment by satishmolletipipra** [comment]
@alertme-edwin We are using amplify angular. this is not working for me.

**Comment by satishmolletipipra** [comment]
@sammartinez Thanks for the response. please let me know whether the latest amplify fixed the "Username cannot be empty" in firefox issue? if yes then i will update the amplify version.

**Comment by sammartinez** [comment]
> @sammartinez Thanks for the response. please let me know whether the latest amplify fixed the "Username cannot be empty" in firefox issue? if yes then i will update the amplify version.

Correct, in the newer implementations of our [Angular UI Components](https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular) the firefox issue is resolved. Will leave this open for you to test.
