### ISSUE TITLE
PushNotification Token not refreshing on Android

### ISSUE THREAD

**Issue by tanguy-roberjot** [aws-amplify/amplify-js#5261]
**Describe the bug**
I implemented PushNotification with amplify as described in the documentation and it's working well, but after few days using my app, i got an "Unregistered or expired token" error in Android while sending Push Notification. It seems that the token has expired and the endpoint is not updating with the new one. The only way that make it works again is uninstalling and installing the app, to get a new token and update the endpoint.

I was investigating and i've seen that the service used in Android (FirebaseInstanceIdService) is deprecated and we should be overriding onNewToken in FirebaseMessagingService instead of override onTokenRefresh of FirebaseInstanceIdService (see sample code)

Maybe it is the cause of this issue. Did anyone experienced it too ?

**To Reproduce**
wait some days after using android app using AWS pinpoint push notifications and check if notification is sent successfully

**Expected behavior**
If the token expires it should refresh for push notifications to continue working.

**Sample code**
This part shouldn't exist anymore:
```
<service
             android:name="com.amazonaws.amplify.pushnotification.RNPushNotificationDeviceIDService">
             <intent-filter>
                 <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
             </intent-filter>
</service>
``` 

And we should override onNewToken this way in com.amazonaws.amplify.pushnotification.RNPushNotificationMessagingService:

```java
public class FCMListenerService extends FirebaseMessagingService {

    /**
     * When newtoken is generated. Save and register FCM with this    token
     */
    @Override
    public void onNewToken(String s) {
        super.onNewToken(s);
        startService(new Intent(this, SaveFCMIdService.class));

    }
```

Finally get the refreshed token this way : 

```java
FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(instanceIdResult -> {
          try {
              String refreshedToken = instanceIdResult.getToken();
          } catch (Exception e) {
              Timber.e(e.getMessage());
          }
      });
```

**Comment by ajpaulingalls** [comment]
I'm seeing this too.  sigh...

**Comment by ArionMiles** [comment]
This is still happening. A day or two later the token is expired and I have to re-register the endpoint. Is there a way to automatically refresh the token in the background periodically?

**Comment by manueliglesias** [comment]
I am reopening this and labeling it as a bug,

As @tanguy-roberjot mentioned, we are using a [now deprecataded class and method](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService.html#onTokenRefresh()).

https://github.com/aws-amplify/amplify-js/blob/e1d122bec0fb67eab0a696ee6e0ffa976631e4f0/packages/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/RNPushNotificationDeviceIDService.java#L41

Guidance seems to be to:

> In favour of overriding onNewToken in FirebaseMessagingService. Once that has been implemented, this service can be safely removed.

https://github.com/aws-amplify/amplify-js/blob/e1d122bec0fb67eab0a696ee6e0ffa976631e4f0/packages/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/RNPushNotificationMessagingService.java#L51

**Comment by amhinson** [comment]
Hey everyone! I'm looking into this, but it seems like it'll take a week or two to fully validate any changes that I'm making based on the reproduction steps provided so far, so bear with me 🙂 

However, in my initial testing, here is what I'm seeing:

The Firebase Cloud Messaging [docs](https://firebase.google.com/docs/cloud-messaging/android/client#sample-register) say that clearing the app data (among other actions) will invalidate a token. I know this isn't exactly the same thing as the token expiring on its own, but its a start. After doing that, I do see a new token created each time starting up the app from the `onRegister` handler. However, this also creates a new endpoint since there isn't an existing one in the cache (https://github.com/aws-amplify/amplify-js/blob/main/packages/analytics/src/Providers/AWSPinpointProvider.ts#L606-L620)

I know clearing the data for the app on the device also removes the cache, which is why a new endpoint is created automatically, but I am curious:
- Are any of you are seeing additional endpoints being created for a device when you see the "Unregistered or expired token" error?

**Comment by amhinson** [comment]
Update: I successfully sent a push notification to the Android device after not opening the app for 3 days. Also, a subsequent push notification was successful after opening the app. I did not see the `onRegister` handler called (as expected).

I will try this test again in a few days, unless someone else finds a quicker solution for reproducing the issue.
