### ISSUE TITLE
Auth.verifyTotpToken returning NotAuthorizedException and stopping new users from setting up TOTP

### ISSUE THREAD

**Issue by charleswduk** [aws-amplify/amplify-js#5271]
**Summary:** 
Auth.verifyTotpToken returns a {code: "NotAuthorizedException", name: "NotAuthorizedException", message: "Invalid session for the user."} error when trying to set up MFA for a new user.

**Detail:**
I have set up a sign in function as described in the Amplify documentation [here](https://aws-amplify.github.io/docs/js/authentication#sign-in). 

When the _challengeName_ equals _MFA_SETUP_, I generate a TOTP QR code without a problem and get the user to submit the code in order set up MFA (as described in the Amplify docs [here](https://aws-amplify.github.io/docs/js/authentication#enabling-totp)).  

To do this, this _confirmTotp_ function is called:

```
confirmTotp = async() =>{

    this.setState({ error: '' }) //Resets error in state

    const { username, password, totpCode } = this.state //Extract these from state

    try {

      const totpUser = await Auth.signIn(username, password); //Create a new CognitoUser

      try{

        const verifyTotp = await Auth.verifyTotpToken(totpUser,totpCode); //Pass the CognitoUser to verifyTotpToken along with the code

        try{

          const setTotp = await Auth.setPreferredMFA(totpUser, 'TOTP'); //Set the preferred MFA type

          // ... 

        }catch(err){

          this.setState({ error: err });

        }

      }catch(err){

       this.setState({ error: err }); 

      }

    }catch (err){

      this.setState({ error: err });

    }

  }
```

It seems like Auth.verifyTotpToken will only accept a fully authenticated CognitoUser, but if this is the case, then how are new users supposed to set up TOTP when the Cognito User Pool is configured to _require_ MFA for all users? Under these circumstances, new users can never authenticate without TOTP being set up and TOTP cannot be set up without new users having authenticated - catch 22? And how is the Sign In function [shown in the Amplify docs](https://aws-amplify.github.io/docs/js/authentication#sign-in) ever meant to work?

Hope I'm missing something basic here. Many thanks in advance for any help!

**Comment by alex-lehan-bloom** [comment]
I've also run into this issue. Is anyone else seeing this. The verification of TOTP won't work because the Cognito user is not yet signed in.

**Comment by ecmascriptguru** [comment]
@sammartinez I got the same issue here.

**Comment by jquesada2016** [comment]
I was facing the same issue, but I figured it out, in case anybody runs into the same thing. You have to make sure that the same user session that was used to initiate the MFA is the same one you pass in to `verifyTOTPToken`.

**Comment by cafesao** [comment]
If you are experiencing the same problem...I have the solution.

After spending 2~3 hours with my team, we found out that we were doing it wrong.

What the flow should look like (User is registered and will be the first login)


`const user = await Auth.signIn(username, password);`

This `user` you must pass on through the entire Auth process, if you have a component for Totp, then pass on the `user` to this component.

With this, the user will have to enter the `setupTOTP`, so that it generates the code for the QR Code.

![image](https://user-images.githubusercontent.com/49770350/182957825-f686e9f3-f0d2-4527-88d9-5f6779b9ed91.png)


The user will take his cell phone or BitWarden, add the QrCode and get the generated code.

With this, the user must enter it, and pay close attention.

You must call `verifyTotpToken`, passing the user (which is the same user as the signI) + Code that the user entered.

After that, the user decides to log off.

Now comes the magic and what 99% of the people get wrong.

From this second login on, when you get to this TOTP part, you should not call `setupTOTP`, but you already know this.

What you don't know is that you **MUST NOT CALL** `verifyTotpToken` **BUT** `confirmSignIn`. 🤯🤯 

![image](https://user-images.githubusercontent.com/49770350/182957672-e80af2a0-9ac6-47f5-8ffb-5e64bc4112d3.png)


When calling the confirmSignIn, you must pass the user object + code + TOTP Type (SMS_MFA or SOFTWARE_TOKEN_MFA)

And everything will work perfectly!

And believe this is in the Doc ksksksks, in this part [here](https://docs.amplify.aws/lib/auth/mfa/q/platform/js/#sign-in-with-custom-auth-challenges). But it is not explicit.

You are welcome for solving hours of suffering!

**Comment by abdallahshaban557** [comment]
Thank you for providing this walkthrough @cafesao. I have created an issue in our documentation repo so that we can improve the experience of building TOTP with Amplify Javascript!

**Comment by chakafasano88** [comment]
@cafesao THANK YOU!!! Last 48hours been banging my head. The documentation is NOT CLEAR. You saved me.
