### ISSUE TITLE
Support sending events data to multiple providers for Analytics

### ISSUE THREAD

**Issue by ayush987goyal** [aws-amplify/amplify-js#5329]
**Is your feature request related to a problem? Please describe.**
I want to send the events data to Pinpoint and Kinesis. Currently this is not supported. We can only send to one provider.

**Describe the solution you'd like**
Amplify Analytics can support sending the data to all the configured providers instead of just one.

**Additional context**
I want to take advantage of various features of Pinpoint (like demographics, Funnels etc.) along with sending the data to Kinesis to be consumed in QuickSight eventually.

**Comment by Amplifiyer** [comment]
This is currently supported by providing a provider option in the `Record` API call of Analytics.

https://github.com/aws-amplify/amplify-js/blob/a53f3510ca2a3d48a9fa5c1937fe5b748b934be2/packages/analytics/src/Analytics.ts#L232-L235

You'll have to call Anlaytics.record twice, one for each provider, and that is expected since input format differs between providers. See below for an example

* Pinpoint
```
  Analytics.record({
    name: "albumVisit",
    attributes: {
      artist: "Eminem"
    },
    metrics: {
      minutesListened: 30
    },
    immediate: true
  })
```
* Kinesis
```
  Analytics.record(
    {
      data: {
        name: "albumVisit",
        attributes: {
          artist: "Eminem"
        },
        metrics: {
          minutesListened: 30
        }
      },
      streamName: "devoastream"
    },
    "AWSKinesis"
  )
```
