### ISSUE TITLE
Consecutive Mutations Fail

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-js#5373]
**Describe the bug**
When I try to mutate an object, and then mutate it again with different data, the object does not change. 
The update mutations operations, on all my models, are nonfunctional.

**To Reproduce**
1. npx create-react-app awsbug
2. cd awsbug
3. npx amplify-app@latest
4. amplify init
5. amplify update api (add User Pool auth with default configurations)
6. amplify push
7. Go to the cognito console and create a user
8. Go to the AppSync console and create a Task:
`
mutation {
    createTask(input:{title:"aws1"}){
        id
    }
}
`
9. Try to update the Task:
`
mutation {
    updateTask(input:{id: <id>, title:"aws2"}){
        id
       title
    }
}
`
10. Try to update the Task:
`
mutation {
    updateTask(input:{id: <id>, title:"aws3"}){
        id
       title
    }
}
`

**Expected behavior**
After executing step 10, the Task should read: title="aws3", but it does not. In fact you can try to update it many more times, and nothing will happen.

**Smartphone (please complete the following information):**

- Device: Mac
- OS: Catalina 10.15.3
- Browser Brave
- Version idk

**Additional context**
I believe this problem to be rooted in the amplify-app script. If you follow the same recipe as above, but replace step 3 with 'amplify init' and step 4 with 'amplify add auth', you will not observe the same bug. This is a HUGE bug guys. It has removed the ability of an entire operation, for all models, in my production app

**Comment by undefobj** [comment]
This is by design as you're using `amplify-app` which is for DataStore and has conflict detection and resolution enabled. When using the DataStore client API it includes the `_version` argument to the GraphQL API allowing the checks to take place. In your mutations above you're manually crafting GraphQL statements without the argument in update operations and hence they will fail. 

If you wish to manually perform GraphQL updates on objects which are provisioned using the DataStore flow you'll need to include the `_version` argument and also specify the fields in the selection set in order to ensure sync occurs: https://aws-amplify.github.io/docs/js/datastore#writing-data-from-the-appsync-console

**Comment by karrettgelley** [comment]
@undefobj Huh. Ok, so how do I know what my _version is?

**Comment by undefobj** [comment]
Normally you shouldn't need to unless you're doing an out of band operation. If that's the case then you'll need to run a query first and then do the update.

**Comment by karrettgelley** [comment]
@undefobj Well in my case, I'm not trying to use DataStore.put, but instead API.graphql. I was under the impression that DataStore works along with the conventional API module. So how would could I make an API.graphql call to update the task?

**Comment by undefobj** [comment]
If you're not using DataStore at all, then I'd recommend you don't setup your API with amplify-app. It's only a convince for setting up the sync service pieces which is why it's only in the DataStore docs. There's nothing stopping you from using both in the same app but it might be a bit cumbersome. I suppose you could run a query from the client or maybe try a local DataStore query (though I'd have to test that) but at that point you might as well just use the DataStore API. So if you need the lower level API category controls, just setup your GraphQL backend with the standard amplify add api flow.

**Comment by karrettgelley** [comment]
@undefobj I was hoping to use DataStore for mobile and API for desktop (sharing the same backend). Is there a chance to eject the DataStore stuff now? I may opt in later, but I'm not ready to use it in prod

**Comment by undefobj** [comment]
There's no "eject button" but you can use `amplify update api` and turn off conflict detection, however it will need to be done for every field so depending on your schema it might be a lot of updates.

Another idea is on the systems you're using just API module, make sure to ask for `_version` in the selection set for all your queries, mutations, and subscriptions. Then in your app logic make sure to store it and provide to the backend. Also maybe just use DataStore on the desktop systems too?

**Comment by karrettgelley** [comment]
@undefobj I agree that DataStore is the right way (for me) in a conceptual sense. I saw your talk on youtube and I was immediately won over. But I have no idea how much it will cost, and its fairly new (I had bad luck w/ v1 and moved on) so theres less docs, etc. Anyways, for now I'll just try to "eject". Thanks for your tip and I'll now close the issue :)

**Comment by undefobj** [comment]
No worries. This is already helpful for us to think about improving the interoperability between API and DataStore categories.
