### ISSUE TITLE
No credentials available, the request will be unsigned

### ISSUE THREAD

**Issue by Quix0tic** [aws-amplify/amplify-js#5398]
**Describe the bug**
After a successful login (username+pass), session token could not be used to call the API (which has restricted access), hence the **API Gateway fails to authorize the request**.

**Screenshots**
![image](https://user-images.githubusercontent.com/5829628/79168268-b8d46280-7de9-11ea-837b-a1f002418b2d.png)

_index.jsx_

```js
import awsconfig from "./aws-exports";
Amplify.configure(awsconfig);
API.configure(awsconfig)
```

```js
await API.get("scribaapi", "/projects/", null)
```

_aws-exports.json_
```json

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:[id]",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_[id]",
    "aws_user_pools_web_client_id": "[id]",
    "oauth": {},
    "aws_user_files_s3_bucket": "[name]-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1",
    "aws_dynamodb_all_tables_region": "eu-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "users-dev",
            "region": "eu-central-1"
        },
        {
            "tableName": "userprojects-dev",
            "region": "eu-central-1"
        }
    ],
    "aws_content_delivery_bucket": "[name]-dev",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://[name]-dev.s3-website.eu-central-1.amazonaws.com",
    "aws_cloud_logic_custom": [
        {
            "name": "scribaapi",
            "endpoint": "https://[id].execute-api.eu-central-1.amazonaws.com/dev",
            "region": "eu-central-1"
        }
    ]
};


export default awsmobile;

```

**Comment by Quix0tic** [comment]
This is the log right after a successful login

![image](https://user-images.githubusercontent.com/5829628/79209160-53ad5b00-7e43-11ea-8525-f5636369aab3.png)

**Comment by Quix0tic** [comment]
Removing `node_modules` and `package-lock.json` solved this issue.

**Comment by dcarlstedt** [comment]
Thanks for posting your resolution. It solved my issue as well. 

For anyone else that may run into this one. You may also notice that Chrome and Firefox will mention a CORS error stating `'Access-Control-Allow-Origin'` is missing even after enabling CORS on API Gateway.  If you take a closer look the request causing the CORS error it's actually a 403 Forbidden with the message  `{"message":"Missing Authentication Token"}`

After doing what @Quix0tic suggested I'm not back up and able to make Authenticated calls using IAM auth to my API Gateway endpoints. 

**Amplify Package Version Used**: aws-amplify: ^3.0.7
**Amplify Vue Plug Version**: asw-amplify-vue: ^2.1.1

VueJS Applications where the main.js file has the following setup: 

```javascript
import { Auth, API, Logger, I18n } from 'aws-amplify'
import { AmplifyPlugin } from 'aws-amplify-vue'

import awsconfig from './aws-exports'

window.LOG_LEVEL = 'DEBUG'//

Auth.configure(awsconfig)
API.configure(awsconfig)

Vue.use(AmplifyPlugin, { API, Logger, I18n, Auth })
```

Example of Code using the Vue Plugin to reference the registered API Amplify Lib in order to call my API Gateway with IAM Auth:

```javascript
const init = {
   headers: {  },
 }

this.$Amplify.API.get('rDevOpsDashboardAPI', '/pipelines', init)
  .then(r => console.log(`Result is: ${r}`))
  .catch(e => console.log(`error: ${e}`))
```
