### ISSUE TITLE
Subscription Typescript Error

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-js#5447]
**Describe the bug**
When I try to create a subscription I get the following error `Property 'subscribe' does not exist on type 'Promise<GraphQLResult<object>>'.ts(2339)`.

**To Reproduce**
1. Create a blank amplify react app
2. Create a subscription:
 ` useEffect(() => {
      let userSubscription: any;
      try {
        userSubscription = API.graphql(
          graphqlOperation(onUpdateUser, { id: userId }),
        ).subscribe({
          next: async (value: { data: OnUpdateUserSubscription }) => {
             return;
          },
        });
      } catch (e) {
        setError(true);
        console.log('sub error', e);
      }

      return () => {
        if (userSubscription) {
          userSubscription.unsubscribe();
        }
      };
    }
  }, [
    userId,
  ]);`

**Expected behavior**
Subscription should work as in the [subscription example in the amplify docs](https://aws-amplify.github.io/docs/js/api#subscriptions).

- OS: MacOS Catalina 10.15.3
- Browser: Brave

**Additional context**
I have been trying to convert my react app to ts recently and I haven't been able to properly convert my subscriptions. I can't find any errors specific to amplify, and the stackoverflow answers do not seem to solve this problem which makes me think this is a bug specific to amplify.

**Comment by humphreylitan** [comment]
I'm also experiencing this same issue. I couldn't seem to find the solution in the internet. I've seen some but they didn't work. 😪

**Comment by saevarb** [comment]
I would highly recommend you use the DataStore API instead of trying to use the generated types and queries. They are nearly impossible to work with in any generic way, and the DataStore stuff automatically generates proper models for all your schemas and lets you do crud operations much more easily.

**Comment by karrettgelley** [comment]
@saevarb DataStore is, in my opinion, not production ready and very expensive (see #5119 ). It is still undergoing large changes and I can't ship with that kind of volatility. Also it operates under a completely different paradigm. Long term I would love to use it, but not now. Thanks for your suggestion though

For now I just ignored the error with `// ts-ignore`. The problem might be as simple as updating the ts type for API.graphql(), as it doesn't break my code by adding the ignore.

**Comment by saevarb** [comment]
@karrettgelley Thank you very much for bringing that issue to my attention! I was not aware of this.

I have been perusing the thread and linked threads, and I just need to make sure I'm not misunderstanding this: Is DataStore syncing the *entire database*, with no regard for auth, so that I have other users' data on every other client? Because I am having a hard time believing that someone would actually implement that.

As for volatility and such, I can definitely [understand and relate to your concerns.](https://github.com/aws-amplify/amplify-js/issues/5452#issuecomment-616379222)

However, as someone who spent a not insignificant amount of time working with the types and queries that are generated for you, I can tell you that it's not gonna be pretty. 
If I had to generate types such that it would be as hard as possible to come up with a general abstraction that unifies them, the types I would generate would not be far from the types that amplify currently generates.

**Comment by karrettgelley** [comment]
@saevarb I appreciate the input but please only comment if you have a fix or a related concern. This post is not about DataStore, and you can read through other issues if you want to know more. This issue also doesn't have to do with my schema or the generated types from my schema. It has to do with the types defined in the aws packages (likely `@aws-amplify/api`). The subscribe function is not recognized as a chainable function of `API.graphql()` according to typescript. 

By the way, with velocity, lambda, and intentional schema design, I should think that you can do pretty much anything with your data.
