### ISSUE TITLE
@key in graphQL not working properly

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-js#5568]
If I add `@key( fields: ["id", "username"])` the getUser requires both id and username rather than require id and have username be used like eq or gt like it used to. Like this

```
getUser(id: ID!, username: String!): User
```

Also when I add `@key(name: "byUsername", fields: ["username", "createdAt"])` no query byUsername gets added to my schema like used to happen on previous versions.

**Comment by RossWilliams** [comment]
If you don’t give a key a name, that key is used on the primary table. If you want to access a model using a key, you need to specify the “queryField” property, not the name property.

Working as intended.

**Comment by 24jr** [comment]
Oh ok you're right I was thinking “queryField” only needed to be provided if you wanted a custom name. 

But my question on the no name one still remains. The second field is just a sort key right but it generates `getUser(id: ID! username: String!): User` and I wouldn't think the sort field would be a requirement for getUser. Expected just  `getUser(id: ID!): User`

**Comment by 24jr** [comment]
Also for named @key's can you not just remove those and add new ones. I keep having errors and just deleting entire api and pushing new from start to get new changes. Its fine now with no users but of course I can't delete all the users in a year if I want to change a named key

**Comment by RossWilliams** [comment]
You are trying to access a single item. If you specify a sort key on a table, to access a unique value you must specify the partition key and the sort key. Otherwise you could have multiple users with the same ID field. Not a bug.

For your latest question, you cannot change a @key that specifies the key structure for the primary table (includes LSIs). You can remove and add named keys (one at a time) that create GSIs. If you try to do more than one GSI operation (add or remove at once on a table, (unless you are creating a fresh table) the operation will fail.

**Comment by 24jr** [comment]
Okay I was initially thinking sort key was strictly for listing data and still required unique ids but makes sense. Thanks for your clarification on all this!
