### ISSUE TITLE
AmplifyAuthenticator customize validation modal positioning and style

### ISSUE THREAD

**Issue by sri7vasu** [aws-amplify/amplify-js#5604]
**Is your feature request related to a problem? Please describe.**
Im using SignUp form like this using React (Typescript) and AmplifyAuthenticator like this below:

```
import React from "react";
import {AuthState} from "@aws-amplify/ui-components"
import {
  AmplifySignUp,
  AmplifyAuthenticator,
  AmplifySignOut,
} from "@aws-amplify/ui-react";

function SignUp() {
  return (
    <AmplifyAuthenticator initialAuthState={AuthState.SignUp}>
      <AmplifySignUp
        headerText="Sign Up"
        usernameAlias="email"
        slot="sign-up"
        ></AmplifySignUp>
      <div>
        My App
        <AmplifySignOut></AmplifySignOut>
      </div>
    </AmplifyAuthenticator>
  );
}
export default SignUp;
```
The functionality and validations are working fine , i placed the signup forum in middle right of my page and still when there is a validation error it shows on top of the page and that too wide as shown in the figure. There is no way to customize the modal nor to change the width or style.

<img width="1440" alt="79911721-6cd77e00-83e6-11ea-9ea3-7c4aa4ac781e" src="https://user-images.githubusercontent.com/5733652/80531479-568a6e80-8960-11ea-92b0-b396ad58b11d.png">

**Describe the solution you'd like**
Needed a way to customize the positioning of the validation modal and styles. It will be helpful.

**Describe alternatives you've considered**
Tried using a different auth framework all together or write my own components using Amplify components but thats lot of work and testing.

**Comment by sawyerh** [comment]
+1 to this feature request. Our team is holding off from updating to the new Amplify UI library because of this. We don't feel the current user experience around error messages is the most user friendly, and we'd like to customize the styling further to match our site. We'd like to either be able to fully customize the CSS of this component, or be able to replace it with our own custom Error component. 

In `aws-amplify-react`, we've accomplished this by hiding the default toast component. We then render our own error component by passing a function into the `Authenticator` component's `errorMessage` prop, storing triggered errors in our own React state, which we can then render however we like.

**Comment by joae** [comment]
@sawyerh How do you hide the Toast component? I'm using react and I can't figure out how to do it

**Comment by wlee221** [comment]
Hello all, we had #7129 merged that will allow you to hide the default error toast and implement your own. You can see @Luke-Davies' example here https://github.com/aws-amplify/amplify-js/issues/6479#issuecomment-797547294. We will close this issue as #7129 solves this, but please feel free to ask any questions.
