### ISSUE TITLE
verifying logged in user's password

### ISSUE THREAD

**Issue by ajitgoel** [aws-amplify/amplify-js#5670]
** Which Category is your question related to? **
Auth and credentials

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
Hi!
I want to give my users the ability to change their password. They will have to enter their old password and their new desired password.
a. What is the recommended way to verify his old password?

```
async changePassword() 
    {
      try 
      {
        const user=await Auth.currentAuthenticatedUser();
        //ToDo: check if old password is valid or not. 
        const result=await Auth.changePassword(user, this.oldPassword, this.newPassword);
        this.$router.push('/user-settings').catch(() => {});  
      } 
      catch (error) 
      {
        console.log(`error: ${JSON.stringify(error)}`);
      };
```

**Comment by mtliendo** [comment]
Hey @ajitgoel 👋 If you get a chance, can you see if bypassing the cache solves the issue:

```diff
- const user=await Auth.currentAuthenticatedUser();
+ const user=await Auth.currentAuthenticatedUser({bypassCache: false});
```

**Comment by ajitgoel** [comment]
Hello @mtliendo , bypassing the cache does not fix the issue.
Also would you have an input on how should the system verify the user's password? I checked the [documentation](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js) but I could not find anything.

**Comment by ajitgoel** [comment]
This item can be closed.

**Comment by mtliendo** [comment]
Hey @ajitgoel glad you got it taken care of!

When you say "system" were you meaning your app? Because of security best practice, the user's password is never made available and can only be reset. However, you can log out the result given back from the password change like so:

```js
const result=await Auth.changePassword(user, this.oldPassword, this.newPassword);
console.log(result)
```

This will log out that the change was successfull and could be made into an alert in your app so that the user gets a custom message about the change.

Enhancing the docs so that they give a sample response is a good idea. Thanks for the feedback!

**Comment by ajitgoel** [comment]
Thank you @mtliendo for your input. I would ask that the AWS amplify team adds "Because of security best practice, the user's password is never made available and can only be reset." to the documentation, if it is not there.
