### ISSUE TITLE
AmplifyAuthenticator in amplify-ui-components/amplify-ui-react doesn't support theme override

### ISSUE THREAD

**Issue by ivenxu** [aws-amplify/amplify-js#5733]
**Describe the bug**
[Migration](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#migration) section implies using amplify-ui-react is better than aws-amplify-react. However, the theme override feature in aws-amplify-react is not implemented.

**Expected behavior**
AmplifyAuthenticator in amplify-ui-components should also have theme customization feature.

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

When it uses withAuthenticator  from aws-amplify-react, it works. Not works if use withAuthenticator  from amplify-ui-react which eventually goes to use AmplifyAuthenticator in amplify-ui-components

```
import { withAuthenticator } from 'aws-amplify-react';
const MyTheme = {
  formSection: { 'display': 'none' }
}

function App() {
  return (
      <ThemeProvider theme={theme}>
          <Router history={browserHistory}>
            <Routes />
          </Router>
      </ThemeProvider>
  );
}

export default withAuthenticator(App, {theme: MyTheme})
```

**Comment by ericclemmons** [comment]
@ivenxu Sorry for the confusion here!

Usage if `withAuthenticator` isn't exactly the same as it was before, which is why `{ theme: MyTheme }` doesn't work. See our migration guide here:
> https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#migration

We took a different approach with theming using CSS variables for `@aws-amplify/ui-react`.

Almost every aspect of the components are available for customization via CSS variables, even more than we supported via `theme` in the past:
> https://docs.amplify.aws/ui/customization/theming/q/framework/react

Also, you'll have an easier time targeting elements 

If `aws-amplify-react` is working for you, don't worry about upgrading just yet :)

The important note is that the foundation of `@aws-amplify/ui-react` (`@aws-amplify/ui-components`) powers Angular, Vue, _and_ React, so we're ensuring all frameworks have the same level of support & features.

**Comment by ivenxu** [comment]
@ericclemmons Thanks for the quick response! 

Css variable is a new feature and is easy to use. However, there're still cases the old way provides more flexibility. For example, styling crossing two elements. This comes to my eyes because I find the signin and signup components are not center to the screen. Then I try to use `theme`. I use flex layout to fix the problem. With the old way, I can 

```
formContainer= { display: 'flex'};
formSection = { margin: 'auto'};
```

May be a new feature request for the new react-ui component is having `className` as prop.

Furthermore, the official document is still leading people to old `theme` object.
https://docs.amplify.aws/lib/auth/customui/q/platform/js

**Comment by ericclemmons** [comment]
@ivenxu Great timing! @jordanranz just fixed the centering problem in https://github.com/aws-amplify/amplify-js/pull/5727. (This was a regression from the previous `aws-amplify-react` implementation).

You have a good point on escape hatches: `amplify-sign-in`, for example, is exposed, but part of the Shadow DOM, otherwise you would be able to target those components _directly_.

Can you open a new Feature Request that the UI team can better answer?  It may be that formContainer & formSection get targeted with specific CSS variables, receive classNames (why not?), or `theme` comes back somehow.

@jordanranz Regarding https://docs.amplify.aws/lib/auth/customui/q/platform/js, should we open an issue in https://github.com/aws-amplify/docs/?

**Comment by ivenxu** [comment]
@ericclemmons  Thanks for the communication! https://github.com/aws-amplify/amplify-js/issues/5750 has added as feature request.

**Comment by ericclemmons** [comment]
@ivenxu This is looking good! I've updated the labels on #5720 and categorized it so it gets the right 👀 .
