### ISSUE TITLE
Separate registration code and forgot password code email

### ISSUE THREAD

**Issue by xon52** [aws-amplify/amplify-js#5754]
**Is your feature request related to a problem? Please describe.**
I have just noticed that I receive the **exact** same confirmation code email whether I register or forget password. The problem is with the exact same link there is no way to know which is being requested, so handling them is really a trial and error scenario which is just crazy.

**Describe the solution you'd like**
Separate default links for registration confirmation (e.g. `/confirm/code`) and forgot password (e.g. `/forgot/code`)

**Comment by tannerabread** [comment]
@xon52 you can customize the message that is sent with the [CustomMessage lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html#cognito-user-pools-lambda-trigger-syntax-custom-message-trigger-source) which should let you customize the email that gets sent for each of the listed sources. The docs even have an [example for the sign-up message](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html#aws-lambda-triggers-custom-message-example)

You can set this up through the Amplify CLI as [shown here](https://docs.amplify.aws/cli/usage/lambda-triggers/#set-up-lambda-triggers)

As this issue is pretty old, I'm not sure if this was possible when you opened it, but would this solve the ask for this feature request?

**Comment by xon52** [comment]
Hey, yeah I don't use this anymore so can't even remember the use case I had. Thanks for your reply though 😄

**Comment by tannerabread** [comment]
Sorry it took so long for someone to get to this, but thanks for the quick response on a 3 year old issue!
