### ISSUE TITLE
DataStore nodeJS

### ISSUE THREAD

**Issue by bkniffler** [aws-amplify/amplify-js#5864]
**Is your feature request related to a problem? Please describe.**
I know that amplify is supposed to be used on frontend and that there is limited sense of using the offline-first datastore from backend systems. But the type-safe interface would make working with the databases really neat from within my lambda functions. Would love to have a way to disable caching and use `DataStore.save`/`DataStore.query` etc from nodeJS backend.

**Comment by ericclemmons** [comment]
Thanks for bringing this up @bkniffler. I totally agree.

I've added this request to our SSR milestone (https://github.com/aws-amplify/amplify-js/milestone/26), since support in Node is solved as part of that initiative.

You can subscribe to this umbrella issue (https://github.com/aws-amplify/amplify-js/issues/5435) as well.

**Comment by bkniffler** [comment]
Thanks for linking that issue. Funny thing that solving SSR might bring this feature as a side effect :)

I've subscribed and will close for now, may very well work if SSR works.
