### ISSUE TITLE
Native ios crash when uploading blob with aws amplify

### ISSUE THREAD

**Issue by thekrol01** [aws-amplify/amplify-js#5874]
**Describe the bug**
This is already a known bug at React native 
https://github.com/facebook/react-native/issues/27857

The bug only happens on IOS not on Android.
For me the crash appeared on IOS after an upgrade from React Native 0.61.4 to 0.61.5.

Because the bug is not fixed yet, Perhaps there is a workaround possible?

**To Reproduce**
1. Upload a blob with the put command

**Expected behavior**
1. no IOS crash when uploading a blob, same behaviour as Android.

**Code Snippet**
This is a snack from the issue mentioned above.
https://snack.expo.io/@chris-feist/document-upload-issue-demo

**What is Configured?**
aws-sdk ( "aws-amplify": "^2.2.7",),  react native 0.61.5 on a physical device with Testflight. Same code works fine with RN 0.61.4. The crash happens randomly after every one or two PUT uploads.

**Smartphone (please complete the following information):**

- Device: all IOS devices 
- OS: 12 and 13

**Comment by amhinson** [comment]
@thekrol01 Could you try using the latest version of `aws-amplify@latest` and see if your problem still persists? The latest release included some updates related to blobs in React Native. Also, since you are coming from Ampify V2, you can check out the [migration guide to V3](https://github.com/aws-amplify/amplify-js#amplify3xx-has-breaking-changes-please-see-the-breaking-changes-below) as well.
