### ISSUE TITLE
amplify add sam

### ISSUE THREAD

**Issue by philhar88** [aws-amplify/amplify-js#5912]
**Is your feature request related to a problem? Please describe.**
It would be great to have a category called 'sam'. Once you add this category you input your SAM ARN and any exports you want to sync.

**Describe the solution you'd like**
The ability to reference existing SAM apps within Amplify would be enormously useful. You could for example deploy an entire backend application with SAM, export a few key variables and then have that used inside lambda functions, dynamodb tables etc.

**Describe alternatives you've considered**
Add CFN directly to Amplify is quite cumbersome and feels like it undoes the primary benefit of amplify (using the cli)

**Comment by perima** [comment]
this will be very useful for back end heavy apps

**Comment by undefobj** [comment]
This isn't something we would add as a category. Categories in Amplify are functional use cases for mobile and web apps, such as Auth or Storage, not implantations.

That being said we're looking at an extendability feature in the CLI to give higher level hooks rather than having to dive down to CloudFormation. Keep an eye on the CLI repo in the future for more.
