### ISSUE TITLE
Cannot get any scopes in Access Token

### ISSUE THREAD

**Issue by zsid** [aws-amplify/amplify-js#5916]
**Describe the bug**
We are using `aws-amplify` to authorise with Cognito and need to get scopes i.e. `openid, profile, custom-scopes`. There are a lot of issues associated with this. For example, there is a very [similar one for custom scopes](https://github.com/aws-amplify/amplify-js/issues/5147) which has been closed. It seems like there has been [a release](https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/CHANGELOG.md) as well but testing it out custom scopes or any other scope is not working at all

**To Reproduce**

* Set up the custom scopes in Cognito as well as `openid` one.
* Add custom scope to amplify config
* Make request
* Expected behavior
* The custom scope and openid one should be contained within the token
 
Version: ` "aws-amplify": "^3.0.13",`
Here is my config
```
{
    Auth: {
      region: 'yourRegion',
      userPoolId: 'userPoolId',
      userPoolWebClientId: 'userPoolWebClientId',
      oauth: {
        domain: 'yourDomain',
        scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin', 'custom-scope-one', 'custom-scope-two'],
        redirectSignIn: 'http://localhost:3000/',
        redirectSignOut: 'http://localhost:3000/',
        responseType: 'code',
      },
    },
  }
```

**Expected behavior**
The custom scope and the other ones (i.e. `openid`, `profile`) should be within the token.
The custom scope should be contained within the token

**Comment by elorzafe** [comment]
@zid
As I mentioned on the issue #5935 and #5921. Previous the change you mention the library was sending the query string param `scopes` instead of `scope` which is the correct param. The default behavior by Cognito when the scope param is missing is that it will return (as is mentioned on this [Authorization endpoint Cognito docs]()) all the scopes available.

Can you check if the scope you have configured are present on AllowedOAuthScopes on your App client (clientId) settings. You can check those on Cognito console under App Integration>App client settings or using aws cli aws cognito-idp describe-user-pool-client --user-pool-id us-west-2_xxxxxxxxx --client-id xxxxxxxxxxxxxxxx

What might happen in your case is that custom scopes on Cognito has a prefix with the resource server identifier. For example the resource server identifiers is `server-1` and I have a scope named `weather`. The custom scope should be `server-1/weather`.

**Comment by zid** [comment]
Looks like you meant to ping @zsid

**Comment by zsid** [comment]
@elorzafe This is still not working. The name for the custom scopes I am using is similar to what you have pointed out i.e. `https://examlpe.com/Hello` and it is selected in the app client settings.

In addition, I am also not getting `openid, profile, email` which are the rest as well. So coming back to your point, looks like they are not included at all and we are getting the default behaviour which is to return the admin.

Some additional context that might be helpful is we are using the `Authenticator` from `aws-amplify-react` as a HOC for our login. We are not hitting the end points directly but the aws package is doing it for us.

**Comment by elorzafe** [comment]
> Looks like you meant to ping @zsid

Thanks @zid

**Comment by zsid** [comment]
@elorzafe, did you manage to replicate it?

**Comment by elorzafe** [comment]
@zsid `Authenticator` components doesn't use OAuth flow, OAuth flows are available using Cognito HostedUI and is the mechanism that Cognito returns custom scope on the access token.

**Comment by zsid** [comment]
@elorzafe getting scopes (custom and standard ones) on the token via the `Authenticator` is a big requirement for us. 

What are the plans to get them outside the `HostedUI`? Speaking to fellow colleagues, only getting the scopes via `HostedUI` have pushed people to use other providers rather than `Cognito` and is seeing as big blocker. I am also getting in big arguments with other suppliers to move to other authentication solutions since we cannot get the scopes via  `Authenticator` which we are using in our applications

**Comment by kamce1999** [comment]
@elorzafe Do you have a response to @zsid?  I need the open id scope but don't what to use the hosted UI.  I'm trying to keep everything contained in AWS so I would prefer to use cognito.  We might have to look at other providers as well.  Is the fix on the road map?
