### ISSUE TITLE
[Datastore] Improve error handling when data is syncing

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/amplify-js#5963]
**Describe the bug**
The console does not produce error (actually it does, read along) when one of the AWSDateTime field stored in DynamoDB is not in the correct format. Took us a long time to figure out why our query isn't returning anything.

**To Reproduce**
1. Create schema.graphql:
```
type Order @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  orderDate: AWSDateTime
  owner: String
}
```

2. Populate the table with orderDate as `2020-05-19T11:5:29.000Z`. It's missing a zero before the 5.
3. Query the Order table.
4. Huala, the query doesn't return anything.
5. Promptly check the console, no error found.
6. But...if you wait long enough, this errors shows up:
```
Possible Unhandled Promise Rejection (id: 408):
Object {
  "data": Object {
    "syncKDSOrders": Object {
      "items": Array [
        Object {
          "_deleted": null,
          "_lastChangedAt": 1590025175868,
          "_version": 2,
          "cancelBy": null,
          "customerName": "XXXX",
          "customerNumber": "XXXXXXXXXXXXXXX",
          "deliveryAddress": null,
          "deliveryNumber": null,
.
.
.

"errors": Array [
    Object {
      "locations": null,
      "message": "Can't serialize value (/syncOrders/items[32]/orderDate) : Unable to serialize `2020-05-23T06:4:37.000Z` as a valid DateTime Object.",
      "path": Array [
        "syncOrders",
        "items",
        32,
        "orderDate",
      ],
    },
  ],
}
```
Interesting bits is contained in the error.

**Expected behavior**
1. I tried catching the error in the query and that didn't work.
2. I tried catching with
```
DataStore.configure({
  errorHandler: (error) => {
    console.warn('Unrecoverable error', { error });
  },
});
```
That didn't work too.
My guess is that it's an error deep inside the source, perhaps somebody can enlighten me.

**What is Configured?**
```
yarn list --depth=0 --pattern amplify
yarn list v1.22.4
├─ @aws-amplify/analytics@3.1.9
├─ @aws-amplify/api-graphql@1.0.11
├─ @aws-amplify/api-rest@1.0.11
├─ @aws-amplify/api@3.1.9
├─ @aws-amplify/auth@3.2.6
├─ @aws-amplify/cache@3.1.9
├─ @aws-amplify/core@3.2.6
├─ @aws-amplify/datastore@2.0.10
├─ @aws-amplify/interactions@3.1.9
├─ @aws-amplify/predictions@3.1.9
├─ @aws-amplify/pubsub@3.0.10
├─ @aws-amplify/storage@3.1.9
├─ @aws-amplify/ui@2.0.2
├─ @aws-amplify/xr@2.1.9
├─ aws-amplify-react-native@4.1.1
└─ aws-amplify@3.0.10
```

Would be great if amplify team members can sort this out with us.

**Comment by mauerbac** [comment]
hi @nubpro - thanks for informing us. We've identified this as a bug and the service should detect this type before syncing. We will work on a fix.

**Comment by wei** [comment]
![image](https://user-images.githubusercontent.com/5880908/98947118-d0301700-24c2-11eb-829b-cdd3914820e9.png)

Local validations in `validateModelFields` is not validating [AppSync Defined Scalars](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) like `AWSDateTime` type. The generated typescript types are showing `string` for `AWSDateTime` so typescript is no help either.

One solutions is to validate these AppSync defined scalars in `validateModelFields`.

/cc @iartemiev for feedback and next steps.

---
[Repro repo](https://github.com/wei/aws-amplify-react/tree/5963) branch `5963`.

**Comment by nubpro** [comment]
@wei Does your PR surfaces the error to `DataStore.errorHandler()`?

**Comment by wei** [comment]
> I tried catching the error in the query and that didn't work.

This method should work now:

![Kapture 2020-11-17 at 22 04 59](https://user-images.githubusercontent.com/5880908/99477700-089b7f00-2921-11eb-946f-80441770eaf7.gif)

**Comment by nubpro** [comment]
@wei That is looking good, but my concern is what will happen if DS is syncing corruped data from AppSync? This could happen if someone had accidentally or carelessly incorrectly manipulated the data directly in DDB.

**Comment by wei** [comment]
When that happens, AppSync sync requests will fail:

![image](https://user-images.githubusercontent.com/5880908/99484357-3509c800-292e-11eb-99b4-5f50fec71481.png)

which is where you are getting that error message

> Can't serialize value (/syncOrders/items[32]/orderDate) : Unable to serialize `2020-05-23T06:4:37.000Z` as a valid DateTime Object.

You don't see this error right away because the wrapper function `jitteredExponentialRetry` is swallowing it and retrying it with exponential backoff.

https://github.com/aws-amplify/amplify-js/blob/8fa348b8ba708434992d97557b0fceebbf7abe9a/packages/datastore/src/sync/processors/sync.ts#L115-L143

Exponential backoffs:

https://github.com/aws-amplify/amplify-js/blob/e85640a4e18fa1d55411038fee58919ad73121fa/packages/core/src/Util/Retry.ts#L58-L68

https://github.com/aws-amplify/amplify-js/blob/e85640a4e18fa1d55411038fee58919ad73121fa/packages/core/src/Util/Retry.ts#L49-L54

Once it retries many times and the next retry delay reaches `maxDelay` (5min), the error is thrown without any more retries.

You are correct at this moment that error is not being caught or exposed through `DataStore.errorHandler`. 

`jitteredRetry` in `sync.ts` or callers of it need a try catch and send the error to `DataStore.errorHandler` for you to access.

## Potential solution

My commit [here](https://github.com/aws-amplify/amplify-js/compare/main...MLH-Fellowship:datastore/fix-sync-error-handling?expand=1) catches the error and notifies the `observer.error` which `datastore.ts`'s `start` method is already subscribed to:

#### Exposing it to user

https://github.com/aws-amplify/amplify-js/blob/863daba34d30b16b2c381a8e4ba9a8379f7d290f/packages/datastore/src/datastore/datastore.ts#L625-L628

We can do something like `this.errorHandler(...)` here and assemble a `SyncError` to pass through. Or perhaps there is a better way to expose this exception to the user?

---

Supporting scenarios bypassing AppSync and updating DynamoDB directly may be out of the scope of this project/component. Perhaps the easiest way is to not manipulate DynamoDB directly or use extreme caution when updating/removing ~

**Comment by nubpro** [comment]
@wei Appreciate the thorough breakdown. I learnt a thing or two!

While I agree with the statement that we shouldn't be modifying the data directly, it would be awesome if the client can do something about it. I really dig your solution.

**Comment by iartemiev** [comment]
@nubpro - we merged a PR that adds clientside validation for AppSync scalars (e.g., AWSDateTime, AWSJSON, etc.). It was deployed as part of aws-amplify@3.3.9.

Regarding surfacing sync errors, we're currently exploring solutions for that. The approach proposed above would cause the sync engine to stop working when a single model encounters an error, which is not the desired behavior. Instead, we're looking into utilizing the Hub for outputting DataStore errors.

Can we close this issue?

**Comment by nubpro** [comment]
> @nubpro - we merged a PR that adds clientside validation for AppSync scalars (e.g., AWSDateTime, AWSJSON, etc.). It was deployed as part of aws-amplify@3.3.9.
> 
> Regarding surfacing sync errors, we're currently exploring solutions for that. The approach proposed above would cause the sync engine to stop working when a single model encounters an error, which is not the desired behavior. Instead, we're looking into utilizing the Hub for outputting DataStore errors.
> 
> Can we close this issue?

Thanks for making the improvement!

Sure lemme close it.

**Comment by nubpro** [comment]
@iartemiev Can I keep this issue open until the underlying issue is resolved since numerous reports of sync error has been occuring lately?

**Comment by efesurekli** [comment]
This is definitely something hugely missing. Hope you re-open this issue.

**Comment by armenr** [comment]
+1 to needing this addressed, and re-opened/resolved.

**Comment by nubpro** [comment]
@efesurekli @armenr Feel free to open a new issue with the problems you are facing.

**Comment by adzrail** [comment]
Are there any suggestions on how to catch the errors raised from `sync.js` file? 
As @nubpro mentioned, I also have `errorHandler` configured, though no error is triggered.

`DataStore.configure({
  errorHandler: (error) => {
    console.warn('Unrecoverable error', { error });
  },
});`

I also checked the `Hub` events, though no events are fired, though there is a lack of `syncQueriesReady` and `ready` events, indicating that something is went wrong?

**Comment by Dennis-Dekker** [comment]
Hi, are there any updates on this issue?

**Comment by nubpro** [comment]
> Hi, are there any updates on this issue?

This issue is closed, please open a new one
