### ISSUE TITLE
App doesn't open on tapping the Notification

### ISSUE THREAD

**Issue by shubham234** [aws-amplify/amplify-js#6000]
**Describe the bug**
On tapping the received notification, the App should open.

**To Reproduce**
1. Kill the App. 
2. Send yourself a notification.
3. Open the App by clicking on the App Icon (Not Notification).
4. Kill the App again.
5. Tap on the notification.
6. You'll see that notification closes but App doesn't open.

**Expected behavior**
The app should open always whenever you tap on the notification.

**Smartphone:**
- Device: OnePlus
- OS: Android 10.

**Environment:**
- React Native 0.59.8
- @aws-amplify/analytics: 3.1.9
- @aws-amplify/api: 3.1.9
- @aws-amplify/auth: 3.2.6
- @aws-amplify/core: 3.2.6
- @aws-amplify/pushnotification: 3.0.9
- @aws-amplify/storage: 3.1.9

**Additional context**
* Tried doing ```exported:true``` on BroadcastReceived in AndroidManifest but no success.

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**
* No logs from Amplify.
* Following logs are printed on adb:
```
2020-06-04 04:12:44.898 1332-1426/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED flg=0x10 (has extras) } to com.myapp.myappname.android.app.beta/com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver
2020-06-04 04:12:44.899 1332-1426/? W/BroadcastQueue: Permission Denial: broadcasting Intent { act=com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED flg=0x10 (has extras) } from com.myapp.myappname.android.app.beta (pid=-1, uid=10476) is not exported from uid 10470 due to receiver com.myapp.myappname.android.app.prod/com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver
```

**Comment by amhinson** [comment]
Hey @shubham234, thanks for opening up this issue! I am able to reproduce the behavior you are seeing. We are in the process of revamping our Push Notification implementation, so I'll make sure we can address this issue as well.

**Comment by shubham234** [comment]
Keep the issue open.

**Comment by The0racle** [comment]
@amhinson  What do we do until then?

**Comment by jenitha-j** [comment]
for me also the same issue, Please help me if you guys already find out the solution.

**Comment by ionutmiftode** [comment]
any updates on this?

**Comment by lucafronterotta** [comment]
I'm experiencing the same problem, I tap on the notification but the app is not opening.
Waiting for a solution...

**Comment by sammartinez** [comment]
@shubham234 are you still for support for this? Please let us know

**Comment by RMG0** [comment]
@shubham234 , did you get this working? as I am sure this issue is still happening for all android apps using this dependency.

I am using latest @aws-amplify/pushnotification but still facing this issue.

Like if you got a notification  and then kill the app, Tapping on the notification wont open it.
Did some debugging and found this. In RNPushNotificationHelper, while creating notification , 
we set pendingIntent 
PendingIntent pendingIntent = PendingIntent.getBroadcast....
Now if we kill the app, the RNPushNotificationBroadcastReceiver also gets killed and so now tapping on notification not finding this. 

I checked some other libraries like 
https://github.com/zo0r/react-native-push-notification
 which uses Service to solve this as Services won't get killed if app gets killed.
I cant use other libraries because amplify is tightly linked to aws pinpoint.

Hope this will help anyone and get better solution.
