### ISSUE TITLE
AWS Amplify Storage Put - ProgressCallBack

### ISSUE THREAD

**Issue by cooperhurt** [aws-amplify/amplify-js#6068]
**Is your feature request related to a problem? Please describe.**
I am not sure if this is desired behavior or a bug that Storage.put has but when you use the ProgressCallback it only spit out when the put has been completed (unless the file is fairly large)

**Describe the solution you'd like**
I think using the progressCalback from past experience and other options is to have progressCalback constantly being update showing how much of the file has been uploaded.

**Additional context**
Here is how I am using it in my code:
```js
Storage.put(fileName,file, { progessCallback(progress) { console.log(progress) }});
```

Even if I do:
```js
await Storage.put(fileName,file, { progessCallback(progress) { console.log(progress) }});
```

I know this works if you use a larger file but for smaller files it doesn't seem to work. Is there any alternatives to this?

Idk if this can easily be achieved:
```js
const emitter = new events.EventEmitter();
		const uploader = new AWSS3ProviderManagedUpload(params, opt, emitter);

		if (acl) {
			params.ACL = acl;
		}

		try {
			emitter.on('sendProgress', progress => {
				if (progressCallback) {
					if (typeof progressCallback === 'function') {
						progressCallback(progress);
					} else {
						logger.warn(
							'progressCallback should be a function, not a ' +
								typeof progressCallback
						);
					}
				}
			});

			const response = await uploader.upload();

			logger.debug('upload result', response);
			dispatchStorageEvent(
				track,
				'upload',
				{ method: 'put', result: 'success' },
				null,
				`Upload success for ${key}`
			);
			return {
				key,
			};
		}
```

**Comment by n0rb** [comment]
any update on this? the calls to progressCallback seem to be fairly rare

**Comment by nadetastic** [comment]
Hi @n0rb, following up on this issue.

Currently, the progress call back event is dependent and based on the number of part size that are sent to S3. Currently the library uploads at about 5 MB at a time.

What that means is that if you upload a file that is 5 MB or less, then you will only see on event, which will be the final success message. In comparison, a 20 MB file will emit 4 events, since 20MB total divided by 5MB at a time = 4 events.

I'll work to update the documentation to call this out. Let me know if you have any questions in the meantime.

**Comment by nadetastic** [comment]
Following up here - I've updated the [documentation](https://docs.amplify.aws/lib/storage/upload/q/platform/js/#event-handlers) to reflect how often the ProgressCallBack event will be fired. I'll go ahead and close out this issue now. Thanks!
