### ISSUE TITLE
Cognito: Email alias should return UserNotConfirmedException

### ISSUE THREAD

**Issue by clintfoster** [aws-amplify/amplify-js#6212]
Whether signing in with **username** or **email alias**, `UserNotConfirmedException` should be returned if the confirmation code hasn't been entered yet.

**To Reproduce**

1. Set up user pool w/ [Option 1](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-aliases-settings-option-1) (email _alias_ instead of email _username_)
1. Sign up with email alias
1. Do not confirm email
1. Try to sign in with email alias
1. Expected: `UserNotConfirmedException`
1. Actual: `UserNotFoundException`

Note: Our user pool was created a few years ago before it was possible to use an email address directly as the username (aka [Option 2](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-aliases-settings-option-2)). Therefore we use Option 1. Since we only want users to know their email address, we generate the username as a UUID (but don't show it to them).

**SDK version**
We're seeing this with the older Cognito JS SDK and with aws/aws-sdk-ios `2.13.4`. Thus, it appears to be a service issue.

**signUp() API request**
Of course, it works slightly differently in JS & iOS. But the input values are the same, e.g. for `signUp()`:

- **username:** UUID like `70011947-a63d-470b-967b-8693d19d5e26`
- **password:** `xxx`
- **attrs:** Only email: `{Name: 'email', Value: 'abc@xyz.com'}`

**authenticateUser() API request**
For `AuthenticationDetails` we are providing email alias & password:

```json
{
      Username: 'abc@xyz.com',
      Password: 'xxx'
}
```

**Related**
Closed (never solved?): https://github.com/aws-amplify/amplify-js/issues/3679

**Comment by JohanAltamar** [comment]
Still waiting for the solution.

**Comment by sammartinez** [comment]
@clintfoster Just to verify, have you reviewed our [documentation](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js) on setting up Auth within Amplify or are you doing [manual configuration with Amplify](https://docs.amplify.aws/lib/auth/start/q/platform/js#re-use-existing-authentication-resource)? Please let us know and we can dig into this further for you

**Comment by baltekgajda** [comment]
@clintfoster did you manage to overcome this issue? I'm encountering the same problem and it is still not fixed :/

**Comment by andradadimitriu** [comment]
same here

**Comment by igoramidzic** [comment]
Still having the issue.
Seems there are 2 paths for a registering user:

1. Sign up
2. Confirm email with code
3. You're logged in 👍 

and

1. Sign up
2. Close app
3. Attempt to log in (realizing its an unconfirmed user)
4. Resend confirmation email
5. Confirm email
6. Log in again
7. You're logged in 👍 

Anyone know a better flow for users returning to the app before confirming their email?

**Comment by joyacv2** [comment]
Hi Everyone!

Why is this closed?

I am using react authenticator component. If a user tries to login without confirm the account the login stuck! Any solution of this?

**Comment by mir1198yusuf** [comment]
I am stuck on this issue.

> Attempt to log in (realizing its an unconfirmed user)

Is above possible to realize unconfirmed user. All I get is user not found while sign in and user already exist while signup ?

**Comment by ManoVikram** [comment]
Is there any solution or work-around for this issue?

**Comment by julien-tamade** [comment]
I'm trying to find a way around this as well. I use an email alias for users to sign in and their cognito username is essentially a uuid. So if they wait too long to verify account or try to log back in without verifying, they get a user not found error instead of not confirmed because the alias isn't verified.

Few ideas I'm toying with:
Auto confirm user and alias in the presignup trigger and then in post confirmation trigger unconfirmed them again if it's first time and send the verification email. That way the email would still be verified but the account wouldn't be enabled (haven't tested to see if unverifying the user also unverifies the email, but it does work to try to sign in with a verified email but unverified account)

In the pre authentication trigger, we check if there's already a user with that email created with an unverified account and we return a custom error to that extent.

Having users recreate account if they miss verification opportunity first time
