### ISSUE TITLE
Limit of 100 subscriptions reached Datastore

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-js#6260]
**Is your feature request related to a problem? Please describe.**

This is a continuation of  issue  #5050.

My solution has a mobile app and a Web/Desktop back end. I have 45 Tables/Models which means that I'd have to have 135 subscriptions. Many of the tables I have in my database do not need to go anywhere near the mobile app and are there to support back end functionality. So I need the ability to specify which tables are subscribed on the mobile/datastore environment.

If I can do that then I can easily live with the 100 susbcription limit - but taking the whole database won't work.

**Describe the solution you'd like**
In DataStore to be able to select which tables/models are subscribed

**Describe alternatives you've considered**
As described in #5050 there are no alternatives - this is a show stopper if your database is of this size.

**Comment by sacrampton** [comment]
I have been through my database and added   @model(subscriptions: null) to 17 of the 45 tables. So if we could select the tables that are enabled for subscription I'd only need (45 -17) * 3 = 84 subscriptions.

**Comment by iartemiev** [comment]
Hi, @sacrampton your proposed solution is on our road map for DataStore. We'll keep this issue updated as we make progress on it.

**Comment by sacrampton** [comment]
Hi @iartemiev  - thanks for getting back to me. It looks like I need to stand down any move to DataStore for the foreseeable future. This is obviously a big step for us to remove DataStore from our planning, and one that I'm reluctant to take so I'm going to ask for an explicit confirmation before I take that drastic step.

As it stands today, if your schema.graphql has more than 33 @models (tables) then there is no way that DataStore can be connected to your AppSync back end. That until this issue is addressed there is absolutely no way we can use DataStore and there is no work around that can be applied in any way/shape/form. We currently do not know if this limitation will be overcome in the short term or the long term.

Sorry to ask for this clarification explicitly, but it affects my planning so I need absolute clarity on this. If you could confirm what I stated is a correct understanding of the situation I'd appreciate it.

**Comment by rahulbhankar786** [comment]
@iartemiev Any update on this.

**Comment by sacrampton** [comment]
@iartemiev Any update on this issue?

I first created an issue related to an offline searchable cache back in September last year (#4085) and am trying to implement DataStore to solve these issues in my production app. My mobile app doesn't need 33 @models - but my total solution (of which the mobile is a component) needs probably double this amount of models. My total solution is comprised of mobile and web components. I need to be able to select which @models my app subscribes to and that fixes the issue.

I need a solution for my app, but I seem to be running into issue after issue that are show stoppers each time. This limitation is the latest show stopper so its really critical to get an indication of when a solution (even a work around) might be available.

**Comment by sacrampton** [comment]
@sammartinez @iartemiev @manueliglesias 

Are there any work arounds for this problem? Currently it would appear that if your entire AppSync schema has more than 33 models you cannot use DataStore. I'm trying to get this confirmed whether we are truly dead in the water on this, or if there is a work around.

My application has a WEB/Backend component and a MOBILE component. The TOTAL solution has 45 models at the moment, but the MOBILE component doesn't need access to all 45 models. I use under 30 models on the MOBILE component, so as long as I can select which ones that subscribe then this all works.

Is there are work around or any other solution to allow me to proceed. Offline persistent cache is critical to me. Please advise / provide guidance on this critical issue.

**Comment by manueliglesias** [comment]
Hi @sacrampton 

One thing you can try for now is to manually modify the schema.js file generated in your models folder to remove the models you don't care about on your mobile app. 

Please note that you would have to do this every time you change the schema since the modelgen command works out then back again

**Comment by sacrampton** [comment]
@manueliglesias - WOW - THANK YOU!!!! That is a fantastic suggestion.

**Comment by danrivett** [comment]
Would love to see some progress on this front as we're going to be running up against this in the month with the extra models we have to implement.

**Comment by laclance** [comment]
we have 47 models, that are all needed and have started hitting this limit

**Comment by sacrampton** [comment]
@iartemiev @manueliglesias Just wanted to check back on this - it has been on roadmap for 6 months and remains a big issue

**Comment by JohnCashmore** [comment]
Is there any update on this, we are finding that subscriptions dont fire for every item updated and appears to be throttled, so we dont get all the data, so we wanted to subscribe to each individual item, which worked great until there was more than 100

**Comment by CarlJoven** [comment]
Any update on this? I am currently working on a project using datastore and I am about to reach the limit and I am really worried because my team still needs to implement additional features sometime in the future. I find it very inconvenient. I suggest that you give a warning in your documentation that datastore is only good for small to medium projects.

**Comment by CarlJoven** [comment]
Can I ask for an option to increase the limit via the support center?

**Comment by undefobj** [comment]
@CarlJoven @JohnCashmore can you give more insights into why more than 100 subscriptions are needed? To be clear this is not a DataStore limit, it's a limit that AppSync has set. That being said 100 subscriptions is a very large number even for very large projects. Perhaps there is a specific use case that you're trying to accomplish which can be met another way than having more active subscriptions to a client?

**Comment by sacrampton** [comment]
Hi @undefobj @CarlJoven @JohnCashmore - for each table/model there are 3 subscriptions (add, update, delete) which are created - which means you can have a maximum of 33 tables/models. My application has 45 tables/models to support the mobile and back end - so I'm 35 subscriptions over the limit. By default, as I understand this, you have no control about what to subscribe to - so when you have more than 45 tables/models you are subscribing to everything (unless I'm missing something).

In my application there are some tables/models I must subscribe to mutations, but equally there are other tables that seldom change and it would be fine to do a periodic refresh (ie. base refresh on an hourly/daily basis). If an application (ie. the mobile) could declare what tables/models wanted to subscribe to and that could be different to other applications (ie. the back end web app) then that would be fine. But I'm not aware of how to achieved that level of control to stay below the 100 subscription limit.

**Comment by CarlJoven** [comment]
Hi, @undefobj I don't need subscriptions for all of the models but when I tried to make the subscriptions param of the model directive null for all of the models which I don't need subscriptions it doesn't work with datastore. I only want to select which model is subscribed but every time I create a new model it forces me to opt-in with the subscriptions.

**Comment by TheMoums** [comment]
Hi @sacrampton,
I ran into exactly the same problem as yours about 1 year ago. When dealing with a large project, the limit of 33 tables rapidly becomes constraining. I have around 50 tables, some of them require subscriptions, some other don't. 

Basically I have divided my architecture into two kind of tables: those that will fully interact with DataStore (subscriptions, data stored in cache) and those that will not (I call these "_unsynced_" table). I currently have 30 tables fully working with DataStore and 20 tables that are unsynced. I choose to unsync a table if it will not require subscriptions and/or if it will contain a very large amount of data (> 50.000 records or a given client. These tables are really slowing down the full syncs in the app).

To unsync a table I just put the attribute **(@subscriptions : null)** in my schema.graphql and, parallel to that, I have a custom script that runs after each new deployment of the api and that sets (**syncable: false**) for each of these tables.

In the backend this makes absolutely no difference for my other resources (lambdas, dynamo streams, SQS queues, ...) as they only use the graphql queries/mutations to interact with the database. 
An other advantage of this method is that it allows me to keep the same **@auth** schema no matter if a table is synced or unsynced.

In the frontend however, as you might have guessed, the DataStore operations (create/update/delete) will not work for those unsynced tables. This is why, I simply use the graphql operations instead (graphql/queries.ts and graphql/mutations.ts) to interact with these tables. And, I sometimes perform a periodic refresh on these tables to make sure that my data stays consistent.
(NB: if you plan to implement this solution on your own and want to **list** every record of an unsynced table, do not use the _list_  queries as they only do scan+filter, use the _sync_ queries instead with your GSI).

Keep in mind that this is a workaround, and if the limit of 100 subscriptions could be increased, I would be the first to be thrilled.

**Comment by sacrampton** [comment]
Hi @TheMoums  - thanks for taking the time to put that down. At a high level that was where I thought we needed to go, glad for your confirmation (and detail). If it isn't too much trouble it would be helpful if you could show me an example of where you put @subscriptions : null in schema.graphql and where precisely you set the syncable:false after the new deployment. Assume that after you do this and run codegen that you don't need to go modifying any code there.

Thanks

Stephen

**Comment by TheMoums** [comment]
@sacrampton 
Here is an example of an unsynced table 
```graphql
 type BasicExampleOfUnsyncedTable
  @model(subscriptions: null) {
  id: ID!
  name: String!
}
```
If I know I'm about to deploy a new schema (api is in state _Update_ when running **amplify status**), I do **yarn deploy:api** (instead of amplify push). 
With a package.json in my frontend that contains
```json 
"scripts": {
    "deploy:api": "amplify push --yes && npm run unsync && amplify codegen",
    "unsync": "node ./script/unsynchronise.js"
  },
```
And unsynchronise.js (code that I'm really not proud of, feel free to improve it)
```js
const fs = require('fs');

const shouldUnsynchronize = (model) => {
  return model.attributes.some((attr) => attr.properties.subscriptions === null);
};

const schemaRaw = fs.readFileSync(__dirname + '/../src/models/schema.js', 'utf-8');
const schemaStr = schemaRaw.toString().split('= ')[1];
const schema = JSON.parse(schemaStr.split(';')[0]);
const schemaCpy = { ...schema };
const modelsKey = Object.keys(schema.models);
for (let key of modelsKey) {
  if (shouldUnsynchronize(schema.models[key])) {
    schemaCpy.models[key]['syncable'] = false;
  }
}

fs.writeFileSync(__dirname + '/../src/models/schema.js', `export const schema=${JSON.stringify(schemaCpy)};`, 'utf8');
```
Which should result to something like
```js
BasicExampleOfUnsyncedTable: {
      name: 'BasicExampleOfUnsyncedTable',
      fields: {
        id: { name: 'id', isArray: false, type: 'ID', isRequired: true, attributes: [] },
        name: { name: 'name', isArray: false, type: 'String', isRequired: true, attributes: [] },
   }
  syncable: false,
  pluralName: 'BasicExampleOfUnsyncedTables',
  attributes: [
       { type: 'model', properties: { subscriptions: null } }, 
    ]
}
```
(Of course in reality, the table has **@key** **@auth** and a lot of other fields, but they are not impacted by the script )

**Comment by undefobj** [comment]
Thank you for giving some helpful answers @TheMoums 

@sacrampton @CarlJoven the suggestions given by @TheMoums are exactly why I was asking this question. It sounds like you most likely do not need us to address this limit on the AppSync side from a service perspective to allow even more subscriptions, but give more clear documentation on disabling subscriptions and also introduce more features on how to control which models are syncable. For example, piggybacking off the above solution we are looking to add a feature in the future where you can have "local only" and "cloud only" models rather than just one ubiquitous "syncable" model like we have today.

Is my understanding correct?

**Comment by sacrampton** [comment]
Hi @undefobj @TheMoums @CarlJoven,

I'll take anything you can provide for now as anything is an improvement. However, what would be nice would be for each CLIENT to be able to specify which models it wants syncable. For example, I might have a master data app where I only need 20 models syncable. But I might have an inspection app that needs 30 models syncable and these might be different to the master data app. The suggestion above "hard codes" which models can and can't be syncable across all apps. Ideally it would be nice to allow flexibility at the client level for the client to specify which models it needs to sync for its own app specific purposes. The key is from the one database I might have many apps / solutions being built.

**Comment by sacrampton** [comment]
Hi @TheMoums - thank you so much for taking the time to document this - I really appreciate it and its super helpful.

Regards, Stephen

**Comment by undefobj** [comment]
> Hi @undefobj @TheMoums @CarlJoven,
> 
> I'll take anything you can provide for now as anything is an improvement. However, what would be nice would be for each CLIENT to be able to specify which models it wants syncable. For example, I might have a master data app where I only need 20 models syncable. But I might have an inspection app that needs 30 models syncable and these might be different to the master data app. The suggestion above "hard codes" which models can and can't be syncable across all apps. Ideally it would be nice to allow flexibility at the client level for the client to specify which models it needs to sync for its own app specific purposes. The key is from the one database I might have many apps / solutions being built.

Ok thanks this helps. We have the syncable/cloud-only/local-only models on our roadmap and this helps prioritize in the coming months. cc @manueliglesias @renebrandel

**Comment by JohnCashmore** [comment]
> @CarlJoven @JohnCashmore can you give more insights into why more than 100 subscriptions are needed? To be clear this is not a DataStore limit, it's a limit that AppSync has set. That being said 100 subscriptions is a very large number even for very large projects. Perhaps there is a specific use case that you're trying to accomplish which can be met another way than having more active subscriptions to a client?

Our specific usecase is similar to this from the docs https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/ios but we happen to have more than the limit items per page, the table tis very high volume in terms of traffic so subscribing to all updates causes us performance issues.

**Comment by JohnCashmore** [comment]
If it was possible to do something like

`
type Subscription {
  onCommentByPostIds(postCommentsId: [ID!]): [Comment]
    @aws_subscribe(mutations: ["createComment"])
}
`

to limit the ids to those on the page it would help in our case

**Comment by sacrampton** [comment]
Hi @TheMoums - just wanted to follow up on a comment in your earlier response (https://github.com/aws-amplify/amplify-js/issues/6260#issuecomment-831080188)

"...This is why, I simply use the graphql operations instead (graphql/queries.ts and graphql/mutations.ts) to interact with these tables. And, I sometimes perform a periodic refresh on these tables to make sure that my data stays consistent.
(NB: if you plan to implement this solution on your own and want to list every record of an unsynced table, do not use the list queries as they only do scan+filter, use the sync queries instead with your GSI)..."

Firstly, when I run amplify codegen models I get graphql/queries.js, graphql/mutations.js, graphql/subscriptions.js and graphql/schema.json - in the above you talk of queries.ts / mutations.ts - am I missing something? There is index.d.ts and schema.d.ts in the models folder.

Secondly, how do I use GSI's like you reference. For example, on a model I have the following GSI's and I can query them with the queryField instead of list like you recommend. I'm not sure how to select a specific GSI in say a base query?
``
  @key(name: "byDefectMediaAssetId", fields: ["defectMediaAssetId"], queryField: "DefectMediaAsset") 
  @key(name: "byDefectMediaDefectId", fields: ["defectMediaDefectId"], queryField: "DefectMediaDefect") 
  @key(name: "byDefectMediaOperatingUnitId", fields: ["defectMediaOperatingUnitId"], queryField: "DefectMediaOperatingUnit") 
  @key(name: "byDefectMediaPackageId", fields: ["defectMediaPackageId"], queryField: "DefectMediaPackage") 
  @key(name: "byDefectMediaPlantId", fields: ["defectMediaPlantId"], queryField: "DefectMediaPlant") 
``

Appreciate any input you have.... Am finding the need to "hack" codegen generated files to get it to work and appreciate the input of someone who has hacked it successfully in the  past.

**Comment by TheMoums** [comment]
Hey @sacrampton,

For your first question: **amplify codegen models** rebuilds the _models_ folder. I was talking about **amplify codegen** which rebuilds the _graphl_ folder. Not to worry about the file extension, It is because I am using Typescript instead of Javascript but queries.js and mutation.js are perfectly fine as well.

As for your 2nd question, in case of doubts, it is always good to take a look at the resolvers built by the api (_amplify/backend/api/${YOUR_API_NAME}/build/resolvers_). The only way I have found to use my GSIs is by using **sync queries**. If you open one sync resolver (Query.sync${TABLENAME}.req.vtl) and read through it, you''ll quickly find that when passing an 'eq' filter with your request, the vtl checks that the first argument of your filter array is a GSI. 

- If it is, it performs a query instead of a scan and checks for the second argument to be a sort key (and all the rest will be used as a standard filter). 
- If it is not, it simply performs a scan+filter

The sync expressions are built in such way so that the syncExpressions of DataStore allow a much more efficient syncing for multi-tenant app. I'm just using these queries for another purpose^^

Here is an example of query that uses clientId as a GSI:
![screen](https://user-images.githubusercontent.com/22890903/119453435-b7d56a80-bd37-11eb-939b-bc757dbb3b8e.png)
![screen](https://user-images.githubusercontent.com/22890903/119453752-0b47b880-bd38-11eb-8d0b-10ba8844d6bc.png)

**Comment by emmafass** [comment]
@TheMoums hi there! Thank you for sharing your solution to this problem. Out of curiosity, do you have a method for using [AppSync Subscriptions](https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/js) for the unsynched tables?

If I'm correct, when you are add `@model(subscriptions: null)` to "BasicExampleOfUnsyncedTable", then `amplify codegen` will not create any subscriptions for this table in `graphql/subscriptions`. I guess you could write and maintain a custom subscription for "BasicExampleOfUnsyncedTable" in a separate file. 

I'm curious about this because I have a few places in my application where there is a form component on a page that creates data. There is a display table component on the same page that should automatically update to display the data. I've hit the 100 subscriptions limit, so some of the tables will need to be unsynched.

**Comment by sacrampton** [comment]
@TheMoums - thanks also for sharing the sync<Model> resolvers - I get it now and wasn't aware how much more sophisticated they are than the list<Model> resolvers. I had been using a queryField to try to get to the GSI's, but that was a poor solution. Thanks again

**Comment by TheMoums** [comment]
Hi @emmafass,
I have thought about it i.e. to find an other way so that I could use the DataStore subscriptions for my synced models and the Appsync subscriptions for my unsynced models. Unfortunately, both subscriptions are intrinsically the same. They are on the same WebSocket so the limit of 100 subscriptions is applicable for both DataStore and Appsync subscriptions. If you have reached the limit with DataStore, you therefore do not have any Appsync subscriptions left.

As for the example you provided, unfortunately I don't see a clean way to do it:
- Simply forcing a refresh of your data after submitting it at the end of your form, so that at least the user that submitted the data has the latest ones (but the other users will not see the updates).
- If you do not want to make too many refresh, you can maintain a state of your unsynced tables in some kind of contexts (e.g. React contexts) on your app. (but again, same problem as before)
- The hackiest way to bypass the subscriptions limit and still have subscriptions would be to create a subscription table (that you listen to) on which you create "subscription records" with a tableName and a GSI so that whenever their subscription fires, every user that has access to the subscription of the record know that they must refetch the tableName on the GSI.
But this solution requires a lot of efforts + require additional writes to the db to write these "subscription records". I haven't tried it out, but if you do, use a small ttl on these records that they are automatically deleted after everyone has refetch their data.

**Comment by emmafass** [comment]
@TheMoums thank you for your response! That's what I was worried about. Option 3 is really interesting, but you're right that it requires a lot of effort. I think I can avoid it for now.

**Comment by felixolivares** [comment]
Is there any updates on this issue ? I'm not sure if there is a status on where you are trying to find a feature to be able to subscribe or unsubscribe on-demand. I'd really appreciate your input. Thanks!

**Comment by samputer** [comment]
I just got burned by this limitation also, at a frustratingly critical moment. We're in the process of marking a handful of tables as having no subscriptions but I anticipate we're going to hit the 100 limit again in the near future. Is there any likelihood of this number of subscriptions being increased?

**Comment by undefobj** [comment]
> I just got burned by this limitation also, at a frustratingly critical moment. We're in the process of marking a handful of tables as having no subscriptions but I anticipate we're going to hit the 100 limit again in the near future. Is there any likelihood of this number of subscriptions being increased?

Can you open up an AWS support request with the AppSync team? It's currently a limit which is being discussed.

**Comment by danrivett** [comment]
@TheMoums thank you so much for your solution to set the `syncable` flag to `false` for any model type with `subscriptions: null`. That saved me a lot time, so I appreciate it.

I was going to update our `package.json` file similar to you to post process the `schema.js` as well, but then decided to take a look at the root cause to see if it was fixable as seems on paper to be a simple problem to solve (famous last words!).

I came across [here](https://github.com/aws-amplify/amplify-codegen/blob/master/packages/appsync-modelgen-plugin/src/visitors/appsync-json-metadata-visitor.ts#L196) as the likely root cause and so decided to make an attempt at fixing it by creating an issue - aws-amplify/amplify-codegen#397 -  alongside a PR (aws-amplify/amplify-codegen#398) to fix it.

@undefobj any chance you could encourage active consideration of the PR given this bug has been open for such a long time? I'd love not to have to build our DataStore models from a fork if at all possible.

**Comment by chstrong** [comment]
Hi guys, 

Based on this issue, I'm currently trying to make a decision if I should use a basic REST backend with Lambda, or if I should use GraphQL or DataStore. Obviously using GraphQL or DataStore would be easier, but obviously not with the current issues at hand.

Question 1: 
- Is this AppSync limit only affecting DataStore, or also GraphQL?

Question 2:
- Am I right in the assumption that the possible workaround is to:
  - Set @model(subscriptions: null) for each model in amplify/backend/api/amplifyDatasource/schema.graphql
  - set "syncable": false for each model in src/models/schema.js

If I can get around the issue, by utilizing the workaround, for my use case I should be fine with it, until the issue has been fixed. 

But if the above wouldn't work, or if this also affects GraphQL then I'd rather go with a simple Lambda REST backend, even though it'll be much more boilerplate code, and I can't utilize the relationship feature that I'd have with GraphQL or Datastore.

Any thoughts based on your experience?

**Comment by undefobj** [comment]
> Hi guys, 
> 
> Based on this issue, I'm currently trying to make a decision if I should use a basic REST backend with Lambda, or if I should use GraphQL or DataStore. Obviously using GraphQL or DataStore would be easier, but obviously not with the current issues at hand.
> 
> Question 1: 
> - Is this AppSync limit only affecting DataStore, or also GraphQL?
> 
> Question 2:
> - Am I right in the assumption that the possible workaround is to:
>   - Set @model(subscriptions: null) for each model in amplify/backend/api/amplifyDatasource/schema.graphql
>   - set "syncable": false for each model in src/models/schema.js
> 
> If I can get around the issue, by utilizing the workaround, for my use case I should be fine with it, until the issue has been fixed. 
> 
> But if the above wouldn't work, or if this also affects GraphQL then I'd rather go with a simple Lambda REST backend, even though it'll be much more boilerplate code, and I can't utilize the relationship feature that I'd have with GraphQL or Datastore.
> 
> Any thoughts based on your experience?

This is AppSync limit, not DataStore. We are working on this on the AppSync side in the coming months to see if we can relax the limit or make it configurable. In the meantime I suggest collapsing your models (try to stay under 30) or disabling subscriptions on models where realtime isn't necessary.

**Comment by sacrampton** [comment]
Hi @chstrong - we use dynamic authorization so the solution for us was to turn off subscriptions all together.

The answer for us is to turn off all subscriptions on the server (set @model(subscriptions:null) on every model) - at the moment subscriptions are only filtered on static authorization - in our case that means every change every person makes goes to every mobile unless we have this set. This turns of subscriptions on the server.

 Then in schema.js just set the models you want to sync (not all of them) to syncable: true - if you don't have this set to true then the model won't sync to DataStore. You won't be able to observe any subscriptions in your code as the server has it turned off.

We are in production with this arrangement. To get updates the user just has to do a delta-Sync - would be good if there was a call similar to database.start where we could do a delta-sync - at the moment requires user to re-open the app. In future we want subscriptions for our app, but need filtering to match our syncExpressions in DataStore - and this announcement has the beginnings of getting there.

https://aws.amazon.com/about-aws/whats-new/2022/04/aws-appsync-enhanced-filtering-graphql-subscriptions/

**Comment by chstrong** [comment]
Hi @sacrampton @undefobj - thanks a lot for your feedback. Much appreciated. I'll run some tests.

**Comment by undefobj** [comment]
Hello @sacrampton and others. We have rolled out changes in AppSync that will allow you to raise this limit with a request via your support team. Public docs on this being a soft limit now will be out soon.
