### ISSUE TITLE
Save user in status FORCE_CHANGE_PASSWORD

### ISSUE THREAD

**Issue by yourGuy** [aws-amplify/amplify-js#6307]
**Is your feature request related to a problem? Please describe.**
I need a user object for calling changePassword/completeNewPassword when user in status FORCE_CHANGE_PASSWORD 

**Describe the solution you'd like**
Save user in status FORCE_CHANGE_PASSWORD to be available in via currentAuthenticatedUser 

**Describe alternatives you've considered**
I looked at issue #24 and IMHO it's solution is insufficient and promotes unsafe storage of user information
 "You'll need to hold this user object" , unless I'm missing something, basically promotes a "by hand" saving of the user object resoled by signIn to local storage, if you wanted it to persist between reloads (something that happens a lot in auth flows)
Note: in my view , after a successful signIn for user in status FORCE_CHANGE_PASSWORD, the user **is** authenticated albit in very restricted scope 
Thank you

**Comment by cwomack** [comment]
@yourGuy, thank you for opening this issue and apologies we didn't get a reply to it sooner.  Let me know if I'm misunderstanding this feature request, but it seems like you're implying the need for the user object to be retained/cached/stored in some way when a user is in the `FORCE_CHANGE_PASSWORD` for "Confirmation Status".  

There shouldn't be a need for this since the authentication flow would require a new sign-in after the user is in this status regardless.  This new sign-in would create a new session and be verified on the server side with Cognito.  I'm sure the docs for [Authentication](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js/) within Amplify have changed a bit since this issue was opened (possibly even Cognito's documentation tied to this). The [temporary passwords](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminSetUserPassword.html) associated with users in this "Confirmation Status" default to a 7 days expiration timeframe if done manually through the Cognito console.  

Were you doing this through the Cognito console or via the AWS CDK? And let me know if I misinterpreted the context or intent of this feature request.

**Comment by yourGuy** [comment]
@cwomack thank you for the reply, I no longer work on the project that prompted the feature request, and my memory of the use case might not be the most accurate but if it is of interest I think the use case was as follows :
- we had a custom cognito auth implementation and most users used it to create their accounts 
- some "special" users wanted their accounts created and confirmed for them 
- so we would do that in the console and them send them to the custom ui to log in with the temporary password 
- cognito would respond with FORCE_CHANGE_PASSWORD
- we would present them with the appropriate ui to get their new password 
- then we would want to make the call to change the password and for that call we would need the user object.
hope this makes sense and / or helps somebody but if not feel free to close the issue
