### ISSUE TITLE
Fails to load in an private/incognito browser session within an iframe

### ISSUE THREAD

**Issue by karldanninger** [aws-amplify/amplify-js#6318]
**Describe the bug**
When an amplify app is embedded via an iframe in a private/incognito browser session, a SecurityError stops the app from running. 

**To Reproduce**
Embed an app in an iframe on another website and load it from a private browser session.

**Expected behavior**
The app should load as you would normally expect, regardless if in incognito mode or not. 

**Screenshots**
Running the app through ngrok, here is the stacktrace. If you were to build/deploy the app, the iframe would be blank with the same error printed in the JS console.

![Screen Shot 2020-07-13 at 10 12 08 PM](https://user-images.githubusercontent.com/792464/87372847-8a843180-c556-11ea-8630-f54c7e0de0e0.png)

**Additional context**
To me, it looks like Amplify has a dependancy that isn't guarding against accessing localStorage from within a private browser session, or `amplify/pubsub` is missing a fallback to accessing window.localStorage when in private browser. In the screenshot you can see one of the top dependancies being `amplify/pubsub`

**Comment by karldanninger** [comment]
Hey @amhinson is there anywhere I could help with this issue?
I'm unfamiliar with the `@aws-amplify/pubsub` repo as a standalone package. Is there sample repos I could fork? Alternatively could I split up `aws-amplify` deps in `package.json` to narrow down the issue?

**Comment by amhinson** [comment]
It looks like this is coming from `paho-mqtt`. From searching their repo, it looks like a [PR](https://github.com/eclipse/paho.mqtt.javascript/pull/191) to fix this issue has been merged a year ago, but there has been no release since then.

**Comment by karldanninger** [comment]
Sweet @amhinson! I'll poke to see if @icraggs could tag 1.1.1

**Comment by karldanninger** [comment]
Hey @amhinson does this help?

package.json dependancies:
```
    "aws-amplify": "^3.0.22",
    "aws-amplify-react": "^4.1.21",
    "aws-appsync": "^4.0.0",
    "aws-appsync-react": "^4.0.0",
```

**Comment by amhinson** [comment]
Are you using PubSub directly?

**Comment by karldanninger** [comment]
No, I'm not.

**Comment by mkrn** [comment]
Is there a way to prevent paho from loading at all? I'd like to use this opportunity to switch to WebSockets (https://aws.amazon.com/blogs/mobile/appsync-realtime/) way but not finding how to do it?

**Comment by mkrn** [comment]
@karldanninger I went around it by patching the paho-mqtt with this https://www.npmjs.com/package/patch-package

**Comment by karldanninger** [comment]
@mkrn that is wonderful to hear! Wow. 

Could you explain what you did to patch it? Was it literally just `yarn patch-package package-name` ?

I still hope that Amplify might either lose the dependancy or fix it somehow.. It seems the authors of `paho-mqtt` are non-responsive.

**Comment by mkrn** [comment]
@karldanninger 
- Edit node_modules/paho-mqtt/paho-mqtt.js  to match the PR 
- Run `npx patch-package paho-mqtt` 
-  Add this script to package.json  "postinstall": "patch-package"
- npm i patch-package 

Worked like a miracle

**Comment by sammartinez** [comment]
resolving as the above workaround is what we would recommend to do to resolve this issue since its out of the control of Amplify as @amhinson has called out.

**Comment by ramadimasatria** [comment]
Hi @sammartinez, we are also experiencing this issue where our app is breaking when run in iframe mode.

I understand that the root cause is out of control of Amplify, but I think we can mitigate it by at least not running `paho-mqtt` when it's not being used.

I noticed that `paho-mqtt` is an [IIFE](https://github.com/eclipse/paho.mqtt.javascript/blob/master/src/paho-mqtt.js#L84), and it will run everytime it's imported ([here](https://github.com/ramadimasatria/amplify-js/blob/main/packages/pubsub/src/Providers/MqttOverWSProvider.ts#L13) and [here](https://github.com/ramadimasatria/amplify-js/blob/main/packages/pubsub/src/Providers/index.ts#L17))

Our use case is we just use the `api-graphql`, which only uses the `AWSAppSyncRealTimeProvider`, but currently it will [import all providers](https://github.com/ramadimasatria/amplify-js/blob/main/packages/api-graphql/src/GraphQLAPI.ts#L26) which causes this issue. Is it possible to update to only import the necessary providers? I would also be glad to submit PR for this.
