### ISSUE TITLE
federatedInfo from cache is null

### ISSUE THREAD

**Issue by dd-ssc** [aws-amplify/amplify-js#6400]
**Describe the bug**

In my React application, I use Google SignIn with AWS Cognito exactly as shown [here](https://docs.amplify.aws/lib/auth/advanced/q/platform/js#google-sign-in-react).

First up: THANK YOU VERY MUCH for the awesome documentation - super helpful and clearly one of the reasons why AWS in general and AWS Amplify especially stand out from the rest! ❤️ 👍 💯

Now, I get valid and plausible credentials using `const credentials = await Auth.federatedSignIn(...)`.

However, when I proceed to [retrieve a JWT token](https://docs.amplify.aws/lib/auth/advanced/q/platform/js#retrieve-jwt-tokens) using `const federatedInfo = Cache.getItem('federatedInfo');`, `federatedInfo` is always `null`.

When I look at Chrome DevTools > _Storage_ > _Local Storage_, clear the cache and log back in using Google SignIn, I see how an `aws-amplify-federatedInfo` key is added with plausible contents, e.g.:

```
{
  expires_at: 159 ... 044
  provider: "google"
  token: "eyJ ... xxw"
  user:
  {
    id: "us-east-1:f16 ... 2db",
    email: "<redacted>",
    name: "<redacted>"
  }
}
```

Further, when I list all cache items using `Cache.getAllKeys()`, all I get is one unrelated `AWSPinpoint_3f38 ... b64` key, although the Chrome Dev Console shows more keys.

What am I doing wrong?

**To Reproduce**

Run code from official AWS docs referenced above.

**Expected behavior**

Expected `Cache.getItem('federatedInfo');` to return info on the federated user.

**Code Snippet**

See code in official AWS docs referenced above.

**Environment**

```
$ npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 52.19 MB / 16.00 GB
    Shell: 5.0.18 - /usr/local/bin/bash
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 77.0.1
    Safari: 13.1.2
  npmPackages:
    @aws-amplify/core: ^3.4.2 => 3.4.2
    @aws-amplify/pubsub: ^3.0.20 => 3.0.20
    @sentry/browser: ^5.19.2 => 5.19.2
    @storybook/addon-actions: ^5.3.19 => 5.3.19
    @storybook/addon-links: ^5.3.19 => 5.3.19
    @storybook/addons: ^5.3.19 => 5.3.19
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4
    @storybook/react: ^5.3.19 => 5.3.19
    aws-amplify: ^3.0.20 => 3.0.20
    aws-amplify-react: ^4.1.19 => 4.1.19
    bootstrap: ^4.5.0 => 4.5.0
    google-auth-library: ^6.0.5 => 6.0.5
    react: ^16.13.1 => 16.13.1
    react-bootstrap: ^1.2.2 => 1.2.2
    react-dom: ^16.13.1 => 16.13.1
    react-google-button: ^0.7.1 => 0.7.1
    react-redux: ^7.2.0 => 7.2.0
    react-router-dom: ^5.2.0 => 5.2.0
    react-scripts: ^3.4.1 => 3.4.1
    redux: ^4.0.5 => 4.0.5
    uuid: ^8.2.0 => 8.2.0
  npmGlobalPackages:
    npm-check-updates: 7.0.2
    npm: 6.14.7
    ttab: 0.6.1
```

**Comment by dd-ssc** [comment]
**Update**

As a workaround, I am able to obtain the federated info I need as described [here](https://stackoverflow.com/a/49575377):

```
const federatedInfo = localStorage.getItem("aws-amplify-federatedInfo");
```

I don't know where `localstorage` comes from, might be some builtin React or browser thing; I don't care, this gets me what I need.

**Comment by Hillsie** [comment]
I am using exactly the same work around as @dd-ssc ;
The root cause appears to be the cache naming structure. I am also using amplify cache in my project and  have observed that if I set the cache with value it has the flowing pattern:
`aws-amplify-cache<key>` so when you use `Cache.getItem(<key>)`  the correct key value is retrieved. 
however, the federated item entry is as above, with `aws-amplify-federatedInfo`,  I would imagine that if the key was `aws-amplify-cachefederatedInfo` the method would work. However, looking in the package, cannot find where this is set on local storage.

This has really messed with the flow of federated login.

**Comment by Hillsie** [comment]
Around about this area.
![image](https://user-images.githubusercontent.com/17975287/89365184-72e43700-d717-11ea-9b23-594b8950ca54.png)

**Comment by sammartinez** [comment]
Hello @dd-ssc, apologizes on the late response to this. Thanks for the nice callouts! We use [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), in order to store these keys as you have called out above so they can persist across browser sessions and expire based on your UserPool. Seeing that you had a workaround, are you looking for additional support on this? Please let us know.

**Comment by dd-ssc** [comment]
Hey @sammartinez 😄 ,
no worries at all, thanks for getting back to this! 👍 
I'm fine with the workaround; closing.
