### ISSUE TITLE
Federated Sign In example if using amazon-cognito-identity-js only

### ISSUE THREAD

**Issue by batmanwannabe** [aws-amplify/amplify-js#6477]
We have a old app that uses amazon-cognito-identity-js for authentication, I need to add SSO login to it, I don't want to update to Amplify just for this. Is there any way amazon-cognito-identity-js can achieve this?

I searched online but could not find anything

**Comment by ashika01** [comment]
@solomon911 I will try to find if there is some example/sample explaining this. Meanwhile, have you tried taking a look into `packages/auth` for our source code on handling federation flows?!

**Comment by cwomack** [comment]
@batmanwannabe, did you get a chance to review what @ashika01 mentioned above?  It's obviously been quite some time since this issue/feature request was opened, but are you still trying to implement SSO with an older Amplify app?  If so, what version and what Social Provider are you trying to do it with?

**Comment by cwomack** [comment]
Closing this since we have not heard back from you.  If you'd like to reply back and provide additional context or address the questions asked above, we'd be happy to reopen this issue.

Thank you!
