### ISSUE TITLE
@aws-sdk v1.0.0-gamma.4 does not export ESM

### ISSUE THREAD

**Issue by superCarton** [aws-amplify/amplify-js#6685]
**Describe the bug**
In an ESM application using aws-amplify library 3.4.6, we encounter a runtime issue when the library is calling functions on @aws-sdk/credential-provider-cognito-identity.

Eg. of javascript runtime issue when calling :
`object(...) is not a function`

In my case, it was breaking on the [following line](https://github.com/aws-amplify/amplify-js/blob/aws-amplify%403.0.24/packages/core/src/Credentials.ts#L267
) which was generating a login issue during the oauth step.

After investigation, @aws-sdk/credential-provider-cognito-identity@1.0.0-gamma.4 does not export ESM in the NPM published versionned. This issue is fixed from @aws-sdk/credential-provider-cognito-identity@1.0.0-gamma.6

[Issue opened on @aws-sdk](https://github.com/aws/aws-sdk-js-v3/issues/1476)

**To Reproduce**
```
$ yarn add @aws-sdk/credential-provider-cognito-identity@1.0.0-gamma.4
$ ls node_modules/@aws-sdk/credential-provider-cognito-identity/dist
cjs
```

```
$ yarn add @aws-sdk/credential-provider-cognito-identity@1.0.0-gamma.6
$ ls node_modules/@aws-sdk/credential-provider-cognito-identity/dist
cjs es
```

**Expected behavior**
All aws-sdk packages should export ESM

**Additional context**
Happens on all browsers.

**Suggested fix**
Bump @aws-sdk packages dependencies to v1.0.0-gamma.6 or higher

**Comment by sammartinez** [comment]
@superCarton Thanks for reporting this, We are aware of the export to ESM is not being export because of `gamma.4` version. We are working on testing the later version, `gamma.6` in order to validate non breaking changes in order to get this issue fixed. I will provide another update later on in the week. Thanks!

**Comment by sammartinez** [comment]
@superCarton ETA next week in getting a deployment out for this. Just wanted to provide another update.

**Comment by wlee221** [comment]
Hello, this is fixed in [#6748](https://github.com/aws-amplify/amplify-js/pull/6748) and is now published on `unstable` [npm tag](https://www.npmjs.com/package/aws-amplify/v/3.1.2-unstable.6). We will update you once it gets released to latest -- meanwhile, please feel free to use `aws-amplify@unstable` to unblock yourself, thanks!

**Comment by wlee221** [comment]
The fix is now released. Thanks for bringing this to our attention 👍

**Comment by superCarton** [comment]
Thanks a lot for your help @wlee221 @sammartinez

**Comment by sammartinez** [comment]
Thanks for reporting this @superCarton !! Always happy to help

**Comment by shox-harri** [comment]
Many thanks @sammartinez and @wlee221 for the super fast fix I really appreciate it.
