### ISSUE TITLE
Adding support for adminUpdateUserAttributes

### ISSUE THREAD

**Issue by matansagee** [aws-amplify/amplify-js#6704]
**Is your feature request related to a problem? Please describe.**
Yes, we are trying to build a user management tool and let the admins to change other users attributes
adminUpdateUserAttributes

**Describe the solution you'd like**
Support adminUpdateUserAttributes in the Admin Queries

**Describe alternatives you've considered**

**Additional context**
Add any other context, an idea of the implementation or screenshots about the feature request here.

**Comment by eperezf** [comment]
Any news on this feature? Would love to have it as we are doing something similar.

**Comment by nadetastic** [comment]
Hi @eperezf @matansagee sorry for the delay on this.

Since this action is exposed by Cognito [1][2], you should be able to add it to your AdminQueries function that is generated when adding admin queries [3] to your auth resources. Here is an example of how this could look like:

```js
async function updateUserAttributes(attributes, username) {
  
  var params = {
    UserAttributes: attributes, // Should be an array
    UserPoolId: 'STRING_VALUE',
    Username: username
  };

  console.log(`Attempting to update ${username} attributes`);

  try {
    await cognitoIdentityServiceProvider.adminUpdateUserAttributes(params).promise();
    console.log(`Success updating ${username} attributes`);
    return {
      message: `Success updating ${username} attributes`,
    };
  } catch (err) {
    console.log(err);
    throw err;
  }
}
```

Then in your express app, be sure to add this method to a route:

```js
app.post('/updateUserAttributes', async (req, res, next) => {
  if (!req.body.username || !req.body.attributes) {
    const err = new Error('username and attributes are required');
    err.statusCode = 400;
    return next(err);
  }

  try {
    const response = await updateUserAttributes(req.body.username, req.body.attributes);
    res.status(200).json(response);
  } catch (err) {
    next(err);
  }
});
```


[1] https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminUpdateUserAttributes.html#API_AdminUpdateUserAttributes_SeeAlso
[2] https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminUpdateUserAttributes-property
[3] https://docs.amplify.aws/cli/auth/admin/#enable-admin-queries

**Comment by nadetastic** [comment]
@eperezf @matansagee I have updated the documentation with some steps on how you can add your own admin actions that are supported by Cognito but not enabled by default.

- https://docs.amplify.aws/cli/auth/admin/#adding-admin-actions

If you have any questions, let me know - I'll be closing this issue out now, thank you all!
