### ISSUE TITLE
packages too large, how can it be reduced?

### ISSUE THREAD

**Issue by eliecer2000** [aws-amplify/amplify-js#6769]
I have been using amplify for a long time for a web app, but lately I use it for a mobile app, and when compiling I see the number of packages that are possibly unnecessary, it takes an app from 200K to almost 5mb for me, the number of unused dependencies seems to be excessive, there is a way to remove or limit the amount of dependencies?

**Comment by harrysolovay** [comment]
Below is my first attempt to help out! This issue might be (in part) the result of your bundler configuration––incase the solution below doesn't apply to you, please follow up with details about your workspace (CRA, CRA ejected / patched, NextJS, etc.).

The AmplifyJS lib depends on the [`aws-sdk`](http://github.com/aws/aws-sdk-js), which unfortunately takes [a toll](https://bundlephobia.com/result?p=aws-sdk@2.749.0) on bundle size. However, it shouldn't need add 5mb. Depending on what categories you're using, try the following:

Instead of importing a category like so:

```ts
import { Auth } from "aws-amplify";
```

Import it like so:

```ts
import { Auth } from "@aws-amplify/auth";
```

And call configure on the singleton:

```ts
Auth.configure(yourConfig);
```

**Question for team members**:

It's worth raising the question of writing a lighter-weight client to sign and send off AWS requests. @sammartinez would it be worthwhile to create a label (perhaps `runtime-bloat`), so that we can more effectively gage when/how to tackle such issues as this. My hunch is that the stable release of [V3](https://github.com/aws/aws-sdk-js-v3) will give us [lighter weight browser clients](https://bundlephobia.com/result?p=@aws-sdk/client-cognito-identity-browser@0.1.0-preview.2), so we don't have to take on this implementation.

**Comment by sw-yx** [comment]
importing the scoped modules shouldn't matter because treeshaking is supposed to work. 

there may be an [xy problem](https://en.m.wikipedia.org/wiki/XY_problem) here. what is root cause of the 5mb? we need a breakdown. OP, can you run https://www.npmjs.com/package/webpack-bundle-analyzer or the Rollup equivalent?

**Comment by eliecer2000** [comment]
> ¡A continuación se muestra mi primer intento de ayudar! Este problema puede ser (en parte) el resultado de la configuración de su paquete; en caso de que la solución a continuación no se aplique a usted, haga un seguimiento con detalles sobre su espacio de trabajo (CRA, CRA expulsado / parcheado, NextJS, etc.).
> 
> El lib AmplifyJS depende del [`aws-sdk`](https://github.com/aws/aws-sdk-js)que, lamentablemente, tiene [un peaje](https://bundlephobia.com/result?p=aws-sdk@2.749.0) en el tamaño del paquete. Sin embargo, no debería ser necesario agregar 5 MB. Dependiendo de las categorías que esté usando, intente lo siguiente:
> 
> En lugar de importar una categoría como esta:
> 
> ```ts
> importar  {  Auth  }  de  "aws-amplify" ;
> ```
> 
> Importarlo así:
> 
> ```ts
> importar  {  Auth  }  de  "@ aws-amplify / auth" ;
> ```
> 
> Y llame a configure en el singleton:
> 
> ```ts
> Auth . configurar ( yourConfig ) ;
> ```
> 
> **Pregunta para los miembros del equipo** :
> 
> Vale la pena plantear la cuestión de escribir un cliente de menor peso para firmar y enviar solicitudes de AWS. @sammartinez, ¿valdría la pena crear una etiqueta (tal vez `runtime-bloat`), para que podamos evaluar de manera más efectiva cuándo / cómo abordar problemas como este? Mi corazonada es que la versión estable de [V3](https://github.com/aws/aws-sdk-js-v3) nos dará [clientes de navegador más livianos](https://bundlephobia.com/result?p=@aws-sdk/client-cognito-identity-browser@0.1.0-preview.2) , por lo que no tenemos que asumir esta implementación.

de esta manera estoy importando mis componentes, como tu dices, las dependencias de @ aws-sdk son muy pesadas

**Comment by eliecer2000** [comment]
> Below is my first attempt to help out! This issue might be (in part) the result of your bundler configuration––incase the solution below doesn't apply to you, please follow up with details about your workspace (CRA, CRA ejected / patched, NextJS, etc.).
> 
> The AmplifyJS lib depends on the [`aws-sdk`](https://github.com/aws/aws-sdk-js), which unfortunately takes [a toll](https://bundlephobia.com/result?p=aws-sdk@2.749.0) on bundle size. However, it shouldn't need add 5mb. Depending on what categories you're using, try the following:
> 
> Instead of importing a category like so:
> 
> ```ts
> import { Auth } from "aws-amplify";
> ```
> 
> Import it like so:
> 
> ```ts
> import { Auth } from "@aws-amplify/auth";
> ```
> 
> And call configure on the singleton:
> 
> ```ts
> Auth.configure(yourConfig);
> ```
> 
> **Question for team members**:
> 
> It's worth raising the question of writing a lighter-weight client to sign and send off AWS requests. @sammartinez would it be worthwhile to create a label (perhaps `runtime-bloat`), so that we can more effectively gage when/how to tackle such issues as this. My hunch is that the stable release of [V3](https://github.com/aws/aws-sdk-js-v3) will give us [lighter weight browser clients](https://bundlephobia.com/result?p=@aws-sdk/client-cognito-identity-browser@0.1.0-preview.2), so we don't have to take on this implementation.

this way I am importing my components, as you say, the @ aws-sdk dependencies are very heavy

**Comment by eliecer2000** [comment]
![Screenshot_74](https://user-images.githubusercontent.com/27373195/92793624-2f16ca00-f374-11ea-8694-2e40095f09c3.png)

**Comment by eliecer2000** [comment]
1.13 mb of the libraries that I am using more, 1.8 mb of @ aws-sdk is 2mb, so far I have achieved this by configuring the webpack, but if there was a way to download it more it would be great.
