### ISSUE TITLE
AmplifyAuthenticator memory leak

### ISSUE THREAD

**Issue by skiltoni** [aws-amplify/amplify-js#6840]
**Describe the bug**

I'm following the documented example for recommended usage (https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#recommended-usage).

If I `console.log` inside `onAuthUIStateChange` then the logged message increases by one on every sign out, indicating a new function is created while the old function(s) are also maintained.

These duplicate functions are all called on signing in again, so state is updated x times, resulting in x calls to render the app.

**To Reproduce**

As above.

**Expected behavior**

`onAuthUIStateChange` to be called once per auth state change.

**Code Snippet**

I'm using the code snippet found in the docs here:
https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#recommended-usage

**Comment by manueliglesias** [comment]
Hi @skiltoni 

Thank you for the report, I've reproduced the bug and I am labeling the issue as such.

---

By adding a `console.log`, the messages are printed x+1 times each time

```tsx
    React.useEffect(() => {
        return onAuthUIStateChange((nextAuthState, authData) => {
            setAuthState(nextAuthState);
            setUser(authData);

            console.log('Hello')
        });
    }, []);
```

![image](https://user-images.githubusercontent.com/6154160/94068587-3e4e3c80-fda4-11ea-9c39-c5140df63d04.png)

**Comment by mtliendo** [comment]
I created a gist that uses `useReducer` and the issue is still present. 

Looking at how the listener is constructed, the `onAuthUIStateChange` function simply wraps the `Hub` module, and I was able to verify that an unsubscribe function is returned. Though a couple of thoughts:

1. When a user signs out, the handler isn't removed -- this makes sense since the component isn't unmounted, but simply changing states.
2. As noted, this only happens when a user signs in (the other auth enums don't retrigger), which sounds like it's at that point the listener first gets set up. 


@manueliglesias Happy to go deeper into this if you could share your thoughts or provide some additional insight 🙂 

![Screen Shot 2021-01-06 at 12 12 41 PM](https://user-images.githubusercontent.com/5106417/103806709-0d280e00-501b-11eb-9021-a3cda16529b0.png)

![Screen Shot 2021-01-06 at 12 27 21 PM](https://user-images.githubusercontent.com/5106417/103806585-dfdb6000-501a-11eb-9345-73a4e2a8c494.png)

**Comment by hkjpotato** [comment]
looking into it, during my local test, I think the problem is not the setState callback being registered multiple time. 

It will only be registered once, yet every time customer signout, an event related to `customGreetingSignOut` will be added (even it exists before) and dispatched. I will look more into it to see how it is triggered and if there is a way to cancel it.
