### ISSUE TITLE
AppSync: Cursor based pagination has a funny bug where NO items are returned, but a nextToken is.

### ISSUE THREAD

**Issue by jamesone** [aws-amplify/amplify-js#6997]
**Describe the bug**

When using cursor based pagination on an AppSync model list, it will return an empty `items` array with a NON NULL`nextToken` which signifies that there are more results, when I query for the next result set, it returns the 3 results that match my query and filter. I am using a limit of 10 & there are only 3 results, I'm confused to why AppSync is not returning these 3 results in my first query? (it should return the 3 results & the nextToken should be NULL)

Context:

- I have a tabview for a screen, the first tab shows the PENDING TODO items, the second tab shows the COMPLETED TODO items.
- I have 3 results that match my COMPLETED filter
- I have around 36 results that match my PENDING filter

**Code Snippet / Explanations**

This is the query for listing the PENDING todos, as u can see there is a limit of 10 & an optional nextToken. This work as expected, I am able to paginate the results correctly.

```
query listTodos($nextToken: String) {
  listTodos(limit: 10, nextToken: $nextToken, filter: {
    status: {
      eq: PENDING
    }
  }) {
    nextToken,
    items {
      id
      title
      status
    }
  }
}
```

This is the query for listing the COMPLETED todos, as u can see there is a limit of 10 & an optional nextToken.This does not work correctly, when I first query for the todos, it returns an empty items array +  a NON NULL nextToken...I then have to run another query with the given nextToken to retrieve the 3 COMPLETED todos...this must be a bug?

```
query listTodos($nextToken: String) {
  listTodos(limit: 10, nextToken: $nextToken, filter: {
    status: {
      eq: COMPLETED
    }
  }) {
    nextToken,
    items {
      id
      title
      status
    }
  }
}
```

**Expected behavior**

When running my listTodos query for COMPLETED todos, it should return the 3 todos in the first query, I shouldn't need to run a subsequent query with the returned nextToken to retrieve the ONLY 3 COMPLETED todos.

When doing pagination with a filter, it should return the ONLY 3 results matching the filter and return a null nextToken.

**Additional context**

- Is there any other context you guys need to help debug? Let me know.

**Comment by hutchida** [comment]
Hi, I'm experiencing the same issue here. I think I understand correctly that it's applying the filter to the entire db but per page, based on the set limit, but what I don't understand is why are empty results returned at all? If I have a db of 30,000 entries with a limit set to 100 per page, that would mean I would need to make 300 api calls (the first filter, then 299 nextToken requests) to make sure I get all the possible results of the filter? That seems kinda crazy...or of course, I'm missing something very basic here. Hopefully the latter! If anyone can shed some light on this I'd be very grateful. Thank you in advance

**Comment by undefobj** [comment]
This is correct, [DynamoDB applies filters to a result set after the database operation has executed](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.FilterExpression). This is standard for NoSQL database engines. Filters can be a nice feature and help for initial onboarding, but you are correct at scale just using a filter isn't going to be the best customer experience especially for large data sets. I would recommend that you look at [`@key` with your GraphQL schema which](https://docs.amplify.aws/cli/graphql-transformer/directives#key) will do targeted DynamoDB queries as the database operation and the result set will return sorted to you based on your expression. They additional filters can be applied to those results should you so choose, but you should treat them as a final tweak on your data set and not the foundational query pattern as you get to production.

Additionally if you use DataStore it will handle sorting and pagination over the locally synced data so that you don't need to think about these DynamoDB specifics. I'd recommend taking a look: https://docs.amplify.aws/lib/datastore/data-access/q/platform/js#query-data

**Comment by hutchida** [comment]
Thanks @undefobj , also, for those who come across this thread, this article helped me understand what was going on:
https://www.alexdebrie.com/posts/dynamodb-filter-expressions/
My solution was to set up new resolvers by modifying the appsync schemas. I would recommend reading this page:
https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-resolvers.html
Starting at 'Setting Up the allPost Resolver (DynamoDB Scan)' and getting all items out first, then moving on to the next section where you just want to get some items out based on a condition...i.e. a filter of sorts. In that document it's the next resolver they create to get items by author name 'Setting Up the allPostsByAuthor Resolver (DynamoDB Query)'. You can swap 'author' for anything else you may have in your table, but you must make sure the field you choose is set up as a GlobalSecondaryIndex. You can do this quite easily in the dynamodb console (https://us-west-2.console.aws.amazon.com/dynamodb/home?region=us-west-2#tables:), choose Tables > *your table name*, then in the right hand panel > Indexes > Create Index. Should be fairly self explanatory from there.
