### ISSUE TITLE
IAM/Cognito auth roles no longer providing proper S3 access via AWS amplify

### ISSUE THREAD

**Issue by joelworsham** [aws-amplify/amplify-js#7076]
**Describe the bug**
React Native project using:

```
    "@aws-amplify/auth": "^3.4.7",
    "@aws-amplify/core": "^3.7.0",
    "@aws-amplify/storage": "^3.3.7",
```

Calling `Storage.get()` for a known resource in the `/public` directory, and then loading the returned signed URL gives me the following error:

```
<Error>
<Code>InvalidAccessKeyId</Code>
<Message>The AWS Access Key Id you provided does not exist in our records.</Message>
<AWSAccessKeyId>undefined</AWSAccessKeyId>
<RequestId>C4AC761E895ABD9B</RequestId>
<HostId>GNpJ3LAUVPyc8os22Q5uX0EvBWpGeblR/zIxnqFJ3jUk6l8J8Bvz6xHCToRnE/BPkHlpykIPOBU=</HostId>
</Error>
```

Note that `AWSAccessKeyId` is `undefined`. At this point, the user has already been authenticated properly via `Auth.signIn()`, so my assumption is that they should gain access to the S3 bucket, given the bucket policy and the IAM trust relationship policy.

Bucket policy (note the presence of the IAM auth'd role should allow access to get the objects):
```
{
  "Version": "2012-10-17",
  "Id": "Policy1599854584652",
  "Statement": [
    {
      "Sid": "Stmt1599854581275",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::XXXXXXXXX:role/Cognito_ExpyHealthStagingAuth_Role"
      },
      "Action": "s3:GetObject",
      "Resource": [
        "arn:aws:s3:::XXXXXXXX",
        "arn:aws:s3:::XXXXXXXX/*"
      ]
    }
  ]
}
```

The IAM trust relationship policy:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "cognito-identity.amazonaws.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "cognito-identity.amazonaws.com:aud": "us-east-1:xxxxxxx-ccde-xxxx-xxxx-xxxxxxxxxxxxx"
        },
        "ForAnyValue:StringLike": {
          "cognito-identity.amazonaws.com:amr": "authenticated"
        }
      }
    }
  ]
}
```

**To Reproduce**
1. User authenticates with `Auth.signIn()` using username/password. Successfully receives the JWT back and is authenticated.
2. Call `Storage.get('someResource.gif')` to get the signed URL of an existing media asset in `/public`
3. Load the returned signed URL into an image source (or the browser)

**Expected behavior**
Signed URL properly loads the desired asset

**What is Configured?**
System is initially configured as so:

```
  Amplify.configure({
    Auth: {
        identityPoolId: 'us-east-1:xxxxxxx-ccde-xxxx-xxxx-xxxxxxxxxxxxx',
        region: 'us-east-1',
        userPoolId: 'us-east-xxxxxxxxx',
        userPoolWebClientId: 'xxxxxxxxxxxxxxx',
      },
    Storage: {
        AWSS3: {
          bucket: 'expyhealth-stg',
          region: 'us-east-1',
        },
      },
  })
``` 

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 788.60 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 81.0
    Safari: 14.0
  npmPackages:
    @aws-amplify/auth: ^3.4.7 => 3.4.7 
    @aws-amplify/core: ^3.7.0 => 3.7.0 
    @aws-amplify/storage: ^3.3.7 => 3.3.7 
    @babel/core: ^7.11.6 => 7.12.3 
    @babel/preset-env: 7.11.5 => 7.11.5 
    @react-native-community/async-storage: ~1.7.1 => 1.7.1 
    @react-native-community/datetimepicker: 2.2.2 => 2.2.2 
    @react-native-community/netinfo: 5.5.1 => 5.5.1 
    axios: ^0.19.2 => 0.19.2 
    babel-preset-expo: ^8.3.0 => 8.3.0 
    env-cmd: ^10.1.0 => 10.1.0 
    expo: ^37.0.0 => 37.0.12 
    expo-av: ~8.1.0 => 8.1.0 
    expo-constants: ~9.0.0 => 9.0.0 
    expo-image-picker: ~8.1.0 => 8.1.0 
    expo-keep-awake: ~8.1.0 => 8.1.0 
    expo-localization: ~8.1.0 => 8.1.0 
    expo-permissions: ~8.1.0 => 8.1.0 
    expo-random: ~8.1.0 => 8.1.0 
    jwt-decode: ^2.2.0 => 2.2.0 
    metro-config: ~0.57.0 => 0.57.0 
    metro-react-native-babel-preset: ^0.63.0 => 0.63.0 
    metro-react-native-babel-transformer: ^0.63.0 => 0.63.0 
    moment: ~2.24.0 => 2.24.0 
    moment-timezone: ^0.5.27 => 0.5.31 
    qs: latest => 6.9.4 
    react: 16.9.0 => 16.9.0 
    react-dom: 16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    react-native-confetti: ^0.1.0 => 0.1.0 
    react-native-elements: ~1.2.7 => 1.2.7 
    react-native-gesture-handler: ~1.6.0 => 1.6.1 
    react-native-get-random-values: ^1.4.0 => 1.5.0 
    react-native-keyboard-aware-scroll-view: ^0.9.1 => 0.9.3 
    react-native-markdown-display: ^6.1.6 => 6.1.6 
    react-native-reanimated: ~1.7.0 => 1.7.1 
    react-native-safe-area-context: 0.7.3 => 0.7.3 
    react-native-screens: ~2.2.0 => 2.2.0 
    react-native-select-input-ios: ^2.0.4 => 2.0.5 
    react-native-snap-carousel: ^3.8.4 => 3.9.1 
    react-native-svg: 11.0.1 => 11.0.1 
    react-native-svg-transformer: ~0.14.3 => 0.14.3 
    react-native-webview: 10.9.0 => 10.9.0 
    react-navigation: ~4.0.10 => 4.0.10 
    react-navigation-animated-switch: ~0.4.1 => 0.4.1 
    react-navigation-stack: ~1.10.3 => 1.10.3 
    react-redux: ~7.1.3 => 7.1.3 
    redux: ~4.0.4 => 4.0.5 
    redux-logger: ~3.0.6 => 3.0.6 
    redux-thunk: ~2.3.0 => 2.3.0 
    semver: ^7.3.2 => 7.3.2 
    sentry-expo: ^2.0.1 => 2.1.2 
  npmGlobalPackages:
    @vue/cli: 4.5.8
    aws-cli: 0.0.2
    contentful-cli: 1.4.36
    ewi-unicorn: 2.1.1
    expo-cli: 3.27.8
    global-pkg-master-builder: 1.20.2
    npm-check-updates: 9.0.3
    npm: 6.14.8
    snyk: 1.420.1
```
</details>

**Smartphone (please complete the following information):**

(using iOS Simulator on MacOS)

- Device: iPhone 11
- OS: iOS13
- Browser: N/A, app loaded in Expo client

**Comment by joelworsham** [comment]
One thing I just noticed is that IAM role management console is telling me the auth'd role has not been used in 47 days... which doesn't make sense, considering it *should* be used right now as I'm testing. It's almost as if this role just stopped being used for some reason.

![Markup 2020-10-29 at 15 39 42](https://user-images.githubusercontent.com/4182573/97624211-2ef28c80-19fd-11eb-967d-926a33f3f29c.png)

**Comment by wlee221** [comment]
Hi @joelworsham, sorry about the delayed response. Unfortunately, we were not able to reproduce this issue. To reproduce, I created a react native app with expo ([repo](https://github.com/wlee221/amplify-react-native-auth/tree/7076-storage-authRole)) with the following CLI commands:

<details>
  <summary><code>amplify add auth</code></summary>
  
```
 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Username
 Do you want to configure advanced settings? No, I am done.
```

</details>

<details>
  <summary><code>amplify add storage</code></summary>
  
```
? Please select from one of the below mentioned services: Content (Images, audio, video, etc.)
? Please provide a friendly name for your resource that will be used to label this category in the project: s3862fc65c
? Please provide bucket name: amplifyreactnativeaua83e1a3bb90a4011959d7ed14a9
? Who should have access: Auth and guest users
? What kind of access do you want for Authenticated users? create/update, read, delete
? What kind of access do you want for Guest users? read
? Do you want to add a Lambda Trigger for your S3 Bucket? No
```

</details>

I did not modifiy the auto-generated backend. In the [app](https://github.com/wlee221/amplify-react-native-auth/tree/7076-storage-authRole), I use `Auth.signIn()` to authenticate ([lines 53-58](https://github.com/wlee221/amplify-react-native-auth/blob/7076-storage-authRole/App.js#L53..L58)). Then I upload an text file ([lines 70 to 74](https://github.com/wlee221/amplify-react-native-auth/blob/7076-storage-authRole/App.js#L70..L74)) and use `Storage.get` to get the signed URL ([lines 76 to 78](https://github.com/wlee221/amplify-react-native-auth/blob/7076-storage-authRole/App.js#L76..L78)). I was still able to access the file via signed URL (and not if I disable access from authRole as expected).

Can you verify that this issues is still persisting with the latest amplify? Please try a fresh install of latest amplify and a singular import of (`aws-amplify` instead of modular imports). 

If it doesn't work, I suggest you try recreating the backend (`amplify delete` then `amplify add storage`) or on a new sample app if your backend is populated with important files. If it still doesn't resolve the issue, please share a sample code and how you set up the CLI.

**Comment by wlee221** [comment]
Can you verify that this issues is still persisting with the latest amplify? Please try a fresh install of latest amplify and a singular import of (aws-amplify instead of modular imports).

If it doesn't work, I suggest you try recreating the backend (amplify delete then amplify add storage) or on a new sample app if your backend is populated with important files. If it still doesn't resolve the issue, please share a sample code and how you set up the CLI.
