### ISSUE TITLE
After sign-in with AmplifyAuthenticator the page goes black and app does not render until page is refresh

### ISSUE THREAD

**Issue by lmend22** [aws-amplify/amplify-js#7132]
**Describe the bug**
When my app starts for the first time after my sign-in with AmplifyAuthenticator, My pages go completely black and nothing happens but If I refresh the page, then the app triggers and works properly but I have to refresh first in order to work.  One thing I notice is that the app componentDidMount function is being invoked before sign-in. 

**To Reproduce**
N/A

**Expected behavior**
After sign in, the app renders and work properly 

**Screenshots**

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/69525449/98392892-c5ced280-2015-11eb-943b-bcdb7fcf927a.png)

**Comment by harrysolovay** [comment]
Please reposition `React.StrictMode` as the outer-most component (and you'll want to remove it entirely in production).

I don't believe a `componentDidMount` is a sign of an issue. Can you please share more information about your workspace setup and backend config. That way I can be more thoughtful in trying to diagnose :)

**Comment by DGabriel12** [comment]
My workspace :
VSCode
Node v12.18.2
React v16.13.1

Reproduced on localhost used amplify/cli for deployment.

the App component is mounting before sign-in, and it's causing the componentDidMount and/or useEffect hooks to prematurely fire.
![noUser](https://user-images.githubusercontent.com/69537253/99284128-2074e500-27f3-11eb-8cc7-f7a4ae7843f9.PNG)
![noUserErrorStack](https://user-images.githubusercontent.com/69537253/99287163-22d93e00-27f7-11eb-9098-03128fb6ed20.PNG)
this is the error that is shown when the app mounts and after you sign in successfully the page hangs on the loading screen because the app doesn't remount with the user credentials.

**Comment by amhinson** [comment]
@DGabriel12 @lmend22 It looks like you might need to manage the Authenticator rendering separately from your app component. If you just nest your app inside `AmplifyAuthenticator`, componentDidMount and useEffect will run (which is the expected behavior for `AmplifyAuthenticator`). Here is our recommended setup: https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#recommended-usage

**Comment by ErikCH** [comment]
Hi @lmend22 

Have you tried using our new Authenticator? Are you still having this issue?

https://ui.docs.amplify.aws/getting-started/installation
