### ISSUE TITLE
@aws-amplify/storage/srcs/Storage.ts uses Object.entries() call on line 134 - which is not supported by certain browsers

### ISSUE THREAD

**Issue by furyozo** [aws-amplify/amplify-js#7195]
User agent we caught this issue on:

`Mozilla/5.0 (SMART-TV; Linux; Tizen 3.0) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.0 Chrome/47.0.2526.69 TV safari/537.36`

Browser:

`Samsung Internet 2.0`

Full error description:

```
TypeError e.configure(src/Storage)
error
Object.entries is not a function
```

**Comment by iartemiev** [comment]
Hey @furyozo, we officially support the following browsers: https://aws.amazon.com/premiumsupport/knowledge-center/browsers-management-console/. Since Samsung Internet uses the Chromium engine, then I would expect the last 2 or 3 versions of Samsung Internet to also be supported. From what I can tell 2.0 is older than that. However, you can try adding polyfills in your app as is described in this comment: https://github.com/aws-amplify/amplify-js/issues/4515#issuecomment-575026258
