### ISSUE TITLE
unauthorized users can write to local datastore

### ISSUE THREAD

**Issue by NodeKing** [aws-amplify/amplify-js#7214]
**Describe the bug**
unauthorized users in the schema.graphql file can still write data to the local datastore. A warning message is displayed in the console, but data still resides in the local datastore. Essentially, data is written to the local datastore, but then fails to sync with DynamoDB. This leads to data inconsistencies between the front and back ends.

Obviously I could write logic in the application to prevent this occurring, but the graphql auth permissions should prevent this on both front and backend.

Warning message received:
```
{localModel: Model, message: "Not Authorized to access createAsset on type Asset", operation: "Create", errorType: "Unauthorized", errorInfo: null, …}
errorInfo: null
errorType: "Unauthorized"
localModel: Model {ModelData...}
message: "Not Authorized to access createAsset on type Asset"
operation: "Create"
remoteModel: null }
```

**To Reproduce**
Ensure cloud sync is configured as per documentation:
https://docs.amplify.aws/lib/datastore/sync/q/platform/js

**schema.graphql file :** 
```
type Asset
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["Admins"], queries: [get, list], mutations: [create, update, delete] }
      { allow: groups, groups: ["Users"], queries: [get, list], mutations: null }
    ]
  ) {
  id: ID!
  name: String!
}
```
**Perform a write to the datastore:**
```
DataStore.save(
              new Asset({
                name: 'assetName',
              })
            );
```

**Expected behavior**
If data is not permitted to be written to dynamoDB, it shouldn't be allowed to be written to the local datastore. 

Amplify version:
    aws-amplify: ^3.3.8 => 3.3.8 
    aws-amplify-angular: ^5.0.37 => 5.0.37 

Note: Data sync works fine when users are permitted via the schema.graphql file.

**Comment by iartemiev** [comment]
Hey @NodeKing, currently, DataStore does not enforce auth rules clientside. This is by design, as we want the AppSync back end to serve as the only source of truth for authorization rules. We recommend that customers add their own business logic around this in their applications.

Also, just want to point out that the `queries` and `mutations` arguments [are deprecated](https://docs.amplify.aws/cli/graphql-transformer/auth#definition) and are not supported with DataStore. When establishing subscriptions for the Sync Engine, DataStore will ignore those arguments.

I suggest using `operations` instead:
```graphql
type Asset
  @model
  @auth(
    rules: [
      { allow: groups, groups: ["Admins"] operations: [create, read, update, delete] }
      { allow: groups, groups: ["Users"], operations: [read] }
    ]
  ) {
  id: ID!
  name: String!
}
```

**Comment by NodeKing** [comment]
I thought that might be the case, thanks @iartemiev
