### ISSUE TITLE
challengeName not present after using verifyTotpToken

### ISSUE THREAD

**Issue by dottodot** [aws-amplify/amplify-js#7254]
The problem does not occur when using the aws-amplify-react components but I'm trying to create a custom component for TOTP setup and it doesn't seem to work correctly.

The following code works without an error

```
 const verifyTotpToken = async ({ totpCode }) => {
        if (
            !Auth ||
            typeof Auth.verifyTotpToken !== 'function' ||
            typeof Auth.setPreferredMFA !== 'function'
        ) {
            throw new Error(
                'No Auth module found, please ensure @aws-amplify/auth is imported'
            );
        }
        const user = authData;
        console.log('verifyTotpToken, user', user);
        try {
            await Auth.verifyTotpToken(user, totpCode);
            try {
                await Auth.setPreferredMFA(user, 'TOTP');
                setSetupMessage('Setup successfully!');
                logger.debug('set up totp success!');
                triggerTOTPEvent('Setup TOTP', 'SUCCESS', user);
            } catch (err) {
                console.log('setPreferredMFA error', err);
                setError('Setup failed!');
            }
        } catch (err) {
            console.log('setup error', err);
            setError('Setup failed!');
            logger.error(err);
        }
    };
```

and results in `preferredMFA` being set to `SOFTWARE_TOKEN_MFA`

but on signing in there is no `challengeName` so the user is never asked to enter a code.

If I then try `await Auth.setPreferredMFA(authData, 'TOTP')` after this I get an error of `User has not verified software token mfa`

I can't see why this is not working as it's not much different to how aws-amplify-react components work.

**Comment by rosspace** [comment]
I'm experiencing the same issue with nearly identical code. I'm using `@aws-amplify/auth` `3.2.14`. I tried upgrading to latest but got errors about missing fields on the configuration but I haven't been able to find any documentation on how to upgrade an existing project or what fields are required.

**Comment by rosspace** [comment]
Some more details - I tried a workaround where my signin code checks both the challengeName and cognitoUser.preferredMFA. Because preferredMFA comes back with the value `SOFTWARE_TOKEN_MFA` I ask the user for a software token. When I try authenticating with the token I get back an error "missing required parameter session". There is an open issue for this #3756 that states this is caused because MFA is not setup for the user.

Since preferredMFA is set if MFA is not actually setup on my account I would expect a challengeName of `MFA_SETUP` but I'm not receiving challengeName at all.

**Comment by rosspace** [comment]
After some more digging I can see that this issue is cased by issue #1226 
My react app could make several calls to `setupTOTP()` because I was trying to automatically display a QR code for the user if they hadn't setup TOTP before. I changed my UI to require the user to request a TOTP code ensuring that `setupTOTO()` is only called once to get it to work for me.

**Comment by mauerbac** [comment]
Sorry for the delay here. I'm reviewing previous issues -- if you are still experiencing an issue, please create a new issue

**Comment by Oli-Flemmer** [comment]
I was having the same issue but fixed it by running Auth.currentAuthenticatedUser after Auth.setPreferredMFA finished. Next time the user logs in they should have an auth challenge.
The flow goes something like this:
setupTOTP -> verifyTotpToken -> setPreferredMFA -> currentAuthenticatedUser -> signOut -> signIn

**Comment by 24jr** [comment]
I am trying to after already setting up totp to put back to 'NOMFA'. When I am signed in with user with totp set up I run
```
let res2 = await Auth.setPreferredMFA(get(user), 'NOMFA');
    console.log('res2', res2);
```
with error "User has not verified software token mfa". Makes sense I guess want to verify totp before doing this. I also havent and didnt use totp when signing in and not sure that I set any remember this device thing but could be whats occuring. Anyway as of now trying to figure out how to switch preferred MFA

I tried calling the verifytotp that I used to add my authapp to begin with and set to TOTP but its not verifying the code. And is this the proper way?
```
if(curMFA === 'SOFTWARE_TOKEN_MFA'){
  const code = '527218'
  let res = await Auth.verifyTotpToken(get(user), code)
  console.log('res', res);
  let res2 = await Auth.setPreferredMFA(get(user), 'NOMFA');
  console.log('res2', res2);
}
```
(I'm just manually typing code here and saving but of course do differently when working)
