### ISSUE TITLE
Encoding issue with rest API and NextJS

### ISSUE THREAD

**Issue by MaximilianSchon** [aws-amplify/amplify-js#7255]
**Describe the bug**
Characters gets encoded incorrectly when using NextJS and using the rest API client. For example "ä" gets encoded as "%E4". 

**To Reproduce**

1. Create a next-app with `npx create-next-app`
2. Configure API 
3. Send an API request to example "/ä". 

**Expected behavior**
That the URL is not encoded at all, or URI encoded. 

**Code Snippet**
```import { API } from 'aws-amplify'

export default function Home() {
  API.get("api", "/ä", null).then(console.log)
  return (<p></p>
  )
}
```
**What is Configured?**
An API. 

**Additional context**
It works as expected with React. 
If you use `unescape(encodeURIComponent(string))` it gets encoded correctly, but then the API Gateway throws InvalidSignatureException.
If you use `encodeURIComponent("ä").toLowerCase()` and send that as the API request, it encodes it correctly.

It also seems that it is caused by the parse function of the url package.

```import { API } from 'aws-amplify'
import {parse} from 'url';
export default function Home() {
  console.log(parse("https://www.google.com/test/ä"));
  API.get("api", "/ä", null).then(console.log)
  
  return (<p></p>
  )
}
```

Prints in the path as "%E4" in the chrome console.

**Comment by ericclemmons** [comment]
I've observed a difference in behavior between React & Next.js as well when there are spaces in URLs for S3 buckets: Getting the S3 resource URL for `path/to/My Custom Font.ttf` works in React, but fails in Next.js.

The fix for Next.js was the following, but then it broke React:

```diff
diff --git a/packages/core/src/Signer.ts b/packages/core/src/Signer.ts
index ea45e7630..5c74507fc 100644
--- a/packages/core/src/Signer.ts
+++ b/packages/core/src/Signer.ts
@@ -164,7 +164,7 @@ const canonical_request = function(request) {
 
 	const result = [
 		request.method || '/',
-		canonical_path(url_info.pathname),
+		canonical_path(encodeURI(url_info.pathname)),
 		canonical_query(url_info.query),
 		canonical_headers(request.headers),
 		signed_headers(request.headers),
```

We should add tests to cover the provided examples by OP too:

```js
encodeURIComponent("ä").toLowerCase()
// "%c3%a4"
```

```js
unescape(encodeURIComponent("ä"))
// "Ã¤"
```

**Comment by ericclemmons** [comment]
I wonder if Next.js is polyfilling the `url` package at all?  Because this isn't just on the server, it's the client, too 🤔

**Comment by mauerbac** [comment]
@ericclemmons , can you take a look at this ? ❤️

**Comment by ericclemmons** [comment]
@mauerbac I have (https://github.com/aws-amplify/amplify-js/issues/7255#issuecomment-733268674), but couldn't reach a resolution that **didn't** break Create React App.

I did see that Next.js includes `url` polyfills, so that could be responsible for the difference in behavior.

We may need a different implementation entirely than what I tried before.  Perhaps using what the customer provided with `toLowerCase()` resolves it?
