### ISSUE TITLE
Authentication broken

### ISSUE THREAD

**Issue by alexeimartov** [aws-amplify/amplify-js#7271]
Had a working project on 3.3.8 yesterday pushed live. By afternoon, authentication was broken. 

Spun up a boilerplate using create-next-app, add amplify and a basic graphql api, could not get auth to work, generic 'authentication error'.

I had pinned to 3.3.8 as 3.3.9 broke the whole graphql framework, lost a weekend figuring that out.

I would provide more information but too tired, twice the whole framework just randomly broke in a simple boilerplate using AWS's own setup guides, first time the graphql api, second time auth, so no idea how this is actually meant to be usable in production.

**Comment by ericclemmons** [comment]
@alexeimartov I'm sorry that you ran into this regression :( `3.3.9` had a regression that was address by #7237 in `3.3.10`.

I've added more tests around this to ensure it doesn't happen again, and we'll be creating more around use-cases as well.

I went through several of my Next.js apps with `3.3.10` without issue.  Just to confirm, did https://docs.amplify.aws/start/q/integration/next work successfully for you with `3.3.8`?

**Comment by ericclemmons** [comment]
Thanks for spending time with me today on this @alexeimartov!

For others following along, the main takeaways I have are:

- If you experience an Auth error on page load (e.g. something saying Auth isn't configured correctly, etc.), `rm -rf node_modules` and follow the next step. Because if there are duplicate copies of Amplify or Auth on the page, its highly likely none of the features will work as expected!
- `yarn add aws-amplify@latest @aws-amplify/ui-react@latest` to ensure both dependencies are in sync.  `yarn list @aws-amplify/auth` or `npm ls @aws-amplify/auth` may still show one dependency, so `rm -rf node_modules` just to be sure.
- If your app loads _with errors from Amplify_, immediately start debugging or reach out for help (https://discord.gg/amplify).
- Use `yarn.lock` or `package-lock.json` with `yarn add ...`.  These are best for reverting back to working versions when something's amiss.

We'll be releasing fixes so this `@aws-amplify/ui-*` interdependency issue goes away 🙏 

@alexeimartov Thanks again. I have a list of things for the team that we'll be discussing to act on your suggestions!

**Comment by PTaylour** [comment]
This worked for me

after re-installing `@latest` `/auth` is deduped

```
npm ls @aws-amplify/auth
├─┬ @aws-amplify/ui-react@0.2.30
│ └─┬ @aws-amplify/ui-components@0.9.5
│   └── @aws-amplify/auth@3.4.13  deduped
└─┬ aws-amplify@3.3.10
  ├─┬ @aws-amplify/api@3.2.13
  │ └─┬ @aws-amplify/api-graphql@1.2.13
  │   └── @aws-amplify/auth@3.4.13  deduped
  ├── @aws-amplify/auth@3.4.13 
  └─┬ @aws-amplify/pubsub@3.2.11
    └── @aws-amplify/auth@3.4.13  deduped
```

and it's happy now
