### ISSUE TITLE
DataStore keeps making a full sync once the TTL of Delta Sync table is reached

### ISSUE THREAD

**Issue by ramakrishnan** [aws-amplify/amplify-js#7272]
**Describe the bug**
Data store keeps making full sync on model and returns all documents instead of returning only the delta changes. What I observed is once the Delta sync table TTL is reached, the next sync call makes a full scan, even though there are no updates happened to the model.

**To Reproduce**
* I have a versioned model with base and delta table. 
* The base table has 300 documents. 
* Delta sync TTL 10 minutes
* System 1 and System 2 are in sync with 300 documents
* Make few inserts, (from system 2)
* Do sync `await DataStore.start();` in system 1. It receives only the new inserts.
* Wait for 10 minutes (Delta sync table drains)
* Do sync `await DataStore.start();` in system 1. Now it receives the complete set. (300 + new documents).

**Expected behavior**
Data Store should always get the delta changes which are not present in the IndexedDB

**Comment by amhinson** [comment]
@ramakrishnan If I'm understanding your issue correctly, this is the intended behavior with how AppSync handles sync operations. Since the Delta sync TTL has passed, it will do a scan of the base table instead of a query of the Delta. Here's a link to the AppSync docs for more info:

https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html#aws-appsync-conflict-detection-and-sync-sync-operations
