### ISSUE TITLE
Auth component autocomplete behavior is broken in Chrome

### ISSUE THREAD

**Issue by sdsanders** [aws-amplify/amplify-js#7378]
**Describe the bug**
Hovering into the list of autocomplete suggestions in an auth component field (like username within the Sign In component) and then out of it will make it look like the field has been filled, but the text in the field is not actually editable.

**To Reproduce**

1. Go to any of the Amplify auhenticator docs pages, for example https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular
2. Click in the username field of the displayed Sign In component
3. You will probably see autocomplete suggestions - hover into the list of suggestions then hover out of it
4. The field will appear filled, but the text will not actually be editable. If you begin typing it will remove the autofilled text

**Expected behavior**
Similar text fields in other web pages will remove the autofilled text from the field when you hover out of the list.

**Code Snippet**
This can be recreated within the hosted Amplify docs

**Screenshots**
Amplify behavior:
![amplify](https://user-images.githubusercontent.com/1165703/101714046-6d4c8400-3a5e-11eb-92a7-5515a3a60f32.gif)

Expected behavior (identical username field in a [Codepen](https://codepen.io/stevendsanders/pen/abmmQpM))
![amplify2](https://user-images.githubusercontent.com/1165703/101714091-7b9aa000-3a5e-11eb-8ea3-61252f6dd6a0.gif)

**Additional context**
I am using Chrome 86 on Windows 10.

**Comment by amhinson** [comment]
Thanks for the details @sdsanders! 🙏 

This does appear to be related to our usage of shadow DOM with StencilJS (and Web Components in general). Here is an open issue that also shows the behavior you are seeing: https://github.com/WICG/webcomponents/issues/894

With that said, I'm not sure if there's much we can do at this point, as the underlying issue is out of our control. I'm going to close this issue for now, but we will keep an eye on this so that we can hopefully improve this experience in the future once this gets resolved with Web Components.

**Comment by sdsanders** [comment]
Thank you for the quick response @amhinson!

Since this is an upstream issue, it would be nice to have the option to disable autocomplete until it is fixed. #5048
