### ISSUE TITLE
getCurrentUser() is null after a successful sign in from the cognito hosted UI

### ISSUE THREAD

**Issue by smneedham** [aws-amplify/amplify-js#760]
There is just about zero documentation around the hosted UI cognito usage after a user has successfully signed in and redirected to the success URL. 

Cognito successfully redirects to my 'sign in URL' and has the 'id_token' in the query field (I'm using the 'token' not 'code' method of auth). When I call the below code on the sign in URL page I always get null in the cognitoUser variable. I would have expected Cognito to reflect the fact that a user has logged in. This means I can never get the session data so I cannot proceed with using Cognito. If I've misunderstood the process then please direct me to the right documentation. 

var userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData);
var cognitoUser = userPool.getCurrentUser(); 
 // cognitoUser is always null 

I'm using the current dist version of amazon-cognito-identity.min.js in the amplify project. 

This happens in all browsers (Safari, FireFox, Chrome) and on Mac OS.

**Comment by logemann** [comment]
userPool.getCurrentUser() is returning a promise isnt it? I have not checked that particular API but a lot of methods in Amplify do and if its the same here, you need to use await or then.

**Comment by SupraDonkey** [comment]
@smneedham You ever get a solution to this issue because Im having the same problem

**Comment by offaxis** [comment]
+1 with the 'code' auth method

**Comment by jnreynoso** [comment]
+1

**Comment by yuankunluo** [comment]
+1

**Comment by ledubenjamin** [comment]
+1

**Comment by hansontech** [comment]
+1

**Comment by mlabieniec** [comment]
The recommended way to use the hosted UI with amplify is documented here:
https://aws-amplify.github.io/amplify-js/media/authentication_guide#using-amazon-cognito-hosted-ui

If you use the Amplify library the process is automated for you including the refreshing of the token when using a token grant. If using the lower level cognito sdk directly, you would also need to use the cognito auth sdk to perform the redirect and refresh (something amplify uses and does for you under the covers):
https://github.com/aws/amazon-cognito-auth-js/blob/master/README.md#usage

When using Amplify, the user is automatically instantiated and logged into your app. Let us know if this helps and what we can do to improve the process/documentation.

**Comment by powerful23** [comment]
If you are using Cognito Hosted UI without `Authenticator`, please make sure you have those steps:
1. Call `Auth.configure(your_auth_configuration)` in the callback page.
2. Use `Auth.currentAuthenticatedUser()` to get the logged in user: https://aws-amplify.github.io/amplify-js/media/authentication_guide#retrieve-current-authenticated-user

If you are not using Amplify but only the Cognito library(amazon-cognito-auth-js and amazon-cognito-identity-js), you need to parse the callback url yourself and then call `getCurrentUser()` in a the success handler: https://github.com/aws/amazon-cognito-auth-js/blob/master/README.md

**Comment by hansontech** [comment]
The Auth.configure source found in https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/Auth.ts, says :

            // if not logged in, try to parse the url.
            this.currentAuthenticatedUser().then(() => {
                logger.debug('user already logged in');
            }).catch(e => {
                logger.debug('not logged in, try to parse the url');
               const curUrl = window.location.href;
                this._cognitoAuthClient.parseCognitoWebResponse(curUrl);
            });

Means, Auth.configure will find chance to parse the callback url. The url should includes oauth login information such as ID token and access token. As a result, this function is able to force Amplify (Auth) to continue the session following after Hosted UI, and to change its status to 'authenticated'. 
Auth.currentAuthenticatedUser() is merely used to retrieve the logged-in user information.

But in my real tests of following the guidelines of the document, currentAuthenticatedUser() always returned 'not authenticated' error.  The snippet in the handler of the callback url is:
              .......
              Auth.configure({
                  oauth: oauth
              })
             Auth.currentAuthenticatedUser()
            .then(user => console.log(user))
            .catch(err => console.log(err))
 
           { By enabling Amplify.Logger.LOG_LEVEL = 'DEBUG', I can see more debug messages too }

amazon-cognito-auth-js did provide an alternative option. The two lines of code below successfully changed the Amplify Auth status to 'authenticated' as I expected. 

             var curUrl = window.location.href;
             auth.parseCognitoWebResponse(curUrl);

           { Although, in this case, it needs extra 'handler' codes to finish the rest of callback tasks }

Just not sure whether this cognito-auth-js will also collaborate with Amplify Auth to refresh tokens as Auth claims.

I am using Vue, instead of React, as the framework, different to what the document normally use. Still, I must say, the documentation is really not enough. They need to improve the documents in a wider coverage and real cases explanation; because, the implementation, from my experience, was not straightforward at all.

**Comment by powerful23** [comment]
For how to use Cognito Hosted UI with Amplify, please check the doc: https://aws-amplify.github.io/docs/js/authentication#using-amazon-cognito-hosted-ui

**Comment by groundswel** [comment]
What if you don't want to use amplify , then after you use hosted ui to login , in the next page how do you retrieve the signed in user tokens/ids etc?

**Comment by SupraDonkey** [comment]
If you are using js I did by using a document ready function on the callback URL page:
`const hashObj = window.location.hash.replace('#', '').split('&').reduce((prev, item) => {
   return Object.assign({[item.split('=')[0]]: item.split('=')[1]}, prev);
}, {});`
check for error:
`if(hashObj.error){...`
else
AccessToken: `hashObj.access_token`
IdToken: `hashObj.id_token`

Then you can use those to authenticate the user

**Comment by groundswel** [comment]
Thank you but I was wondering if the hosted UI saves the Cognito id/token and other information somewhere in local storage?

**Comment by SupraDonkey** [comment]
No you would need to do that, I stored it in cookies

**Comment by SupraDonkey** [comment]
Think about it, how would Cognito have access to your local storage? Kinda dangerous no?

The key is the callback URL, it sends the results to it which allows you to do whatever you want with the results. I moved away from the hosted UI because it wasnt flexible enough for me and built my own screens and use Cognito to authenticate against, so if you think about it that way, Cognito hosted UI is just a conduit for authentication and sends back error or with tokens and related user information for use as you wish:  authorization(permissions based on roles and groups), etc.

**Comment by groundswel** [comment]
I don't think I was referring to Cognito having access to local storage but the cognito-sdk having access to local storage to save the id/token from the hosted UI in a well known key value pair so that it is available for later pages in the application to use it. But since you explained it I think it is pretty clear that this cannot be done by hosted UI as the URI is being redirected to the callback URL , so the local storage saving has to be done there.  However without saving it to local storage I think  there is no way that a multiple page web application can have access to the id token that is returned by Cognito once a successful sign in occurs.

**Comment by SupraDonkey** [comment]
Without saving it yourself, you are correct. It would be the same no matter whether you use the hosted UI or not. 
I had the same thought process as you are ;)

**Comment by cajund** [comment]
> If you are using js I did by using a document ready function on the callback URL page:
> `const hashObj = window.location.hash.replace('#', '').split('&').reduce((prev, item) => { return Object.assign({[item.split('=')[0]]: item.split('=')[1]}, prev); }, {});`
> check for error:
> `if(hashObj.error){...`
> else
> AccessToken: `hashObj.access_token`
> IdToken: `hashObj.id_token`
> 
> Then you can use those to authenticate the user

Understanding that this is a close request - just wanted to ask how the user can be authenticated using the JWT. Can anyone point to an example? Is it something that passes through STS or can it be done in the Identity pool?

Thanks,
