### ISSUE TITLE
AWS Cognito user able to sign in, but API “Does not exist” when using I can access using access token on console?

### ISSUE THREAD

**Issue by wordisthebird** [aws-amplify/amplify-js#7670]
Hey guys,

Im a bit lost here and would love some help. I am trying to connect my React Native app to a basic Lambda function.

I have no bother Registering a user, Confirming a user or Signing in. I can see all of these things in the Cognito Console.

I also am able to test the access to the API with the Authorizers part of the API Gateway and get a Response Code: 200 with the correct email and other details from cognito.

**Expected behavior**
I want to get a response from the API but instead I get ' API_NAME does not exist'

**Code Snippet**

Imports:

`import { API, Auth } from 'aws-amplify';`
 ```
async signIn(email: string, password: string) {
        try {
          //sign in the user
          const user = await Auth.signIn(email, password);
    
          AlertHelper.show('info', 'Signed in!', user)
    
          const token = user.signInUserSession.idToken.jwtToken
    
          console.log('token:', token )
    
          const requestInfo = {
           headers: {
            Authorization: token
           }
    
//get the Data Here
        const data = await API.get('API_NAME','/hello',requestInfo)
        console.log('Data: ',data )
      }
     
        }
        catch(error){
          console.log('Error: ', error)      
        }
    
      }
```

**What is Configured?**
```
const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_xxxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "API_NAME",
            "endpoint": "https://endpoint",
            "region": "eu-west-1"
        }
    ]
};


Here is the index.js from the function

exports.handler = async (event) => {
    // TODO implement


    if(event.requestContext.authorizer){
        console.log('Claims: ',event.requestContext.authorizer.claims)
    }

    const response = {
        statusCode: 200,
    //  Uncomment below to enable CORS requests
     headers: {
         "Access-Control-Allow-Origin": "*",
         "Access-Control-Allow-Headers": "*"
     }, 
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
};




```
**Smartphone (please complete the following information):**

Iphone 11

and 

Android Samsung A20E

**Additional context**

**Comment by amhinson** [comment]
Can you describe what steps you took to create the Lambda function? Was it with `amplify add api`?

**Comment by wordisthebird** [comment]
Hi there,
I used `amplify add api`

Then added the name of the API

Then I added `/hello` for the path

Then I used a lambda function previously created

Then I restricted the access to Authenticated/guest-users

Then I didn't add more paths

**Comment by amhinson** [comment]
Would you be able to double check the values you're providing for `API_NAME`? I've tried to replicate the issue you are seeing, but everything appears to be working when I create a new rest API with Lambda via the CLI.

**Comment by mikhael28** [comment]
I just had the same problem - I have a mature react app running, I run amplify add api, add a rest dynamodb crud api with Node, everything gets pushed, but afterwards - my 'api does not exist' message is the same as theirs.

I ran the first operation using amplify-cli version 4.41, then deleted everything, ran it with version 4.40 - same issue. Unfortunately, it looks like something is broken with `amplify add api`.

@amhinson @wordisthebird in the future, would be very helpful if you would give the version number of the packages you are using.

**Comment by mikhael28** [comment]
Specifically, the problem is with the REST api creation. I created a graphql api 3-4 weeks ago, no problems.

**Comment by wordisthebird** [comment]
Hi @amhinson, thank you for your reply. I get the `API_NAME` from the AWS-exports.js file under the `name:` category which is an auto generated file. The name of the API is the same on the Aws console.

I really cant think of what else I could be doing wrong, any ideas.  How are you re creating the issue as maybe I am doing something wrong here.

**Comment by wordisthebird** [comment]
> Specifically, the problem is with the REST api creation. I created a graphql api 3-4 weeks ago, no problems. Same dep versions.

Hi @mikhael28 thank you very much for your response! would you have a link to any good tutorials / documentation on how to link up a graphql to a react native app

**Comment by wordisthebird** [comment]
Update:

I can test the api on the console and also get a 200 response with the basic 'Hello from Lambda' message. What am I missing??
![Screenshot 2021-02-03 at 10 28 18](https://user-images.githubusercontent.com/23181835/106734266-b9551880-660a-11eb-92a7-2c4002a20a00.png)

**Comment by mikhael28** [comment]
The problem appears to be, from my vantage point, not a problem with the

creation of the API itself. It appears to be an error with the
initialization logic of the aws-amplify/core library. When it's running

Amplify.configure of the aws-exports object, there appears to be some
problem with how it is making those API's available to the 'global
state', as it were, accessible for the `aws-amplify/api` library.

**Comment by amhinson** [comment]
@mikhael28 @wordisthebird Could you share your `package.json`? This might possibly be due to duplicate dependencies. We now only recommend using the `aws-amplify` package and not any of the modular packages directly.

> would you have a link to any good tutorials / documentation on how to link up a graphql to a react native app

The docs have a [getting started guide](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js#create-the-graphql-api) that will work for React Native as well.

**Comment by mikhael28** [comment]
Here is my package.json, though I am a little confused - when did you
start not recommending the module packages? When I was doing a audit on

my bundle size, aws-amplify was adding a huge weight to the bundled js -

when I added the modular libraries and updated my imports, it went down

by 800kb. Does the base amplify package support tree shaking now?

"dependencies": {
    "@aws-amplify/api": "^3.2.17",
    "@aws-amplify/auth": "^3.4.17",
    "@aws-amplify/core": "^3.8.9",
    "@aws-amplify/pubsub": "^3.2.15",
    "@aws-amplify/storage": "^3.3.17",
    "@material-ui/core": "^4.11.2",
    "@sanity/block-content-to-react": "^2.0.6",
    "@sanity/client": "^0.141.6",
    "@sanity/image-url": "^0.140.19",
    "classnames": "^2.2.6",
    "generate-password": "^1.4.2",
    "lodash.clonedeep": "^4.5.0",
    "lodash.sortby": "^4.7.0",
    "prop-types": "^15.7.2",
    "pure-react-carousel": "^1.27.4",
    "react": "^17.0.1",
    "react-accessible-accordion": "^3.3.3",
    "react-beautiful-dnd": "^13.0.0",
    "react-bootstrap": "^0.32.4",
    "react-calendar": "^3.2.1",
    "react-dom": "^17.0.1",
    "react-icons": "^4.1.0",
    "react-loading-skeleton": "^2.1.1",
    "react-quill": "^1.3.5",
    "react-redux": "^7.1.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.1",
    "react-spring": "^8.0.27",
    "react-stripe-elements": "^1.6.0",
    "reactour": "^1.18.0",
    "redux": "^4.0.4",
    "source-map-explorer": "^2.5.2",
    "styled-components": "^4.4.1",
    "toasted-notes": "^3.2.0",
    "uuid": "^3.3.3",
    "victory": "^35.1.1",
    "web-vitals": "^0.2.4",
    "workbox-background-sync": "^5.1.3",
    "workbox-broadcast-update": "^5.1.3",
    "workbox-cacheable-response": "^5.1.3",
    "workbox-core": "^5.1.3",
    "workbox-expiration": "^5.1.3",
    "workbox-google-analytics": "^5.1.3",
    "workbox-navigation-preload": "^5.1.3",
    "workbox-precaching": "^5.1.3",
    "workbox-range-requests": "^5.1.3",
    "workbox-routing": "^5.1.3",
    "workbox-strategies": "^5.1.3",
    "workbox-streams": "^5.1.3"
  },
  "scripts": {
    "analyze": "source-map-explorer 'build/static/js/*.js'",

    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "serve": "serve -s build"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "cypress": "^3.4.1",
    "redux-devtools": "^3.5.0"
  }

On February 8, 2021, Steve Denton <notifications@github.com> wrote:
> @mikhael28 <https://github.com/mikhael28>
> @wordisthebird <https://github.com/wordisthebird> Could you share your

> package.json? This might possibly be due to duplicate dependencies. We

> now only recommend using the aws-amplify package and not any of the
> modular packages directly.
>
> > would you have a link to any good tutorials / documentation on how

> > to link up a graphql to a react native app
> >
>
> The docs have a getting started guide
> <https://docs.amplify.aws/lib/graphqlapi/getting-
> started/q/platform/js#create-the-graphql-api> that will work for React

> Native as well.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/aws-

amplify/amplify-js/issues/7670#issuecomment-775402697>, or unsubscribe

<https://github.com/notifications/unsubscribe-
auth/ADUAHC6N7JLHK5BJDZN3WN3S6A6SZANCNFSM4W7EJEHQ>.

**Comment by amhinson** [comment]
> Does the base amplify package support tree shaking now? 

Yep, tree shaking was introduced with the last major version bump (3.0.0).

**Comment by mikhael28** [comment]
My bundle size did not reflect that, though perhaps I was on 2.x for
some reason. I will give that another try when I have time, thanks for

the heads up! 

On February 8, 2021, Steve Denton <notifications@github.com> wrote:
> > Does the base amplify package support tree shaking now?
> >
>
> Yep, tree shaking was introduced with the last major version bump
> (3.0.0).
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/aws-

amplify/amplify-js/issues/7670#issuecomment-775463089>, or unsubscribe

<https://github.com/notifications/unsubscribe-
auth/ADUAHC2X54B4KQ3UNDJP323S6BHGZANCNFSM4W7EJEHQ>.
