### ISSUE TITLE
should not show the "No account? Create account" link, if configured User sign ups not allowed

### ISSUE THREAD

**Issue by t829702** [aws-amplify/amplify-js#7685]
**Describe the bug**
for a web app I want to disable user to self sign up, but for admins to create users for them; from Cognito Console or Admin UI it's easy to disable user sign up; then this Sign In form still shows a `"No account? Create account"` and user can still enter that sign up form and if user actually did that, it shows `"SignUp is not permitted for this user pool"` that's true, but why should this show up and get user confusing?

![image](https://user-images.githubusercontent.com/49542456/106956886-1d034280-66ec-11eb-89b7-6e4fce88a89e.png)
![image](https://user-images.githubusercontent.com/49542456/106957162-8420f700-66ec-11eb-99e6-08c0e28c599c.png)

**To Reproduce**

**Expected behavior**
that `"No account? Create account"` should not show up at all; when configured `User sign ups allowed? No` Only administrators can create users

**Comment by sammartinez** [comment]
Hello @t829702, please find this [documentation](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#hiding-form-fields) to help you with the hiding of your form.

**Comment by t829702** [comment]
No, that link https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#hiding-form-fields says how to hide some form fields, like if no need of phone number field:

> Hiding form fields
> Often you will not need a default form field, for example the phone number field

but what I requested is how to hide the text `No account? Create account` in the Sign in form ?? and hide the Sign Up form, do not allow user self up at all?

**Comment by t829702** [comment]
it's very reproducible, just create a blank project, with react/vue or others, `amplify add auth`, and disable user signup from amplify console; but the default login form is always showing the `No account? Create account` /cc @sammartinez ??

**Comment by sammartinez** [comment]
Hey @t829702, thanks for this feedback. You are correct that the documentation I linked allows you to hide form fields. However, to your point we are not exposing in the `AmplifyAuthenticator` to hide the sign up form. We have the boolean available to hide the signup form from the `AmplifySignIn` component. Here is the link to the [README](https://github.com/aws-amplify/amplify-js/issues/4315#issuecomment-781367638) to set the flag to hide it. You will need to create a [custom form field](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#custom-form-fields) in order to do this. I will mark this as a feature request since I believe this should be present at the `AmplifyAuthenticator` parent component and not inside of a child component.

**Comment by ErikCH** [comment]
@t829702 As @sammartinez has already mentioned you can use the custom form fields to remove that sign up text. It should look something like this.

```
const App = () => {
  return (
    <AmplifyAuthenticator>
      <AmplifySignUp
        slot="sign-up"
        hideSignUp="true" />
...
```

**Comment by wlee221** [comment]
Closing as stale. Please let us know if the above solution doesn't work.
