### ISSUE TITLE
Federated Login Users Cannot Reset (Forgot) Their Password

### ISSUE THREAD

**Issue by ChihweiLHBird** [aws-amplify/amplify-js#7704]
Currently, a user login with Google account cannot reset their password via `forgotPassword`. It would be better to let the user set/reset the password for the account even the identity is from Google or other providers. 

Alternatively, maybe amplify can return a error when users try to forgot password for theri federated login account, in case they forgot their account is from Google.

**Comment by cwomack** [comment]
Hello, @ChihweiLHBird.  Any type of password resets for your Google account would need to be done through the 3rd Party Federated provider (Google in this case).  Unfortunately, we won't be able to implement this as a feature request so I'll close this issue. 

If I misunderstood what you're asking for or there's more context that I'm missing, please feel free to reply back and we can reopen this issue.

**Comment by ChihweiLHBird** [comment]
@cwomack 

Maybe you missed this part below?

Alternatively, maybe amplify can return a error when users try to forgot password for theri federated login account, in case they forgot their account is from Google.

**Comment by cwomack** [comment]
@ChihweiLHBird, thanks for the quick reply! Didn't miss that part, but after reviewing this issue internally there was some uncertainty on that second part (especially due to being unable to reset a Google account's password through Amplify).  We thought it was implying an error being returned if the Google password couldn't be reset. 

To confirm what the part you reiterated means, are you asking for a new error to be returned when the forgotPassword method is called that would _include_ which Federated provider is being used for a given user's account login?
