### ISSUE TITLE
Upgrading the amplify packages causes the UI components to freeze (Angular

### ISSUE THREAD

**Issue by dudutwizer** [aws-amplify/amplify-js#7794]
**Describe the bug**
Upgrading the packages causes the component to freeze. The user can't click on anything inside the form. The form is shown, but the buttons aren't working. 
It seems that there is an overlay that blocks user-input. I couldn't point out the exact root cause, so I started from scratch. The only difference between a working environment and a not-working environment is the aws-amplify packages and the new HTML snippet. 

This field should expend on click:
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/24310417/108684786-00447880-74fc-11eb-8411-7628eb83c0a5.png">

but nothing happens.

I will appreciate your help to fix it as it's a blocker.

**To Reproduce**

1. Upgrade aws-amplify from 2.2.6 to 3.3.20
2. Delete aws-amplify-ui and install aws-amplify/ui-angular (1.0.2)
3. Upgrade aws-amplify-angular from 4.1.7 to 5.0.49
4. Update the component HTML from:

```html
<br>
<amplify-authenticator></amplify-authenticator>
<div *ngIf="signedIn">
    <app-table></app-table>
</div>
```

to

```html
<br>
<amplify-authenticator *ngIf="authState !== 'signedin'"></amplify-authenticator>

<div *ngIf="authState === 'signedin' && user" class="App">
  <amplify-sign-out></amplify-sign-out>
    <app-table></app-table>
</div>

```

**Expected behavior**
The component should be clickable

**Screenshots**
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/24310417/108683864-d8a0e080-74fa-11eb-871a-f073b2a03085.png">

**More details**
```

Angular CLI: 8.3.29
Node: 14.13.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.29
@angular-devkit/build-angular     0.803.29
@angular-devkit/build-optimizer   0.803.29
@angular-devkit/build-webpack     0.803.29
@angular-devkit/core              8.3.29
@angular-devkit/schematics        8.3.29
@angular/cdk                      8.2.3
@angular/cli                      8.3.29
@angular/material                 8.2.3
@ngtools/webpack                  8.3.29
@schematics/angular               8.3.29
@schematics/update                0.803.29
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

```
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/24310417/108685112-69c48700-74fc-11eb-8162-2303f1a44c62.png">

**Comment by wlee221** [comment]
Hi @dudutwizer, following up from our discusison in #6388: 

Have you tried using slotted approach instead of `v-if`?

```
<amplify-authenticator>
    <amplify-sign-out></amplify-sign-out>
    <app-instance-table></app-instance-table>
</amplify-authenticator>
```

and remove the `onAuthUIStateChange` callbacks / `authState` / `user`. This is (visually) equivalent to using `*ngif` and you no longer need to manage the auth related variables. Please let me know if it works, or why this isn't a suitable solution.

With regards to the *ngif pattern *with* `@angular/material`, I stand by https://github.com/aws-amplify/amplify-js/issues/6388#issuecomment-749313841 and that this is likely a bug from `@angular/material` because `onAuthUIStateChange` is working as intended:
- it updates the `authState` / `user` to correct state,
- Angular renders the correct `ng-if` block,
- and this happens when `*ngIf="authState === 'signedin'` block doesn't have amplify ui-components.

Please feel free to disagree or share ideas why this would be happening. I'll audit @angular/material for related issues and possible friction points (there might be some unexpected behavior from web component usage), but again I'm afraid there's not much we can do from Amplify side at this point if that is not the case.

**Comment by wlee221** [comment]
With regards to the *ngif pattern *with* `@angular/material`, I stand by https://github.com/aws-amplify/amplify-js/issues/6388#issuecomment-749313841 and that this is likely a bug from `@angular/material` because `onAuthUIStateChange` is working as intended:
- it updates the `authState` / `user` to correct state,
- Angular renders the correct `ng-if` block,
- and this happens when `*ngIf="authState === 'signedin'` block doesn't have amplify ui-components.

Please feel free to disagree or share ideas why this would be happening. I'll audit @angular/material for related issues and possible friction points (there might be some unexpected behavior from web component usage), but again I'm afraid there's not much we can do from Amplify side at this point if that is not the case.

**Comment by wlee221** [comment]
@dudutwizer, I came across https://github.com/angular/components/issues/21779#issuecomment-773640161 that was really helpful and related! I tried using `NgZone.run` and I was successful in getting the material element to work:

_App.component.ts
```ts
// ...
export class AppComponent {
  title = 'amplify-angular-auth';
  user: CognitoUserInterface | undefined;
  authState: AuthState;
  value = '';

  constructor(private zone: NgZone) {}

  ngOnInit() {
    onAuthUIStateChange((authState, authData) => {
      this.zone.run(() => {
        console.log(authState, authData, this.zone);
        this.authState = authState;
        this.user = authData as CognitoUserInterface;
      });
    });
  }

  // ...
}
```

_App.component.html_
```ts
<amplify-authenticator
  *ngIf="authState !== 'signedin'"
  username-alias="email"
></amplify-authenticator>
<amplify-sign-out></amplify-sign-out>

<div *ngIf="authState === 'signedin'">
  <form>
    <mat-form-field>
      <mat-label>Enter value</mat-label>
      <input matInput type="text" [(ngModel)]="value" (ngModelChange)="handleInput()" name="input" />
    </mat-form-field>
  </form>
</div>
```

Can you try using `zone.run` inside `onAuthUIStateChange` and see if it works? Thanks!

**Comment by dudutwizer** [comment]
AWESOME! YES!

thank you very much.

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/24310417/109780677-e4358b00-7c0f-11eb-9c36-31f048a0c85d.png">

now we just need to update amplify docs to match this solution.

Thank you @wlee221 for your deep dive here.

**Comment by dudutwizer** [comment]
https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular

**Comment by wlee221** [comment]
You're welcome! I'll wait on updating the docs because this is specific to using `@angular/material`. We're working on making this flow more friendly with Angular, so we'll update the docs after that happens.
