### ISSUE TITLE
Update mutations on connection is not working with latest version of amplify

### ISSUE THREAD

**Issue by TheMoums** [aws-amplify/amplify-js#7840]
**Describe the bug**
Hello, I have updated all my aws-amplify packages to their latest versions as well as the amplify cli, and it seems that one particular case of update mutations is not working anymore.

A (very) simplified version of my schema.graphql 

```graphql
type Building @model {
  id: ID!
  units: [Unit!] @connection(keyName: "byBuilding", fields: ["id"])
}
```
```graphql
type Unit @model @key(name: "byBuilding", fields: ["buildingId"]) {
  id: ID!
  buildingId: ID!
  building: Building @connection(fields: ["buildingId"])
  }
```
In previous versions, whenever I would update my Unit to put it on another Building, I would do something like:
```js
await DataStore.save(
      Unit.copyOf(fromStore, (updated) => {
        updated.building = ...
      })
    );
```
Which would result in a mutation like 
![old_screen](https://user-images.githubusercontent.com/22890903/109502838-ccd49180-7a99-11eb-9c21-cc0e9bcebab4.PNG)

Basically, the previous version would send the whole record in the update mutation (Here I was updating the 'Unit4' to put it on the 'Building3').

Unfortunately, it seems that, with the latest versions of aws-amplify, some kind of optimisation is performed to send only the fields that have changed. Which is working when I update simple fields on a given record but failing when updating connections between models.

Here is the same example as before **but** with the latest version

![new_screen_not_working](https://user-images.githubusercontent.com/22890903/109503320-68fe9880-7a9a-11eb-9fcb-2488e790bb52.PNG)

As you can see, the field buildingId is ignored which results in the impossibility to update the Unit in order to put it on another Building.
 ```json
"@aws-amplify/api": "3.2.24",
 "@aws-amplify/auth": "3.4.24",
 "@aws-amplify/cache": "3.1.49",
 "@aws-amplify/core": "3.8.16",
 "@aws-amplify/datastore": "2.9.10",
 "@aws-amplify/predictions": "3.2.24",
 "@aws-amplify/storage": "3.3.24",
```
amplify --v : 4.44.1

**Comment by iartemiev** [comment]
Hey @TheMoums, you're correct in that we recently modified the behavior for update mutations to where only changed fields are sent in the mutation input. This change was made in order to comply with the Automerge conflict resolution strategy, which requires this to function correctly. It looks like we missed some test cases around relations. I'll mark this as a bug and will work towards resolving it ASAP. 

This change was added in @aws-amplify/datastore@2.9.4 (which is part of aws-amplify@3.3.15), so in the meantime, I'd suggest downgrading your library to **aws-amplify@3.3.14** (or @aws-amplify/datastore@2.9.3 if you're installing them separately) to restore the previous behavior where all fields in a model are included in the update mutation.

**Comment by iartemiev** [comment]
Hello again! [PR](https://github.com/aws-amplify/amplify-js/pull/7935) that fixes this issue is up. I'll post another update once it's been merged and deployed.

**Comment by iartemiev** [comment]
@TheMoums the PR has been deployed.
Please install aws-amplify@3.3.26 or @aws-amplify/datastore@2.9.15 and let me know if that solves this issue.

**Comment by TheMoums** [comment]
Version @aws-amplify/datastore@2.9.15 fixed this issue. 
Thanks a lot !
