### ISSUE TITLE
initialAuthState for react native withAuthenticator

### ISSUE THREAD

**Issue by oxbits** [aws-amplify/amplify-js#8077]
it would be great if initialAuthState worked in react native with withAuthenticator

like this : 

https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#withauthenticator

unless it already does work and i am doing it wrong

**Comment by tannerabread** [comment]
This issue is slightly outdated and hopefully solved by the recent release of the new React Native UI Authenticator which allows you to [set the initial state ](https://ui.docs.amplify.aws/react-native/connected-components/authenticator/configuration#initial-state)

If I misunderstood your concern and you are still struggling with this issue, please feel free to comment
