### ISSUE TITLE
Auth.js throws "Pending sign-in attempt already in progress" on login using Chrome

### ISSUE THREAD

**Issue by Sebastian-G** [aws-amplify/amplify-js#8079]
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 917.25 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    npm: 7.6.3 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Chrome Canary: 92.0.4475.0
    Firefox: 79.0
    Firefox Developer Edition: 88.0
    Safari: 14.0.3
  npmPackages:
    @angular-builders/jest: ~11.1.1 => 11.1.1 
    @angular-devkit/build-angular: ^0.1102.5 => 0.1102.5 
    @angular-material-components/color-picker: ~5.0.2 => 5.0.2 
    @angular-material-extensions/password-strength: ^8.1.1 => 8.1.1 
    @angular/animations: ~11.2.6 => 11.2.6 
    @angular/cdk: ^11.2.5 => 11.2.5 
    @angular/cli: ~11.2.5 => 11.2.5 
    @angular/common: ~11.2.6 => 11.2.6 
    @angular/compiler: ~11.2.6 => 11.2.6 
    @angular/compiler-cli: ~11.2.6 => 11.2.6 
    @angular/core: ~11.2.6 => 11.2.6 
    @angular/flex-layout: ^11.0.0-beta.33 => 11.0.0-beta.33 
    @angular/forms: ~11.2.6 => 11.2.6 
    @angular/language-service: ~11.2.6 => 11.2.6 
    @angular/localize: ^11.2.6 => 11.2.6 
    @angular/material: ^11.2.5 => 11.2.5 
    @angular/material-moment-adapter: ~11.2.5 => 11.2.5 
    @angular/platform-browser: ~11.2.6 => 11.2.6 
    @angular/platform-browser-dynamic: ~11.2.6 => 11.2.6 
    @angular/router: ~11.2.6 => 11.2.6 
    @aws-amplify/analytics: ^4.0.17 => 4.0.17 
    @aws-amplify/api: ^3.2.29 => 3.2.29 
    @aws-amplify/auth: ^3.4.29 => 3.4.29 
    @aws-amplify/core: ^3.8.21 => 3.8.21 
    @aws-amplify/interactions: ^3.3.29 => 3.3.29 
    @aws-amplify/pubsub: ^3.2.27 => 3.2.27 
    @aws-amplify/storage: ^3.3.29 => 3.3.29 
    @aws-amplify/xr: ^2.2.29 => 2.2.29 
    @types/node: ^14.14.35 => 14.14.35 
    aws-amplify-angular: ^5.0.30 => 5.0.54 
    backoff-rxjs: ^6.3.3 => 6.5.7 
    codelyzer: ^6.0.1 => 6.0.1 
    core-js: ^3.6.4 => 3.9.1 
    crypto-js: ^4.0.0 => 4.0.0 
    http-status-codes: ^1.4.0 => 1.4.0 
    i18n-iso-countries: ^4.3.1 => 4.3.1 
    jwt-decode: ^2.2.0 => 2.2.0 
    roboto-fontface: ^0.10.0 => 0.10.0 
    rxjs: ^6.6.3 => 6.6.6 
    sass: ~1.32.6 => 1.32.8 
    ts-jest: ~26.5.4 => 26.5.4 
    ts-node: ~9.0.0 => 9.0.0 
    tslib: ^2.0.0 => 2.1.0 
    tslint: ~6.1.3 => 6.1.3 
    typescript: ~4.1.5 => 4.1.5 
    uuid: ^8.3.0 => 8.3.2 
    wait-on: ^5.2.0 => 5.3.0 
    zone.js: ~0.10.2 => 0.10.3 
  npmGlobalPackages:
    @angular/cli: 11.2.5
    json-server: 0.16.3
    npm: 7.6.3

```

</details>

### Describe the bug

On login using the "normal" login (username and password) the following issue occurs:

The login isn't effected by this behavior.

```
core.js:6162 ERROR Error: Pending sign-in attempt already in progress
    at AuthClass.push.v4IS.AuthClass.signInWithPassword (Auth.js:529)
    at AuthClass.push.v4IS.AuthClass.signIn (Auth.js:415)
    at AuthClass.Auth.signIn (auth.decorator.js:35)
    at AuthClass.Auth.signIn (auth.decorator.js:35)
    at LoginComponent.submit (login.component.ts:90)
```

### Expected behavior

Login without any error messages, thrown by Auth.js

### Reproduction steps

I was only able to reproduce this bug using Chrome.

1. login by username and password  
2. Error occurs :sad

### Code Snippet

```javascript
this.amplifyService.auth().signIn({username, password}))
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Related Issues: 
- maybe this is a related issue for REACT (https://github.com/aws-amplify/amplify-js/issues/7763#)

**Comment by bilsak18** [comment]
I have the same error thrown in my case.

I have amplify authentication working correctly in my REACT app. I tried testing it with Cypress based on this [doc](https://docs.cypress.io/guides/testing-strategies/amazon-cognito-authentication) but I never got it to work. I get different errors, sometimes it's this **pending** error, and some other times the **signIn** function simply never resolves.

**Comment by chrisbonifacio** [comment]
> I have the same error thrown in my case.
> 
> I have amplify authentication working correctly in my REACT app. I tried testing it with Cypress based on this [doc](https://docs.cypress.io/guides/testing-strategies/amazon-cognito-authentication) but I never got it to work. I get different errors, sometimes it's this **pending** error, and some other times the **signIn** function simply never resolves.

Hi! Thank you for commenting. It's good to know that this is happening on multiple frameworks so that narrows it down to being specific to the package. As I try to reproduce this issue, could you please let me know what packages and versions of amplify you are using?

**Comment by bilsak18** [comment]
Hello, sure I can provide you with such information.
I use these two amplify packages: 
`"aws-amplify": "^3.3.23",`
`"aws-amplify-react": "^4.2.26",`

**Comment by chrisbonifacio** [comment]
@bilsak18 Thank you for responding with your package versions.

@Sebastian-G I see there are many aws packages in your environment information.

If you could both please follow the instructions on this page and run the appropriate terminal command from within your project directories, it might give us some insight into whether or not our packages might have duplicate/mismatching versions. 
https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js

If there are any, it has been known to cause issues with Auth and Amplify.configure() among other things. Make sure to use the latest versions of any amplify packages you might be using.

@bilsak18 I think this is less likely to be the cause of your issue as you only have two amplify packages.

Recently someone has found a solution for the same error. I'm not sure if  the cause is the same but it should be worth trying
https://github.com/aws-amplify/amplify-js/issues/7191#issuecomment-728234443

**Comment by Sebastian-G** [comment]
I'm upgrading all dependencies to following versions:

```
    "@aws-amplify/analytics": "^4.0.18",
    "@aws-amplify/api": "^3.2.30",
    "@aws-amplify/auth": "^3.4.30",
    "@aws-amplify/core": "^3.8.22",
    "@aws-amplify/interactions": "^3.3.30",
    "@aws-amplify/pubsub": "^3.2.28",
    "@aws-amplify/storage": "^3.4.0",
    "@aws-amplify/xr": "^2.2.30",
```

**Comment by bilsak18** [comment]
@chrisbonifacio Thank you for investigating the issue. On my side, I refactored my code very often, trying to find some solution to this issue, and so I lost the current error in the refactoring process and was only left with the second error like I explained it in [my first comment above](https://github.com/aws-amplify/amplify-js/issues/8079#issuecomment-819331976), which doesn't appear all the time.

I figured lately that it's only a matter of timeout of the `Auth.signIn` request when executed in the Cypress environment. Since Cypress by default times out its commands after 4 seconds, and since my `Auth.signIn` call SOMETIMES takes longer to resolve well the test fails and I never see my `Auth.signIn` request resolving. This doesn't happen all the time, cause SOME OTHER TIMES the `Auth.signIn` resolves quicker than the 4 seconds timeout and everything works out just fine.

NOTE: This only happens in my test environment. My live app works fine all the time.

**Comment by chrisbonifacio** [comment]
@bilsak18 Okay, that makes sense. I don't have too much experience with Cypress but from some googling I can see that it's not straightforward to work with when it comes to asynchronous code.

Good to know it's more of an issue with the way the testing framework handles async code than Amplify itself!

If you're still interested in trying to get Cypress to wait for your promises to resolve, the answer on this stack overflow page might be helpful: https://stackoverflow.com/questions/49980311/cypress-io-how-to-handle-async-code

@Sebastian-G Thank you for upgrading your packages! I'm sorry that hasn't helped with the issue though.  Would you mind sharing the full code snippet responsible for making the `Auth.signIn` request so that I can take a look at how you're using it?

**Comment by rraczae** [comment]
this is still a major issue in react native: https://github.com/aws-amplify/amplify-js/issues/7763

**Comment by chrisbonifacio** [comment]
@Sebastian-G Closing this issue for now as we have not heard back from you in nearly a month.

@rraczae We're unable to consistently reproduce this issue with a properly configured Auth. This issue is more than likely caused by Auth being misconfigured, which could be a red herring because usually the real cause is some discrepancy with package versions and/or the `amazon-cognito-identity-js` package not being linked properly.

If you can, try to go through the steps here and see if it helps

https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js

**Comment by NickFoden** [comment]
Was the resolution to downgrade a major version? I am on latest just installing and following steps for amplify today, and it works well locally and then throws this same error in production signing in with email and password. Hosting on Vercel since using Next.js 12. 

``` 
 "aws-amplify": "^4.3.11",
 "next": "12.0.7",
 ```

```
error signing in Error: Pending sign-in attempt already in progress
