### ISSUE TITLE
Cognito does not send Access-Control-Allow-* headers when sending an invalid or expired token

### ISSUE THREAD

**Issue by Mikilll94** [aws-amplify/amplify-js#8152]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line

System:
    OS: macOS 11.2.3
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 141.59 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 87.0
    Safari: 14.0.3
  npmGlobalPackages:
    @angular/cli: 9.1.6
    @vue/cli: 4.5.12
    npm: 7.5.4
    pnpm: 5.18.6
    serve: 11.3.1
    yarn: 1.22.10
```

</details>

### Describe the bug

When sending a request with invalid or expired token to Cognito, the server does not return `Access-Control-Allow-Origin` header which causes CORS error.

Here is the response from Cognito:

![Screenshot 2021-04-22 at 16 36 18](https://user-images.githubusercontent.com/17653648/115733104-de933080-a388-11eb-9ef1-efe1924cc0e0.png)

Because of this CORS error I am not able to read the status code (401 Unauthorized) in my app and redirect users to the login page based on this status code.

### Expected behavior

Cognito should always return `Access-Control-Allow-*` headers. Right now it sends these headers only when the response is successful. When the response is not successful, they should also be send.

### Reproduction steps

1. Make a request from your app to Cognito with invalid or expired token.
2. You will receive a CORS error.

**Comment by chrisbonifacio** [comment]
Hey 👋 Thanks for raising this! After reading over this issue, it appears to be more of a feature request and will be labeled as such. This should make it more visible for the team to take a look and determine whether it can be fit into a release. 

I hope that helps!

**Comment by chrisbonifacio** [comment]
Hey @Mikilll94. I apologize for mislabeling this issue, after reading it over and asking a member of the team to take a look as well, we agree that this is unintended behavior and therefore a possible bug. We are currently trying to reproduce the issue.

In my attempts so far I have only received a 400 status code when sending an invalid/expired token. From your screenshot it looks like you were testing in Postman. If you don't mind, could you please let me know what URL, headers, body, etc you were using to reproduce it in Postman so that I may try to do the same?

**Comment by Mikilll94** [comment]
@chrisbonifacio 
Please take a look at the screenshot again. `Access-Control-Allow-*` headers is not returned from Cognito. This is the bug.

I have searched more and noticed that this bug is already reported on the AWS forum. You can read it here: https://forums.aws.amazon.com/thread.jspa?messageID=764227

This serious bug with AWS Cognito is not solved from Mar 24, 2016

If you have more questions, feel free to ask.

**Comment by chrisbonifacio** [comment]
@Mikilll94 I see. In my efforts to reproduce the issue however, this is the response I've been getting from Cognito when I send an expired/invalid token. So, because you're getting a CORS error you're not getting any error message other than `UnauthorizedException` in the headers, correct?

<img width="896" alt="Screen Shot 2021-04-28 at 11 16 07 AM" src="https://user-images.githubusercontent.com/16952986/116429185-a6ba3c00-a813-11eb-9a86-f9d59ad3da4d.png">
<img width="827" alt="Screen Shot 2021-04-28 at 11 17 16 AM" src="https://user-images.githubusercontent.com/16952986/116429193-a883ff80-a813-11eb-92f8-b991384d5b2f.png">

**Comment by Mikilll94** [comment]
@chrisbonifacio 
Yeah, exactly. I am getting a CORS error and cannot get any meaningful error message from Cognito. I cannot even retrieve the status code.

I don't know why in your case the "Access-Control-Allow-Origin" header is returned. In my app, this header is not returned and for the guys on the forum (https://forums.aws.amazon.com/thread.jspa?messageID=764227) this is also not working.

**Comment by Mikilll94** [comment]
@chrisbonifacio 
I have an idea. This issue may exists only when you have a Lambda with a Cognito authorizer. You need to send invalid/expired token to the Lambda with authorizer.

**Comment by chrisbonifacio** [comment]
@Mikilll94 That's a good idea, I am currently testing and will report back with the results. Thank you!

**Comment by chrisbonifacio** [comment]
Hey @Mikilll94 , This seems to be related to Amazon Cognito specifically instead of Amplify JavaScript. Amplify JavaScript acts as a proxy to Amazon Cognito. We suggest you open an issue via the [AWS Forums for Cognito](https://forums.aws.amazon.com/forum.jspa?forumID=173).

Thanks,
Amplify team
