### ISSUE TITLE
WebSocket connection failed 

### ISSUE THREAD

**Issue by MedNabilEssefaihi** [aws-amplify/amplify-js#8537]
Dear There,

I am using React app with DynamDB with GrapgQL Api and Have some Subscrption methods. 
When ever I reload the page I get this error:

![2222](https://user-images.githubusercontent.com/74948380/124402427-1bd05300-dd28-11eb-98a1-e98f76989ef2.png)

Why I get this error ?

**Comment by chrisbonifacio** [comment]
@MedNabilEssefaihi Can you sure the code where you're starting and handling the subscription?

**Comment by MedNabilEssefaihi** [comment]
dear @chrisbonifacio,

Thank you for your answer, Actually I am using many subscriptions in my code
This is an example:
![2](https://user-images.githubusercontent.com/74948380/124843497-f5a9ed80-df89-11eb-8ce8-281ace39385b.png)

**Comment by chrisbonifacio** [comment]
Hi @MedNabilEssefaihi apologies for the delay. Are you still experiencing this issue? If so, could you make sure you're using the latest versions of `@aws-amplify/cli`, and `aws-amplify` and let me know if the issue persists?

**Comment by MedNabilEssefaihi** [comment]
Dear @chrisbonifacio.
Yes, I still have the same issue even after update.

**Comment by chrisbonifacio** [comment]
@MedNabilEssefaihi hmm, okay I may need to try reproduce the issue. The easiest way may be to use your dev environment if you're okay with that. Otherwise, you could either add the info request in our [bug report form](https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=&template=1.bug_report.yaml) here or create a new issue with it and make sure it's filled out with any relevant info like your auth configuration, schema, minimal steps to reproduce, etc.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
