### ISSUE TITLE
Geo: AmplifyMapLibreRequest.createMapLibreMap() is a mouthful and a misnomer

### ISSUE THREAD

**Issue by mojodna** [aws-amplify/amplify-js#8689]
### Is this related to another service?

Geo

### Describe the feature you'd like to request

Context: https://docs.amplify.aws/lib/geo/maps/q/platform/js#add-map-to-html-website

Not only is `AmplifyMapLibreRequest.createMapLibreMap` a long name, but it also doesn't reflect what it does. The "Request" bit originally reflected that it provides a `transformRequest` function suitable for use with AWS, but that's no longer directly visible to developers.

"MapLibre" is also a bit overly specific / prescriptive, as the created function is also compatible with Mapbox GL JS (1.x and 2.x). I agree that this library should use MapLibre by default (`amazon-location-helpers` takes a `mapgl` param that allows the default module to be overridden; if I were doing it again, I might pass the `maplibregl.Map` constructor instead), but `createMap` feels suitably descriptive while remaining agnostic.

The default "export" (`maplibreAmplify`) also feels somewhat arbitrary (though less so than `[window].aws_amplify_core`); is there also an opportunity here to be more intentional?

While I'm discussing `createMapLibreMap`, what's the purpose of the `region` key? I'm guessing that it's to support Map resources in regions that don't match the Cognito pool, but it's weird to intermingle that with keys that are passed to the `Map` constructor. If the map name comes from `aws-exports.js` (I can't see how to provide it otherwise), shouldn't the region too?

### Describe the solution you'd like

A more concise method signature that reflects what it does.

### Describe alternatives you've considered

[`amazon-location-helpers`](https://github.com/aws-samples/amazon-location-samples/tree/main/amazon-location-helpers#readme), but this is very similar.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by thaddmt** [comment]
To your first point, it should be possible and uncontroversial to move that static method out of `AmplifyMapLibreRequest`. Don't have any problem with this.

Originally we named the method `createMap` but wanted to make sure that developers knew that they were receiving a `maplibregl.Map` object rather then some type of Amplify Map (this is made clear in TS but not everyone uses TS). I would not mind changing it back to `createMap`.

For the default export was there a name that you felt would be more appropriate? This library was made for using Amplify Geo with Maplibre so we went with that but we are open to suggestions!

The region key was added because at the time we did not have an API available for getting the region from `aws-exports.js` but now that we have it we are going to be making that parameter optional and getting the region for the developer - https://github.com/aws-amplify/maplibre-gl-js-amplify/pull/29

**Comment by thaddmt** [comment]
https://github.com/aws-amplify/maplibre-gl-js-amplify/pull/31

**Comment by mojodna** [comment]
I like what you did in aws-amplify/maplibre-gl-js-amplify#31. A hearty +1 to `createMap`. Thoughts on allowing a MapLibre / Mapbox GL `Map` constructor as an optional argument to support a wider variety of versions, provided they follow the same contract/itnerface?

I think something like `AmplifyMapLibre` would be a better name for the default export, since it's a collection of methods and stuff that help work together. Keeping `Request` in there feels like it gets overly-specific. If you need a modifier, maybe `Utils` (but everyone hates a kitchen sink utils package ;-).

For `region` and other Amplify-specific properties, is it possible to separate them into separate arguments to avoid future conflicts where something may be relevant (but mean different things) to both Amplify + MapLibre?

**Comment by thaddmt** [comment]
Can look into adding the maplibre/mapbox constructor as a parameter and splitting out amplify specific properties in the current pr we have open.

I'll discuss with Praveen in another PR about renaming the default export

**Comment by thaddmt** [comment]
Pr for renaming bundle - https://github.com/aws-amplify/maplibre-gl-js-amplify/pull/39

**Comment by thaddmt** [comment]
Think we addressed all of the concerns here, going to close for now but feel free to re-open if you see any other issues!
