### ISSUE TITLE
Not usable in NodeJS

### ISSUE THREAD

**Issue by sallar** [aws-amplify/amplify-js#876]
**Do you want to request a feature or report a bug?**
Bug Report

**What is the current behavior?**
Throws an Error when using in NodeJS

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.**
1. Require this module in NodeJS
2. Try to use it

**What is the expected behavior?**
The codebase should not have direct references to `window` object at all. This is considered bad practice. Authentication for example, is something one might want to use in NodeJS instead of browser or RN. There should be getters instead of accessing `window`, so they can be polyfilled when necessary.

Also if you're not going to support NodeJS, please kindly specify this in the docs or README, right now the docs are very vague about this matter.

Thank you ♥️

**Comment by mlabieniec** [comment]
@sallar, we have included some [polyfills](https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Common/Polyfills/Polyfills.ts) that polyfill the window object so that it is usable in node. The only other thing you would need to do is include a fetch module i.e. [node-fetch](https://www.npmjs.com/package/node-fetch) for the fetch requests done by the amazon cognito sdk, see here: https://github.com/aws/aws-amplify/issues/403

**Comment by sallar** [comment]
@mlabieniec thanks. But the polyfill doesn’t seem to work. As soon as you `import` the module it throws an error. Is there any example of usage in node?

**Comment by sallar** [comment]
The errors appear to come from importing everything from RNComponents folder

**Comment by wzup** [comment]
Same error
https://github.com/aws/aws-amplify/issues/1066

**Comment by elorzafe** [comment]
Hi @flaviocordova I check on node.js an App that uses Auth and is working if you install node-fetch 
and then add `global.fetch = require('node-fetch');` before importing Amplify.

**Comment by flaviocordova** [comment]
Hi @elorzafe, thanks for your prompt reply...

My problem (or anyone with a vuejs ssr application) is not that nodejs should mock the browser environment better but instead should not do that at all..

The point here is that amplify should *not* create a window object because it's making the server-side code to misbehave.

take a look at https://github.com/vuejs/vue/blob/3eb37acf98e2d9737de897ebe7bdb7e9576bcc21/src/core/util/env.js, line 7 and you'll find it:

```
export const inBrowser = typeof window !== 'undefined'
```

When the app is first built (on dev mode) window is undefined, so the engine assume it's running server-side. Once amplify is loaded, window is now an object and all the components and requests will cause the server to behave like a browser.

I think amplify should not change the current environment to mock a browser but instead should just read it to identify if it's running in browser or in node and then decide behave accordingly. For example: I should not need to import node-fetch to mock the browser - amplify should do that automatically when it "senses" it's not running in the browser.

Doesn't it make sense?

**Comment by mlabieniec** [comment]
@flaviocordova thanks for the detailed response. The point of this pollyfill was originally for providing the for amplify to run in node. We'll take a look at this and see if there is a way we can address this. Please feel free to provide suggestion/PR in the meantime.

**Comment by flaviocordova** [comment]
Hi @mlabieniec, thanks !!!

I understand the motivation to mock the browser, I just think thats not the best approach. But, sincerely, who never, right ? 😄 

I don't know the code details but I'd consider removing polyfill and addressing the fetch issue first (since it's seems to be the reason why polyfill was created).
A facade to fetch method that checks if it should fetch directly (browser) or use node-fetch (or something else) should do the magic without big impact on the current source..


Do you have an idea of when polyfill was released ? I was wondering if using an old version could prevent the issue now until a permanent solution is released.

**Comment by sallar** [comment]
It's not possible to even polyfill. If you use the `import amplify from ...` syntax for importing the library, the library code runs before everything else (unlike `require`). So `window.fetch = ...` doesnt work. The best way is just to remove all references to it from the library. 

I'll maybe submit a PR for this when I get a bit of free time.

**Comment by bugeats** [comment]
It's not just the `window` object. Here the lib assumes access to the `navigator` object without doing any checking:

https://github.com/aws-amplify/amplify-js/blob/fe1324ffad3821041a324904ba8d4d52c1977688/packages/amazon-cognito-identity-js/src/CognitoUser.js#L494

You could go a long way by simply building your stuff in Node to discover these kinds of errors. There's no reason to have a hard dependency on `navigator`.

BTW those of you trying to get this work in Node, try something like this:
```javascript
// stupid assumes global fetch
global.fetch = require('node-fetch');
global.navigator = {};
```

Make sure you leave the snarky comment in there so everyone knows of your displeasure.

**Comment by ispyinternet** [comment]
Please un-polyfill window in Node. Breaks my environment!!

**Comment by romainquellec** [comment]
Breaking a lot with next right now. I'm using noSSR for now, but it's not a viable solution at the end. 👍  for this issue.

**Comment by bingtimren** [comment]
Hi if you just want to use AppSync service with node client I built a template project here. 
https://github.com/bingtimren/aws-appsync-nodejs-template.js

Hope it helps.

**Comment by natebushman** [comment]
Using some of the aforementioned hacks I was able to get an older version of aws-amplify (0.4.8) to work with Node.js v10.3.0.  However there are some bugs in that version of aws-amplify and I'd really like to upgrade to aws-amplify 1.1.4.  However the same hacks don't work and I can't seem to get aws-amplify 1.1.4 working with Node.js.  

Has anyone successfully nudged aws-amplify 1.1.4 to work with Node?  If so, can you please explain how you did so?

Amplify Team:  PLEASE make Amplify work with Node.js.  This will be extremely helpful as it will enable us to use shared code for node test scripts as well as web and react clients.

**Comment by romainquellec** [comment]
I got this issue fixed with "1.1.6-unstable.2" but it does not with "1.1.9".

**Comment by closedLoop** [comment]
For those also using typescript on a node-js backend and are getting a `ReferenceError: fetch is not defined` error

`npm install` these packages:
```
    "amazon-cognito-identity-js": "3.0.11"
    "node-fetch": "^2.3.0"
```

Then include:
```typescript
import Global = NodeJS.Global;
export interface GlobalWithCognitoFix extends Global {
    fetch: any
}
declare const global: GlobalWithCognitoFix;
global.fetch = require('node-fetch');
```

**Comment by homerjam** [comment]
Can you please make it clear on the website where these major gaps in functionality are that one would expect from a project like this? Or mark it as a beta product?

**Comment by aldegoeij** [comment]
referencing tickets #3486, #3506, #3615, #3015, #876, #3477 and webpack/webpack#6522

**Comment by talaikis** [comment]
Ia hev included `core-js`, etc.  and it works fine, one of examples: https://www.npmjs.com/package/@talaikis/s3-db
