### ISSUE TITLE
Invalid Password Format Validation for correct password without spaces

### ISSUE THREAD

**Issue by BravesDevs** [aws-amplify/amplify-js#8780]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, REST API

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I want a free trial of the clearbit and tried to sign up using my personal email from WEB using my desktop using microsoft edge browser but whenever I submit details and try to tap next button the password format validation message pops up though the format is correct, please clear this issue asap because several other colleagues of mine tried to sign up but we all stucked. 

### Expected behavior

The password format validation only get activate when input password format does not match with the required password format criteria

### Reproduction steps

NA

### Code Snippet

```javascript
// Put your code below this line.

```
NA

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @BravesDevs 👋 I'm not sure I understand the issue. You mentioned "clearbit free trial", so I googled it and found this webpage. 

<img width="978" alt="Screen Shot 2021-08-20 at 10 47 44 AM" src="https://user-images.githubusercontent.com/16952986/130251574-7203ee12-5258-4567-b460-ec5eb18f7615.png">

Is this an app you're developing?

If so, are you using Amplify UI components or the `Auth` library directly? If you can include any code, screenshots, or use the `Record a loom` button when posting a comment to record a video of the behavior, that could help us understand the problem better.

Otherwise, I don't see any calls to Amazon Cognito when signing up so I'm not sure if this is an issue related to our libraries.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
