### ISSUE TITLE
doc needs more details on backend setup

### ISSUE THREAD

**Issue by whatsdis** [aws-amplify/amplify-js#929]
Hi, 

Regarding https://github.com/aws-samples/aws-mobile-react-sample

I need some more clear instructions on how to setup the cognito pools, preferrably via aws cli

when I ran `awsmobile run` it only shows the registration form but nothing else works. No userpool is hte message I am seeing.

**Comment by jordanranz** [comment]
Hello, we have made many improvements to the Amplify Auth category that have solved many issues related to the "no userPool" problem. We have also migrated the usage of the awsmobile cli to the Amplify cli. Please follow the instructions here: https://aws-amplify.github.io/docs/js/authentication#automated-setup

I will close this issue now due to legacy code. Please open a new issue if the instructions above are not helpful.
