### ISSUE TITLE
How to add user to group after signup using "admin-add-user-to-group"

### ISSUE THREAD

**Issue by umangm99** [aws-amplify/amplify-js#937]
How to use admin-add-user-to-group in react app environment?

I'm trying 

 var params = {
        GroupName: 'unisorter-user',
        UserPoolId: 'ap-south-1_ABCDEXYG',
        Username: 'e8bda141-abcde-1234-bf1f-5b90ae78859e'
      };
      
      const responseAws = AWS
        .CognitoIdentityServiceProvider
        .adminAddUserToGroup(params, function (err, data) {
          if (err) {
            console.log(err, err.stack);
          } else {
            console.log(data);
          }
        });
      console.log('response', responseAws);

But it is not working.
Any help will be appreciable. Thanks

**Comment by mlabieniec** [comment]
@umangm99 what is the error you are receiving? In order to accomplish this you would need to be sure your credentials (secret key/access key) have the appropriate permissions to perform this task in the appropriate IAM role/policy. Can you provide some more details i.e. debug log, and platform/browser, sdk version etc.

**Comment by oluomoniyi** [comment]
https://github.com/aws-amplify/amplify-js/issues/1213

**Comment by jordanranz** [comment]
Going to close this as a response was made and a duplicate was posted. Please reopen if you have any further questions or concerns.
