### ISSUE TITLE
[React-Native 0.66] Attempted to remove more RCTLinkingManager listeners than added

### ISSUE THREAD

**Issue by retyui** [aws-amplify/amplify-js#9492]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
"react-native": "0.66.4"
"@aws-amplify/auth": "^4.3.20",
"@aws-amplify/core": "^4.3.12",
```

</details>

### Describe the bug

I've create a new React Native porject and latest version of amplify:

```
"@aws-amplify/auth": "^4.3.20",
"@aws-amplify/core": "^4.3.12",
```

Add when run application see the next error:

https://github.com/aws-amplify/amplify-js/blob/9924a31397761fccd03f53336d754b98367199a8/packages/auth/src/urlListener.native.ts#L41-L42

^^^ it is the reason of this error!

<img src="https://user-images.githubusercontent.com/4661784/150009130-02df780a-823d-4bda-8ede-d19f613cb03f.png" width=375 />

### Expected behavior

It is nonsense! when you create fresh project and install latest versions of amplify to see an error!

### Reproduction steps

...

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Device

iPhone X; iOS 15

**Comment by calebpollman** [comment]
@retyui Thanks for opening an issue for your PR. For due diligence, I am attempting to recreate the scenario you have described in this ticket. Unfortunately, adding: 
```
"@aws-amplify/auth": "^4.3.20",
"@aws-amplify/core": "^4.3.12",
```
to the dependencies of a fresh React Native Project does not result in the attached screenshot. Are there additional steps that need to be taken?

**Comment by retyui** [comment]
@calebpollman Please run `.configure` once

```
import Amplify from 'aws-amplify';

Amplify.configure(config);
```

**Comment by calebpollman** [comment]
@retyui I went ahead and added Amplify `auth` to a sample app and am calling `Amplify.configure` with the generated `config` object. Was unable to recreate the scenario in your screenshot, here is a screenshot from my sample app:

![image](https://user-images.githubusercontent.com/15002885/151224344-5aa7049b-c5ba-4f72-a3a5-255c0311139a.png)

Is there a step I am missing? It's odd to me that the screenshot you have attached shows a call to `Linking.removeEventListener` with no listeners configured.

**Comment by retyui** [comment]
Sorry @calebpollman you should be used `Auth` instead of `Amplify`
```tsx
Auth.configure(config);
```

**Comment by calebpollman** [comment]
@retyui Was also unable to recreate the error in the initial screenshot by calling `Auth.configure`. 

Did some proactive research while trying to replicate and ultimately I do not think that usage of the `Auth` module can result in that error. While there is a potential call to `Linking.removeEventListener` inside `urlListener`, [the conditional gating it](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/urlListener.native.ts#L40) will **always** evaluate to `false` due to an error in the code, preventing execution of  `Linking.removeEventListener('url', handler)`.

That being said, the issue you pointed out in https://github.com/aws-amplify/amplify-js/pull/9450 regarding `subscription.remove` is still valid and agree that we do need to address the issues in `urlListener`. 

Because this issue has not been replicated using the instructions given, and the code in the description that would trigger the error is unreachable, I am going to close this issue, but let's continue working on the PR.
