### ISSUE TITLE
Datastore does not sync if there is soft deleted invalid item

### ISSUE THREAD

**Issue by matart15** [aws-amplify/amplify-js#9620]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 37.27 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.17 - ~/.yvm/shim/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v12.22.1/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 97.0
    Safari: 15.3
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.21
    @nestjs/cli: 8.1.5
    @teambit/bvm: 0.0.34
    aws-cdk: 2.3.0
    detox-cli: 19.0.0
    eas-cli: 0.47.0
    expo-cli: 5.2.0
    http-server: 14.1.0
    npm: 8.3.0
    nx: 13.2.3
    pm2: 5.1.2
    prisma: 3.5.0



```

</details>

### Describe the bug

1. created a model with the not required field
type Door @model {
  id: ID!
  name: String!
  allowedCompanies: [String]
  doorNo: String
  httpEndpoint: String!
  serviceUuid: String!
  index: Int!
  imageUrl: String!
}
2. added some data without doorNo

3. deleted items without doorNo from AdminUI

4. changed doorNo to required

5. AdminUI breaks (but admin UI team said [it is expected](https://github.com/aws-amplify/amplify-adminui/issues/484).). Now the problem is **Amplify Datastore implemented in the app breaks** too. React Native app does not show any error message. Just results are empty array.

If I check `dynamo DB` deleted items on `step 3` are soft deleted.

![Screen Shot 2022-02-10 at 17 21 22](https://user-images.githubusercontent.com/17027219/153368283-8ff9c55b-8a65-41d2-a5dc-0304b59202ea.png)

If I delete them from `DynamoDB` manually, React native app syncs without problem.

But if I am not wrong that would break my `@searchable` index ( last time I deleted dynamo items directly, they showed up on search query. I suppose that is expected behavior)

PS: In both cases, I tried completely deleting the installed app.

### Expected behavior

soft deleted items should not cause sync error

### Reproduction steps

same as above

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @matart15 👋 thanks for raising this issue. Deleted items have a TTL so that other clients can sync them down and know which records need to be deleted from their local storage. I don't think this behavior can be avoided for the sake of data integrity.

DataStore in this case will not sync simply because of the record on the server not meeting the model's field type requirement. This will result in a GraphQL error along the lines of "Cannot return null for non-nullable type: String".

If you're changing a field from nullable to required, you should backfill the data so that field is populated with some kind of acceptable default value. The same would be true for a non-versioned API (DataStore not enabled) and would also result in this error.

The team is in the midst of cataloguing some of these types of errors and defining better error handling but for now, backfilling data is the only supported path forward.

**Comment by chrisbonifacio** [comment]
Hi 👋 thanks for raising this issue. Deleted items have a TTL so that other clients can sync them down and know which records need to be deleted from their local storage. I don't think this behavior can be avoided for the sake of data integrity.

DataStore in this case will not sync because of the record on the server not meeting the model's field type requirement. This will result in a GraphQL error along the lines of "Cannot return null for non-nullable type: String".

If you're changing a field from nullable to required, you should backfill any existing data with that field as null to some kind of acceptable default value so they can be syncable again on the frontend. Unfortunately for now, this is the only supported path forward.

The team is actively working to catalogue errors like this and defining better error handling.

**Comment by chrisbonifacio** [comment]
One thing we noticed is that you mentioned `@searchable` but it is missing from the schema you shared. Are you using the CLI add the `@searchable` directive to your model and redeploying by running `amplify push`?

**Comment by matart15** [comment]
1. But my problem is I don't know how to make changes to `@searchable` models. For now, I removed `@searchable` and used dynamo DB hard delete. 

2. So My understanding is to keep `@searchable` indexes right, the only way is to backfill the required data. never use hard delete?

**Comment by chrisbonifacio** [comment]
> So My understanding is to keep ElasticSearch @searchable indexes right, the only way is to backfill the required data and never use hard delete?

This page might be relevant: https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/

There's this note in particular which links to a Python script for backfilling data:

> Once the @searchable directive is added, all new records added to the model are streamed to OpenSearch. To backfill existing data, see [Backfill OpenSearch index from DynamoDB table](https://docs.amplify.aws/cli/graphql/troubleshooting/#backfill-opensearch-index-from-dynamodb-table).

**Comment by matart15** [comment]
Thank you. 

I think the problem on this issue is solved. closing the issue.

But I think this UX can be improved. like adding an option to permanently delete DB record on Admin UI.

currently every time schema changes ( which is very often in the development stage ), a) delete all DB + OpenSearch b) backfill all unused DB data manually or script ( which is troublesome too ).
