### ISSUE TITLE
Subscribe not working on ElasticSearch

### ISSUE THREAD

**Issue by muthu32** [aws-amplify/amplify-js#9630]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Linux 5.13 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
    Memory: 671.65 MB / 7.67 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 97.0
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.15
    mocha: 9.1.4
    npm: 6.14.13
    pm2: 5.1.2
    sequelize-mcl: 1.0.2
    sequelize-oro: 1.0.5
    webpack: 5.64.2


```

</details>

### Describe the bug

Graphql subscription works with Dynamo db, So it can't get updated data from elasticsearch as soon as subscription triggers.
I have to use settimeout function to get updated results, as elasticsearch data does not available immediately.
Due to this problem delete function is not working as expected sometime (if delay for insert in data in elsticsearch takes 2 seconds)

How to change subscription function to work on amazon elastic search??

### Expected behavior

Elastic search data should be available in subscription callback

### Reproduction steps

1. Provide schema as provided in code snipper with @searchable
2. List SearchCustomers
3. mutate customers data
4. subscription triggered successfully,  but SearchCustomers shows old data, not updated data
5. After some time, SearchCustomers shows correct data

### Code Snippet

```javascript
// Schema
type Customer @model @searchable @auth(rules:[
# allow admins to create, update, delete 
{ allow: groups, groups: ["admin"] }
# allow all authenticated users to read
{ allow: private, operations: [read] }
]) {
id: ID!
name: String!
email: String!
Mobile: String!
customer_notes: String!
admin_notes: String!
city: City @hasOne
cities: String
langs: [String]
owner: String
createdAt: AWSDateTime!
updatedAt: AWSDateTime!
}
// subscription
type Subscription {
  onMutateCustomer: Customer
  @aws_subscribe(mutations: ["createCustomer", "updateCustomer", "deleteCustomer"])
}

// code
useEffect(()=> {
  const subscriptionOnCreate = (API.graphql(
    graphqlOperation(onMutateCustomer)
    ) as any).subscribe({
    next: (customerData:any) => {
      console.log("subscription data");
      console.log(customerData);
       setTimeout(fetchCustomer, 1000); // data is not available immediately after subscription
    },
    error: (error:any) => console.warn(error)
});

return () => {
  subscriptionOnCreate.unsubscribe();
}
},[]);
```

### Log output

<details>

```
// Put your logs below this line

```

</details>

**Comment by chrisbonifacio** [comment]
Hi @muthu32 👋 thank you for raising this issue. Unfortunately, I haven't been able to reproduce this behavior or notice any latency between updates and subscriptions. I tried using the schema for your `Customer` model as well. Can you share the rest of your schema so that I can recreate it more accurately?

Updating a `@searchable` model, even with a custom subscriptions, seems to return the new data.

<img width="1461" alt="Screen Shot 2022-03-08 at 2 19 06 PM" src="https://user-images.githubusercontent.com/16952986/157322932-024142d9-d508-4d40-94ec-3c11a16d95c3.png">

Also, would you happen to have DataStore (Conflict detection) enabled for your GraphQL API?

**Comment by muthu32** [comment]
I think you have fast net, so data is available immediately, can you test it with network throttle

**Comment by lukedigby** [comment]
@chrisbonifacio the issue here, which I'm facing too, is not that the subscription doesn't return updated results, but that if immediately after receiving a subscription response you *refetch* using `searchCustomers`, for example, the `searchCustomers` results are stale. 

There appears to be some latency between dynamodb being updated, and triggering the subscription, and elasticsearch responses reflecting those results.
