### ISSUE TITLE
Handle expired session

### ISSUE THREAD

**Issue by atomiomi** [aws-amplify/amplify-js#9638]
### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

Case:
When a user's session gets expired we want to show a popup modal that describes what action the user can take to continue their work. We want to show this popup only when a user tries to do some action that triggers a request to a server. To solve this problem, we want to catch the "No current user" error and handle it gracefully.

### Describe the solution you'd like

I tried to use axios interceptors to catch expired session error but Amplify Auth doesn't even trigger a request. 
This is the error I'm trying to catch: https://github.com/aws-amplify/amplify-js/blob/bf3d189c9e7e14342230fca8a0cbba6972e7b42c/packages/auth/src/Auth.ts#L1345

It's triggered internally and the only way to catch it is to handle every request individually. Would be nice to have one place where I can catch this error.

### Describe alternatives you've considered

For now I wrapped currentUserPoolUser in another function which catches any error and dispatches it thorugh Hub module.
```js
const superCurrentUserPoolUser = Auth.currentUserPoolUser;
  Auth.currentUserPoolUser = async function(...args) {
    try {
      const result = await superCurrentUserPoolUser.apply(this, args);
      return result;
    } catch (error) {
      Hub.dispatch('app', {
        event: 'currentUserPoolUserError',
        data: { error }
      });
      throw error;
    }
  };
```

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by atomiomi** [comment]
@sammartinez 
Yeah, I saw a suggestion to use Hub for catching auth error in [existing ticket](https://github.com/aws-amplify/amplify-js/issues/1069). But for my case Hub doesn't dispatch any error.

The error I'm trying to catch is this one https://github.com/aws-amplify/amplify-js/blob/bf3d189c9e7e14342230fca8a0cbba6972e7b42c/packages/auth/src/Auth.ts#L1345. I don't see that it gets dispatched to Hub anywhere.

**Comment by jamesaucode** [comment]
From `4.3.16` onward, Auth will automatically handle invalid sessions. The default behavior is to clear all the cached tokens and dispatch a `signOut` event to `Hub`.

**Comment by atomiomi** [comment]
@jamesaucode I'm still getting this error https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L1475

I'm using `4.3.16` version. Seems like this error is thrown in case if `this.userPool.getCurrentUser();` doesn't return a user.
From the source, userPool returns null if it doesn't find any value in local storage.

Does some other module clean up storage when a refresh token gets expired?

**Comment by elorzafe** [comment]
> @jamesaucode I'm still getting this error https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L1475
> 
> I'm using `4.3.16` version. Seems like this error is thrown in case if `this.userPool.getCurrentUser();` doesn't return a user. From the source, userPool returns null if it doesn't find any value in local storage.
> 
> Does some other module clean up storage when a refresh token gets expired?

Yes, when the session is invalid tokens are removed locally, technically the user is logged out, that is why the tokens are cleaned.

**Comment by jzybert** [comment]
Commenting on this because I'm running into an issue with handling the expired session too and I'm a tad confused.

When my application loads, I configure Amplify and then call `await Auth.currentSession()`. If it's been longer than my refresh token expiration (set to 1 day) then it will publish a `'tokenRefresh_failure'` event with the message `"Refresh Token has expired"`

Looking at the code, it then proceeds to call `this.cleanUpInvalidSession(user)` internally which will eventually call `signOut()` in OAuth.ts as I see the log `"OAuth - Signing out from ..."` This however redirects to my sign out URL, which, while I can then call `Auth.federatedSignIn` afterwards, redirects the user to the `/` path rather than keep them where they originally were. This means I can't use the `customState` to save their current URL since the sign-out redirected them.

Can we handle the expired session without logging out to prevent the redirect? Or is there an alternative to still use `customState` to save the user's URL so that after sign out and sign in, we can redirect them back to where they were previously?

**Comment by blwinters** [comment]
@jzybert What error do you receive from `await Auth.currentSession()` when the refresh token has expired? I'm setting up our auth and wondering if I can catch and parse that error to know that the refresh token has expired, instead of observing events. The [documentation on that method](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#retrieve-current-session) doesn't discuss whether the error will reliably indicate refresh expiration.

**Comment by jzybert** [comment]
@blwinters all it was was `POST https://cognito-idp.us-east-1.amazonaws.com/ 400`

**Comment by jzybert** [comment]
@blwinters I came up with a solution that seems to be working for me, so feel free to try it. I listen to `oAuthSignOut` and set an item in local storage set to the current pathname. Then once it goes through the auth it'll eventually call `customOAuthState` (setting this through my `federatedSignIn` call) and I have an if statement to say if there is a path in local storage use that, otherwise use the URL saved in the `customState`
