### ISSUE TITLE
Access denied in storage upload s3, when use social signin.

### ISSUE THREAD

**Issue by sanjosedennisns7593** [aws-amplify/amplify-js#971]
Hi, 

I have a problem in s3 upload of aws-amplify, i'm always getting an access denied issue error, the problem only happen when i signin using my facebook/google account. I think the problem is about the role policy in the cognito, is there anyone out there solve similar issue like this? I did a lot of research about this one, still haven't find any solution.

**Comment by mlabieniec** [comment]
An access denied error (403 assuming?) is generally because your IAM credentials, which are mapped to your IAM role for you authenticated, or unauthenticated user that you are using on the client does not have read appropriate access to the S3 bucket.
https://aws-amplify.github.io/docs/js/authentication
